import path from "path";
import { fileURLToPath } from "url";
import { spawnSync } from "node:child_process";
import fs from "node:fs";
import withSerwistInit from "@serwist/next";

const projectRoot = path.dirname(fileURLToPath(import.meta.url));

const revision =
  spawnSync("git", ["rev-parse", "HEAD"], { encoding: "utf-8" }).stdout?.trim() ||
  crypto.randomUUID();

/** Published Beautiful Archive routes only — never holding.json. */
function buildArchivePrecacheEntries() {
  const entriesPath = path.join(projectRoot, "content/archive/entries.json");
  const lensesPath = path.join(projectRoot, "content/archive/lenses.json");
  const publicDataDir = path.join(projectRoot, "public/archive/data");

  const entries = JSON.parse(fs.readFileSync(entriesPath, "utf8"));
  if (!Array.isArray(entries)) {
    throw new Error("content/archive/entries.json must be an array");
  }

  const lenses = JSON.parse(fs.readFileSync(lensesPath, "utf8"));
  if (!Array.isArray(lenses)) {
    throw new Error("content/archive/lenses.json must be an array");
  }

  fs.mkdirSync(publicDataDir, { recursive: true });
  // Public JSON mirrors published data only (entries.json / lenses.json).
  fs.writeFileSync(
    path.join(publicDataDir, "entries.json"),
    `${JSON.stringify(entries)}\n`,
  );
  fs.writeFileSync(
    path.join(publicDataDir, "lenses.json"),
    `${JSON.stringify(lenses)}\n`,
  );

  const pageUrls = [
    "/archive",
    ...entries.map((entry) => `/archive/${entry.id}`),
  ];
  const jsonUrls = [
    "/archive/data/entries.json",
    "/archive/data/lenses.json",
  ];

  fs.writeFileSync(
    path.join(projectRoot, "app/sw-archive-meta.js"),
    [
      "/**",
      " * Generated by next.config.mjs at build/dev start. Do not edit by hand.",
      " * Used by the service worker for Beautiful Archive caching.",
      " */",
      `export const ARCHIVE_CACHE_REVISION = ${JSON.stringify(revision)};`,
      "",
      "/** Precached archive page routes (published entries only — never holding). */",
      `export const ARCHIVE_PAGE_URLS = ${JSON.stringify(pageUrls, null, 2)};`,
      "",
      "/** Precached published archive JSON payloads. */",
      `export const ARCHIVE_JSON_URLS = ${JSON.stringify(jsonUrls, null, 2)};`,
      "",
    ].join("\n"),
  );

  return [...pageUrls, ...jsonUrls].map((url) => ({ url, revision }));
}

const archivePrecacheEntries = buildArchivePrecacheEntries();

const withSerwist = withSerwistInit({
  swSrc: "app/sw.js",
  swDest: "public/sw.js",
  disable: process.env.NODE_ENV === "development",
  reloadOnOnline: true,
  cacheOnNavigation: false,
  // Never glob all of /public (banners/textures are huge). Precache only what
  // the offline shell needs; other /brand/* assets use CacheFirst at runtime.
  globPublicPatterns: [],
  additionalPrecacheEntries: [
    { url: "/offline", revision },
    { url: "/brand/trf-crest-transparent.png", revision },
    { url: "/brand/trf-icon-192.png", revision },
    { url: "/brand/trf-maskable-192.png", revision },
    ...archivePrecacheEntries,
  ],
});

/** @type {import('next').NextConfig} */
const nextConfig = {
  turbopack: {
    root: projectRoot,
  },
};

export default withSerwist(nextConfig);
