-- TM SAMPLE merge batch 4/4: 52 new rows (of 292 new)
-- Paste into Supabase SQL Editor AFTER players_batch_01–06.
-- Run in order tm_01 → tm_04.
insert into public.players (
  id, person_id, canonical, name, category, league, clubs,
  nationality, position, birth_year, shirt_number, era_start, era_end,
  world_cup_editions, aliases, clues
) values
(
  '1e787e6a',
  'valentin-rongier',
  true,
  'Valentin Rongier',
  'ligue_1',
  'ligue_1',
  array['Nantes', 'Marseille', 'Stade Rennais'],
  'France',
  'MF',
  1994,
  null,
  2014,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2014-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A France midfielder in the 2014-2025 window.', 'SAMPLE: Club path in this league window: Nantes, Marseille, Stade Rennais.', 'SAMPLE: 302 appearances, 15 goals, 24 assists (39 combined) in the logged window.', 'SAMPLE: Initials V.R. Surname shape length 7.']
),
(
  '6609e698',
  'gaetan-laborde',
  true,
  'Gaëtan Laborde',
  'ligue_1',
  'ligue_1',
  array['Girondins Bordeaux', 'Montpellier HSC', 'OGC Nice', 'Stade Rennais'],
  'France',
  'FW',
  1994,
  null,
  2015,
  2024,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2015-2024 league regular logged near the top of the appearances table.', 'SAMPLE: A France forward in the 2015-2024 window.', 'SAMPLE: Club path in this league window: Girondins Bordeaux, Montpellier HSC, OGC Nice, Stade Rennais.', 'SAMPLE: 297 appearances, 88 goals, 40 assists (128 combined) in the logged window.', 'SAMPLE: Initials G.L. Surname shape length 7.']
),
(
  '1e785e35',
  'remy-cabella',
  true,
  'Rémy Cabella',
  'ligue_1',
  'ligue_1',
  array['Saint-Étienne', 'Nantes', 'LOSC Lille', 'Montpellier HSC', 'Marseille'],
  'France',
  'MF',
  1990,
  null,
  2012,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A France midfielder in the 2012-2025 window.', 'SAMPLE: Club path in this league window: Saint-Étienne, Nantes, LOSC Lille, Montpellier HSC.', 'SAMPLE: 295 appearances, 56 goals, 46 assists (102 combined) in the logged window.', 'SAMPLE: Initials R.C. Surname shape length 7.']
),
(
  '35dda889',
  'djibril-sidibe',
  true,
  'Djibril Sidibé',
  'ligue_1',
  'ligue_1',
  array['Monaco', 'Toulouse', 'LOSC Lille'],
  'France',
  'DF',
  1992,
  null,
  2012,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A France defender in the 2012-2025 window.', 'SAMPLE: Club path in this league window: Monaco, Toulouse, LOSC Lille.', 'SAMPLE: 285 appearances, 14 goals, 32 assists (46 combined) in the logged window.', 'SAMPLE: Initials D.S. Surname shape length 6.']
),
(
  '48dfe76d',
  'hilton',
  true,
  'Hilton',
  'ligue_1',
  'ligue_1',
  array['Montpellier HSC'],
  'Brazil',
  'DF',
  1977,
  null,
  2012,
  2020,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2020 league regular logged near the top of the appearances table.', 'SAMPLE: A Brazil defender in the 2012-2020 window.', 'SAMPLE: Club path in this league window: Montpellier HSC.', 'SAMPLE: 285 appearances, 9 goals, 6 assists (15 combined) in the logged window.', 'SAMPLE: Initials H. Surname shape length 6.']
),
(
  'dd4bb2b0',
  'benjamin-lecomte',
  true,
  'Benjamin Lecomte',
  'ligue_1',
  'ligue_1',
  array['Monaco', 'Lorient', 'Montpellier HSC'],
  'France',
  'GK',
  1991,
  null,
  2012,
  2024,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2024 league regular logged near the top of the appearances table.', 'SAMPLE: A France goalkeeper in the 2012-2024 window.', 'SAMPLE: Club path in this league window: Monaco, Lorient, Montpellier HSC.', 'SAMPLE: 284 appearances, 0 goals, 2 assists (2 combined) in the logged window.', 'SAMPLE: Initials B.L. Surname shape length 7.']
),
(
  '8415d853',
  'romain-hamouma',
  true,
  'Romain Hamouma',
  'ligue_1',
  'ligue_1',
  array['Ajaccio', 'Saint-Étienne'],
  'France',
  'FW',
  1987,
  null,
  2012,
  2022,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2022 league regular logged near the top of the appearances table.', 'SAMPLE: A France forward in the 2012-2022 window.', 'SAMPLE: Club path in this league window: Ajaccio, Saint-Étienne.', 'SAMPLE: 284 appearances, 52 goals, 44 assists (96 combined) in the logged window.', 'SAMPLE: Initials R.H. Surname shape length 7.']
),
(
  '9e0efed4',
  'thomas-mangani',
  true,
  'Thomas Mangani',
  'ligue_1',
  'ligue_1',
  array['Ajaccio', 'Angers SCO', 'Nancy-Lorraine'],
  'France',
  'MF',
  1987,
  null,
  2012,
  2022,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2022 league regular logged near the top of the appearances table.', 'SAMPLE: A France midfielder in the 2012-2022 window.', 'SAMPLE: Club path in this league window: Ajaccio, Angers SCO, Nancy-Lorraine.', 'SAMPLE: 283 appearances, 26 goals, 31 assists (57 combined) in the logged window.', 'SAMPLE: Initials T.M. Surname shape length 7.']
),
(
  '8dacc782',
  'benoit-costil',
  true,
  'Benoît Costil',
  'ligue_1',
  'ligue_1',
  array['Girondins Bordeaux', 'Stade Rennais'],
  'France',
  'GK',
  1987,
  null,
  2012,
  2021,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2021 league regular logged near the top of the appearances table.', 'SAMPLE: A France goalkeeper in the 2012-2021 window.', 'SAMPLE: Club path in this league window: Girondins Bordeaux, Stade Rennais.', 'SAMPLE: 280 appearances, 0 goals, 1 assists (1 combined) in the logged window.', 'SAMPLE: Initials B.C. Surname shape length 6.']
),
(
  'feac1c4f',
  'alban-lafont',
  true,
  'Alban Lafont',
  'ligue_1',
  'ligue_1',
  array['Nantes', 'Toulouse'],
  'Ivory Coast',
  'GK',
  1999,
  null,
  2015,
  2024,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2015-2024 league regular logged near the top of the appearances table.', 'SAMPLE: A Ivory Coast goalkeeper in the 2015-2024 window.', 'SAMPLE: Club path in this league window: Nantes, Toulouse.', 'SAMPLE: 278 appearances, 0 goals, 0 assists (0 combined) in the logged window.', 'SAMPLE: Initials A.L. Surname shape length 6.']
),
(
  '9c7fc2da',
  'stephane-ruffier',
  true,
  'Stéphane Ruffier',
  'ligue_1',
  'ligue_1',
  array['Saint-Étienne'],
  'France',
  'GK',
  1986,
  null,
  2012,
  2019,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2019 league regular logged near the top of the appearances table.', 'SAMPLE: A France goalkeeper in the 2012-2019 window.', 'SAMPLE: Club path in this league window: Saint-Étienne.', 'SAMPLE: 277 appearances, 0 goals, 0 assists (0 combined) in the logged window.', 'SAMPLE: Initials S.R. Surname shape length 7.']
),
(
  '54e8c703',
  'issiaga-sylla',
  true,
  'Issiaga Sylla',
  'ligue_1',
  'ligue_1',
  array['Toulouse', 'GFC Ajaccio', 'Montpellier HSC', 'RC Lens'],
  'Guinea',
  'DF',
  1994,
  null,
  2012,
  2024,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2024 league regular logged near the top of the appearances table.', 'SAMPLE: A Guinea defender in the 2012-2024 window.', 'SAMPLE: Club path in this league window: Toulouse, GFC Ajaccio, Montpellier HSC, RC Lens.', 'SAMPLE: 276 appearances, 13 goals, 17 assists (30 combined) in the logged window.', 'SAMPLE: Initials I.S. Surname shape length 5.']
),
(
  '22f9d89b',
  'nicolas-de-preville',
  true,
  'Nicolas de Préville',
  'ligue_1',
  'ligue_1',
  array['Girondins Bordeaux', 'Metz', 'LOSC Lille', 'Stade Reims'],
  'France',
  'FW',
  1991,
  null,
  2012,
  2021,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2021 league regular logged near the top of the appearances table.', 'SAMPLE: A France forward in the 2012-2021 window.', 'SAMPLE: Club path in this league window: Girondins Bordeaux, Metz, LOSC Lille, Stade Reims.', 'SAMPLE: 273 appearances, 51 goals, 32 assists (83 combined) in the logged window.', 'SAMPLE: Initials N.D.P. Surname shape length 8.']
),
(
  '3b00bb82',
  'dante',
  true,
  'Dante',
  'ligue_1',
  'ligue_1',
  array['OGC Nice'],
  'Brazil',
  'DF',
  1983,
  null,
  2016,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2016-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Brazil defender in the 2016-2025 window.', 'SAMPLE: Club path in this league window: OGC Nice.', 'SAMPLE: 272 appearances, 7 goals, 10 assists (17 combined) in the logged window.', 'SAMPLE: Initials D. Surname shape length 5.']
),
(
  'acac81d9',
  'ismael-traore',
  true,
  'Ismaël Traoré',
  'ligue_1',
  'ligue_1',
  array['Angers SCO', 'Metz', 'Stade Brestois 29'],
  'Ivory Coast',
  'DF',
  1986,
  null,
  2012,
  2023,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2023 league regular logged near the top of the appearances table.', 'SAMPLE: A Ivory Coast defender in the 2012-2023 window.', 'SAMPLE: Club path in this league window: Angers SCO, Metz, Stade Brestois 29.', 'SAMPLE: 265 appearances, 17 goals, 8 assists (25 combined) in the logged window.', 'SAMPLE: Initials I.T. Surname shape length 6.']
),
(
  '0a19359a',
  'andy-delort',
  true,
  'Andy Delort',
  'ligue_1',
  'ligue_1',
  array['Ajaccio', 'Nantes', 'Toulouse', 'Montpellier HSC', 'OGC Nice', 'SM Caen'],
  'Algeria',
  'FW',
  1991,
  null,
  2012,
  2024,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2024 league regular logged near the top of the appearances table.', 'SAMPLE: A Algeria forward in the 2012-2024 window.', 'SAMPLE: Club path in this league window: Ajaccio, Nantes, Toulouse, Montpellier HSC.', 'SAMPLE: 261 appearances, 85 goals, 32 assists (117 combined) in the logged window.', 'SAMPLE: Initials A.D. Surname shape length 6.']
),
(
  '37badfd9',
  'benjamin-bourigeaud',
  true,
  'Benjamin Bourigeaud',
  'ligue_1',
  'ligue_1',
  array['RC Lens', 'Stade Rennais'],
  'France',
  'MF',
  1994,
  null,
  2014,
  2024,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2014-2024 league regular logged near the top of the appearances table.', 'SAMPLE: A France midfielder in the 2014-2024 window.', 'SAMPLE: Club path in this league window: RC Lens, Stade Rennais.', 'SAMPLE: 261 appearances, 54 goals, 49 assists (103 combined) in the logged window.', 'SAMPLE: Initials B.B. Surname shape length 10.']
),
(
  '43775fe3',
  'marcus-coco',
  true,
  'Marcus Coco',
  'ligue_1',
  'ligue_1',
  array['EA Guingamp', 'Nantes'],
  'Guadeloupe',
  'DF',
  1996,
  null,
  2014,
  2024,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2014-2024 league regular logged near the top of the appearances table.', 'SAMPLE: A Guadeloupe defender in the 2014-2024 window.', 'SAMPLE: Club path in this league window: EA Guingamp, Nantes.', 'SAMPLE: 260 appearances, 11 goals, 14 assists (25 combined) in the logged window.', 'SAMPLE: Initials M.C. Surname shape length 4.']
),
(
  'b8106b45',
  'pierre-lees-melou',
  true,
  'Pierre Lees-Melou',
  'ligue_1',
  'ligue_1',
  array['Dijon FCO', 'OGC Nice', 'Paris', 'Stade Brestois 29'],
  'France',
  'MF',
  1993,
  null,
  2016,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2016-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A France midfielder in the 2016-2025 window.', 'SAMPLE: Club path in this league window: Dijon FCO, OGC Nice, Paris, Stade Brestois 29.', 'SAMPLE: 256 appearances, 35 goals, 28 assists (63 combined) in the logged window.', 'SAMPLE: Initials P.L.M. Surname shape length 5.']
),
(
  '57172caa',
  'baptiste-santamaria',
  true,
  'Baptiste Santamaria',
  'ligue_1',
  'ligue_1',
  array['Angers SCO', 'OGC Nice', 'Stade Rennais'],
  'France',
  'MF',
  1995,
  null,
  2016,
  2024,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2016-2024 league regular logged near the top of the appearances table.', 'SAMPLE: A France midfielder in the 2016-2024 window.', 'SAMPLE: Club path in this league window: Angers SCO, OGC Nice, Stade Rennais.', 'SAMPLE: 249 appearances, 6 goals, 5 assists (11 combined) in the logged window.', 'SAMPLE: Initials B.S. Surname shape length 10.']
),
(
  '343edb58',
  'jimmy-briand',
  true,
  'Jimmy Briand',
  'ligue_1',
  'ligue_1',
  array['EA Guingamp', 'Girondins Bordeaux', 'Olympique Lyon'],
  'France',
  'FW',
  1985,
  null,
  2012,
  2021,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2021 league regular logged near the top of the appearances table.', 'SAMPLE: A France forward in the 2012-2021 window.', 'SAMPLE: Club path in this league window: EA Guingamp, Girondins Bordeaux, Olympique Lyon.', 'SAMPLE: 244 appearances, 54 goals, 28 assists (82 combined) in the logged window.', 'SAMPLE: Initials J.B. Surname shape length 6.']
),
(
  '655f8c43',
  'hamari-traore',
  true,
  'Hamari Traoré',
  'ligue_1',
  'ligue_1',
  array['Paris', 'Stade Reims', 'Stade Rennais'],
  'Mali',
  'DF',
  1992,
  null,
  2015,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2015-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Mali defender in the 2015-2025 window.', 'SAMPLE: Club path in this league window: Paris, Stade Reims, Stade Rennais.', 'SAMPLE: 241 appearances, 7 goals, 25 assists (32 combined) in the logged window.', 'SAMPLE: Initials H.T. Surname shape length 6.']
),
(
  'a3d5ce5a',
  'ryad-boudebouz',
  true,
  'Ryad Boudebouz',
  'ligue_1',
  'ligue_1',
  array['Saint-Étienne', 'Sochaux-Montbéliard', 'Montpellier HSC', 'SC Bastia'],
  'Algeria',
  'MF',
  1990,
  null,
  2012,
  2021,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2021 league regular logged near the top of the appearances table.', 'SAMPLE: A Algeria midfielder in the 2012-2021 window.', 'SAMPLE: Club path in this league window: Saint-Étienne, Sochaux-Montbéliard, Montpellier HSC, SC Bastia.', 'SAMPLE: 239 appearances, 29 goals, 46 assists (75 combined) in the logged window.', 'SAMPLE: Initials R.B. Surname shape length 9.']
),
(
  '9f8dd971',
  'kevin-monnet-paquet',
  true,
  'Kévin Monnet-Paquet',
  'ligue_1',
  'ligue_1',
  array['Saint-Étienne', 'Lorient'],
  'France',
  'FW',
  1988,
  null,
  2012,
  2020,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2020 league regular logged near the top of the appearances table.', 'SAMPLE: A France forward in the 2012-2020 window.', 'SAMPLE: Club path in this league window: Saint-Étienne, Lorient.', 'SAMPLE: 235 appearances, 21 goals, 18 assists (39 combined) in the logged window.', 'SAMPLE: Initials K.M.P. Surname shape length 6.']
),
(
  'f1ab71d7',
  'yunis-abdelhamid',
  true,
  'Yunis Abdelhamid',
  'ligue_1',
  'ligue_1',
  array['Saint-Étienne', 'Dijon FCO', 'Stade Reims'],
  'Morocco',
  'DF',
  1987,
  null,
  2016,
  2024,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2016-2024 league regular logged near the top of the appearances table.', 'SAMPLE: A Morocco defender in the 2016-2024 window.', 'SAMPLE: Club path in this league window: Saint-Étienne, Dijon FCO, Stade Reims.', 'SAMPLE: 235 appearances, 13 goals, 2 assists (15 combined) in the logged window.', 'SAMPLE: Initials Y.A. Surname shape length 10.']
),
(
  '64600171',
  'corentin-tolisso',
  true,
  'Corentin Tolisso',
  'ligue_1',
  'ligue_1',
  array['Olympique Lyon'],
  'France',
  'MF',
  1994,
  null,
  2013,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2013-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A France midfielder in the 2013-2025 window.', 'SAMPLE: Club path in this league window: Olympique Lyon.', 'SAMPLE: 233 appearances, 42 goals, 28 assists (70 combined) in the logged window.', 'SAMPLE: Initials C.T. Surname shape length 7.']
),
(
  'd891242d',
  'frederic-guilbert',
  true,
  'Frédéric Guilbert',
  'ligue_1',
  'ligue_1',
  array['Girondins Bordeaux', 'Nantes', 'RC Strasbourg Alsace', 'SM Caen'],
  'France',
  'DF',
  1994,
  null,
  2014,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2014-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A France defender in the 2014-2025 window.', 'SAMPLE: Club path in this league window: Girondins Bordeaux, Nantes, RC Strasbourg Alsace, SM Caen.', 'SAMPLE: 233 appearances, 5 goals, 15 assists (20 combined) in the logged window.', 'SAMPLE: Initials F.G. Surname shape length 8.']
),
(
  '13803057',
  'nolan-roux',
  true,
  'Nolan Roux',
  'ligue_1',
  'ligue_1',
  array['Saint-Étienne', 'EA Guingamp', 'Metz', 'LOSC Lille', 'Nîmes Olympique'],
  'France',
  'FW',
  1988,
  null,
  2012,
  2020,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2020 league regular logged near the top of the appearances table.', 'SAMPLE: A France forward in the 2012-2020 window.', 'SAMPLE: Club path in this league window: Saint-Étienne, EA Guingamp, Metz, LOSC Lille.', 'SAMPLE: 232 appearances, 58 goals, 16 assists (74 combined) in the logged window.', 'SAMPLE: Initials N.R. Surname shape length 4.']
),
(
  '443c0d73',
  'florent-mollet',
  true,
  'Florent Mollet',
  'ligue_1',
  'ligue_1',
  array['Metz', 'Nantes', 'Montpellier HSC'],
  'France',
  'MF',
  1991,
  null,
  2016,
  2024,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2016-2024 league regular logged near the top of the appearances table.', 'SAMPLE: A France midfielder in the 2016-2024 window.', 'SAMPLE: Club path in this league window: Metz, Nantes, Montpellier HSC.', 'SAMPLE: 230 appearances, 33 goals, 25 assists (58 combined) in the logged window.', 'SAMPLE: Initials F.M. Surname shape length 6.']
),
(
  '7bd90e9c',
  'loic-perrin',
  true,
  'Loïc Perrin',
  'ligue_1',
  'ligue_1',
  array['Saint-Étienne'],
  'France',
  'DF',
  1985,
  null,
  2012,
  2019,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2019 league regular logged near the top of the appearances table.', 'SAMPLE: A France defender in the 2012-2019 window.', 'SAMPLE: Club path in this league window: Saint-Étienne.', 'SAMPLE: 227 appearances, 17 goals, 8 assists (25 combined) in the logged window.', 'SAMPLE: Initials L.P. Surname shape length 6.']
),
(
  'ec8a0bdd',
  'ruben-aguilar',
  true,
  'Ruben Aguilar',
  'ligue_1',
  'ligue_1',
  array['Monaco', 'Montpellier HSC', 'RC Lens'],
  'France',
  'DF',
  1993,
  null,
  2017,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2017-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A France defender in the 2017-2025 window.', 'SAMPLE: Club path in this league window: Monaco, Montpellier HSC, RC Lens.', 'SAMPLE: 227 appearances, 6 goals, 22 assists (28 combined) in the logged window.', 'SAMPLE: Initials R.A. Surname shape length 7.']
),
(
  'e5863beb',
  'youssouf-sabaly',
  true,
  'Youssouf Sabaly',
  'ligue_1',
  'ligue_1',
  array['Girondins Bordeaux', 'Nantes', 'Thonon Évian Grand Genève'],
  'Senegal',
  'DF',
  1993,
  null,
  2013,
  2020,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2013-2020 league regular logged near the top of the appearances table.', 'SAMPLE: A Senegal defender in the 2013-2020 window.', 'SAMPLE: Club path in this league window: Girondins Bordeaux, Nantes, Thonon Évian Grand Genève.', 'SAMPLE: 226 appearances, 3 goals, 19 assists (22 combined) in the logged window.', 'SAMPLE: Initials Y.S. Surname shape length 6.']
),
(
  '3a7f3300',
  'jonathan-bamba',
  true,
  'Jonathan Bamba',
  'ligue_1',
  'ligue_1',
  array['Angers SCO', 'Saint-Étienne', 'LOSC Lille'],
  'Ivory Coast',
  'FW',
  1996,
  null,
  2014,
  2022,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2014-2022 league regular logged near the top of the appearances table.', 'SAMPLE: A Ivory Coast forward in the 2014-2022 window.', 'SAMPLE: Club path in this league window: Angers SCO, Saint-Étienne, LOSC Lille.', 'SAMPLE: 225 appearances, 38 goals, 39 assists (77 combined) in the logged window.', 'SAMPLE: Initials J.B. Surname shape length 5.']
),
(
  '15166c4c',
  'alexander-djiku',
  true,
  'Alexander Djiku',
  'ligue_1',
  'ligue_1',
  array['RC Strasbourg Alsace', 'SC Bastia', 'SM Caen'],
  'Ghana',
  'DF',
  1994,
  null,
  2014,
  2022,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2014-2022 league regular logged near the top of the appearances table.', 'SAMPLE: A Ghana defender in the 2014-2022 window.', 'SAMPLE: Club path in this league window: RC Strasbourg Alsace, SC Bastia, SM Caen.', 'SAMPLE: 221 appearances, 5 goals, 3 assists (8 combined) in the logged window.', 'SAMPLE: Initials A.D. Surname shape length 5.']
),
(
  'cdf32d9c',
  'romain-thomas',
  true,
  'Romain Thomas',
  'ligue_1',
  'ligue_1',
  array['Angers SCO'],
  'France',
  'DF',
  1988,
  null,
  2015,
  2021,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2015-2021 league regular logged near the top of the appearances table.', 'SAMPLE: A France defender in the 2015-2021 window.', 'SAMPLE: Club path in this league window: Angers SCO.', 'SAMPLE: 219 appearances, 14 goals, 2 assists (16 combined) in the logged window.', 'SAMPLE: Initials R.T. Surname shape length 6.']
),
(
  'a314af4f',
  'yannick-cahuzac',
  true,
  'Yannick Cahuzac',
  'ligue_1',
  'ligue_1',
  array['Toulouse', 'RC Lens', 'SC Bastia'],
  'France',
  'MF',
  1985,
  null,
  2012,
  2021,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2021 league regular logged near the top of the appearances table.', 'SAMPLE: A France midfielder in the 2012-2021 window.', 'SAMPLE: Club path in this league window: Toulouse, RC Lens, SC Bastia.', 'SAMPLE: 219 appearances, 6 goals, 3 assists (9 combined) in the logged window.', 'SAMPLE: Initials Y.C. Surname shape length 7.']
),
(
  'f1a25cef',
  'angelo-fulgini',
  true,
  'Angelo Fulgini',
  'ligue_1',
  'ligue_1',
  array['Angers SCO', 'RC Lens'],
  'New Caledonia',
  'MF',
  1996,
  null,
  2017,
  2024,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2017-2024 league regular logged near the top of the appearances table.', 'SAMPLE: A New Caledonia midfielder in the 2017-2024 window.', 'SAMPLE: Club path in this league window: Angers SCO, RC Lens.', 'SAMPLE: 218 appearances, 23 goals, 18 assists (41 combined) in the logged window.', 'SAMPLE: Initials A.F. Surname shape length 7.']
),
(
  '5e9f76be',
  'romain-del-castillo',
  true,
  'Romain Del Castillo',
  'ligue_1',
  'ligue_1',
  array['Olympique Lyon', 'Stade Brestois 29', 'Stade Rennais'],
  'France',
  'FW',
  1996,
  null,
  2015,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2015-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A France forward in the 2015-2025 window.', 'SAMPLE: Club path in this league window: Olympique Lyon, Stade Brestois 29, Stade Rennais.', 'SAMPLE: 217 appearances, 31 goals, 42 assists (73 combined) in the logged window.', 'SAMPLE: Initials R.D.C. Surname shape length 8.']
),
(
  '014d163d',
  'maxime-gonalons',
  true,
  'Maxime Gonalons',
  'ligue_1',
  'ligue_1',
  array['Clermont Foot 63', 'Olympique Lyon'],
  'France',
  'MF',
  1989,
  null,
  2012,
  2023,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2023 league regular logged near the top of the appearances table.', 'SAMPLE: A France midfielder in the 2012-2023 window.', 'SAMPLE: Club path in this league window: Clermont Foot 63, Olympique Lyon.', 'SAMPLE: 215 appearances, 7 goals, 6 assists (13 combined) in the logged window.', 'SAMPLE: Initials M.G. Surname shape length 8.']
),
(
  '653c7056',
  'souleymane-camara',
  true,
  'Souleymane Camara',
  'ligue_1',
  'ligue_1',
  array['Montpellier HSC'],
  'Senegal',
  'FW',
  1982,
  null,
  2012,
  2019,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2019 league regular logged near the top of the appearances table.', 'SAMPLE: A Senegal forward in the 2012-2019 window.', 'SAMPLE: Club path in this league window: Montpellier HSC.', 'SAMPLE: 213 appearances, 30 goals, 18 assists (48 combined) in the logged window.', 'SAMPLE: Initials S.C. Surname shape length 6.']
),
(
  'd07e950c',
  'abdoulaye-toure',
  true,
  'Abdoulaye Touré',
  'ligue_1',
  'ligue_1',
  array['Nantes', 'Le Havre AC'],
  'Guinea',
  'MF',
  1994,
  null,
  2013,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2013-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Guinea midfielder in the 2013-2025 window.', 'SAMPLE: Club path in this league window: Nantes, Le Havre AC.', 'SAMPLE: 212 appearances, 23 goals, 9 assists (32 combined) in the logged window.', 'SAMPLE: Initials A.T. Surname shape length 5.']
),
(
  'bc2b1f33',
  'joris-chotard',
  true,
  'Joris Chotard',
  'ligue_1',
  'ligue_1',
  array['Montpellier HSC', 'Stade Brestois 29'],
  'France',
  'MF',
  2001,
  null,
  2019,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2019-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A France midfielder in the 2019-2025 window.', 'SAMPLE: Club path in this league window: Montpellier HSC, Stade Brestois 29.', 'SAMPLE: 210 appearances, 4 goals, 12 assists (16 combined) in the logged window.', 'SAMPLE: Initials J.C. Surname shape length 7.']
),
(
  'ca3b9ac4',
  'lucas-deaux',
  true,
  'Lucas Deaux',
  'ligue_1',
  'ligue_1',
  array['EA Guingamp', 'Nantes', 'Nîmes Olympique'],
  'France',
  'MF',
  1988,
  null,
  2013,
  2020,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2013-2020 league regular logged near the top of the appearances table.', 'SAMPLE: A France midfielder in the 2013-2020 window.', 'SAMPLE: Club path in this league window: EA Guingamp, Nantes, Nîmes Olympique.', 'SAMPLE: 210 appearances, 11 goals, 12 assists (23 combined) in the logged window.', 'SAMPLE: Initials L.D. Surname shape length 5.']
),
(
  '26cc8450',
  'arnaud-nordin',
  true,
  'Arnaud Nordin',
  'ligue_1',
  'ligue_1',
  array['Saint-Étienne', 'Montpellier HSC', 'Stade Rennais'],
  'France',
  'FW',
  1998,
  null,
  2016,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2016-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A France forward in the 2016-2025 window.', 'SAMPLE: Club path in this league window: Saint-Étienne, Montpellier HSC, Stade Rennais.', 'SAMPLE: 208 appearances, 34 goals, 22 assists (56 combined) in the logged window.', 'SAMPLE: Initials A.N. Surname shape length 6.']
),
(
  '4ada4309',
  'aleksandr-golovin',
  true,
  'Aleksandr Golovin',
  'ligue_1',
  'ligue_1',
  array['Monaco'],
  'Russia',
  'MF',
  1996,
  null,
  2018,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2018-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Russia midfielder in the 2018-2025 window.', 'SAMPLE: Club path in this league window: Monaco.', 'SAMPLE: 206 appearances, 36 goals, 38 assists (74 combined) in the logged window.', 'SAMPLE: Initials A.G. Surname shape length 7.']
),
(
  '9d80c85d',
  'moses-simon',
  true,
  'Moses Simon',
  'ligue_1',
  'ligue_1',
  array['Nantes', 'Paris'],
  'Nigeria',
  'FW',
  1995,
  null,
  2019,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2019-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Nigeria forward in the 2019-2025 window.', 'SAMPLE: Club path in this league window: Nantes, Paris.', 'SAMPLE: 206 appearances, 36 goals, 41 assists (77 combined) in the logged window.', 'SAMPLE: Initials M.S. Surname shape length 5.']
),
(
  '0f819a60',
  'fabien-lemoine',
  true,
  'Fabien Lemoine',
  'ligue_1',
  'ligue_1',
  array['Saint-Étienne', 'Lorient'],
  'France',
  'MF',
  1987,
  null,
  2012,
  2021,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2021 league regular logged near the top of the appearances table.', 'SAMPLE: A France midfielder in the 2012-2021 window.', 'SAMPLE: Club path in this league window: Saint-Étienne, Lorient.', 'SAMPLE: 205 appearances, 6 goals, 10 assists (16 combined) in the logged window.', 'SAMPLE: Initials F.L. Surname shape length 7.']
),
(
  '3450aea6',
  'amine-gouiri',
  true,
  'Amine Gouiri',
  'ligue_1',
  'ligue_1',
  array['OGC Nice', 'Olympique Lyon', 'Marseille', 'Stade Rennais'],
  'Algeria',
  'FW',
  2000,
  null,
  2017,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2017-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Algeria forward in the 2017-2025 window.', 'SAMPLE: Club path in this league window: OGC Nice, Olympique Lyon, Marseille, Stade Rennais.', 'SAMPLE: 202 appearances, 65 goals, 32 assists (97 combined) in the logged window.', 'SAMPLE: Initials A.G. Surname shape length 6.']
),
(
  '68df6e9f',
  'florent-balmont',
  true,
  'Florent Balmont',
  'ligue_1',
  'ligue_1',
  array['Dijon FCO', 'LOSC Lille'],
  'France',
  'MF',
  1980,
  null,
  2012,
  2019,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2019 league regular logged near the top of the appearances table.', 'SAMPLE: A France midfielder in the 2012-2019 window.', 'SAMPLE: Club path in this league window: Dijon FCO, LOSC Lille.', 'SAMPLE: 202 appearances, 4 goals, 20 assists (24 combined) in the logged window.', 'SAMPLE: Initials F.B. Surname shape length 7.']
),
(
  '18c56129',
  'martin-terrier',
  true,
  'Martin Terrier',
  'ligue_1',
  'ligue_1',
  array['LOSC Lille', 'Olympique Lyon', 'RC Strasbourg Alsace', 'Stade Rennais'],
  'France',
  'FW',
  1997,
  null,
  2016,
  2023,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2016-2023 league regular logged near the top of the appearances table.', 'SAMPLE: A France forward in the 2016-2023 window.', 'SAMPLE: Club path in this league window: LOSC Lille, Olympique Lyon, RC Strasbourg Alsace, Stade Rennais.', 'SAMPLE: 202 appearances, 60 goals, 24 assists (84 combined) in the logged window.', 'SAMPLE: Initials M.T. Surname shape length 7.']
),
(
  'b91a63cd',
  'jeremy-sorbon',
  true,
  'Jérémy Sorbon',
  'ligue_1',
  'ligue_1',
  array['EA Guingamp'],
  'France',
  'DF',
  1983,
  null,
  2013,
  2018,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2013-2018 league regular logged near the top of the appearances table.', 'SAMPLE: A France defender in the 2013-2018 window.', 'SAMPLE: Club path in this league window: EA Guingamp.', 'SAMPLE: 201 appearances, 5 goals, 0 assists (5 combined) in the logged window.', 'SAMPLE: Initials J.S. Surname shape length 6.']
),
(
  '00a029f4',
  'vincent-pajot',
  true,
  'Vincent Pajot',
  'ligue_1',
  'ligue_1',
  array['Angers SCO', 'Saint-Étienne', 'Metz', 'Stade Rennais'],
  'France',
  'MF',
  1990,
  null,
  2012,
  2021,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2021 league regular logged near the top of the appearances table.', 'SAMPLE: A France midfielder in the 2012-2021 window.', 'SAMPLE: Club path in this league window: Angers SCO, Saint-Étienne, Metz, Stade Rennais.', 'SAMPLE: 201 appearances, 8 goals, 9 assists (17 combined) in the logged window.', 'SAMPLE: Initials V.P. Surname shape length 5.']
)
on conflict (id) do update set
  person_id = excluded.person_id,
  canonical = excluded.canonical,
  name = excluded.name,
  category = excluded.category,
  league = excluded.league,
  clubs = excluded.clubs,
  nationality = excluded.nationality,
  position = excluded.position,
  birth_year = excluded.birth_year,
  shirt_number = excluded.shirt_number,
  era_start = excluded.era_start,
  era_end = excluded.era_end,
  world_cup_editions = excluded.world_cup_editions,
  aliases = excluded.aliases,
  clues = excluded.clues;

