-- TM SAMPLE merge batch 2/4: 80 new rows (of 292 new)
-- Paste into Supabase SQL Editor AFTER players_batch_01–06.
-- Run in order tm_01 → tm_04.
insert into public.players (
  id, person_id, canonical, name, category, league, clubs,
  nationality, position, birth_year, shirt_number, era_start, era_end,
  world_cup_editions, aliases, clues
) values
(
  '0d118db7',
  'cristhian-stuani',
  true,
  'Cristhian Stuani',
  'la_liga',
  'la_liga',
  array['Girona', 'RCD Espanyol Barcelona'],
  'Uruguay',
  'FW',
  1986,
  null,
  2012,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Uruguay forward in the 2012-2025 window.', 'SAMPLE: Club path in this league window: Girona, RCD Espanyol Barcelona.', 'SAMPLE: 284 appearances, 99 goals, 14 assists (113 combined) in the logged window.', 'SAMPLE: Initials C.S. Surname shape length 6.']
),
(
  'bc28b5c4',
  'denis-suarez',
  true,
  'Denis Suárez',
  'la_liga',
  'la_liga',
  array['Celta de Vigo', 'Deportivo Alavés', 'Barcelona', 'RCD Espanyol Barcelona', 'Sevilla', 'Villarreal'],
  'Spain',
  'MF',
  1994,
  null,
  2014,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2014-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Spain midfielder in the 2014-2025 window.', 'SAMPLE: Club path in this league window: Celta de Vigo, Deportivo Alavés, Barcelona, RCD Espanyol Barcelona.', 'SAMPLE: 282 appearances, 16 goals, 39 assists (55 combined) in the logged window.', 'SAMPLE: Initials D.S. Surname shape length 6.']
),
(
  'f2756990',
  'juanmi',
  true,
  'Juanmi',
  'la_liga',
  'la_liga',
  array['Cádiz', 'Getafe', 'Málaga', 'Real Betis Balompié', 'Real Sociedad'],
  'Spain',
  'FW',
  1993,
  null,
  2012,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Spain forward in the 2012-2025 window.', 'SAMPLE: Club path in this league window: Cádiz, Getafe, Málaga, Real Betis Balompié.', 'SAMPLE: 279 appearances, 64 goals, 14 assists (78 combined) in the logged window.', 'SAMPLE: Initials J. Surname shape length 6.']
),
(
  '8faea144',
  'jordi-alba',
  true,
  'Jordi Alba',
  'la_liga',
  'la_liga',
  array['Barcelona'],
  'Spain',
  'DF',
  1989,
  null,
  2012,
  2022,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2022 league regular logged near the top of the appearances table.', 'SAMPLE: A Spain defender in the 2012-2022 window.', 'SAMPLE: Club path in this league window: Barcelona.', 'SAMPLE: 278 appearances, 14 goals, 60 assists (74 combined) in the logged window.', 'SAMPLE: Initials J.A. Surname shape length 4.']
),
(
  'aac705a5',
  'brais-mendez',
  true,
  'Brais Méndez',
  'la_liga',
  'la_liga',
  array['Celta de Vigo', 'Real Sociedad'],
  'Spain',
  'MF',
  1997,
  null,
  2017,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2017-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Spain midfielder in the 2017-2025 window.', 'SAMPLE: Club path in this league window: Celta de Vigo, Real Sociedad.', 'SAMPLE: 275 appearances, 42 goals, 29 assists (71 combined) in the logged window.', 'SAMPLE: Initials B.M. Surname shape length 6.']
),
(
  '4d47cecb',
  'marcos-llorente',
  true,
  'Marcos Llorente',
  'la_liga',
  'la_liga',
  array['Atletico Madrid', 'Deportivo Alavés', 'Real Madrid'],
  'Spain',
  'DF',
  1995,
  null,
  2015,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2015-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Spain defender in the 2015-2025 window.', 'SAMPLE: Club path in this league window: Atletico Madrid, Deportivo Alavés, Real Madrid.', 'SAMPLE: 270 appearances, 24 goals, 33 assists (57 combined) in the logged window.', 'SAMPLE: Initials M.L. Surname shape length 8.']
),
(
  '05924ca4',
  'federico-valverde',
  true,
  'Federico Valverde',
  'la_liga',
  'la_liga',
  array['Deportivo de La Coruña', 'Real Madrid'],
  'Uruguay',
  'MF',
  1998,
  null,
  2017,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2017-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Uruguay midfielder in the 2017-2025 window.', 'SAMPLE: Club path in this league window: Deportivo de La Coruña, Real Madrid.', 'SAMPLE: 268 appearances, 25 goals, 30 assists (55 combined) in the logged window.', 'SAMPLE: Initials F.V. Surname shape length 8.']
),
(
  '5a26aba2',
  'jesus-navas',
  true,
  'Jesús Navas',
  'la_liga',
  'la_liga',
  array['Sevilla'],
  'Spain',
  'MF',
  1985,
  null,
  2012,
  2024,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2024 league regular logged near the top of the appearances table.', 'SAMPLE: A Spain midfielder in the 2012-2024 window.', 'SAMPLE: Club path in this league window: Sevilla.', 'SAMPLE: 268 appearances, 3 goals, 30 assists (33 combined) in the logged window.', 'SAMPLE: Initials J.N. Surname shape length 5.']
),
(
  '1b68e91c',
  'santi-mina',
  true,
  'Santi Mina',
  'la_liga',
  'la_liga',
  array['Celta de Vigo', 'Valencia'],
  'Spain',
  'FW',
  1995,
  null,
  2012,
  2021,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2021 league regular logged near the top of the appearances table.', 'SAMPLE: A Spain forward in the 2012-2021 window.', 'SAMPLE: Club path in this league window: Celta de Vigo, Valencia.', 'SAMPLE: 268 appearances, 63 goals, 25 assists (88 combined) in the logged window.', 'SAMPLE: Initials S.M. Surname shape length 4.']
),
(
  '1ba7209e',
  'munir-el-haddadi',
  true,
  'Munir El Haddadi',
  'la_liga',
  'la_liga',
  array['CD Leganés', 'Deportivo Alavés', 'Barcelona', 'Getafe', 'Sevilla', 'UD Las Palmas', 'Valencia'],
  'Morocco',
  'MF',
  1995,
  null,
  2014,
  2024,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2014-2024 league regular logged near the top of the appearances table.', 'SAMPLE: A Morocco midfielder in the 2014-2024 window.', 'SAMPLE: Club path in this league window: CD Leganés, Deportivo Alavés, Barcelona, Getafe.', 'SAMPLE: 267 appearances, 47 goals, 22 assists (69 combined) in the logged window.', 'SAMPLE: Initials M.E.H. Surname shape length 7.']
),
(
  '81168425',
  'willian-jose',
  true,
  'Willian José',
  'la_liga',
  'la_liga',
  array['Real Betis Balompié', 'Real Madrid', 'Real Sociedad', 'UD Las Palmas'],
  'Brazil',
  'FW',
  1991,
  null,
  2013,
  2023,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2013-2023 league regular logged near the top of the appearances table.', 'SAMPLE: A Brazil forward in the 2013-2023 window.', 'SAMPLE: Club path in this league window: Real Betis Balompié, Real Madrid, Real Sociedad, UD Las Palmas.', 'SAMPLE: 267 appearances, 82 goals, 26 assists (108 combined) in the logged window.', 'SAMPLE: Initials W.J. Surname shape length 4.']
),
(
  '4681fdea',
  'jorge-molina',
  true,
  'Jorge Molina',
  'la_liga',
  'la_liga',
  array['Getafe', 'Granada', 'Real Betis Balompié'],
  'Spain',
  'FW',
  1982,
  null,
  2012,
  2021,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2021 league regular logged near the top of the appearances table.', 'SAMPLE: A Spain forward in the 2012-2021 window.', 'SAMPLE: Club path in this league window: Getafe, Granada, Real Betis Balompié.', 'SAMPLE: 261 appearances, 67 goals, 27 assists (94 combined) in the logged window.', 'SAMPLE: Initials J.M. Surname shape length 6.']
),
(
  '289f75b8',
  'igor-zubeldia',
  true,
  'Igor Zubeldia',
  'la_liga',
  'la_liga',
  array['Real Sociedad'],
  'Spain',
  'DF',
  1997,
  null,
  2015,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2015-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Spain defender in the 2015-2025 window.', 'SAMPLE: Club path in this league window: Real Sociedad.', 'SAMPLE: 259 appearances, 3 goals, 10 assists (13 combined) in the logged window.', 'SAMPLE: Initials I.Z. Surname shape length 8.']
),
(
  '4d8203f3',
  'asier-illarramendi',
  true,
  'Asier Illarramendi',
  'la_liga',
  'la_liga',
  array['Real Madrid', 'Real Sociedad'],
  'Spain',
  'MF',
  1990,
  null,
  2012,
  2022,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2022 league regular logged near the top of the appearances table.', 'SAMPLE: A Spain midfielder in the 2012-2022 window.', 'SAMPLE: Club path in this league window: Real Madrid, Real Sociedad.', 'SAMPLE: 258 appearances, 13 goals, 13 assists (26 combined) in the logged window.', 'SAMPLE: Initials A.I. Surname shape length 12.']
),
(
  'c25bc754',
  'david-lopez',
  true,
  'David López',
  'la_liga',
  'la_liga',
  array['Girona', 'RCD Espanyol Barcelona'],
  'Spain',
  'DF',
  1989,
  null,
  2013,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2013-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Spain defender in the 2013-2025 window.', 'SAMPLE: Club path in this league window: Girona, RCD Espanyol Barcelona.', 'SAMPLE: 258 appearances, 17 goals, 9 assists (26 combined) in the logged window.', 'SAMPLE: Initials D.L. Surname shape length 5.']
),
(
  '92cbc394',
  'fran-beltran',
  true,
  'Fran Beltrán',
  'la_liga',
  'la_liga',
  array['Celta de Vigo', 'Girona'],
  'Spain',
  'MF',
  1999,
  null,
  2018,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2018-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Spain midfielder in the 2018-2025 window.', 'SAMPLE: Club path in this league window: Celta de Vigo, Girona.', 'SAMPLE: 257 appearances, 9 goals, 3 assists (12 combined) in the logged window.', 'SAMPLE: Initials F.B. Surname shape length 7.']
),
(
  'e1967774',
  'unai-lopez',
  true,
  'Unai López',
  'la_liga',
  'la_liga',
  array['Athletic Bilbao', 'CD Leganés', 'Rayo Vallecano'],
  'Spain',
  'MF',
  1995,
  null,
  2014,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2014-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Spain midfielder in the 2014-2025 window.', 'SAMPLE: Club path in this league window: Athletic Bilbao, CD Leganés, Rayo Vallecano.', 'SAMPLE: 255 appearances, 11 goals, 13 assists (24 combined) in the logged window.', 'SAMPLE: Initials U.L. Surname shape length 5.']
),
(
  '54276f30',
  'mikel-balenziaga',
  true,
  'Mikel Balenziaga',
  'la_liga',
  'la_liga',
  array['Athletic Bilbao', 'Real Valladolid'],
  'Spain',
  'DF',
  1988,
  null,
  2012,
  2022,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2022 league regular logged near the top of the appearances table.', 'SAMPLE: A Spain defender in the 2012-2022 window.', 'SAMPLE: Club path in this league window: Athletic Bilbao, Real Valladolid.', 'SAMPLE: 253 appearances, 1 goals, 8 assists (9 combined) in the logged window.', 'SAMPLE: Initials M.B. Surname shape length 10.']
),
(
  'a4dab10b',
  'borja-iglesias',
  true,
  'Borja Iglesias',
  'la_liga',
  'la_liga',
  array['Celta de Vigo', 'RCD Espanyol Barcelona', 'Real Betis Balompié'],
  'Spain',
  'FW',
  1993,
  null,
  2014,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2014-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Spain forward in the 2014-2025 window.', 'SAMPLE: Club path in this league window: Celta de Vigo, RCD Espanyol Barcelona, Real Betis Balompié.', 'SAMPLE: 252 appearances, 81 goals, 15 assists (96 combined) in the logged window.', 'SAMPLE: Initials B.I. Surname shape length 8.']
),
(
  '1de8d074',
  'jose-maria-gimenez',
  true,
  'José María Giménez',
  'la_liga',
  'la_liga',
  array['Atletico Madrid'],
  'Uruguay',
  'DF',
  1995,
  null,
  2013,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2013-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Uruguay defender in the 2013-2025 window.', 'SAMPLE: Club path in this league window: Atletico Madrid.', 'SAMPLE: 248 appearances, 5 goals, 6 assists (11 combined) in the logged window.', 'SAMPLE: Initials J.M.G. Surname shape length 7.']
),
(
  '8c6eb2b1',
  'alex-remiro',
  true,
  'Álex Remiro',
  'la_liga',
  'la_liga',
  array['Real Sociedad'],
  'Spain',
  'GK',
  1995,
  null,
  2019,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2019-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Spain goalkeeper in the 2019-2025 window.', 'SAMPLE: Club path in this league window: Real Sociedad.', 'SAMPLE: 246 appearances, 0 goals, 0 assists (0 combined) in the logged window.', 'SAMPLE: Initials Á.R. Surname shape length 6.']
),
(
  '5d38ccda',
  'pape-diop',
  true,
  'Pape Diop',
  'la_liga',
  'la_liga',
  array['Levante UD', 'RCD Espanyol Barcelona', 'SD Eibar'],
  'Senegal',
  'MF',
  1986,
  null,
  2012,
  2020,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2020 league regular logged near the top of the appearances table.', 'SAMPLE: A Senegal midfielder in the 2012-2020 window.', 'SAMPLE: Club path in this league window: Levante UD, RCD Espanyol Barcelona, SD Eibar.', 'SAMPLE: 244 appearances, 10 goals, 5 assists (15 combined) in the logged window.', 'SAMPLE: Initials P.D. Surname shape length 4.']
),
(
  '55a14c55',
  'sergi-roberto',
  true,
  'Sergi Roberto',
  'la_liga',
  'la_liga',
  array['Barcelona'],
  'Spain',
  'MF',
  1992,
  null,
  2012,
  2023,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2023 league regular logged near the top of the appearances table.', 'SAMPLE: A Spain midfielder in the 2012-2023 window.', 'SAMPLE: Club path in this league window: Barcelona.', 'SAMPLE: 243 appearances, 12 goals, 33 assists (45 combined) in the logged window.', 'SAMPLE: Initials S.R. Surname shape length 7.']
),
(
  '5eb94936',
  'adrian-embarba',
  true,
  'Adrián Embarba',
  'la_liga',
  'la_liga',
  array['Rayo Vallecano', 'RCD Espanyol Barcelona', 'UD Almería'],
  'Spain',
  'FW',
  1992,
  null,
  2013,
  2024,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2013-2024 league regular logged near the top of the appearances table.', 'SAMPLE: A Spain forward in the 2013-2024 window.', 'SAMPLE: Club path in this league window: Rayo Vallecano, RCD Espanyol Barcelona, UD Almería.', 'SAMPLE: 240 appearances, 20 goals, 25 assists (45 combined) in the logged window.', 'SAMPLE: Initials A.E. Surname shape length 7.']
),
(
  '18d0f6b9',
  'nacho-fernandez',
  true,
  'Nacho Fernández',
  'la_liga',
  'la_liga',
  array['Real Madrid'],
  'Spain',
  'DF',
  1990,
  null,
  2012,
  2023,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2023 league regular logged near the top of the appearances table.', 'SAMPLE: A Spain defender in the 2012-2023 window.', 'SAMPLE: Club path in this league window: Real Madrid.', 'SAMPLE: 240 appearances, 12 goals, 7 assists (19 combined) in the logged window.', 'SAMPLE: Initials N.F. Surname shape length 9.']
),
(
  'c589895b',
  'leo-baptistao',
  true,
  'Léo Baptistão',
  'la_liga',
  'la_liga',
  array['Atletico Madrid', 'Rayo Vallecano', 'RCD Espanyol Barcelona', 'Real Betis Balompié', 'UD Almería', 'Villarreal'],
  'Brazil',
  'FW',
  1992,
  null,
  2012,
  2023,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2023 league regular logged near the top of the appearances table.', 'SAMPLE: A Brazil forward in the 2012-2023 window.', 'SAMPLE: Club path in this league window: Atletico Madrid, Rayo Vallecano, RCD Espanyol Barcelona, Real Betis Balompié.', 'SAMPLE: 238 appearances, 45 goals, 25 assists (70 combined) in the logged window.', 'SAMPLE: Initials L.B. Surname shape length 9.']
),
(
  'e422eac0',
  'tomas-pina',
  true,
  'Tomás Pina',
  'la_liga',
  'la_liga',
  array['Deportivo Alavés', 'RCD Mallorca', 'Villarreal'],
  'Spain',
  'MF',
  1987,
  null,
  2012,
  2021,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2021 league regular logged near the top of the appearances table.', 'SAMPLE: A Spain midfielder in the 2012-2021 window.', 'SAMPLE: Club path in this league window: Deportivo Alavés, RCD Mallorca, Villarreal.', 'SAMPLE: 238 appearances, 7 goals, 5 assists (12 combined) in the logged window.', 'SAMPLE: Initials T.P. Surname shape length 4.']
),
(
  'd2128adc',
  'jon-moncayola',
  true,
  'Jon Moncayola',
  'la_liga',
  'la_liga',
  array['CA Osasuna'],
  'Spain',
  'MF',
  1998,
  null,
  2019,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2019-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Spain midfielder in the 2019-2025 window.', 'SAMPLE: Club path in this league window: CA Osasuna.', 'SAMPLE: 237 appearances, 7 goals, 13 assists (20 combined) in the logged window.', 'SAMPLE: Initials J.M. Surname shape length 9.']
),
(
  'ab14d9d1',
  'kevin-gameiro',
  true,
  'Kévin Gameiro',
  'la_liga',
  'la_liga',
  array['Atletico Madrid', 'Sevilla', 'Valencia'],
  'France',
  'FW',
  1987,
  null,
  2013,
  2020,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2013-2020 league regular logged near the top of the appearances table.', 'SAMPLE: A France forward in the 2013-2020 window.', 'SAMPLE: Club path in this league window: Atletico Madrid, Sevilla, Valencia.', 'SAMPLE: 237 appearances, 74 goals, 22 assists (96 combined) in the logged window.', 'SAMPLE: Initials K.G. Surname shape length 7.']
),
(
  '318b4927',
  'sergi-gomez',
  true,
  'Sergi Gómez',
  'la_liga',
  'la_liga',
  array['Celta de Vigo', 'RCD Espanyol Barcelona', 'Sevilla'],
  'Spain',
  'DF',
  1992,
  null,
  2014,
  2024,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2014-2024 league regular logged near the top of the appearances table.', 'SAMPLE: A Spain defender in the 2014-2024 window.', 'SAMPLE: Club path in this league window: Celta de Vigo, RCD Espanyol Barcelona, Sevilla.', 'SAMPLE: 237 appearances, 2 goals, 3 assists (5 combined) in the logged window.', 'SAMPLE: Initials S.G. Surname shape length 5.']
),
(
  'a9753c8e',
  'unai-simon',
  true,
  'Unai Simón',
  'la_liga',
  'la_liga',
  array['Athletic Bilbao'],
  'Spain',
  'GK',
  1997,
  null,
  2018,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2018-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Spain goalkeeper in the 2018-2025 window.', 'SAMPLE: Club path in this league window: Athletic Bilbao.', 'SAMPLE: 237 appearances, 0 goals, 0 assists (0 combined) in the logged window.', 'SAMPLE: Initials U.S. Surname shape length 5.']
),
(
  'c6f1ff59',
  'alex-berenguer',
  true,
  'Álex Berenguer',
  'la_liga',
  'la_liga',
  array['Athletic Bilbao', 'CA Osasuna'],
  'Spain',
  'FW',
  1995,
  null,
  2016,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2016-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Spain forward in the 2016-2025 window.', 'SAMPLE: Club path in this league window: Athletic Bilbao, CA Osasuna.', 'SAMPLE: 237 appearances, 31 goals, 35 assists (66 combined) in the logged window.', 'SAMPLE: Initials Á.B. Surname shape length 9.']
),
(
  '71cd344e',
  'pedro-leon',
  true,
  'Pedro León',
  'la_liga',
  'la_liga',
  array['Getafe', 'SD Eibar'],
  'Spain',
  'FW',
  1986,
  null,
  2012,
  2020,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2020 league regular logged near the top of the appearances table.', 'SAMPLE: A Spain forward in the 2012-2020 window.', 'SAMPLE: Club path in this league window: Getafe, SD Eibar.', 'SAMPLE: 235 appearances, 27 goals, 36 assists (63 combined) in the logged window.', 'SAMPLE: Initials P.L. Surname shape length 4.']
),
(
  'ebd35fce',
  'vicente-iborra',
  true,
  'Vicente Iborra',
  'la_liga',
  'la_liga',
  array['Levante UD', 'Sevilla', 'Villarreal'],
  'Spain',
  'MF',
  1988,
  null,
  2012,
  2021,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2021 league regular logged near the top of the appearances table.', 'SAMPLE: A Spain midfielder in the 2012-2021 window.', 'SAMPLE: Club path in this league window: Levante UD, Sevilla, Villarreal.', 'SAMPLE: 234 appearances, 32 goals, 12 assists (44 combined) in the logged window.', 'SAMPLE: Initials V.I. Surname shape length 6.']
),
(
  '7c09bb00',
  'marko-dmitrovic',
  true,
  'Marko Dmitrovic',
  'la_liga',
  'la_liga',
  array['CD Leganés', 'RCD Espanyol Barcelona', 'SD Eibar', 'Sevilla'],
  'Serbia',
  'GK',
  1992,
  null,
  2017,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2017-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Serbia goalkeeper in the 2017-2025 window.', 'SAMPLE: Club path in this league window: CD Leganés, RCD Espanyol Barcelona, SD Eibar, Sevilla.', 'SAMPLE: 233 appearances, 1 goals, 0 assists (1 combined) in the logged window.', 'SAMPLE: Initials M.D. Surname shape length 9.']
),
(
  '03cba79e',
  'victor-sanchez',
  true,
  'Víctor Sánchez',
  'la_liga',
  'la_liga',
  array['RCD Espanyol Barcelona'],
  'Spain',
  'MF',
  1987,
  null,
  2012,
  2019,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2019 league regular logged near the top of the appearances table.', 'SAMPLE: A Spain midfielder in the 2012-2019 window.', 'SAMPLE: Club path in this league window: RCD Espanyol Barcelona.', 'SAMPLE: 233 appearances, 10 goals, 17 assists (27 combined) in the logged window.', 'SAMPLE: Initials V.S. Surname shape length 7.']
),
(
  'af6d9244',
  'ante-budimir',
  true,
  'Ante Budimir',
  'la_liga',
  'la_liga',
  array['CA Osasuna', 'RCD Mallorca'],
  'Croatia',
  'FW',
  1991,
  null,
  2019,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2019-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Croatia forward in the 2019-2025 window.', 'SAMPLE: Club path in this league window: CA Osasuna, RCD Mallorca.', 'SAMPLE: 232 appearances, 95 goals, 12 assists (107 combined) in the logged window.', 'SAMPLE: Initials A.B. Surname shape length 7.']
),
(
  '0cacd995',
  'piotr-zielinski',
  true,
  'Piotr Zielinski',
  'serie_a',
  'serie_a',
  array['Empoli', 'Inter Milan', 'SSC Napoli', 'Udinese Calcio'],
  'Poland',
  'MF',
  1994,
  null,
  2012,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Poland midfielder in the 2012-2025 window.', 'SAMPLE: Club path in this league window: Empoli, Inter Milan, SSC Napoli, Udinese Calcio.', 'SAMPLE: 423 appearances, 50 goals, 54 assists (104 combined) in the logged window.', 'SAMPLE: Initials P.Z. Surname shape length 9.']
),
(
  'bb7caf9f',
  'francesco-acerbi',
  true,
  'Francesco Acerbi',
  'serie_a',
  'serie_a',
  array['Milan', 'Chievo Verona', 'Inter Milan', 'Società Sportiva Lazio S.p.A.', 'US Sassuolo'],
  'Italy',
  'DF',
  1988,
  null,
  2012,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Italy defender in the 2012-2025 window.', 'SAMPLE: Club path in this league window: Milan, Chievo Verona, Inter Milan, Società Sportiva Lazio S.p.A..', 'SAMPLE: 406 appearances, 23 goals, 8 assists (31 combined) in the logged window.', 'SAMPLE: Initials F.A. Surname shape length 6.']
),
(
  'ea4be6ca',
  'antonio-candreva',
  true,
  'Antonio Candreva',
  'serie_a',
  'serie_a',
  array['Inter Milan', 'Società Sportiva Lazio S.p.A.', 'UC Sampdoria', 'US Salernitana 1919'],
  'Italy',
  'MF',
  1987,
  null,
  2012,
  2023,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2023 league regular logged near the top of the appearances table.', 'SAMPLE: A Italy midfielder in the 2012-2023 window.', 'SAMPLE: Club path in this league window: Inter Milan, Società Sportiva Lazio S.p.A., UC Sampdoria, US Salernitana 1919.', 'SAMPLE: 400 appearances, 75 goals, 89 assists (164 combined) in the logged window.', 'SAMPLE: Initials A.C. Surname shape length 8.']
),
(
  '505323f6',
  'alessio-romagnoli',
  true,
  'Alessio Romagnoli',
  'serie_a',
  'serie_a',
  array['Milan', 'Associazione Sportiva Roma', 'Società Sportiva Lazio S.p.A.', 'UC Sampdoria'],
  'Italy',
  'DF',
  1995,
  null,
  2012,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Italy defender in the 2012-2025 window.', 'SAMPLE: Club path in this league window: Milan, Associazione Sportiva Roma, Società Sportiva Lazio S.p.A., UC Sampdoria.', 'SAMPLE: 367 appearances, 15 goals, 4 assists (19 combined) in the logged window.', 'SAMPLE: Initials A.R. Surname shape length 9.']
),
(
  '50d16968',
  'matteo-politano',
  true,
  'Matteo Politano',
  'serie_a',
  'serie_a',
  array['Inter Milan', 'SSC Napoli', 'US Sassuolo'],
  'Italy',
  'FW',
  1993,
  null,
  2015,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2015-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Italy forward in the 2015-2025 window.', 'SAMPLE: Club path in this league window: Inter Milan, SSC Napoli, US Sassuolo.', 'SAMPLE: 363 appearances, 55 goals, 49 assists (104 combined) in the logged window.', 'SAMPLE: Initials M.P. Surname shape length 8.']
),
(
  '42417d79',
  'juan-cuadrado',
  true,
  'Juan Cuadrado',
  'serie_a',
  'serie_a',
  array['ACF Fiorentina', 'Atalanta BC', 'Inter Milan', 'Juventus', 'Pisa Sporting Club'],
  'Colombia',
  'MF',
  1988,
  null,
  2012,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Colombia midfielder in the 2012-2025 window.', 'SAMPLE: Club path in this league window: ACF Fiorentina, Atalanta BC, Inter Milan, Juventus.', 'SAMPLE: 361 appearances, 41 goals, 67 assists (108 combined) in the logged window.', 'SAMPLE: Initials J.C. Surname shape length 8.']
),
(
  'ae674fdb',
  'andrea-belotti',
  true,
  'Andrea Belotti',
  'serie_a',
  'serie_a',
  array['ACF Fiorentina', 'Associazione Sportiva Roma', 'Cagliari Calcio', 'Como 1907', 'Palermo', 'Torino'],
  'Italy',
  'FW',
  1993,
  null,
  2014,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2014-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Italy forward in the 2014-2025 window.', 'SAMPLE: Club path in this league window: ACF Fiorentina, Associazione Sportiva Roma, Cagliari Calcio, Como 1907.', 'SAMPLE: 356 appearances, 116 goals, 32 assists (148 combined) in the logged window.', 'SAMPLE: Initials A.B. Surname shape length 7.']
),
(
  'cf16604c',
  'duvan-zapata',
  true,
  'Duván Zapata',
  'serie_a',
  'serie_a',
  array['Atalanta BC', 'SSC Napoli', 'Torino', 'UC Sampdoria', 'Udinese Calcio'],
  'Colombia',
  'FW',
  1991,
  null,
  2013,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2013-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Colombia forward in the 2013-2025 window.', 'SAMPLE: Club path in this league window: Atalanta BC, SSC Napoli, Torino, UC Sampdoria.', 'SAMPLE: 354 appearances, 127 goals, 52 assists (179 combined) in the logged window.', 'SAMPLE: Initials D.Z. Surname shape length 6.']
),
(
  '79cde65a',
  'giacomo-bonaventura',
  true,
  'Giacomo Bonaventura',
  'serie_a',
  'serie_a',
  array['Milan', 'ACF Fiorentina', 'Atalanta BC'],
  'Italy',
  'MF',
  1989,
  null,
  2012,
  2023,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2023 league regular logged near the top of the appearances table.', 'SAMPLE: A Italy midfielder in the 2012-2023 window.', 'SAMPLE: Club path in this league window: Milan, ACF Fiorentina, Atalanta BC.', 'SAMPLE: 348 appearances, 62 goals, 54 assists (116 combined) in the logged window.', 'SAMPLE: Initials G.B. Surname shape length 11.']
),
(
  'cd2825e9',
  'cristiano-biraghi',
  true,
  'Cristiano Biraghi',
  'serie_a',
  'serie_a',
  array['ACF Fiorentina', 'Catania', 'Chievo Verona', 'Delfino Pescara 1936', 'Inter Milan', 'Torino'],
  'Italy',
  'DF',
  1992,
  null,
  2013,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2013-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Italy defender in the 2013-2025 window.', 'SAMPLE: Club path in this league window: ACF Fiorentina, Catania, Chievo Verona, Delfino Pescara 1936.', 'SAMPLE: 343 appearances, 15 goals, 38 assists (53 combined) in the logged window.', 'SAMPLE: Initials C.B. Surname shape length 7.']
),
(
  '8be26e05',
  'lorenzo-de-silvestri',
  true,
  'Lorenzo De Silvestri',
  'serie_a',
  'serie_a',
  array['Bologna Football Club 1909', 'Torino', 'UC Sampdoria'],
  'Italy',
  'DF',
  1988,
  null,
  2012,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Italy defender in the 2012-2025 window.', 'SAMPLE: Club path in this league window: Bologna Football Club 1909, Torino, UC Sampdoria.', 'SAMPLE: 341 appearances, 26 goals, 20 assists (46 combined) in the logged window.', 'SAMPLE: Initials L.D.S. Surname shape length 9.']
),
(
  'f7d0c09d',
  'bryan-cristante',
  true,
  'Bryan Cristante',
  'serie_a',
  'serie_a',
  array['Milan', 'Associazione Sportiva Roma', 'Atalanta BC', 'Delfino Pescara 1936', 'Palermo'],
  'Italy',
  'MF',
  1995,
  null,
  2013,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2013-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Italy midfielder in the 2013-2025 window.', 'SAMPLE: Club path in this league window: Milan, Associazione Sportiva Roma, Atalanta BC, Delfino Pescara 1936.', 'SAMPLE: 340 appearances, 31 goals, 22 assists (53 combined) in the logged window.', 'SAMPLE: Initials B.C. Surname shape length 9.']
),
(
  '6f1fc4db',
  'domenico-berardi',
  true,
  'Domenico Berardi',
  'serie_a',
  'serie_a',
  array['US Sassuolo'],
  'Italy',
  'FW',
  1994,
  null,
  2013,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2013-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Italy forward in the 2013-2025 window.', 'SAMPLE: Club path in this league window: US Sassuolo.', 'SAMPLE: 340 appearances, 130 goals, 88 assists (218 combined) in the logged window.', 'SAMPLE: Initials D.B. Surname shape length 7.']
),
(
  '7fc0b6bf',
  'giovanni-simeone',
  true,
  'Giovanni Simeone',
  'serie_a',
  'serie_a',
  array['ACF Fiorentina', 'Cagliari Calcio', 'Genoa CFC', 'Hellas Verona', 'SSC Napoli', 'Torino'],
  'Argentina',
  'FW',
  1995,
  null,
  2016,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2016-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Argentina forward in the 2016-2025 window.', 'SAMPLE: Club path in this league window: ACF Fiorentina, Cagliari Calcio, Genoa CFC, Hellas Verona.', 'SAMPLE: 330 appearances, 84 goals, 25 assists (109 combined) in the logged window.', 'SAMPLE: Initials G.S. Surname shape length 7.']
),
(
  '36fd1955',
  'stephan-el-shaarawy',
  true,
  'Stephan El Shaarawy',
  'serie_a',
  'serie_a',
  array['Milan', 'Associazione Sportiva Roma'],
  'Italy',
  'FW',
  1992,
  null,
  2012,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Italy forward in the 2012-2025 window.', 'SAMPLE: Club path in this league window: Milan, Associazione Sportiva Roma.', 'SAMPLE: 320 appearances, 71 goals, 41 assists (112 combined) in the logged window.', 'SAMPLE: Initials S.E.S. Surname shape length 8.']
),
(
  '5727265b',
  'manuel-locatelli',
  true,
  'Manuel Locatelli',
  'serie_a',
  'serie_a',
  array['Milan', 'Juventus', 'US Sassuolo'],
  'Italy',
  'MF',
  1998,
  null,
  2015,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2015-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Italy midfielder in the 2015-2025 window.', 'SAMPLE: Club path in this league window: Milan, Juventus, US Sassuolo.', 'SAMPLE: 315 appearances, 15 goals, 25 assists (40 combined) in the logged window.', 'SAMPLE: Initials M.L. Surname shape length 9.']
),
(
  'e1e9e70a',
  'danilo-d-ambrosio',
  true,
  'Danilo D''Ambrosio',
  'serie_a',
  'serie_a',
  array['Monza', 'Inter Milan', 'Torino'],
  'Italy',
  'DF',
  1988,
  null,
  2012,
  2024,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2024 league regular logged near the top of the appearances table.', 'SAMPLE: A Italy defender in the 2012-2024 window.', 'SAMPLE: Club path in this league window: Monza, Inter Milan, Torino.', 'SAMPLE: 312 appearances, 21 goals, 25 assists (46 combined) in the logged window.', 'SAMPLE: Initials D.D. Surname shape length 8.']
),
(
  '59c5ff66',
  'matias-vecino',
  true,
  'Matías Vecino',
  'serie_a',
  'serie_a',
  array['ACF Fiorentina', 'Cagliari Calcio', 'Empoli', 'Inter Milan', 'Società Sportiva Lazio S.p.A.'],
  'Uruguay',
  'MF',
  1991,
  null,
  2013,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2013-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Uruguay midfielder in the 2013-2025 window.', 'SAMPLE: Club path in this league window: ACF Fiorentina, Cagliari Calcio, Empoli, Inter Milan.', 'SAMPLE: 312 appearances, 29 goals, 21 assists (50 combined) in the logged window.', 'SAMPLE: Initials M.V. Surname shape length 6.']
),
(
  '4da003ac',
  'stefan-de-vrij',
  true,
  'Stefan de Vrij',
  'serie_a',
  'serie_a',
  array['Inter Milan', 'Società Sportiva Lazio S.p.A.'],
  'Netherlands',
  'DF',
  1992,
  null,
  2014,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2014-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Netherlands defender in the 2014-2025 window.', 'SAMPLE: Club path in this league window: Inter Milan, Società Sportiva Lazio S.p.A..', 'SAMPLE: 308 appearances, 20 goals, 6 assists (26 combined) in the logged window.', 'SAMPLE: Initials S.D.V. Surname shape length 4.']
),
(
  'b82cd7e7',
  'danilo',
  true,
  'Danilo',
  'serie_a',
  'serie_a',
  array['Bologna Football Club 1909', 'Udinese Calcio'],
  'Brazil',
  'DF',
  1984,
  null,
  2012,
  2020,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2020 league regular logged near the top of the appearances table.', 'SAMPLE: A Brazil defender in the 2012-2020 window.', 'SAMPLE: Club path in this league window: Bologna Football Club 1909, Udinese Calcio.', 'SAMPLE: 307 appearances, 11 goals, 2 assists (13 combined) in the logged window.', 'SAMPLE: Initials D. Surname shape length 6.']
),
(
  'c191073a',
  'jose-callejon',
  true,
  'José Callejón',
  'serie_a',
  'serie_a',
  array['ACF Fiorentina', 'SSC Napoli'],
  'Spain',
  'FW',
  1987,
  null,
  2013,
  2021,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2013-2021 league regular logged near the top of the appearances table.', 'SAMPLE: A Spain forward in the 2013-2021 window.', 'SAMPLE: Club path in this league window: ACF Fiorentina, SSC Napoli.', 'SAMPLE: 305 appearances, 65 goals, 60 assists (125 combined) in the logged window.', 'SAMPLE: Initials J.C. Surname shape length 8.']
),
(
  'b4f2d837',
  'remo-freuler',
  true,
  'Remo Freuler',
  'serie_a',
  'serie_a',
  array['Atalanta BC', 'Bologna Football Club 1909'],
  'Switzerland',
  'MF',
  1992,
  null,
  2015,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2015-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Switzerland midfielder in the 2015-2025 window.', 'SAMPLE: Club path in this league window: Atalanta BC, Bologna Football Club 1909.', 'SAMPLE: 301 appearances, 21 goals, 21 assists (42 combined) in the logged window.', 'SAMPLE: Initials R.F. Surname shape length 7.']
),
(
  'e0aeeb09',
  'lorenzo-pellegrini',
  true,
  'Lorenzo Pellegrini',
  'serie_a',
  'serie_a',
  array['Associazione Sportiva Roma', 'US Sassuolo'],
  'Italy',
  'MF',
  1996,
  null,
  2014,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2014-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Italy midfielder in the 2014-2025 window.', 'SAMPLE: Club path in this league window: Associazione Sportiva Roma, US Sassuolo.', 'SAMPLE: 300 appearances, 50 goals, 49 assists (99 combined) in the logged window.', 'SAMPLE: Initials L.P. Surname shape length 10.']
),
(
  '03141b3a',
  'luis-muriel',
  true,
  'Luis Muriel',
  'serie_a',
  'serie_a',
  array['ACF Fiorentina', 'Atalanta BC', 'UC Sampdoria', 'Udinese Calcio'],
  'Colombia',
  'FW',
  1991,
  null,
  2012,
  2023,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2023 league regular logged near the top of the appearances table.', 'SAMPLE: A Colombia forward in the 2012-2023 window.', 'SAMPLE: Club path in this league window: ACF Fiorentina, Atalanta BC, UC Sampdoria, Udinese Calcio.', 'SAMPLE: 299 appearances, 96 goals, 45 assists (141 combined) in the logged window.', 'SAMPLE: Initials L.M. Surname shape length 6.']
),
(
  '6d0c8961',
  'darko-lazovic',
  true,
  'Darko Lazović',
  'serie_a',
  'serie_a',
  array['Genoa CFC', 'Hellas Verona'],
  'Serbia',
  'MF',
  1990,
  null,
  2015,
  2024,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2015-2024 league regular logged near the top of the appearances table.', 'SAMPLE: A Serbia midfielder in the 2015-2024 window.', 'SAMPLE: Club path in this league window: Genoa CFC, Hellas Verona.', 'SAMPLE: 295 appearances, 21 goals, 42 assists (63 combined) in the logged window.', 'SAMPLE: Initials D.L. Surname shape length 7.']
),
(
  'fb371e7e',
  'alessandro-florenzi',
  true,
  'Alessandro Florenzi',
  'serie_a',
  'serie_a',
  array['Milan', 'Associazione Sportiva Roma'],
  'Italy',
  'DF',
  1991,
  null,
  2012,
  2024,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2024 league regular logged near the top of the appearances table.', 'SAMPLE: A Italy defender in the 2012-2024 window.', 'SAMPLE: Club path in this league window: Milan, Associazione Sportiva Roma.', 'SAMPLE: 287 appearances, 28 goals, 33 assists (61 combined) in the logged window.', 'SAMPLE: Initials A.F. Surname shape length 8.']
),
(
  '4779a060',
  'mario-pasalic',
  true,
  'Mario Pašalić',
  'serie_a',
  'serie_a',
  array['Milan', 'Atalanta BC'],
  'Croatia',
  'MF',
  1995,
  null,
  2016,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2016-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Croatia midfielder in the 2016-2025 window.', 'SAMPLE: Club path in this league window: Milan, Atalanta BC.', 'SAMPLE: 287 appearances, 55 goals, 34 assists (89 combined) in the logged window.', 'SAMPLE: Initials M.P. Surname shape length 7.']
),
(
  'f53f0dd8',
  'matteo-darmian',
  true,
  'Matteo Darmian',
  'serie_a',
  'serie_a',
  array['Inter Milan', 'Parma Calcio 1913', 'Torino'],
  'Italy',
  'DF',
  1989,
  null,
  2012,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Italy defender in the 2012-2025 window.', 'SAMPLE: Club path in this league window: Inter Milan, Parma Calcio 1913, Torino.', 'SAMPLE: 286 appearances, 14 goals, 18 assists (32 combined) in the logged window.', 'SAMPLE: Initials M.D. Surname shape length 7.']
),
(
  'cf94940e',
  'armando-izzo',
  true,
  'Armando Izzo',
  'serie_a',
  'serie_a',
  array['Monza', 'Genoa CFC', 'Torino'],
  'Italy',
  'DF',
  1992,
  null,
  2014,
  2024,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2014-2024 league regular logged near the top of the appearances table.', 'SAMPLE: A Italy defender in the 2014-2024 window.', 'SAMPLE: Club path in this league window: Monza, Genoa CFC, Torino.', 'SAMPLE: 285 appearances, 11 goals, 5 assists (16 combined) in the logged window.', 'SAMPLE: Initials A.I. Surname shape length 4.']
),
(
  'b96250f2',
  'hakan-calhanoglu',
  true,
  'Hakan Çalhanoğlu',
  'serie_a',
  'serie_a',
  array['Milan', 'Inter Milan'],
  'Türkiye',
  'MF',
  1994,
  null,
  2017,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2017-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Türkiye midfielder in the 2017-2025 window.', 'SAMPLE: Club path in this league window: Milan, Inter Milan.', 'SAMPLE: 285 appearances, 59 goals, 66 assists (125 combined) in the logged window.', 'SAMPLE: Initials H.Ç. Surname shape length 10.']
),
(
  '6b773cf2',
  'berat-djimsiti',
  true,
  'Berat Djimsiti',
  'serie_a',
  'serie_a',
  array['Atalanta BC', 'Benevento Calcio'],
  'Albania',
  'DF',
  1993,
  null,
  2015,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2015-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Albania defender in the 2015-2025 window.', 'SAMPLE: Club path in this league window: Atalanta BC, Benevento Calcio.', 'SAMPLE: 284 appearances, 5 goals, 11 assists (16 combined) in the logged window.', 'SAMPLE: Initials B.D. Surname shape length 8.']
),
(
  '52026886',
  'gianluca-mancini',
  true,
  'Gianluca Mancini',
  'serie_a',
  'serie_a',
  array['Associazione Sportiva Roma', 'Atalanta BC'],
  'Italy',
  'DF',
  1996,
  null,
  2017,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2017-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Italy defender in the 2017-2025 window.', 'SAMPLE: Club path in this league window: Associazione Sportiva Roma, Atalanta BC.', 'SAMPLE: 283 appearances, 22 goals, 10 assists (32 combined) in the logged window.', 'SAMPLE: Initials G.M. Surname shape length 7.']
),
(
  '44962ac2',
  'adam-marusic',
  true,
  'Adam Marusic',
  'serie_a',
  'serie_a',
  array['Società Sportiva Lazio S.p.A.'],
  'Montenegro',
  'DF',
  1992,
  null,
  2017,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2017-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Montenegro defender in the 2017-2025 window.', 'SAMPLE: Club path in this league window: Società Sportiva Lazio S.p.A..', 'SAMPLE: 280 appearances, 15 goals, 16 assists (31 combined) in the logged window.', 'SAMPLE: Initials A.M. Surname shape length 7.']
),
(
  '9ce25180',
  'riccardo-orsolini',
  true,
  'Riccardo Orsolini',
  'serie_a',
  'serie_a',
  array['Atalanta BC', 'Bologna Football Club 1909'],
  'Italy',
  'FW',
  1997,
  null,
  2017,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2017-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Italy forward in the 2017-2025 window.', 'SAMPLE: Club path in this league window: Atalanta BC, Bologna Football Club 1909.', 'SAMPLE: 280 appearances, 75 goals, 31 assists (106 combined) in the logged window.', 'SAMPLE: Initials R.O. Surname shape length 8.']
),
(
  'a8372324',
  'edin-dzeko',
  true,
  'Edin Dzeko',
  'serie_a',
  'serie_a',
  array['ACF Fiorentina', 'Associazione Sportiva Roma', 'Inter Milan'],
  'Bosnia and Herzegovina',
  'FW',
  1986,
  null,
  2015,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2015-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Bosnia and Herzegovina forward in the 2015-2025 window.', 'SAMPLE: Club path in this league window: ACF Fiorentina, Associazione Sportiva Roma, Inter Milan.', 'SAMPLE: 279 appearances, 107 goals, 50 assists (157 combined) in the logged window.', 'SAMPLE: Initials E.D. Surname shape length 5.']
),
(
  '31e0e7f6',
  'juan-jesus',
  true,
  'Juan Jesus',
  'serie_a',
  'serie_a',
  array['Associazione Sportiva Roma', 'Inter Milan', 'SSC Napoli'],
  'Brazil',
  'DF',
  1991,
  null,
  2012,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Brazil defender in the 2012-2025 window.', 'SAMPLE: Club path in this league window: Associazione Sportiva Roma, Inter Milan, SSC Napoli.', 'SAMPLE: 279 appearances, 5 goals, 2 assists (7 combined) in the logged window.', 'SAMPLE: Initials J.J. Surname shape length 5.']
),
(
  '0680c157',
  'roberto-soriano',
  true,
  'Roberto Soriano',
  'serie_a',
  'serie_a',
  array['Bologna Football Club 1909', 'Torino', 'UC Sampdoria'],
  'Italy',
  'MF',
  1991,
  null,
  2012,
  2022,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2022 league regular logged near the top of the appearances table.', 'SAMPLE: A Italy midfielder in the 2012-2022 window.', 'SAMPLE: Club path in this league window: Bologna Football Club 1909, Torino, UC Sampdoria.', 'SAMPLE: 279 appearances, 34 goals, 32 assists (66 combined) in the logged window.', 'SAMPLE: Initials R.S. Surname shape length 7.']
),
(
  '4feeed88',
  'gregoire-defrel',
  true,
  'Grégoire Defrel',
  'serie_a',
  'serie_a',
  array['Associazione Sportiva Roma', 'Cesena', 'UC Sampdoria', 'US Sassuolo'],
  'France',
  'FW',
  1991,
  null,
  2014,
  2023,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2014-2023 league regular logged near the top of the appearances table.', 'SAMPLE: A France forward in the 2014-2023 window.', 'SAMPLE: Club path in this league window: Associazione Sportiva Roma, Cesena, UC Sampdoria, US Sassuolo.', 'SAMPLE: 277 appearances, 51 goals, 28 assists (79 combined) in the logged window.', 'SAMPLE: Initials G.D. Surname shape length 6.']
),
(
  '9e93aad3',
  'nicola-sansone',
  true,
  'Nicola Sansone',
  'serie_a',
  'serie_a',
  array['Bologna Football Club 1909', 'Parma Calcio 1913', 'US Lecce', 'US Sassuolo'],
  'Italy',
  'FW',
  1991,
  null,
  2012,
  2024,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2024 league regular logged near the top of the appearances table.', 'SAMPLE: A Italy forward in the 2012-2024 window.', 'SAMPLE: Club path in this league window: Bologna Football Club 1909, Parma Calcio 1913, US Lecce, US Sassuolo.', 'SAMPLE: 276 appearances, 41 goals, 42 assists (83 combined) in the logged window.', 'SAMPLE: Initials N.S. Surname shape length 7.']
),
(
  'bec1b38e',
  'rolando-mandragora',
  true,
  'Rolando Mandragora',
  'serie_a',
  'serie_a',
  array['ACF Fiorentina', 'Crotone', 'Genoa CFC', 'Juventus', 'Torino', 'Udinese Calcio'],
  'Italy',
  'MF',
  1997,
  null,
  2014,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2014-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Italy midfielder in the 2014-2025 window.', 'SAMPLE: Club path in this league window: ACF Fiorentina, Crotone, Genoa CFC, Juventus.', 'SAMPLE: 276 appearances, 24 goals, 22 assists (46 combined) in the logged window.', 'SAMPLE: Initials R.M. Surname shape length 10.']
),
(
  '703cfba2',
  'giovanni-di-lorenzo',
  true,
  'Giovanni Di Lorenzo',
  'serie_a',
  'serie_a',
  array['Empoli', 'SSC Napoli'],
  'Italy',
  'DF',
  1993,
  null,
  2018,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2018-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Italy defender in the 2018-2025 window.', 'SAMPLE: Club path in this league window: Empoli, SSC Napoli.', 'SAMPLE: 275 appearances, 21 goals, 35 assists (56 combined) in the logged window.', 'SAMPLE: Initials G.D.L. Surname shape length 7.']
),
(
  '5d6e2022',
  'milan-badelj',
  true,
  'Milan Badelj',
  'serie_a',
  'serie_a',
  array['ACF Fiorentina', 'Genoa CFC', 'Società Sportiva Lazio S.p.A.'],
  'Croatia',
  'MF',
  1989,
  null,
  2014,
  2024,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2014-2024 league regular logged near the top of the appearances table.', 'SAMPLE: A Croatia midfielder in the 2014-2024 window.', 'SAMPLE: Club path in this league window: ACF Fiorentina, Genoa CFC, Società Sportiva Lazio S.p.A..', 'SAMPLE: 273 appearances, 12 goals, 15 assists (27 combined) in the logged window.', 'SAMPLE: Initials M.B. Surname shape length 6.']
),
(
  'fca7e627',
  'wojciech-szczesny',
  true,
  'Wojciech Szczesny',
  'serie_a',
  'serie_a',
  array['Associazione Sportiva Roma', 'Juventus'],
  'Poland',
  'GK',
  1990,
  null,
  2015,
  2023,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2015-2023 league regular logged near the top of the appearances table.', 'SAMPLE: A Poland goalkeeper in the 2015-2023 window.', 'SAMPLE: Club path in this league window: Associazione Sportiva Roma, Juventus.', 'SAMPLE: 272 appearances, 0 goals, 1 assists (1 combined) in the logged window.', 'SAMPLE: Initials W.S. Surname shape length 8.']
)
on conflict (id) do update set
  person_id = excluded.person_id,
  canonical = excluded.canonical,
  name = excluded.name,
  category = excluded.category,
  league = excluded.league,
  clubs = excluded.clubs,
  nationality = excluded.nationality,
  position = excluded.position,
  birth_year = excluded.birth_year,
  shirt_number = excluded.shirt_number,
  era_start = excluded.era_start,
  era_end = excluded.era_end,
  world_cup_editions = excluded.world_cup_editions,
  aliases = excluded.aliases,
  clues = excluded.clues;

