-- Batch 3/6: rows 161-240 of 407
-- Paste into Supabase SQL Editor and Run (in order 01 → 06)
insert into public.players (
  id, person_id, canonical, name, category, league, clubs,
  nationality, position, birth_year, shirt_number, era_start, era_end,
  world_cup_editions, aliases, clues
) values
(
  '9a4edcd7',
  'sergio-busquets',
  true,
  'Sergio Busquets',
  'la_liga',
  'la_liga',
  array['Barcelona'],
  'Spain',
  'MF',
  1988,
  5,
  2008,
  2023,
  array[]::integer[],
  array[]::text[],
  array['You watch the game, you don''t see him. You watch him, you see the whole game.', 'A Spanish pivot who made one touch decisions look pre recorded.', 'La Masia to fifteen years of invisible dominance.', 'The 2011 peak, the axis of the greatest club side ever.', 'Busi. Initials S.B.']
),
(
  'a36bae3e',
  'iker-casillas',
  false,
  'Iker Casillas',
  'la_liga',
  'la_liga',
  array['Real Madrid'],
  'Spain',
  'GK',
  1981,
  1,
  1999,
  2015,
  array[]::integer[],
  array['San Iker'],
  array['A teenager thrown into goal for Madrid who stayed for 725 games.', 'A Spanish goalkeeper of reflex saves that broke replay machines.', 'Madrid academy to five league titles and a Porto farewell.', 'The double save against Robben''s through balls, repeatedly, everywhere.', 'San Iker. Initials I.C.']
),
(
  '62bda145',
  'sergio-ramos',
  true,
  'Sergio Ramos',
  'la_liga',
  'la_liga',
  array['Real Madrid', 'Sevilla'],
  'Spain',
  'DF',
  1986,
  4,
  2004,
  2021,
  array[]::integer[],
  array[]::text[],
  array['More red cards than any Madrid player, more clutch goals than most strikers.', 'A Spanish center back who defended like a duelist and scored like a nine.', 'Sevilla''s kid to Madrid''s captain, five titles.', '93:12 exists because of his header habit, minted in Lisbon.', 'Initials S.R.']
),
(
  '76e9609b',
  'cristiano-ronaldo',
  false,
  'Cristiano Ronaldo',
  'la_liga',
  'la_liga',
  array['Real Madrid'],
  'Portugal',
  'FW',
  1985,
  7,
  2009,
  2018,
  array[]::integer[],
  array['CR7'],
  array['311 league goals in 292 games. La Liga never saw a ratio like it.', 'A Portuguese forward at war with Messi across nine seasons of absurdity.', 'A world record from Manchester to nine years in white.', 'The 2011-12 title, 46 goals, scoring away at every single club.', 'CR7.']
),
(
  'b16ddca4',
  'karim-benzema',
  true,
  'Karim Benzema',
  'la_liga',
  'la_liga',
  array['Real Madrid'],
  'France',
  'FW',
  1987,
  9,
  2009,
  2023,
  array[]::integer[],
  array['Big Benz'],
  array['He waited a decade as the supporting act, then won the Ballon d''Or as the lead.', 'A French number nine of velvet touch and late career explosion.', 'Lyon''s prodigy to Madrid''s record books.', 'The 2022 comeback season, hat tricks against PSG and Chelsea.', 'Big Benz. Initials K.B.']
),
(
  'f081ffd9',
  'luka-modric',
  false,
  'Luka Modric',
  'la_liga',
  'la_liga',
  array['Real Madrid'],
  'Croatia',
  'MF',
  1985,
  10,
  2012,
  2025,
  array[]::integer[],
  array[]::text[],
  array['A Ballon d''Or interrupting the Messi Ronaldo duopoly, won from Madrid''s midfield.', 'A Croatian midfielder who outside of the boots passes his way through press conferences too.', 'Spurs to more than a decade in white.', 'The 2018 golden year, Champions League and World Cup final.', 'Initials L.M.']
),
(
  'ae778d63',
  'toni-kroos',
  false,
  'Toni Kroos',
  'la_liga',
  'la_liga',
  array['Real Madrid'],
  'Germany',
  'MF',
  1990,
  8,
  2014,
  2024,
  array[]::integer[],
  array[]::text[],
  array['Six Champions Leagues and a retirement while still the best passer in Spain.', 'A German midfielder who completed passes like other people breathe.', 'Bayern to a decade of Madrid trophies.', 'The 2024 farewell season, still untouchable at 34.', 'Initials T.K.']
),
(
  'e17ee318',
  'gareth-bale',
  false,
  'Gareth Bale',
  'la_liga',
  'la_liga',
  array['Real Madrid'],
  'Wales',
  'FW',
  1989,
  11,
  2013,
  2022,
  array[]::integer[],
  array[]::text[],
  array['Golf. Madrid. Wales. In that order, said the flag, and he never disagreed.', 'A Welsh forward of overhead kicks and outside lane sprints.', 'A world record from Spurs to five Champions Leagues.', 'The 2014 Copa final run around Bartra, off the pitch and back.', 'Initials G.B.']
),
(
  '790a1811',
  'luis-suarez',
  false,
  'Luis Suarez',
  'la_liga',
  'la_liga',
  array['Barcelona', 'Atletico Madrid'],
  'Uruguay',
  'FW',
  1987,
  9,
  2014,
  2022,
  array[]::integer[],
  array[]::text[],
  array['The front three''s finisher, then Atletico''s revenge title after Barcelona binned him.', 'A Uruguayan striker who scored 40 in the treble season''s league run.', 'Liverpool to MSN to a title winning Atletico exile.', 'The 2021 title clincher for Atletico, tears at full time.', 'El Pistolero. Initials L.S.']
),
(
  '5de16f86',
  'neymar',
  true,
  'Neymar',
  'la_liga',
  'la_liga',
  array['Barcelona'],
  'Brazil',
  'FW',
  1992,
  11,
  2013,
  2017,
  array[]::integer[],
  array['Ney'],
  array['The N in the greatest front three ever assembled in Spain.', 'A Brazilian winger of dazzle, dives and 105 goals in four years.', 'Santos to Barcelona''s treble to the world record exit.', 'The 2015 treble as MSN''s third blade.', 'Ney. Initials N.']
),
(
  'b0bb4038',
  'antoine-griezmann',
  false,
  'Antoine Griezmann',
  'la_liga',
  'la_liga',
  array['Atletico Madrid', 'Real Sociedad'],
  'France',
  'FW',
  1991,
  7,
  2009,
  2026,
  array[]::integer[],
  array[]::text[],
  array['Atletico''s golden boy twice over, with an awkward Barcelona sandwich between.', 'A French forward who does every job and celebrates like a gamer.', 'Sociedad to Atletico''s title machine, out and back again.', 'The 2021 title era and a decade of big Atletico nights.', 'Grizi. Initials A.G.']
),
(
  'd0f0e0ac',
  'hristo-stoichkov',
  false,
  'Hristo Stoichkov',
  'la_liga',
  'la_liga',
  array['Barcelona'],
  'Bulgaria',
  'FW',
  1966,
  8,
  1992,
  1998,
  array[]::integer[],
  array[]::text[],
  array['The angriest man in Cruyff''s Dream Team, and its sharpest blade.', 'A Bulgarian forward who once stamped a referee and won a Ballon d''Or anyway.', 'CSKA to four straight titles at Barcelona.', 'The 1994 title charge, snarling all the way.', 'Initials H.S.']
),
(
  'fec5f26f',
  'romario',
  false,
  'Romario',
  'la_liga',
  'la_liga',
  array['Barcelona', 'Valencia'],
  'Brazil',
  'FW',
  1966,
  10,
  1993,
  1996,
  array[]::integer[],
  array[]::text[],
  array['Cruyff promised he''d score 30. He scored 30, then told everyone he told them.', 'A Brazilian penalty box predator on a Barcelona layover.', 'Vasco to the Dream Team''s spearhead.', 'The 1994 Clasico hat trick, cow tail flick included.', 'Initials R.']
),
(
  '086efc0d',
  'rivaldo',
  false,
  'Rivaldo',
  'la_liga',
  'la_liga',
  array['Barcelona', 'Deportivo La Coruna'],
  'Brazil',
  'MF',
  1972,
  10,
  1996,
  2002,
  array[]::integer[],
  array[]::text[],
  array['An overhead kick in minute 90 of the final match to reach the Champions League.', 'A Brazilian number ten carrying Barcelona between two golden eras.', 'Deportivo to Barcelona''s Ballon d''Or years.', 'The 2001 hat trick against Valencia, capped by the bicycle.', 'Initials R.']
),
(
  '83c630cf',
  'patrick-kluivert',
  true,
  'Patrick Kluivert',
  'la_liga',
  'la_liga',
  array['Barcelona'],
  'Netherlands',
  'FW',
  1976,
  9,
  1998,
  2004,
  array[]::integer[],
  array[]::text[],
  array['The Ajax wonderboy led Barcelona''s line either side of the millennium.', 'A Dutch number nine of first time finishes and famous genes.', 'Milan misstep to five Barcelona seasons.', 'The 1998-99 title, spearheading Van Gaal''s Dutch colony.', 'Initials P.K.']
),
(
  '131e7dd6',
  'samuel-etoo',
  true,
  'Samuel Etoo',
  'la_liga',
  'la_liga',
  array['Barcelona', 'Mallorca'],
  'Cameroon',
  'FW',
  1981,
  9,
  2000,
  2009,
  array[]::integer[],
  array[]::text[],
  array['Bought from Mallorca, he told Madrid''s discards he''d run like a black man to live like a white one, then apologized and just scored instead.', 'A Cameroonian striker of pace, fury and enormous finals.', 'Mallorca''s star to Barcelona''s treble spearhead.', 'Scoring in the 2006 and 2009 Champions League finals.', 'Initials S.E.']
),
(
  'c6708fcb',
  'david-villa',
  false,
  'David Villa',
  'la_liga',
  'la_liga',
  array['Valencia', 'Barcelona', 'Atletico Madrid'],
  'Spain',
  'FW',
  1981,
  7,
  2003,
  2014,
  array[]::integer[],
  array['El Guaje'],
  array['Spain''s record scorer finally got his Barcelona move and a Wembley final goal.', 'A Spanish striker whose left foot never needed a second invitation.', 'Sporting to Valencia''s idol to the 2011 treble.', 'The Wembley 2011 final, curling in the third.', 'El Guaje. Initials D.V.']
),
(
  '554c57da',
  'fernando-torres',
  false,
  'Fernando Torres',
  'la_liga',
  'la_liga',
  array['Atletico Madrid'],
  'Spain',
  'FW',
  1984,
  9,
  2001,
  2019,
  array[]::integer[],
  array['El Nino'],
  array['The teenage captain of Atletico before the fifty million pound world knew him.', 'A Spanish striker, blond braid years, Calderon prince years.', 'Atletico''s boy captain, back home for the last dance.', 'Returning in 2015 to the Calderon''s loudest welcome.', 'El Nino. Initials F.T.']
),
(
  '67f20b21',
  'diego-forlan',
  false,
  'Diego Forlan',
  'la_liga',
  'la_liga',
  array['Atletico Madrid', 'Villarreal'],
  'Uruguay',
  'FW',
  1979,
  7,
  2004,
  2011,
  array[]::integer[],
  array[]::text[],
  array['Two European Golden Shoes in Spain, from two unfashionable dressing rooms.', 'A Uruguayan striker whose strikes arrived pre polished.', 'A United reject reborn at Villarreal and Atletico.', 'The 2010 Europa League final double for Atletico.', 'Cachavacha. Initials D.F.']
),
(
  '159cd52c',
  'diego-godin',
  true,
  'Diego Godin',
  'la_liga',
  'la_liga',
  array['Atletico Madrid', 'Villarreal'],
  'Uruguay',
  'DF',
  1986,
  2,
  2007,
  2019,
  array[]::integer[],
  array['El Faraon'],
  array['Atletico''s warrior captain, scorer of the header that won a league at the Camp Nou.', 'A Uruguayan center back of scars and clean sheets.', 'Villarreal to a decade of Cholo''s trenches.', 'May 2014, the equalizing header that clinched the title.', 'El Faraon. Initials D.G.']
),
(
  'cadc1727',
  'jan-oblak',
  true,
  'Jan Oblak',
  'la_liga',
  'la_liga',
  array['Atletico Madrid'],
  'Slovenia',
  'GK',
  1993,
  13,
  2014,
  2026,
  array[]::integer[],
  array[]::text[],
  array['Four Zamoras in five years, the wall behind Cholo''s fortress.', 'A Slovenian goalkeeper of enormous calm and bigger saves.', 'Benfica to a decade guarding Atletico.', 'The triple save against Leverkusen, one sequence, three miracles.', 'Initials J.O.']
),
(
  'f3805c33',
  'thibaut-courtois',
  true,
  'Thibaut Courtois',
  'la_liga',
  'la_liga',
  array['Real Madrid', 'Atletico Madrid'],
  'Belgium',
  'GK',
  1992,
  1,
  2011,
  2026,
  array[]::integer[],
  array[]::text[],
  array['He won titles on both sides of Madrid''s divide, a decade apart.', 'A Belgian goalkeeper, six foot six of stretched limbs.', 'Atletico loan legend to Madrid''s number one.', 'The 2022 Champions League final, nine saves against Liverpool.', 'Initials T.C.']
),
(
  'a71f05cb',
  'marc-andre-ter-stegen',
  true,
  'Marc-Andre ter Stegen',
  'la_liga',
  'la_liga',
  array['Barcelona'],
  'Germany',
  'GK',
  1992,
  1,
  2014,
  2026,
  array[]::integer[],
  array[]::text[],
  array['Barcelona''s keeper who plays like an eleventh outfielder with gloves on.', 'A German goalkeeper of insane close range reflexes.', 'Gladbach to a decade at the Camp Nou.', 'The 2015 treble as the cup keeper turned undisputed one.', 'Initials M.A.T.S.']
),
(
  '35e13ed2',
  'robert-lewandowski',
  true,
  'Robert Lewandowski',
  'la_liga',
  'la_liga',
  array['Barcelona'],
  'Poland',
  'FW',
  1988,
  9,
  2022,
  2026,
  array[]::integer[],
  array['Lewy'],
  array['He arrived in Spain at 34 and immediately won the Golden Boot anyway.', 'A Polish striker whose movement is a masterclass with subtitles.', 'Bavaria''s record machine to a Barcelona renaissance.', 'The 2022-23 title, top scorer in his debut season.', 'Lewy. Initials R.L.']
),
(
  '1a649838',
  'vinicius-junior',
  true,
  'Vinicius Junior',
  'la_liga',
  'la_liga',
  array['Real Madrid'],
  'Brazil',
  'FW',
  2000,
  7,
  2018,
  2026,
  array[]::integer[],
  array['Vini'],
  array['Booed, abused, and answering everything with Champions League final goals.', 'A Brazilian winger who turned final third chaos into an art form.', 'Flamengo teenager to Madrid''s left wing throne.', 'Scoring in two Champions League finals before turning 24.', 'Vini. Initials V.J.']
),
(
  '1ec1decd',
  'jude-bellingham',
  false,
  'Jude Bellingham',
  'la_liga',
  'la_liga',
  array['Real Madrid'],
  'England',
  'MF',
  2003,
  5,
  2023,
  2026,
  array[]::integer[],
  array[]::text[],
  array['He arrived from Germany a midfielder and spent his first Spanish autumn as a striker somehow.', 'An English midfielder scoring last minute Clasico winners at twenty.', 'Dortmund to a Galactico welcome.', 'The 2023 debut months, winners in both Clasicos.', 'Initials J.B.']
),
(
  '291a0749',
  'lamine-yamal',
  true,
  'Lamine Yamal',
  'la_liga',
  'la_liga',
  array['Barcelona'],
  'Spain',
  'FW',
  2007,
  10,
  2023,
  2026,
  array[]::integer[],
  array[]::text[],
  array['He assisted in a Clasico at sixteen and made wonderkid sound insufficient.', 'A Spanish winger, left footed, from Rocafonda, 304 on the celebration.', 'La Masia''s fastest ever elevator.', 'The 2024-25 season announcing a new era''s face.', 'Initials L.Y.']
),
(
  '9000ce74',
  'pedri',
  true,
  'Pedri',
  'la_liga',
  'la_liga',
  array['Barcelona'],
  'Spain',
  'MF',
  2002,
  8,
  2020,
  2026,
  array[]::integer[],
  array[]::text[],
  array['Signed from Las Palmas for peanuts, compared to Iniesta within a year.', 'A Spanish midfielder who receives on the half turn like it''s inherited.', 'Las Palmas to the Camp Nou''s engine room.', 'The 2021 Golden Boy year, seventy games without blinking.', 'Initials P.']
),
(
  'b858bc0d',
  'gavi',
  true,
  'Gavi',
  'la_liga',
  'la_liga',
  array['Barcelona'],
  'Spain',
  'MF',
  2004,
  6,
  2021,
  2026,
  array[]::integer[],
  array[]::text[],
  array['He tackles like a street fight and passes like a seminar, at eighteen.', 'A Spanish midfielder of fury and touch in one small frame.', 'La Masia to a first team fixture at seventeen.', 'The 2022 Golden Boy award, following his midfield partner.', 'Initials G.']
),
(
  '04be7660',
  'koke',
  true,
  'Koke',
  'la_liga',
  'la_liga',
  array['Atletico Madrid'],
  'Spain',
  'MF',
  1992,
  6,
  2009,
  2026,
  array[]::integer[],
  array[]::text[],
  array['Atletico''s one club captain, more appearances than anyone in their history.', 'A Spanish midfielder of quiet lungs and permanent availability.', 'Academy to record appearance holder.', 'Both title runs, 2014 and 2021, his engine underneath.', 'Initials K.']
),
(
  '64c6d7f0',
  'roberto-carlos',
  false,
  'Roberto Carlos',
  'la_liga',
  'la_liga',
  array['Real Madrid'],
  'Brazil',
  'DF',
  1973,
  3,
  1996,
  2007,
  array[]::integer[],
  array[]::text[],
  array['A left back whose free kicks required physicists and whose overlaps required stamina science.', 'A Brazilian defender, thighs of legend, eleven Madrid seasons.', 'Inter misfit to Madrid institution.', 'The 98 mph rocket against Tenerife, one of hundreds.', 'Initials R.C.']
),
(
  '42f6b30c',
  'fernando-hierro',
  true,
  'Fernando Hierro',
  'la_liga',
  'la_liga',
  array['Real Madrid'],
  'Spain',
  'DF',
  1968,
  4,
  1992,
  2003,
  array[]::integer[],
  array[]::text[],
  array['A center back with 102 league goals. Read that again.', 'A Spanish captain who defended, scored and led for a decade.', 'Valladolid to Madrid''s spine through the nineties.', 'Five titles and the armband through the Galactico dawn.', 'Initials F.H.']
),
(
  'ba26dcf0',
  'kaka',
  true,
  'Kaka',
  'la_liga',
  'la_liga',
  array['Real Madrid'],
  'Brazil',
  'MF',
  1982,
  8,
  2009,
  2013,
  array[]::integer[],
  array[]::text[],
  array['The last Ballon d''Or winner before the duopoly, unveiled in white to 50,000.', 'A Brazilian playmaker whose Madrid years never matched the Milan magic.', 'Milan''s best player alive to the Bernabeu''s what if.', 'The 2009 arrival summer alongside a certain Portuguese.', 'Initials K.']
),
(
  '53dfba24',
  'xabi-alonso',
  true,
  'Xabi Alonso',
  'la_liga',
  'la_liga',
  array['Real Madrid', 'Real Sociedad'],
  'Spain',
  'MF',
  1981,
  14,
  1999,
  2014,
  array[]::integer[],
  array[]::text[],
  array['Five years conducting Madrid''s tempo before conducting from touchlines.', 'A Spanish midfielder of switches, sprays and a red card he planned.', 'Liverpool to Madrid''s Decima engine room.', 'La Decima 2014, suspended for the final he built.', 'Initials X.A.']
),
(
  '9bd0eb77',
  'isco',
  true,
  'Isco',
  'la_liga',
  'la_liga',
  array['Real Madrid', 'Malaga', 'Real Betis'],
  'Spain',
  'MF',
  1992,
  22,
  2011,
  2026,
  array[]::integer[],
  array[]::text[],
  array['Peak Isco was a Clasico problem nobody ever solved.', 'A Spanish playmaker of tight turns and streetball nerve.', 'Malaga''s jewel to Madrid''s magician to a Betis revival.', 'The 2017 Clasico masterclass in the false nine role.', 'Initials I.']
),
(
  '2d803fb9',
  'marcelo',
  true,
  'Marcelo',
  'la_liga',
  'la_liga',
  array['Real Madrid'],
  'Brazil',
  'DF',
  1988,
  12,
  2007,
  2022,
  array[]::integer[],
  array[]::text[],
  array['The most decorated player in Madrid''s entire history is a smiling left back.', 'A Brazilian defender who attacked like a winger with tenure.', 'Fluminense teen to 25 trophies in white.', 'The 2018 fourth Champions League as vice captain.', 'Initials M.']
),
(
  'aa699089',
  'angel-di-maria',
  true,
  'Angel Di Maria',
  'la_liga',
  'la_liga',
  array['Real Madrid'],
  'Argentina',
  'MF',
  1988,
  22,
  2010,
  2014,
  array[]::integer[],
  array['Fideo'],
  array['The 2014 Champions League final''s best player, sold that same summer.', 'An Argentine winger of skinny legs and endless final assists.', 'Benfica to Madrid''s Decima run.', 'Man of the match in Lisbon, then gone.', 'Fideo. Initials A.D.M.']
),
(
  'bad87b83',
  'radamel-falcao',
  true,
  'Radamel Falcao',
  'la_liga',
  'la_liga',
  array['Atletico Madrid', 'Rayo Vallecano'],
  'Colombia',
  'FW',
  1986,
  9,
  2011,
  2013,
  array[]::integer[],
  array['El Tigre'],
  array['Two seasons at Atletico, 52 goals, and a Chelsea demolition in Monaco''s colors before that fell apart.', 'A Colombian number nine at his terrifying pre injury peak in Spain.', 'Porto''s hammer to the Calderon.', 'The 2012 Super Cup hat trick against Chelsea.', 'El Tigre. Initials R.F.']
),
(
  '5c70fe9b',
  'diego-costa',
  true,
  'Diego Costa',
  'la_liga',
  'la_liga',
  array['Atletico Madrid'],
  'Spain',
  'FW',
  1988,
  19,
  2010,
  2020,
  array[]::integer[],
  array[]::text[],
  array['Cholo''s perfect striker, all elbows and title winning goals, twice over.', 'A Brazilian born Spanish forward of maximum hostility.', 'Loans and fights to Atletico''s 2014 title spearhead.', 'The 2013-14 title, 27 goals of pure siege warfare.', 'Initials D.C.']
),
(
  'ae8cf120',
  'gaizka-mendieta',
  true,
  'Gaizka Mendieta',
  'la_liga',
  'la_liga',
  array['Valencia'],
  'Spain',
  'MF',
  1974,
  6,
  1992,
  2003,
  array[]::integer[],
  array[]::text[],
  array['Back to back Champions League finals with a mid table wage bill.', 'A Spanish midfielder, Valencia''s captain at the century''s turn.', 'Castellon to Valencia''s golden run.', 'The 2000 and 2001 finals, Europe''s best midfielder both years.', 'Initials G.M.']
),
(
  '25fc9645',
  'santiago-canizares',
  true,
  'Santiago Canizares',
  'la_liga',
  'la_liga',
  array['Valencia', 'Real Madrid'],
  'Spain',
  'GK',
  1969,
  1,
  1992,
  2008,
  array[]::integer[],
  array[]::text[],
  array['Bleached hair, big gloves, and a Valencia era of clean sheets.', 'A Spanish goalkeeper who lost a World Cup to a bathroom cologne bottle.', 'Madrid''s backup to Valencia''s two title wall.', 'The 2002 and 2004 title winning seasons behind him.', 'Initials S.C.']
),
(
  '02c3eaa6',
  'joaquin',
  true,
  'Joaquin',
  'la_liga',
  'la_liga',
  array['Real Betis', 'Valencia'],
  'Spain',
  'MF',
  1981,
  17,
  2000,
  2023,
  array[]::integer[],
  array[]::text[],
  array['He played La Liga across four different decades and laughed through all of them.', 'A Spanish winger, Betis royalty, football''s happiest man.', 'Betis to Valencia and home again, retiring at 41.', 'A Champions League hat trick at 38 years old.', 'Initials J.']
),
(
  '3394b446',
  'iago-aspas',
  true,
  'Iago Aspas',
  'la_liga',
  'la_liga',
  array['Celta Vigo'],
  'Spain',
  'FW',
  1987,
  10,
  2008,
  2026,
  array[]::integer[],
  array['El Principe de las Bateas'],
  array['The prince of the sardine tins never left, and Celta never needed anyone else.', 'A Spanish forward, Moana born, top Spanish scorer season after season.', 'A Liverpool blip, then home forever.', 'Carrying Celta through a decade, often visibly alone.', 'Initials I.A.']
),
(
  '90a6089d',
  'antonio-puerta',
  true,
  'Antonio Puerta',
  'la_liga',
  'la_liga',
  array['Sevilla'],
  'Spain',
  'MF',
  1984,
  16,
  2004,
  2007,
  array[]::integer[],
  array[]::text[],
  array['Sevilla''s number 16 is remembered before every great European night at the Pizjuan.', 'A Sevillano winger whose extra time semifinal strike sent his club toward glory.', 'One club, Sevilla, forever young.', 'The 2006 UEFA Cup semifinal winner against Schalke.', 'Sevilla''s eternal 16. Initials A.P.']
),
(
  'd35e2a99',
  'ivan-rakitic',
  true,
  'Ivan Rakitic',
  'la_liga',
  'la_liga',
  array['Barcelona', 'Sevilla'],
  'Croatia',
  'MF',
  1988,
  4,
  2011,
  2024,
  array[]::integer[],
  array[]::text[],
  array['He scored in a Champions League final and captained Sevilla to a Europa League first.', 'A Croatian midfielder of clean strikes and cleaner logistics.', 'Schalke to Sevilla''s captain to Barcelona''s treble.', 'Opening the scoring in the 2015 Berlin final.', 'Initials I.R.']
),
(
  '8a5d172e',
  'roberto-baggio',
  false,
  'Roberto Baggio',
  'serie_a',
  'serie_a',
  array['Juventus', 'AC Milan', 'Brescia'],
  'Italy',
  'FW',
  1967,
  10,
  1992,
  2004,
  array[]::integer[],
  array[]::text[],
  array['Italy''s most loved number ten, sold between rival cities under riot conditions.', 'An Italian fantasista of ponytail, Buddhism and impossible balance.', 'Fiorentina to Juventus caused actual riots, then both Milans, then Brescia.', 'The 1993 Ballon d''Or as Serie A''s crown jewel.', 'Il Divin Codino. Initials R.B.']
),
(
  'b6a49e8d',
  'paolo-maldini',
  false,
  'Paolo Maldini',
  'serie_a',
  'serie_a',
  array['AC Milan'],
  'Italy',
  'DF',
  1968,
  3,
  1992,
  2009,
  array[]::integer[],
  array[]::text[],
  array['902 games, one shirt, and a chest that never seemed to need tackles.', 'An Italian defender whose positioning made sliding obsolete.', 'Milan at sixteen, Milan at forty one.', 'Five European Cups across three decades of red and black.', 'Il Capitano. Initials P.M.']
),
(
  '54936e33',
  'franco-baresi',
  false,
  'Franco Baresi',
  'serie_a',
  'serie_a',
  array['AC Milan'],
  'Italy',
  'DF',
  1960,
  6,
  1992,
  1997,
  array[]::integer[],
  array[]::text[],
  array['Number six, retired forever, for the man who invented stepping out of defense.', 'An Italian libero of five foot nine and total command.', 'Milan''s captain through the Sacchi revolution.', 'The offside trap of the late eighties, conducted like an orchestra.', 'Initials F.B.']
),
(
  'ffe83707',
  'alessandro-del-piero',
  false,
  'Alessandro Del Piero',
  'serie_a',
  'serie_a',
  array['Juventus'],
  'Italy',
  'FW',
  1974,
  10,
  1993,
  2012,
  array[]::integer[],
  array['Pinturicchio'],
  array['Serie B could not scare him. He stayed, scored twenty, and came back up with them.', 'An Italian number ten with a corner of the goal named after him.', 'Nineteen years and 290 goals, all in black and white.', 'Staying through Calciopoli''s relegation, captain in the dark.', 'Pinturicchio. Initials A.D.P.']
),
(
  '1f480ea1',
  'francesco-totti',
  false,
  'Francesco Totti',
  'serie_a',
  'serie_a',
  array['Roma'],
  'Italy',
  'FW',
  1976,
  10,
  1993,
  2017,
  array[]::integer[],
  array['Er Pupone', 'Il Capitano'],
  array['He won a Scudetto for Rome and turned down every throne to keep it.', 'An Italian number ten who made loyalty look like the greatest trophy.', 'One club, 25 years, 250 Serie A goals.', 'The 2001 title, Rome painted yellow and red for weeks.', 'Er Pupone. Initials F.T.']
),
(
  'be193856',
  'pavel-nedved',
  true,
  'Pavel Nedved',
  'serie_a',
  'serie_a',
  array['Juventus', 'Lazio'],
  'Czech Republic',
  'MF',
  1972,
  11,
  1996,
  2009,
  array[]::integer[],
  array[]::text[],
  array['A Ballon d''Or for a Czech engine who never stopped running or shooting.', 'A Czech midfielder, blond mane, thunder in both feet.', 'Lazio''s 2000 title to Juventus''s midfield throne.', 'The 2003 Ballon d''Or, suspended for the final he''d earned.', 'Furia Ceca. Initials P.N.']
),
(
  '315ca38b',
  'zinedine-zidane',
  false,
  'Zinedine Zidane',
  'serie_a',
  'serie_a',
  array['Juventus'],
  'France',
  'MF',
  1972,
  21,
  1996,
  2001,
  array[]::integer[],
  array['Zizou'],
  array['Serie A crowned him twice league champion before the world knew his ceiling.', 'A French playmaker learning cruelty in football''s hardest league.', 'Bordeaux to five Turin seasons.', 'The 1997 and 1998 Scudetti as Juve''s conductor.', 'Zizou. Initials Z.Z.']
),
(
  '6e498846',
  'gabriel-batistuta',
  false,
  'Gabriel Batistuta',
  'serie_a',
  'serie_a',
  array['Fiorentina', 'Roma'],
  'Argentina',
  'FW',
  1969,
  9,
  1992,
  2003,
  array[]::integer[],
  array['Batigol'],
  array['He stayed loyal through Serie B, then finally chased a Scudetto at 31 and got it.', 'An Argentine nine whose strikes registered on seismographs.', 'Nine Florence years, then the Rome title he deserved.', 'The 2001 title winner against his beloved Fiorentina, refusing to celebrate.', 'Batigol. Initials G.B.']
),
(
  '728f182e',
  'christian-vieri',
  true,
  'Christian Vieri',
  'serie_a',
  'serie_a',
  array['Inter Milan', 'Lazio'],
  'Italy',
  'FW',
  1973,
  32,
  1992,
  2006,
  array[]::integer[],
  array['Bobo'],
  array['Transferred for a world record and scored headers like demolition work.', 'An Italian number nine of brute power and surprising touch.', 'A club a year until Inter got five.', 'The 2002-03 Capocannoniere, 24 goals of violence.', 'Bobo. Initials C.V.']
),
(
  '1b482566',
  'filippo-inzaghi',
  true,
  'Filippo Inzaghi',
  'serie_a',
  'serie_a',
  array['AC Milan', 'Juventus'],
  'Italy',
  'FW',
  1973,
  9,
  1995,
  2012,
  array[]::integer[],
  array['Pippo'],
  array['Born offside, said Ferguson. Scored 300 goals from onside, said the record.', 'An Italian poacher who celebrated like every goal saved his life.', 'Piacenza to Juve to Milan''s European nights.', 'Two in the 2007 Champions League final, revenge for Istanbul.', 'Pippo. Initials F.I.']
),
(
  '1efa7ca9',
  'andriy-shevchenko',
  true,
  'Andriy Shevchenko',
  'serie_a',
  'serie_a',
  array['AC Milan'],
  'Ukraine',
  'FW',
  1976,
  7,
  1999,
  2009,
  array[]::integer[],
  array['Sheva'],
  array['Ballon d''Or 2004, the deadliest import Serie A had seen in a generation.', 'A Ukrainian striker of clean technique and cold conclusions.', 'Dynamo Kyiv to Milan''s 175 goals.', 'The 2004 golden year, Scudetto and the award.', 'Sheva. Initials A.S.']
),
(
  'a646ac63',
  'kaka',
  false,
  'Kaka',
  'serie_a',
  'serie_a',
  array['AC Milan'],
  'Brazil',
  'MF',
  1982,
  22,
  2003,
  2009,
  array[]::integer[],
  array[]::text[],
  array['The last man to win the Ballon d''Or before two others made it private property.', 'A Brazilian playmaker who ran through midfields like they were revolving doors.', 'Sao Paulo to Milan''s 2007 crown.', 'Old Trafford 2007, the two goal semifiinal masterpiece.', 'Ricky. Initials K.']
),
(
  '86cc9c8d',
  'ronaldo',
  false,
  'Ronaldo',
  'serie_a',
  'serie_a',
  array['Inter Milan', 'AC Milan'],
  'Brazil',
  'FW',
  1976,
  9,
  1997,
  2008,
  array[]::integer[],
  array['R9'],
  array['Inter''s Fenomeno years contained football''s highest peak and cruelest knee.', 'A Brazilian striker who was, for two Serie A seasons, unplayable by consensus.', 'Barcelona to Inter''s roar and heartbreak.', 'The 1998 UEFA Cup final destruction of Lazio.', 'R9.']
),
(
  '7047568e',
  'zlatan-ibrahimovic',
  true,
  'Zlatan Ibrahimovic',
  'serie_a',
  'serie_a',
  array['AC Milan', 'Inter Milan', 'Juventus'],
  'Sweden',
  'FW',
  1981,
  11,
  2004,
  2023,
  array[]::integer[],
  array['Ibra'],
  array['Scudetti with three different Italian giants, some of them even kept.', 'A Swedish striker of taekwondo finishes and third person interviews.', 'Juve to Inter to Milan, twice, retiring at 41.', 'The 2021 Milan return, top scoring at 39.', 'Ibra. Initials Z.I.']
),
(
  '6c1f70f3',
  'gianluigi-buffon',
  false,
  'Gianluigi Buffon',
  'serie_a',
  'serie_a',
  array['Juventus', 'Parma'],
  'Italy',
  'GK',
  1978,
  1,
  1995,
  2023,
  array[]::integer[],
  array['Gigi'],
  array['The world record keeper fee, set in 2001, still unbroken for two decades.', 'An Italian goalkeeper who followed his club to Serie B out of love.', 'Parma prodigy to Juve''s 10 Scudetti.', 'Staying for the 2006-07 Serie B season, saving everything anyway.', 'Gigi. Initials G.B.']
),
(
  '7978a29e',
  'fabio-cannavaro',
  false,
  'Fabio Cannavaro',
  'serie_a',
  'serie_a',
  array['Parma', 'Inter Milan', 'Juventus', 'Napoli'],
  'Italy',
  'DF',
  1973,
  5,
  1992,
  2009,
  array[]::integer[],
  array[]::text[],
  array['A Ballon d''Or for defending, collected in the same year Italian football burned.', 'An Italian center back who timed tackles like a watchmaker.', 'Napoli boy, Parma''s wall, Juve''s captain.', 'The 2006 double of World Cup and golden ball.', 'Initials F.C.']
),
(
  '71d68165',
  'alessandro-nesta',
  true,
  'Alessandro Nesta',
  'serie_a',
  'serie_a',
  array['AC Milan', 'Lazio'],
  'Italy',
  'DF',
  1976,
  13,
  1993,
  2012,
  array[]::integer[],
  array[]::text[],
  array['The most elegant defender of his generation, sold to pay a club''s debts.', 'An Italian center back whose sliding tackles were fine art.', 'Lazio''s captain and 2000 title, then Milan''s decade.', 'The 2000 Scudetto with his boyhood club before the forced sale.', 'Initials A.N.']
),
(
  '83993545',
  'andrea-pirlo',
  false,
  'Andrea Pirlo',
  'serie_a',
  'serie_a',
  array['AC Milan', 'Juventus'],
  'Italy',
  'MF',
  1979,
  21,
  1995,
  2015,
  array[]::integer[],
  array[]::text[],
  array['Milan converted a failed number ten into the deepest genius Serie A produced.', 'An Italian regista of free kicks and unbotherable calm.', 'Inter let him go. Milan and Juve collected the interest.', 'Four straight Scudetti after Juventus signed him for free.', 'The Architect. Initials A.P.']
),
(
  'ed1535dc',
  'gennaro-gattuso',
  true,
  'Gennaro Gattuso',
  'serie_a',
  'serie_a',
  array['AC Milan'],
  'Italy',
  'MF',
  1978,
  8,
  1999,
  2012,
  array[]::integer[],
  array['Ringhio'],
  array['The growling other half of Pirlo, biting so the artist could paint.', 'An Italian midfielder of tackles, snarls and total honesty.', 'Rangers detour to Milan''s engine room.', 'The 2007 Champions League, doing the dirty work of two men.', 'Ringhio. Initials G.G.']
),
(
  '3cfb25a0',
  'clarence-seedorf',
  true,
  'Clarence Seedorf',
  'serie_a',
  'serie_a',
  array['AC Milan', 'Inter Milan', 'Sampdoria'],
  'Netherlands',
  'MF',
  1976,
  10,
  1995,
  2012,
  array[]::integer[],
  array[]::text[],
  array['The only man to win the Champions League with three clubs, two of them Italian.', 'A Dutch midfielder of power, class and press conference fluency.', 'Ajax and Madrid before a decade at Milan.', 'The 2007 final, running Istanbul''s ghosts out of Athens.', 'Initials C.S.']
),
(
  '7c08838f',
  'hernan-crespo',
  true,
  'Hernan Crespo',
  'serie_a',
  'serie_a',
  array['Parma', 'Lazio', 'Inter Milan', 'AC Milan'],
  'Argentina',
  'FW',
  1975,
  9,
  1996,
  2012,
  array[]::integer[],
  array[]::text[],
  array['A world record fee between Parma and Lazio, and goals everywhere he unpacked.', 'An Argentine nine of textbook movement and finishing.', 'Parma to Lazio to Inter to Milan, scoring throughout.', 'The 2000-01 Capocannoniere season with Lazio.', 'Valdanito. Initials H.C.']
),
(
  '6d3fa924',
  'javier-zanetti',
  true,
  'Javier Zanetti',
  'serie_a',
  'serie_a',
  array['Inter Milan'],
  'Argentina',
  'DF',
  1973,
  4,
  1995,
  2014,
  array[]::integer[],
  array['Pupi', 'Il Capitano'],
  array['858 games for one club and roughly zero bad ones.', 'An Argentine captain who played every position except tired.', 'Banfield to nineteen Inter seasons.', 'Captaining the 2010 treble at 36.', 'Pupi. Initials J.Z.']
),
(
  'b9080a14',
  'esteban-cambiasso',
  true,
  'Esteban Cambiasso',
  'serie_a',
  'serie_a',
  array['Inter Milan'],
  'Argentina',
  'MF',
  1980,
  19,
  2004,
  2014,
  array[]::integer[],
  array['Cuchu'],
  array['Madrid gave him away free. Inter built a treble on the mistake.', 'An Argentine midfielder, bald, brilliant, always exactly where needed.', 'Madrid''s error to Inter''s engine.', 'The 2010 treble''s most underrated part.', 'Cuchu. Initials E.C.']
),
(
  '7160e50f',
  'diego-milito',
  true,
  'Diego Milito',
  'serie_a',
  'serie_a',
  array['Inter Milan', 'Genoa'],
  'Argentina',
  'FW',
  1979,
  22,
  2005,
  2014,
  array[]::integer[],
  array['Il Principe'],
  array['Both goals in the treble final, one season after arriving from Genoa.', 'An Argentine striker who looked ordinary until the ball arrived.', 'Genoa to Inter''s greatest single season signing.', 'Madrid 2010, two finishes, immortality.', 'Il Principe. Initials D.M.']
),
(
  '03401210',
  'samuel-etoo',
  false,
  'Samuel Etoo',
  'serie_a',
  'serie_a',
  array['Inter Milan'],
  'Cameroon',
  'FW',
  1981,
  9,
  2009,
  2011,
  array[]::integer[],
  array[]::text[],
  array['He accepted playing right wing back for Mourinho and won everything for it.', 'A Cameroonian striker sacrificing ego for the treble.', 'Barcelona swap deal to Inter''s crown.', 'The 2010 treble, defending like a full back in the semi.', 'Initials S.E.']
),
(
  'f15ebeb1',
  'wesley-sneijder',
  false,
  'Wesley Sneijder',
  'serie_a',
  'serie_a',
  array['Inter Milan'],
  'Netherlands',
  'MF',
  1984,
  10,
  2009,
  2013,
  array[]::integer[],
  array[]::text[],
  array['The treble''s brain, robbed of a Ballon d''Or by year''s end voting.', 'A Dutch number ten hitting every pass of 2010 clean.', 'Madrid clearout to Inter''s masterpiece.', 'The 2010 season, club treble plus a World Cup final.', 'Initials W.S.']
),
(
  'c654e457',
  'paulo-dybala',
  true,
  'Paulo Dybala',
  'serie_a',
  'serie_a',
  array['Juventus', 'Roma', 'Palermo'],
  'Argentina',
  'FW',
  1993,
  21,
  2012,
  2026,
  array[]::integer[],
  array['La Joya'],
  array['The Jewel signed for Palermo money and masked up for a hundred Juve goals.', 'An Argentine number ten of left footed curlers and the Dybala mask.', 'Palermo to Juve''s ten and Roma''s love.', 'The 2017 double over Barcelona, both goals art.', 'La Joya. Initials P.D.']
),
(
  '80462851',
  'gonzalo-higuain',
  true,
  'Gonzalo Higuain',
  'serie_a',
  'serie_a',
  array['Napoli', 'Juventus', 'AC Milan'],
  'Argentina',
  'FW',
  1987,
  9,
  2013,
  2020,
  array[]::integer[],
  array['Pipita'],
  array['36 goals in a season for Napoli, then the ninety million euro betrayal.', 'An Argentine striker of feast, famine and one unforgivable transfer.', 'Madrid to Napoli''s record to Juve''s cash.', 'The 2016 Capocannoniere record season, 36 in 35.', 'Pipita. Initials G.H.']
),
(
  '8f3d1cf2',
  'paul-pogba',
  true,
  'Paul Pogba',
  'serie_a',
  'serie_a',
  array['Juventus'],
  'France',
  'MF',
  1993,
  10,
  2012,
  2016,
  array[]::integer[],
  array[]::text[],
  array['Free from Manchester at nineteen, sold back for a world record at 23.', 'A French midfielder of long legs, long range and dab celebrations.', 'United''s academy escape to four Scudetti.', 'The 2015 Champions League final run as Serie A''s crown prince.', 'Initials P.P.']
),
(
  'f3b2bbf9',
  'giorgio-chiellini',
  true,
  'Giorgio Chiellini',
  'serie_a',
  'serie_a',
  array['Juventus'],
  'Italy',
  'DF',
  1984,
  3,
  2004,
  2022,
  array[]::integer[],
  array[]::text[],
  array['Grazie Giorgio banners, and the most honest fouls in football history.', 'An Italian center back who studied economics and forwards equally.', 'Livorno to seventeen Juve seasons.', 'Nine straight Scudetti anchoring the BBC line.', 'King Kong. Initials G.C.']
),
(
  '946b88a0',
  'leonardo-bonucci',
  true,
  'Leonardo Bonucci',
  'serie_a',
  'serie_a',
  array['Juventus', 'AC Milan'],
  'Italy',
  'DF',
  1987,
  19,
  2005,
  2023,
  array[]::integer[],
  array[]::text[],
  array['Sold to Milan over a headbutt argument, back a year later like nothing happened.', 'An Italian center back who launched attacks like a quarterback.', 'Bari to Juve''s BBC to that Milan gap year.', 'Eight Scudetti passing through the lines.', 'Initials L.B.']
),
(
  '9934d3d5',
  'gianluigi-donnarumma',
  true,
  'Gianluigi Donnarumma',
  'serie_a',
  'serie_a',
  array['AC Milan'],
  'Italy',
  'GK',
  1999,
  99,
  2015,
  2021,
  array[]::integer[],
  array['Gigio'],
  array['A Serie A debut at sixteen years and 242 days between Milan''s posts.', 'An Italian goalkeeper the size of a door and quick as a cat.', 'Milan''s teenage number one before the free transfer storm.', 'Debuting at sixteen under Mihajlovic, 2015.', 'Gigio. Initials G.D.']
),
(
  'b342452e',
  'ciro-immobile',
  true,
  'Ciro Immobile',
  'serie_a',
  'serie_a',
  array['Lazio', 'Torino'],
  'Italy',
  'FW',
  1990,
  17,
  2009,
  2024,
  array[]::integer[],
  array[]::text[],
  array['Four Capocannonieri and a European record 36 goal season for Lazio.', 'An Italian nine, doubted everywhere except the box.', 'Torino breakout to Lazio''s record books.', 'The 2020 season, 36 goals, European Golden Shoe.', 'Initials C.I.']
),
(
  '7cf4d174',
  'lorenzo-insigne',
  true,
  'Lorenzo Insigne',
  'serie_a',
  'serie_a',
  array['Napoli'],
  'Italy',
  'FW',
  1991,
  24,
  2010,
  2022,
  array[]::integer[],
  array['Il Magnifico'],
  array['The tiny Napoli captain whose curled far post finish had its own name.', 'An Italian winger, Naples born, il tiro a giro on demand.', 'Boyhood club captaincy through 2022.', 'The Euro winning summer as Napoli''s magnifico.', 'Il Magnifico. Initials L.I.']
),
(
  'a90d2a83',
  'dries-mertens',
  true,
  'Dries Mertens',
  'serie_a',
  'serie_a',
  array['Napoli'],
  'Belgium',
  'FW',
  1987,
  14,
  2013,
  2022,
  array[]::integer[],
  array['Ciro'],
  array['Converted to striker at 29, he broke Maradona''s Napoli scoring record.', 'A Belgian forward, tiny, joyful, deadly through the middle.', 'PSV to Napoli''s record 148 goals.', 'The 2016-17 conversion season, 28 goals from nowhere.', 'Ciro. Initials D.M.']
)
on conflict (id) do update set
  person_id = excluded.person_id,
  canonical = excluded.canonical,
  name = excluded.name,
  category = excluded.category,
  league = excluded.league,
  clubs = excluded.clubs,
  nationality = excluded.nationality,
  position = excluded.position,
  birth_year = excluded.birth_year,
  shirt_number = excluded.shirt_number,
  era_start = excluded.era_start,
  era_end = excluded.era_end,
  world_cup_editions = excluded.world_cup_editions,
  aliases = excluded.aliases,
  clues = excluded.clues;

-- Verify this batch: select count(*) from public.players; -- expect 240 cumulative after all batches through 03
