-- TM SAMPLE merge batch 5/5: 6 rows (nationality backfill)
-- Paste into Supabase SQL Editor AFTER players_batch_tm_01–04.
insert into public.players (
  id, person_id, canonical, name, category, league, clubs,
  nationality, position, birth_year, shirt_number, era_start, era_end,
  world_cup_editions, aliases, clues
) values
(
  '03a036bc',
  'marc-albrighton',
  true,
  'Marc Albrighton',
  'premier_league',
  'premier_league',
  array['Aston Villa', 'Leicester City'],
  'England',
  'MF',
  1989,
  null,
  2012,
  2022,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2022 league regular logged near the top of the appearances table.', 'SAMPLE: A England midfielder in the 2012-2022 window.', 'SAMPLE: Club path in this league window: Aston Villa, Leicester City.', 'SAMPLE: 252 appearances, 13 goals, 39 assists (52 combined) in the logged window.', 'SAMPLE: Initials M.A. Surname shape length 10.']
),
(
  'd65f88b4',
  'samir-handanovic',
  true,
  'Samir Handanovic',
  'serie_a',
  'serie_a',
  array['Inter Milan'],
  'Bosnia and Herzegovina',
  'GK',
  1984,
  null,
  2012,
  2022,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2022 league regular logged near the top of the appearances table.', 'SAMPLE: A Bosnia and Herzegovina goalkeeper in the 2012-2022 window.', 'SAMPLE: Club path in this league window: Inter Milan.', 'SAMPLE: 380 appearances, 0 goals, 0 assists (0 combined) in the logged window.', 'SAMPLE: Initials S.H. Surname shape length 10.']
),
(
  'f57bbc74',
  'fabio-quagliarella',
  true,
  'Fabio Quagliarella',
  'serie_a',
  'serie_a',
  array['Juventus', 'Torino', 'UC Sampdoria'],
  'Italy',
  'FW',
  1983,
  null,
  2012,
  2022,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2022 league regular logged near the top of the appearances table.', 'SAMPLE: A Italy forward in the 2012-2022 window.', 'SAMPLE: Club path in this league window: Juventus, Torino, UC Sampdoria.', 'SAMPLE: 336 appearances, 117 goals, 32 assists (149 combined) in the logged window.', 'SAMPLE: Initials F.Q. Surname shape length 12.']
),
(
  'faf8c500',
  'radja-nainggolan',
  true,
  'Radja Nainggolan',
  'serie_a',
  'serie_a',
  array['Associazione Sportiva Roma', 'Cagliari Calcio', 'Inter Milan'],
  'Belgium',
  'MF',
  1988,
  null,
  2012,
  2020,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2020 league regular logged near the top of the appearances table.', 'SAMPLE: A Belgium midfielder in the 2012-2020 window.', 'SAMPLE: Club path in this league window: Associazione Sportiva Roma, Cagliari Calcio, Inter Milan.', 'SAMPLE: 287 appearances, 45 goals, 31 assists (76 combined) in the logged window.', 'SAMPLE: Initials R.N. Surname shape length 10.']
),
(
  'ee067485',
  'marvin-plattenhardt',
  true,
  'Marvin Plattenhardt',
  'bundesliga',
  'bundesliga',
  array['1.FC Nuremberg', 'Hertha BSC'],
  'Germany',
  'DF',
  1992,
  null,
  2012,
  2022,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2022 league regular logged near the top of the appearances table.', 'SAMPLE: A Germany defender in the 2012-2022 window.', 'SAMPLE: Club path in this league window: 1.FC Nuremberg, Hertha BSC.', 'SAMPLE: 260 appearances, 8 goals, 36 assists (44 combined) in the logged window.', 'SAMPLE: Initials M.P. Surname shape length 12.']
),
(
  '3580305e',
  'julian-baumgartlinger',
  true,
  'Julian Baumgartlinger',
  'bundesliga',
  'bundesliga',
  array['1.FSV Mainz 05', 'Bayer Leverkusen', 'Augsburg'],
  'Austria',
  'MF',
  1988,
  null,
  2012,
  2022,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2022 league regular logged near the top of the appearances table.', 'SAMPLE: A Austria midfielder in the 2012-2022 window.', 'SAMPLE: Club path in this league window: 1.FSV Mainz 05, Bayer Leverkusen, Augsburg.', 'SAMPLE: 229 appearances, 7 goals, 8 assists (15 combined) in the logged window.', 'SAMPLE: Initials J.B. Surname shape length 14.']
)
on conflict (id) do update set
  person_id = excluded.person_id,
  canonical = excluded.canonical,
  name = excluded.name,
  category = excluded.category,
  league = excluded.league,
  clubs = excluded.clubs,
  nationality = excluded.nationality,
  position = excluded.position,
  birth_year = excluded.birth_year,
  shirt_number = excluded.shirt_number,
  era_start = excluded.era_start,
  era_end = excluded.era_end,
  world_cup_editions = excluded.world_cup_editions,
  aliases = excluded.aliases,
  clues = excluded.clues;

