-- TM SAMPLE merge batch 3/4: 80 new rows (of 292 new)
-- Paste into Supabase SQL Editor AFTER players_batch_01–06.
-- Run in order tm_01 → tm_04.
insert into public.players (
  id, person_id, canonical, name, category, league, clubs,
  nationality, position, birth_year, shirt_number, era_start, era_end,
  world_cup_editions, aliases, clues
) values
(
  '26fee72b',
  'mattia-perin',
  true,
  'Mattia Perin',
  'serie_a',
  'serie_a',
  array['Delfino Pescara 1936', 'Genoa CFC', 'Juventus'],
  'Italy',
  'GK',
  1992,
  null,
  2012,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Italy goalkeeper in the 2012-2025 window.', 'SAMPLE: Club path in this league window: Delfino Pescara 1936, Genoa CFC, Juventus.', 'SAMPLE: 271 appearances, 0 goals, 0 assists (0 combined) in the logged window.', 'SAMPLE: Initials M.P. Surname shape length 5.']
),
(
  '49690449',
  'davide-zappacosta',
  true,
  'Davide Zappacosta',
  'serie_a',
  'serie_a',
  array['Associazione Sportiva Roma', 'Atalanta BC', 'Genoa CFC', 'Torino'],
  'Italy',
  'MF',
  1992,
  null,
  2014,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2014-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Italy midfielder in the 2014-2025 window.', 'SAMPLE: Club path in this league window: Associazione Sportiva Roma, Atalanta BC, Genoa CFC, Torino.', 'SAMPLE: 270 appearances, 23 goals, 26 assists (49 combined) in the logged window.', 'SAMPLE: Initials D.Z. Surname shape length 10.']
),
(
  '66042b6a',
  'borja-valero',
  true,
  'Borja Valero',
  'serie_a',
  'serie_a',
  array['ACF Fiorentina', 'Inter Milan'],
  'Spain',
  'MF',
  1985,
  null,
  2012,
  2020,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2020 league regular logged near the top of the appearances table.', 'SAMPLE: A Spain midfielder in the 2012-2020 window.', 'SAMPLE: Club path in this league window: ACF Fiorentina, Inter Milan.', 'SAMPLE: 268 appearances, 18 goals, 41 assists (59 combined) in the logged window.', 'SAMPLE: Initials B.V. Surname shape length 6.']
),
(
  '1fa2f2bc',
  'rodrigo-palacio',
  true,
  'Rodrigo Palacio',
  'serie_a',
  'serie_a',
  array['Bologna Football Club 1909', 'Inter Milan'],
  'Argentina',
  'FW',
  1982,
  null,
  2012,
  2020,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2020 league regular logged near the top of the appearances table.', 'SAMPLE: A Argentina forward in the 2012-2020 window.', 'SAMPLE: Club path in this league window: Bologna Football Club 1909, Inter Milan.', 'SAMPLE: 267 appearances, 58 goals, 44 assists (102 combined) in the logged window.', 'SAMPLE: Initials R.P. Surname shape length 7.']
),
(
  '1ec079ec',
  'sergej-milinkovic-savic',
  true,
  'Sergej Milinković-Savić',
  'serie_a',
  'serie_a',
  array['Società Sportiva Lazio S.p.A.'],
  'Serbia',
  'MF',
  1995,
  null,
  2015,
  2022,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2015-2022 league regular logged near the top of the appearances table.', 'SAMPLE: A Serbia midfielder in the 2015-2022 window.', 'SAMPLE: Club path in this league window: Società Sportiva Lazio S.p.A..', 'SAMPLE: 267 appearances, 57 goals, 48 assists (105 combined) in the logged window.', 'SAMPLE: Initials S.M.S. Surname shape length 5.']
),
(
  '9514df56',
  'danilo-cataldi',
  true,
  'Danilo Cataldi',
  'serie_a',
  'serie_a',
  array['ACF Fiorentina', 'Benevento Calcio', 'Genoa CFC', 'Società Sportiva Lazio S.p.A.'],
  'Italy',
  'MF',
  1994,
  null,
  2015,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2015-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Italy midfielder in the 2015-2025 window.', 'SAMPLE: Club path in this league window: ACF Fiorentina, Benevento Calcio, Genoa CFC, Società Sportiva Lazio S.p.A..', 'SAMPLE: 266 appearances, 14 goals, 14 assists (28 combined) in the logged window.', 'SAMPLE: Initials D.C. Surname shape length 7.']
),
(
  '44a5fbc8',
  'manuel-lazzari',
  true,
  'Manuel Lazzari',
  'serie_a',
  'serie_a',
  array['Società Sportiva Lazio S.p.A.', 'SPAL'],
  'Italy',
  'DF',
  1993,
  null,
  2017,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2017-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Italy defender in the 2017-2025 window.', 'SAMPLE: Club path in this league window: Società Sportiva Lazio S.p.A., SPAL.', 'SAMPLE: 264 appearances, 7 goals, 29 assists (36 combined) in the logged window.', 'SAMPLE: Initials M.L. Surname shape length 7.']
),
(
  'ee6b0ffd',
  'allan',
  true,
  'Allan',
  'serie_a',
  'serie_a',
  array['SSC Napoli', 'Udinese Calcio'],
  'Brazil',
  'MF',
  1991,
  null,
  2012,
  2019,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2019 league regular logged near the top of the appearances table.', 'SAMPLE: A Brazil midfielder in the 2012-2019 window.', 'SAMPLE: Club path in this league window: SSC Napoli, Udinese Calcio.', 'SAMPLE: 262 appearances, 12 goals, 28 assists (40 combined) in the logged window.', 'SAMPLE: Initials A. Surname shape length 5.']
),
(
  '088c99df',
  'marcelo-brozovic',
  true,
  'Marcelo Brozović',
  'serie_a',
  'serie_a',
  array['Inter Milan'],
  'Croatia',
  'MF',
  1992,
  null,
  2014,
  2022,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2014-2022 league regular logged near the top of the appearances table.', 'SAMPLE: A Croatia midfielder in the 2014-2022 window.', 'SAMPLE: Club path in this league window: Inter Milan.', 'SAMPLE: 261 appearances, 25 goals, 34 assists (59 combined) in the logged window.', 'SAMPLE: Initials M.B. Surname shape length 8.']
),
(
  '1b97d67a',
  'rafael-toloi',
  true,
  'Rafael Tolói',
  'serie_a',
  'serie_a',
  array['Associazione Sportiva Roma', 'Atalanta BC'],
  'Italy',
  'DF',
  1990,
  null,
  2013,
  2024,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2013-2024 league regular logged near the top of the appearances table.', 'SAMPLE: A Italy defender in the 2013-2024 window.', 'SAMPLE: Club path in this league window: Associazione Sportiva Roma, Atalanta BC.', 'SAMPLE: 258 appearances, 10 goals, 15 assists (25 combined) in the logged window.', 'SAMPLE: Initials R.T. Surname shape length 5.']
),
(
  '6bc1aa12',
  'gian-marco-ferrari',
  true,
  'Gian Marco Ferrari',
  'serie_a',
  'serie_a',
  array['Crotone', 'UC Sampdoria', 'US Sassuolo'],
  'Italy',
  'DF',
  1992,
  null,
  2016,
  2023,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2016-2023 league regular logged near the top of the appearances table.', 'SAMPLE: A Italy defender in the 2016-2023 window.', 'SAMPLE: Club path in this league window: Crotone, UC Sampdoria, US Sassuolo.', 'SAMPLE: 255 appearances, 12 goals, 9 assists (21 combined) in the logged window.', 'SAMPLE: Initials G.M.F. Surname shape length 7.']
),
(
  'c46b12ac',
  'karol-linetty',
  true,
  'Karol Linetty',
  'serie_a',
  'serie_a',
  array['Torino', 'UC Sampdoria'],
  'Poland',
  'MF',
  1995,
  null,
  2016,
  2024,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2016-2024 league regular logged near the top of the appearances table.', 'SAMPLE: A Poland midfielder in the 2016-2024 window.', 'SAMPLE: Club path in this league window: Torino, UC Sampdoria.', 'SAMPLE: 255 appearances, 14 goals, 15 assists (29 combined) in the logged window.', 'SAMPLE: Initials K.L. Surname shape length 7.']
),
(
  'd7fe4db1',
  'senad-lulic',
  true,
  'Senad Lulic',
  'serie_a',
  'serie_a',
  array['Società Sportiva Lazio S.p.A.'],
  'Bosnia and Herzegovina',
  'MF',
  1986,
  null,
  2012,
  2020,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2020 league regular logged near the top of the appearances table.', 'SAMPLE: A Bosnia and Herzegovina midfielder in the 2012-2020 window.', 'SAMPLE: Club path in this league window: Società Sportiva Lazio S.p.A..', 'SAMPLE: 255 appearances, 24 goals, 41 assists (65 combined) in the logged window.', 'SAMPLE: Initials S.L. Surname shape length 5.']
),
(
  '17f0d74b',
  'andrea-petagna',
  true,
  'Andrea Petagna',
  'serie_a',
  'serie_a',
  array['Milan', 'Monza', 'Atalanta BC', 'Cagliari Calcio', 'SPAL', 'SSC Napoli', 'UC Sampdoria'],
  'Italy',
  'FW',
  1995,
  null,
  2013,
  2024,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2013-2024 league regular logged near the top of the appearances table.', 'SAMPLE: A Italy forward in the 2013-2024 window.', 'SAMPLE: Club path in this league window: Milan, Monza, Atalanta BC, Cagliari Calcio.', 'SAMPLE: 253 appearances, 49 goals, 27 assists (76 combined) in the logged window.', 'SAMPLE: Initials A.P. Surname shape length 7.']
),
(
  '4eea1cee',
  'oliver-baumann',
  true,
  'Oliver Baumann',
  'bundesliga',
  'bundesliga',
  array['SC Freiburg', 'TSG 1899 Hoffenheim'],
  'Germany',
  'GK',
  1990,
  null,
  2012,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Germany goalkeeper in the 2012-2025 window.', 'SAMPLE: Club path in this league window: SC Freiburg, TSG 1899 Hoffenheim.', 'SAMPLE: 459 appearances, 0 goals, 3 assists (3 combined) in the logged window.', 'SAMPLE: Initials O.B. Surname shape length 7.']
),
(
  '084d1f0e',
  'matthias-ginter',
  true,
  'Matthias Ginter',
  'bundesliga',
  'bundesliga',
  array['Borussia Dortmund', 'Borussia Monchengladbach', 'SC Freiburg'],
  'Germany',
  'DF',
  1994,
  null,
  2012,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Germany defender in the 2012-2025 window.', 'SAMPLE: Club path in this league window: Borussia Dortmund, Borussia Monchengladbach, SC Freiburg.', 'SAMPLE: 399 appearances, 24 goals, 22 assists (46 combined) in the logged window.', 'SAMPLE: Initials M.G. Surname shape length 6.']
),
(
  '5ecf7548',
  'maximilian-arnold',
  true,
  'Maximilian Arnold',
  'bundesliga',
  'bundesliga',
  array['VfL Wolfsburg'],
  'Germany',
  'MF',
  1994,
  null,
  2012,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Germany midfielder in the 2012-2025 window.', 'SAMPLE: Club path in this league window: VfL Wolfsburg.', 'SAMPLE: 398 appearances, 45 goals, 49 assists (94 combined) in the logged window.', 'SAMPLE: Initials M.A. Surname shape length 6.']
),
(
  'bf606af2',
  'julian-brandt',
  true,
  'Julian Brandt',
  'bundesliga',
  'bundesliga',
  array['Bayer Leverkusen', 'Borussia Dortmund'],
  'Germany',
  'MF',
  1996,
  null,
  2013,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2013-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Germany midfielder in the 2013-2025 window.', 'SAMPLE: Club path in this league window: Bayer Leverkusen, Borussia Dortmund.', 'SAMPLE: 383 appearances, 77 goals, 91 assists (168 combined) in the logged window.', 'SAMPLE: Initials J.B. Surname shape length 6.']
),
(
  '7ec45c5c',
  'kevin-vogt',
  true,
  'Kevin Vogt',
  'bundesliga',
  'bundesliga',
  array['1.FC Köln', '1.FC Union Berlin', 'Augsburg', 'SV Werder Bremen', 'TSG 1899 Hoffenheim'],
  'Germany',
  'DF',
  1991,
  null,
  2012,
  2024,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2024 league regular logged near the top of the appearances table.', 'SAMPLE: A Germany defender in the 2012-2024 window.', 'SAMPLE: Club path in this league window: 1.FC Köln, 1.FC Union Berlin, Augsburg, SV Werder Bremen.', 'SAMPLE: 352 appearances, 4 goals, 11 assists (15 combined) in the logged window.', 'SAMPLE: Initials K.V. Surname shape length 4.']
),
(
  'dff21c81',
  'jonathan-tah',
  true,
  'Jonathan Tah',
  'bundesliga',
  'bundesliga',
  array['Bayer Leverkusen', 'Bayern Munich', 'Hamburger SV'],
  'Germany',
  'DF',
  1996,
  null,
  2013,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2013-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Germany defender in the 2013-2025 window.', 'SAMPLE: Club path in this league window: Bayer Leverkusen, Bayern Munich, Hamburger SV.', 'SAMPLE: 335 appearances, 17 goals, 13 assists (30 combined) in the logged window.', 'SAMPLE: Initials J.T. Surname shape length 3.']
),
(
  'ca262ffd',
  'dominik-kohr',
  true,
  'Dominik Kohr',
  'bundesliga',
  'bundesliga',
  array['1.FSV Mainz 05', 'Bayer Leverkusen', 'Eintracht Frankfurt', 'Augsburg'],
  'Germany',
  'DF',
  1994,
  null,
  2012,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Germany defender in the 2012-2025 window.', 'SAMPLE: Club path in this league window: 1.FSV Mainz 05, Bayer Leverkusen, Eintracht Frankfurt, Augsburg.', 'SAMPLE: 333 appearances, 13 goals, 16 assists (29 combined) in the logged window.', 'SAMPLE: Initials D.K. Surname shape length 4.']
),
(
  '18ee8ba4',
  'lukas-hradecky',
  true,
  'Lukas Hradecky',
  'bundesliga',
  'bundesliga',
  array['Bayer Leverkusen', 'Eintracht Frankfurt'],
  'Finland',
  'GK',
  1989,
  null,
  2015,
  2024,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2015-2024 league regular logged near the top of the appearances table.', 'SAMPLE: A Finland goalkeeper in the 2015-2024 window.', 'SAMPLE: Club path in this league window: Bayer Leverkusen, Eintracht Frankfurt.', 'SAMPLE: 323 appearances, 0 goals, 0 assists (0 combined) in the logged window.', 'SAMPLE: Initials L.H. Surname shape length 8.']
),
(
  'b509d20c',
  'andrej-kramaric',
  true,
  'Andrej Kramaric',
  'bundesliga',
  'bundesliga',
  array['TSG 1899 Hoffenheim'],
  'Croatia',
  'FW',
  1991,
  null,
  2015,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2015-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Croatia forward in the 2015-2025 window.', 'SAMPLE: Club path in this league window: TSG 1899 Hoffenheim.', 'SAMPLE: 320 appearances, 140 goals, 67 assists (207 combined) in the logged window.', 'SAMPLE: Initials A.K. Surname shape length 8.']
),
(
  'e8793928',
  'maximilian-eggestein',
  true,
  'Maximilian Eggestein',
  'bundesliga',
  'bundesliga',
  array['SC Freiburg', 'SV Werder Bremen'],
  'Germany',
  'MF',
  1996,
  null,
  2014,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2014-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Germany midfielder in the 2014-2025 window.', 'SAMPLE: Club path in this league window: SC Freiburg, SV Werder Bremen.', 'SAMPLE: 318 appearances, 19 goals, 24 assists (43 combined) in the logged window.', 'SAMPLE: Initials M.E. Surname shape length 9.']
),
(
  '2bb638cb',
  'nico-elvedi',
  true,
  'Nico Elvedi',
  'bundesliga',
  'bundesliga',
  array['Borussia Monchengladbach'],
  'Switzerland',
  'DF',
  1996,
  null,
  2015,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2015-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Switzerland defender in the 2015-2025 window.', 'SAMPLE: Club path in this league window: Borussia Monchengladbach.', 'SAMPLE: 318 appearances, 15 goals, 12 assists (27 combined) in the logged window.', 'SAMPLE: Initials N.E. Surname shape length 6.']
),
(
  'f03dbf33',
  'daniel-caligiuri',
  true,
  'Daniel Caligiuri',
  'bundesliga',
  'bundesliga',
  array['Augsburg', 'Schalke 04', 'SC Freiburg', 'VfL Wolfsburg'],
  'Italy',
  'FW',
  1988,
  null,
  2012,
  2022,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2022 league regular logged near the top of the appearances table.', 'SAMPLE: A Italy forward in the 2012-2022 window.', 'SAMPLE: Club path in this league window: Augsburg, Schalke 04, SC Freiburg, VfL Wolfsburg.', 'SAMPLE: 308 appearances, 45 goals, 48 assists (93 combined) in the logged window.', 'SAMPLE: Initials D.C. Surname shape length 9.']
),
(
  'eb974406',
  'vincenzo-grifo',
  true,
  'Vincenzo Grifo',
  'bundesliga',
  'bundesliga',
  array['Borussia Monchengladbach', 'SC Freiburg', 'TSG 1899 Hoffenheim'],
  'Italy',
  'FW',
  1993,
  null,
  2012,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Italy forward in the 2012-2025 window.', 'SAMPLE: Club path in this league window: Borussia Monchengladbach, SC Freiburg, TSG 1899 Hoffenheim.', 'SAMPLE: 306 appearances, 73 goals, 77 assists (150 combined) in the logged window.', 'SAMPLE: Initials V.G. Surname shape length 5.']
),
(
  'd71bb07e',
  'leonardo-bittencourt',
  true,
  'Leonardo Bittencourt',
  'bundesliga',
  'bundesliga',
  array['1.FC Köln', 'Borussia Dortmund', 'Hannover 96', 'SV Werder Bremen', 'TSG 1899 Hoffenheim'],
  'Germany',
  'MF',
  1993,
  null,
  2012,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Germany midfielder in the 2012-2025 window.', 'SAMPLE: Club path in this league window: 1.FC Köln, Borussia Dortmund, Hannover 96, SV Werder Bremen.', 'SAMPLE: 304 appearances, 32 goals, 36 assists (68 combined) in the logged window.', 'SAMPLE: Initials L.B. Surname shape length 11.']
),
(
  '4b907279',
  'robin-knoche',
  true,
  'Robin Knoche',
  'bundesliga',
  'bundesliga',
  array['1.FC Union Berlin', 'VfL Wolfsburg'],
  'Germany',
  'DF',
  1992,
  null,
  2012,
  2023,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2023 league regular logged near the top of the appearances table.', 'SAMPLE: A Germany defender in the 2012-2023 window.', 'SAMPLE: Club path in this league window: 1.FC Union Berlin, VfL Wolfsburg.', 'SAMPLE: 303 appearances, 16 goals, 8 assists (24 combined) in the logged window.', 'SAMPLE: Initials R.K. Surname shape length 6.']
),
(
  '31473732',
  'niklas-sule',
  true,
  'Niklas Süle',
  'bundesliga',
  'bundesliga',
  array['Bayern Munich', 'Borussia Dortmund', 'TSG 1899 Hoffenheim'],
  'Germany',
  'DF',
  1995,
  null,
  2012,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Germany defender in the 2012-2025 window.', 'SAMPLE: Club path in this league window: Bayern Munich, Borussia Dortmund, TSG 1899 Hoffenheim.', 'SAMPLE: 300 appearances, 16 goals, 12 assists (28 combined) in the logged window.', 'SAMPLE: Initials N.S. Surname shape length 4.']
),
(
  '66ef7e37',
  'jonas-hofmann',
  true,
  'Jonas Hofmann',
  'bundesliga',
  'bundesliga',
  array['1.FSV Mainz 05', 'Bayer Leverkusen', 'Borussia Dortmund', 'Borussia Monchengladbach'],
  'Germany',
  'MF',
  1992,
  null,
  2012,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Germany midfielder in the 2012-2025 window.', 'SAMPLE: Club path in this league window: 1.FSV Mainz 05, Bayer Leverkusen, Borussia Dortmund, Borussia Monchengladbach.', 'SAMPLE: 298 appearances, 55 goals, 63 assists (118 combined) in the logged window.', 'SAMPLE: Initials J.H. Surname shape length 7.']
),
(
  'fce06b23',
  'yannick-gerhardt',
  true,
  'Yannick Gerhardt',
  'bundesliga',
  'bundesliga',
  array['1.FC Köln', 'VfL Wolfsburg'],
  'Germany',
  'MF',
  1994,
  null,
  2014,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2014-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Germany midfielder in the 2014-2025 window.', 'SAMPLE: Club path in this league window: 1.FC Köln, VfL Wolfsburg.', 'SAMPLE: 295 appearances, 21 goals, 29 assists (50 combined) in the logged window.', 'SAMPLE: Initials Y.G. Surname shape length 8.']
),
(
  '9a5f3391',
  'kevin-trapp',
  true,
  'Kevin Trapp',
  'bundesliga',
  'bundesliga',
  array['Eintracht Frankfurt'],
  'Germany',
  'GK',
  1990,
  null,
  2012,
  2024,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2024 league regular logged near the top of the appearances table.', 'SAMPLE: A Germany goalkeeper in the 2012-2024 window.', 'SAMPLE: Club path in this league window: Eintracht Frankfurt.', 'SAMPLE: 293 appearances, 0 goals, 0 assists (0 combined) in the logged window.', 'SAMPLE: Initials K.T. Surname shape length 5.']
),
(
  'cfd518fd',
  'lars-stindl',
  true,
  'Lars Stindl',
  'bundesliga',
  'bundesliga',
  array['Borussia Monchengladbach', 'Hannover 96'],
  'Germany',
  'MF',
  1988,
  null,
  2012,
  2022,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2022 league regular logged near the top of the appearances table.', 'SAMPLE: A Germany midfielder in the 2012-2022 window.', 'SAMPLE: Club path in this league window: Borussia Monchengladbach, Hannover 96.', 'SAMPLE: 292 appearances, 77 goals, 58 assists (135 combined) in the logged window.', 'SAMPLE: Initials L.S. Surname shape length 6.']
),
(
  '8027b9c7',
  'yann-sommer',
  true,
  'Yann Sommer',
  'bundesliga',
  'bundesliga',
  array['Bayern Munich', 'Borussia Monchengladbach'],
  'Switzerland',
  'GK',
  1988,
  null,
  2014,
  2022,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2014-2022 league regular logged near the top of the appearances table.', 'SAMPLE: A Switzerland goalkeeper in the 2014-2022 window.', 'SAMPLE: Club path in this league window: Bayern Munich, Borussia Monchengladbach.', 'SAMPLE: 291 appearances, 0 goals, 1 assists (1 combined) in the logged window.', 'SAMPLE: Initials Y.S. Surname shape length 6.']
),
(
  'cf5cdbe6',
  'michael-gregoritsch',
  true,
  'Michael Gregoritsch',
  'bundesliga',
  'bundesliga',
  array['Augsburg', 'Schalke 04', 'Hamburger SV', 'SC Freiburg'],
  'Austria',
  'FW',
  1994,
  null,
  2015,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2015-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Austria forward in the 2015-2025 window.', 'SAMPLE: Club path in this league window: Augsburg, Schalke 04, Hamburger SV, SC Freiburg.', 'SAMPLE: 287 appearances, 65 goals, 28 assists (93 combined) in the logged window.', 'SAMPLE: Initials M.G. Surname shape length 11.']
),
(
  'ae092a4f',
  'patrick-herrmann',
  true,
  'Patrick Herrmann',
  'bundesliga',
  'bundesliga',
  array['Borussia Monchengladbach'],
  'Germany',
  'FW',
  1991,
  null,
  2012,
  2023,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2023 league regular logged near the top of the appearances table.', 'SAMPLE: A Germany forward in the 2012-2023 window.', 'SAMPLE: Club path in this league window: Borussia Monchengladbach.', 'SAMPLE: 287 appearances, 37 goals, 44 assists (81 combined) in the logged window.', 'SAMPLE: Initials P.H. Surname shape length 8.']
),
(
  '8a6c533b',
  'rani-khedira',
  true,
  'Rani Khedira',
  'bundesliga',
  'bundesliga',
  array['1.FC Union Berlin', 'Augsburg', 'RB Leipzig', 'VfB Stuttgart'],
  'Tunisia',
  'MF',
  1994,
  null,
  2013,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2013-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Tunisia midfielder in the 2013-2025 window.', 'SAMPLE: Club path in this league window: 1.FC Union Berlin, Augsburg, RB Leipzig, VfB Stuttgart.', 'SAMPLE: 287 appearances, 14 goals, 8 assists (22 combined) in the logged window.', 'SAMPLE: Initials R.K. Surname shape length 7.']
),
(
  '0d296b36',
  'niklas-stark',
  true,
  'Niklas Stark',
  'bundesliga',
  'bundesliga',
  array['1.FC Nuremberg', 'Hertha BSC', 'SV Werder Bremen'],
  'Germany',
  'DF',
  1995,
  null,
  2012,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Germany defender in the 2012-2025 window.', 'SAMPLE: Club path in this league window: 1.FC Nuremberg, Hertha BSC, SV Werder Bremen.', 'SAMPLE: 284 appearances, 9 goals, 5 assists (14 combined) in the logged window.', 'SAMPLE: Initials N.S. Surname shape length 5.']
),
(
  '252a762a',
  'koen-casteels',
  true,
  'Koen Casteels',
  'bundesliga',
  'bundesliga',
  array['SV Werder Bremen', 'TSG 1899 Hoffenheim', 'VfL Wolfsburg'],
  'Belgium',
  'GK',
  1992,
  null,
  2012,
  2023,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2023 league regular logged near the top of the appearances table.', 'SAMPLE: A Belgium goalkeeper in the 2012-2023 window.', 'SAMPLE: Club path in this league window: SV Werder Bremen, TSG 1899 Hoffenheim, VfL Wolfsburg.', 'SAMPLE: 283 appearances, 0 goals, 1 assists (1 combined) in the logged window.', 'SAMPLE: Initials K.C. Surname shape length 8.']
),
(
  '332056de',
  'nadiem-amiri',
  true,
  'Nadiem Amiri',
  'bundesliga',
  'bundesliga',
  array['1.FSV Mainz 05', 'Bayer Leverkusen', 'TSG 1899 Hoffenheim'],
  'Germany',
  'MF',
  1996,
  null,
  2014,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2014-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Germany midfielder in the 2014-2025 window.', 'SAMPLE: Club path in this league window: 1.FSV Mainz 05, Bayer Leverkusen, TSG 1899 Hoffenheim.', 'SAMPLE: 282 appearances, 39 goals, 36 assists (75 combined) in the logged window.', 'SAMPLE: Initials N.A. Surname shape length 5.']
),
(
  '2a05af06',
  'kevin-volland',
  true,
  'Kevin Volland',
  'bundesliga',
  'bundesliga',
  array['1.FC Union Berlin', 'Bayer Leverkusen', 'TSG 1899 Hoffenheim'],
  'Germany',
  'MF',
  1992,
  null,
  2012,
  2024,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2024 league regular logged near the top of the appearances table.', 'SAMPLE: A Germany midfielder in the 2012-2024 window.', 'SAMPLE: Club path in this league window: 1.FC Union Berlin, Bayer Leverkusen, TSG 1899 Hoffenheim.', 'SAMPLE: 277 appearances, 80 goals, 67 assists (147 combined) in the logged window.', 'SAMPLE: Initials K.V. Surname shape length 7.']
),
(
  '9fb596e3',
  'jonathan-schmid',
  true,
  'Jonathan Schmid',
  'bundesliga',
  'bundesliga',
  array['Augsburg', 'SC Freiburg', 'TSG 1899 Hoffenheim'],
  'France',
  'DF',
  1990,
  null,
  2012,
  2022,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2022 league regular logged near the top of the appearances table.', 'SAMPLE: A France defender in the 2012-2022 window.', 'SAMPLE: Club path in this league window: Augsburg, SC Freiburg, TSG 1899 Hoffenheim.', 'SAMPLE: 276 appearances, 34 goals, 40 assists (74 combined) in the logged window.', 'SAMPLE: Initials J.S. Surname shape length 6.']
),
(
  '7fd71248',
  'max-kruse',
  true,
  'Max Kruse',
  'bundesliga',
  'bundesliga',
  array['1.FC Union Berlin', 'Borussia Monchengladbach', 'SC Freiburg', 'SV Werder Bremen', 'VfL Wolfsburg'],
  'Germany',
  'FW',
  1988,
  null,
  2012,
  2022,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2022 league regular logged near the top of the appearances table.', 'SAMPLE: A Germany forward in the 2012-2022 window.', 'SAMPLE: Club path in this league window: 1.FC Union Berlin, Borussia Monchengladbach, SC Freiburg, SV Werder Bremen.', 'SAMPLE: 273 appearances, 95 goals, 72 assists (167 combined) in the logged window.', 'SAMPLE: Initials M.K. Surname shape length 5.']
),
(
  '947c9f3b',
  'christoph-kramer',
  true,
  'Christoph Kramer',
  'bundesliga',
  'bundesliga',
  array['Bayer Leverkusen', 'Borussia Monchengladbach'],
  'Germany',
  'MF',
  1991,
  null,
  2013,
  2023,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2013-2023 league regular logged near the top of the appearances table.', 'SAMPLE: A Germany midfielder in the 2013-2023 window.', 'SAMPLE: Club path in this league window: Bayer Leverkusen, Borussia Monchengladbach.', 'SAMPLE: 271 appearances, 10 goals, 14 assists (24 combined) in the logged window.', 'SAMPLE: Initials C.K. Surname shape length 6.']
),
(
  '6da625a9',
  'kevin-kampl',
  true,
  'Kevin Kampl',
  'bundesliga',
  'bundesliga',
  array['Bayer Leverkusen', 'Borussia Dortmund', 'RB Leipzig'],
  'Slovenia',
  'MF',
  1990,
  null,
  2014,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2014-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Slovenia midfielder in the 2014-2025 window.', 'SAMPLE: Club path in this league window: Bayer Leverkusen, Borussia Dortmund, RB Leipzig.', 'SAMPLE: 270 appearances, 13 goals, 22 assists (35 combined) in the logged window.', 'SAMPLE: Initials K.K. Surname shape length 5.']
),
(
  'ca0a1be8',
  'peter-gulacsi',
  true,
  'Péter Gulácsi',
  'bundesliga',
  'bundesliga',
  array['RB Leipzig'],
  'Hungary',
  'GK',
  1990,
  null,
  2016,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2016-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Hungary goalkeeper in the 2016-2025 window.', 'SAMPLE: Club path in this league window: RB Leipzig.', 'SAMPLE: 269 appearances, 0 goals, 2 assists (2 combined) in the logged window.', 'SAMPLE: Initials P.G. Surname shape length 7.']
),
(
  '3df218b0',
  'marcel-sabitzer',
  true,
  'Marcel Sabitzer',
  'bundesliga',
  'bundesliga',
  array['Bayern Munich', 'Borussia Dortmund', 'RB Leipzig'],
  'Austria',
  'MF',
  1994,
  null,
  2016,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2016-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Austria midfielder in the 2016-2025 window.', 'SAMPLE: Club path in this league window: Bayern Munich, Borussia Dortmund, RB Leipzig.', 'SAMPLE: 262 appearances, 40 goals, 34 assists (74 combined) in the logged window.', 'SAMPLE: Initials M.S. Surname shape length 8.']
),
(
  'ff215af5',
  'willi-orban',
  true,
  'Willi Orbán',
  'bundesliga',
  'bundesliga',
  array['RB Leipzig'],
  'Hungary',
  'DF',
  1992,
  null,
  2016,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2016-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Hungary defender in the 2016-2025 window.', 'SAMPLE: Club path in this league window: RB Leipzig.', 'SAMPLE: 259 appearances, 28 goals, 5 assists (33 combined) in the logged window.', 'SAMPLE: Initials W.O. Surname shape length 5.']
),
(
  '7cd9ac31',
  'waldemar-anton',
  true,
  'Waldemar Anton',
  'bundesliga',
  'bundesliga',
  array['Borussia Dortmund', 'Hannover 96', 'VfB Stuttgart'],
  'Germany',
  'DF',
  1996,
  null,
  2015,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2015-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Germany defender in the 2015-2025 window.', 'SAMPLE: Club path in this league window: Borussia Dortmund, Hannover 96, VfB Stuttgart.', 'SAMPLE: 254 appearances, 10 goals, 10 assists (20 combined) in the logged window.', 'SAMPLE: Initials W.A. Surname shape length 5.']
),
(
  '5116ac55',
  'john-brooks',
  true,
  'John Brooks',
  'bundesliga',
  'bundesliga',
  array['Hertha BSC', 'TSG 1899 Hoffenheim', 'VfL Wolfsburg'],
  'United States',
  'DF',
  1993,
  null,
  2013,
  2023,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2013-2023 league regular logged near the top of the appearances table.', 'SAMPLE: A United States defender in the 2013-2023 window.', 'SAMPLE: Club path in this league window: Hertha BSC, TSG 1899 Hoffenheim, VfL Wolfsburg.', 'SAMPLE: 252 appearances, 14 goals, 7 assists (21 combined) in the logged window.', 'SAMPLE: Initials J.B. Surname shape length 6.']
),
(
  'e3494b1d',
  'filip-kostic',
  true,
  'Filip Kostić',
  'bundesliga',
  'bundesliga',
  array['Eintracht Frankfurt', 'Hamburger SV', 'VfB Stuttgart'],
  'Serbia',
  'MF',
  1992,
  null,
  2014,
  2022,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2014-2022 league regular logged near the top of the appearances table.', 'SAMPLE: A Serbia midfielder in the 2014-2022 window.', 'SAMPLE: Club path in this league window: Eintracht Frankfurt, Hamburger SV, VfB Stuttgart.', 'SAMPLE: 249 appearances, 35 goals, 68 assists (103 combined) in the logged window.', 'SAMPLE: Initials F.K. Surname shape length 6.']
),
(
  '38eedfc1',
  'ridle-baku',
  true,
  'Ridle Baku',
  'bundesliga',
  'bundesliga',
  array['1.FSV Mainz 05', 'RB Leipzig', 'VfL Wolfsburg'],
  'Germany',
  'DF',
  1998,
  null,
  2017,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2017-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Germany defender in the 2017-2025 window.', 'SAMPLE: Club path in this league window: 1.FSV Mainz 05, RB Leipzig, VfL Wolfsburg.', 'SAMPLE: 248 appearances, 24 goals, 27 assists (51 combined) in the logged window.', 'SAMPLE: Initials R.B. Surname shape length 4.']
),
(
  '6a8d5850',
  'yussuf-poulsen',
  true,
  'Yussuf Poulsen',
  'bundesliga',
  'bundesliga',
  array['Hamburger SV', 'RB Leipzig'],
  'Denmark',
  'FW',
  1994,
  null,
  2016,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2016-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Denmark forward in the 2016-2025 window.', 'SAMPLE: Club path in this league window: Hamburger SV, RB Leipzig.', 'SAMPLE: 248 appearances, 50 goals, 27 assists (77 combined) in the logged window.', 'SAMPLE: Initials Y.P. Surname shape length 7.']
),
(
  '15f2e102',
  'david-alaba',
  true,
  'David Alaba',
  'bundesliga',
  'bundesliga',
  array['Bayern Munich'],
  'Austria',
  'DF',
  1992,
  null,
  2012,
  2020,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2020 league regular logged near the top of the appearances table.', 'SAMPLE: A Austria defender in the 2012-2020 window.', 'SAMPLE: Club path in this league window: Bayern Munich.', 'SAMPLE: 246 appearances, 20 goals, 27 assists (47 combined) in the logged window.', 'SAMPLE: Initials D.A. Surname shape length 5.']
),
(
  '6f041388',
  'maximilian-mittelstadt',
  true,
  'Maximilian Mittelstädt',
  'bundesliga',
  'bundesliga',
  array['Hertha BSC', 'VfB Stuttgart'],
  'Germany',
  'DF',
  1997,
  null,
  2015,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2015-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Germany defender in the 2015-2025 window.', 'SAMPLE: Club path in this league window: Hertha BSC, VfB Stuttgart.', 'SAMPLE: 239 appearances, 11 goals, 31 assists (42 combined) in the logged window.', 'SAMPLE: Initials M.M. Surname shape length 11.']
),
(
  'bb32f451',
  'davie-selke',
  true,
  'Davie Selke',
  'bundesliga',
  'bundesliga',
  array['1.FC Köln', 'Hertha BSC', 'RB Leipzig', 'SV Werder Bremen'],
  'Germany',
  'FW',
  1995,
  null,
  2013,
  2023,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2013-2023 league regular logged near the top of the appearances table.', 'SAMPLE: A Germany forward in the 2013-2023 window.', 'SAMPLE: Club path in this league window: 1.FC Köln, Hertha BSC, RB Leipzig, SV Werder Bremen.', 'SAMPLE: 238 appearances, 46 goals, 20 assists (66 combined) in the logged window.', 'SAMPLE: Initials D.S. Surname shape length 5.']
),
(
  '5ca84c07',
  'dayot-upamecano',
  true,
  'Dayot Upamecano',
  'bundesliga',
  'bundesliga',
  array['Bayern Munich', 'RB Leipzig'],
  'France',
  'DF',
  1998,
  null,
  2016,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2016-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A France defender in the 2016-2025 window.', 'SAMPLE: Club path in this league window: Bayern Munich, RB Leipzig.', 'SAMPLE: 238 appearances, 9 goals, 12 assists (21 combined) in the logged window.', 'SAMPLE: Initials D.U. Surname shape length 9.']
),
(
  '1b399934',
  'marius-wolf',
  true,
  'Marius Wolf',
  'bundesliga',
  'bundesliga',
  array['1.FC Köln', 'Borussia Dortmund', 'Eintracht Frankfurt', 'Augsburg', 'Hannover 96', 'Hertha BSC'],
  'Germany',
  'DF',
  1995,
  null,
  2015,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2015-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Germany defender in the 2015-2025 window.', 'SAMPLE: Club path in this league window: 1.FC Köln, Borussia Dortmund, Eintracht Frankfurt, Augsburg.', 'SAMPLE: 236 appearances, 15 goals, 26 assists (41 combined) in the logged window.', 'SAMPLE: Initials M.W. Surname shape length 4.']
),
(
  '34c3af6c',
  'thorgan-hazard',
  true,
  'Thorgan Hazard',
  'bundesliga',
  'bundesliga',
  array['Borussia Dortmund', 'Borussia Monchengladbach'],
  'Belgium',
  'MF',
  1993,
  null,
  2014,
  2023,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2014-2023 league regular logged near the top of the appearances table.', 'SAMPLE: A Belgium midfielder in the 2014-2023 window.', 'SAMPLE: Club path in this league window: Borussia Dortmund, Borussia Monchengladbach.', 'SAMPLE: 234 appearances, 43 goals, 52 assists (95 combined) in the logged window.', 'SAMPLE: Initials T.H. Surname shape length 6.']
),
(
  '6f2c69fd',
  'christian-gentner',
  true,
  'Christian Gentner',
  'bundesliga',
  'bundesliga',
  array['1.FC Union Berlin', 'VfB Stuttgart'],
  'Germany',
  'MF',
  1985,
  null,
  2012,
  2020,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2020 league regular logged near the top of the appearances table.', 'SAMPLE: A Germany midfielder in the 2012-2020 window.', 'SAMPLE: Club path in this league window: 1.FC Union Berlin, VfB Stuttgart.', 'SAMPLE: 233 appearances, 24 goals, 27 assists (51 combined) in the logged window.', 'SAMPLE: Initials C.G. Surname shape length 7.']
),
(
  '0c30d1d0',
  'karim-bellarabi',
  true,
  'Karim Bellarabi',
  'bundesliga',
  'bundesliga',
  array['Bayer Leverkusen', 'Eintracht Braunschweig'],
  'Germany',
  'FW',
  1990,
  null,
  2012,
  2022,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2022 league regular logged near the top of the appearances table.', 'SAMPLE: A Germany forward in the 2012-2022 window.', 'SAMPLE: Club path in this league window: Bayer Leverkusen, Eintracht Braunschweig.', 'SAMPLE: 231 appearances, 36 goals, 52 assists (88 combined) in the logged window.', 'SAMPLE: Initials K.B. Surname shape length 9.']
),
(
  'e2acc161',
  'mitchell-weiser',
  true,
  'Mitchell Weiser',
  'bundesliga',
  'bundesliga',
  array['Bayer Leverkusen', 'Bayern Munich', 'Hertha BSC', 'SV Werder Bremen'],
  'Germany',
  'DF',
  1994,
  null,
  2013,
  2024,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2013-2024 league regular logged near the top of the appearances table.', 'SAMPLE: A Germany defender in the 2013-2024 window.', 'SAMPLE: Club path in this league window: Bayer Leverkusen, Bayern Munich, Hertha BSC, SV Werder Bremen.', 'SAMPLE: 231 appearances, 19 goals, 46 assists (65 combined) in the logged window.', 'SAMPLE: Initials M.W. Surname shape length 6.']
),
(
  '90f06b87',
  'oscar-wendt',
  true,
  'Oscar Wendt',
  'bundesliga',
  'bundesliga',
  array['Borussia Monchengladbach'],
  'Sweden',
  'DF',
  1985,
  null,
  2012,
  2020,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2020 league regular logged near the top of the appearances table.', 'SAMPLE: A Sweden defender in the 2012-2020 window.', 'SAMPLE: Club path in this league window: Borussia Monchengladbach.', 'SAMPLE: 230 appearances, 16 goals, 18 assists (34 combined) in the logged window.', 'SAMPLE: Initials O.W. Surname shape length 5.']
),
(
  '2a1acfd3',
  'jonas-hector',
  true,
  'Jonas Hector',
  'bundesliga',
  'bundesliga',
  array['1.FC Köln'],
  'Germany',
  'DF',
  1990,
  null,
  2014,
  2022,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2014-2022 league regular logged near the top of the appearances table.', 'SAMPLE: A Germany defender in the 2014-2022 window.', 'SAMPLE: Club path in this league window: 1.FC Köln.', 'SAMPLE: 228 appearances, 12 goals, 21 assists (33 combined) in the logged window.', 'SAMPLE: Initials J.H. Surname shape length 6.']
),
(
  'bfdd0526',
  'danny-da-costa',
  true,
  'Danny da Costa',
  'bundesliga',
  'bundesliga',
  array['1.FSV Mainz 05', 'Bayer Leverkusen', 'Eintracht Frankfurt', 'Ingolstadt 04'],
  'Germany',
  'DF',
  1993,
  null,
  2015,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2015-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Germany defender in the 2015-2025 window.', 'SAMPLE: Club path in this league window: 1.FSV Mainz 05, Bayer Leverkusen, Eintracht Frankfurt, Ingolstadt 04.', 'SAMPLE: 227 appearances, 6 goals, 25 assists (31 combined) in the logged window.', 'SAMPLE: Initials D.D.C. Surname shape length 5.']
),
(
  '6c2af090',
  'vladimir-darida',
  true,
  'Vladimír Darida',
  'bundesliga',
  'bundesliga',
  array['Hertha BSC', 'SC Freiburg'],
  'Czech Republic',
  'MF',
  1990,
  null,
  2013,
  2022,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2013-2022 league regular logged near the top of the appearances table.', 'SAMPLE: A Czech Republic midfielder in the 2013-2022 window.', 'SAMPLE: Club path in this league window: Hertha BSC, SC Freiburg.', 'SAMPLE: 224 appearances, 22 goals, 32 assists (54 combined) in the logged window.', 'SAMPLE: Initials V.D. Surname shape length 6.']
),
(
  'aabcee34',
  'raphael-guerreiro',
  true,
  'Raphaël Guerreiro',
  'bundesliga',
  'bundesliga',
  array['Bayern Munich', 'Borussia Dortmund'],
  'Portugal',
  'DF',
  1993,
  null,
  2016,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2016-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Portugal defender in the 2016-2025 window.', 'SAMPLE: Club path in this league window: Bayern Munich, Borussia Dortmund.', 'SAMPLE: 223 appearances, 42 goals, 47 assists (89 combined) in the logged window.', 'SAMPLE: Initials R.G. Surname shape length 9.']
),
(
  'a62b1e85',
  'sebastian-rode',
  true,
  'Sebastian Rode',
  'bundesliga',
  'bundesliga',
  array['Bayern Munich', 'Borussia Dortmund', 'Eintracht Frankfurt'],
  'Germany',
  'MF',
  1990,
  null,
  2012,
  2023,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2023 league regular logged near the top of the appearances table.', 'SAMPLE: A Germany midfielder in the 2012-2023 window.', 'SAMPLE: Club path in this league window: Bayern Munich, Borussia Dortmund, Eintracht Frankfurt.', 'SAMPLE: 222 appearances, 13 goals, 11 assists (24 combined) in the logged window.', 'SAMPLE: Initials S.R. Surname shape length 4.']
),
(
  '16aa3d8b',
  'dominique-heintz',
  true,
  'Dominique Heintz',
  'bundesliga',
  'bundesliga',
  array['1.FC Köln', '1.FC Union Berlin', 'SC Freiburg', 'VfL Bochum'],
  'Germany',
  'DF',
  1993,
  null,
  2015,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2015-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Germany defender in the 2015-2025 window.', 'SAMPLE: Club path in this league window: 1.FC Köln, 1.FC Union Berlin, SC Freiburg, VfL Bochum.', 'SAMPLE: 219 appearances, 4 goals, 3 assists (7 combined) in the logged window.', 'SAMPLE: Initials D.H. Surname shape length 6.']
),
(
  '2138a72b',
  'timothy-chandler',
  true,
  'Timothy Chandler',
  'bundesliga',
  'bundesliga',
  array['1.FC Nuremberg', 'Eintracht Frankfurt'],
  'United States',
  'DF',
  1990,
  null,
  2012,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A United States defender in the 2012-2025 window.', 'SAMPLE: Club path in this league window: 1.FC Nuremberg, Eintracht Frankfurt.', 'SAMPLE: 219 appearances, 11 goals, 17 assists (28 combined) in the logged window.', 'SAMPLE: Initials T.C. Surname shape length 8.']
),
(
  '1e95e803',
  'gonzalo-castro',
  true,
  'Gonzalo Castro',
  'bundesliga',
  'bundesliga',
  array['Arminia Bielefeld', 'Bayer Leverkusen', 'Borussia Dortmund', 'VfB Stuttgart'],
  'Germany',
  'MF',
  1987,
  null,
  2012,
  2021,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2021 league regular logged near the top of the appearances table.', 'SAMPLE: A Germany midfielder in the 2012-2021 window.', 'SAMPLE: Club path in this league window: Arminia Bielefeld, Bayer Leverkusen, Borussia Dortmund, VfB Stuttgart.', 'SAMPLE: 218 appearances, 26 goals, 49 assists (75 combined) in the logged window.', 'SAMPLE: Initials G.C. Surname shape length 6.']
),
(
  '42447253',
  'benjamin-andre',
  true,
  'Benjamin André',
  'ligue_1',
  'ligue_1',
  array['Ajaccio', 'LOSC Lille', 'Stade Rennais'],
  'France',
  'MF',
  1990,
  null,
  2012,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A France midfielder in the 2012-2025 window.', 'SAMPLE: Club path in this league window: Ajaccio, LOSC Lille, Stade Rennais.', 'SAMPLE: 432 appearances, 22 goals, 26 assists (48 combined) in the logged window.', 'SAMPLE: Initials B.A. Surname shape length 5.']
),
(
  '775131e4',
  'anthony-lopes',
  true,
  'Anthony Lopes',
  'ligue_1',
  'ligue_1',
  array['Nantes', 'Olympique Lyon'],
  'Portugal',
  'GK',
  1990,
  null,
  2012,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Portugal goalkeeper in the 2012-2025 window.', 'SAMPLE: Club path in this league window: Nantes, Olympique Lyon.', 'SAMPLE: 427 appearances, 0 goals, 2 assists (2 combined) in the logged window.', 'SAMPLE: Initials A.L. Surname shape length 5.']
),
(
  'f15e1dbe',
  'adrien-thomasson',
  true,
  'Adrien Thomasson',
  'ligue_1',
  'ligue_1',
  array['Nantes', 'RC Lens', 'RC Strasbourg Alsace', 'Thonon Évian Grand Genève'],
  'France',
  'MF',
  1993,
  null,
  2014,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2014-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A France midfielder in the 2014-2025 window.', 'SAMPLE: Club path in this league window: Nantes, RC Lens, RC Strasbourg Alsace, Thonon Évian Grand Genève.', 'SAMPLE: 376 appearances, 49 goals, 60 assists (109 combined) in the logged window.', 'SAMPLE: Initials A.T. Surname shape length 9.']
),
(
  '7dcb98ab',
  'jordan-ferri',
  true,
  'Jordan Ferri',
  'ligue_1',
  'ligue_1',
  array['Montpellier HSC', 'Nîmes Olympique', 'Olympique Lyon'],
  'France',
  'MF',
  1992,
  null,
  2012,
  2024,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2024 league regular logged near the top of the appearances table.', 'SAMPLE: A France midfielder in the 2012-2024 window.', 'SAMPLE: Club path in this league window: Montpellier HSC, Nîmes Olympique, Olympique Lyon.', 'SAMPLE: 357 appearances, 11 goals, 27 assists (38 combined) in the logged window.', 'SAMPLE: Initials J.F. Surname shape length 5.']
),
(
  '660fa224',
  'ludovic-blas',
  true,
  'Ludovic Blas',
  'ligue_1',
  'ligue_1',
  array['EA Guingamp', 'Nantes', 'Stade Rennais'],
  'France',
  'MF',
  1997,
  null,
  2015,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2015-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A France midfielder in the 2015-2025 window.', 'SAMPLE: Club path in this league window: EA Guingamp, Nantes, Stade Rennais.', 'SAMPLE: 325 appearances, 53 goals, 41 assists (94 combined) in the logged window.', 'SAMPLE: Initials L.B. Surname shape length 4.']
),
(
  '65cc15db',
  'wahbi-khazri',
  true,
  'Wahbi Khazri',
  'ligue_1',
  'ligue_1',
  array['Saint-Étienne', 'Girondins Bordeaux', 'Montpellier HSC', 'SC Bastia', 'Stade Rennais'],
  'Tunisia',
  'FW',
  1991,
  null,
  2012,
  2024,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2024 league regular logged near the top of the appearances table.', 'SAMPLE: A Tunisia forward in the 2012-2024 window.', 'SAMPLE: Club path in this league window: Saint-Étienne, Girondins Bordeaux, Montpellier HSC, SC Bastia.', 'SAMPLE: 319 appearances, 75 goals, 39 assists (114 combined) in the logged window.', 'SAMPLE: Initials W.K. Surname shape length 6.']
),
(
  'b92b9821',
  'valere-germain',
  true,
  'Valère Germain',
  'ligue_1',
  'ligue_1',
  array['Monaco', 'Montpellier HSC', 'OGC Nice', 'Marseille'],
  'France',
  'FW',
  1990,
  null,
  2013,
  2022,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2013-2022 league regular logged near the top of the appearances table.', 'SAMPLE: A France forward in the 2013-2022 window.', 'SAMPLE: Club path in this league window: Monaco, Montpellier HSC, OGC Nice, Marseille.', 'SAMPLE: 311 appearances, 61 goals, 29 assists (90 combined) in the logged window.', 'SAMPLE: Initials V.G. Surname shape length 7.']
),
(
  'e7486a4c',
  'morgan-sanson',
  true,
  'Morgan Sanson',
  'ligue_1',
  'ligue_1',
  array['Montpellier HSC', 'OGC Nice', 'Marseille', 'RC Strasbourg Alsace'],
  'France',
  'MF',
  1994,
  null,
  2013,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2013-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A France midfielder in the 2013-2025 window.', 'SAMPLE: Club path in this league window: Montpellier HSC, OGC Nice, Marseille, RC Strasbourg Alsace.', 'SAMPLE: 304 appearances, 41 goals, 40 assists (81 combined) in the logged window.', 'SAMPLE: Initials M.S. Surname shape length 6.']
)
on conflict (id) do update set
  person_id = excluded.person_id,
  canonical = excluded.canonical,
  name = excluded.name,
  category = excluded.category,
  league = excluded.league,
  clubs = excluded.clubs,
  nationality = excluded.nationality,
  position = excluded.position,
  birth_year = excluded.birth_year,
  shirt_number = excluded.shirt_number,
  era_start = excluded.era_start,
  era_end = excluded.era_end,
  world_cup_editions = excluded.world_cup_editions,
  aliases = excluded.aliases,
  clues = excluded.clues;

