-- Batch 6/6: rows 401-407 of 407
-- Paste into Supabase SQL Editor and Run (in order 01 → 06)
insert into public.players (
  id, person_id, canonical, name, category, league, clubs,
  nationality, position, birth_year, shirt_number, era_start, era_end,
  world_cup_editions, aliases, clues
) values
(
  '40a798bb',
  'diego-costa',
  false,
  'Diego Costa',
  'premier_league',
  'premier_league',
  array['Chelsea'],
  'Spain',
  'FW',
  1988,
  19,
  2014,
  2018,
  array[]::integer[],
  array[]::text[],
  array['He fought center backs for a living and won two titles as a bonus.', 'A Spanish striker of elbows, grins and cold finishes.', 'Atletico''s warhead to Chelsea''s double champion.', 'The 2014-15 title, 20 goals and 200 arguments.', 'Initials D.C.']
),
(
  'aa1b00c3',
  'emmanuel-adebayor',
  true,
  'Emmanuel Adebayor',
  'premier_league',
  'premier_league',
  array['Arsenal', 'Manchester City', 'Tottenham Hotspur', 'Crystal Palace'],
  'Togo',
  'FW',
  1984,
  25,
  2006,
  2016,
  array[]::integer[],
  array[]::text[],
  array['The knee slide from one end of the pitch to the other, in front of his old fans.', 'A Togolese striker of peaks that infuriated and delighted.', 'Arsenal to City to Spurs, collecting enemies and goals.', 'The hundred meter celebration against Arsenal, 2009.', 'Initials E.A.']
),
(
  'b5121e66',
  'joe-hart',
  true,
  'Joe Hart',
  'premier_league',
  'premier_league',
  array['Manchester City', 'West Ham United', 'Burnley'],
  'England',
  'GK',
  1987,
  1,
  2006,
  2020,
  array[]::integer[],
  array[]::text[],
  array['England''s number one through three World Cups, City''s four Golden Gloves.', 'An English goalkeeper of shampoo ads and big saves.', 'Shrewsbury to City''s first titles.', 'The Milan night of 2011, save after save after save.', 'Initials J.H.']
),
(
  '468ef4b0',
  'jarrod-bowen',
  true,
  'Jarrod Bowen',
  'premier_league',
  'premier_league',
  array['West Ham United'],
  'England',
  'FW',
  1996,
  20,
  2020,
  2026,
  array[]::integer[],
  array[]::text[],
  array['The Hammer who won a European final in Prague with the last meaningful kick.', 'An English forward, non league at eighteen, England international at twenty six.', 'Hull to West Ham''s talisman.', 'Prague 2023, minute 90, through on goal, history.', 'Initials J.B.']
),
(
  '8eb0b8cf',
  'ollie-watkins',
  true,
  'Ollie Watkins',
  'premier_league',
  'premier_league',
  array['Aston Villa'],
  'England',
  'FW',
  1995,
  11,
  2020,
  2026,
  array[]::integer[],
  array[]::text[],
  array['The semifinal winner at Wembley that sent a nation and Villa Park into orbit.', 'An English striker of channel runs and late arrivals.', 'Exeter to Brentford to Villa''s spearhead.', 'The Euro 2024 semifinal winner against Holland, off the bench.', 'Initials O.W.']
),
(
  'f1525fba',
  'alexander-isak',
  true,
  'Alexander Isak',
  'premier_league',
  'premier_league',
  array['Newcastle United', 'Liverpool'],
  'Sweden',
  'FW',
  1999,
  14,
  2022,
  2026,
  array[]::integer[],
  array[]::text[],
  array['A Swedish striker so smooth Newcastle fans wrote hymns before the record sale south.', 'A Swedish number nine who runs upright like the game is easy.', 'Sociedad to Tyneside to Anfield.', 'The 2025 Carabao Cup final goal that ended Newcastle''s 70 year wait.', 'Initials A.I.']
),
(
  '79943b99',
  'william-saliba',
  true,
  'William Saliba',
  'premier_league',
  'premier_league',
  array['Arsenal'],
  'France',
  'DF',
  2001,
  2,
  2022,
  2026,
  array[]::integer[],
  array[]::text[],
  array['Three loans, then he returned and Arsenal''s defense grew up overnight.', 'A French center back of long strides and no visible panic.', 'Saint Etienne to Arsenal via patience.', 'The 2022-23 emergence that transformed the title race.', 'Initials W.S.']
)
on conflict (id) do update set
  person_id = excluded.person_id,
  canonical = excluded.canonical,
  name = excluded.name,
  category = excluded.category,
  league = excluded.league,
  clubs = excluded.clubs,
  nationality = excluded.nationality,
  position = excluded.position,
  birth_year = excluded.birth_year,
  shirt_number = excluded.shirt_number,
  era_start = excluded.era_start,
  era_end = excluded.era_end,
  world_cup_editions = excluded.world_cup_editions,
  aliases = excluded.aliases,
  clues = excluded.clues;

-- Verify this batch: select count(*) from public.players; -- expect 407 cumulative after all batches through 06
