-- Batch 2/6: rows 81-160 of 407
-- Paste into Supabase SQL Editor and Run (in order 01 → 06)
insert into public.players (
  id, person_id, canonical, name, category, league, clubs,
  nationality, position, birth_year, shirt_number, era_start, era_end,
  world_cup_editions, aliases, clues
) values
(
  '8074645d',
  'achraf-hakimi',
  true,
  'Achraf Hakimi',
  'world_cup',
  null,
  array['Paris Saint-Germain'],
  'Morocco',
  'DF',
  1998,
  2,
  2018,
  2022,
  array[2018, 2022]::integer[],
  array[]::text[],
  array['A Panenka against the country of his birth in the 2022 shootout.', 'A Moroccan right back with winger''s legs, part of Africa''s first semifinalists.', 'Madrid academy to Dortmund to Inter to Paris.', 'The chipped winning penalty against Spain, Doha 2022.', 'Initials A.H.']
),
(
  'f9cd323e',
  'yassine-bounou',
  true,
  'Yassine Bounou',
  'world_cup',
  null,
  array['Al-Hilal'],
  'Morocco',
  'GK',
  1991,
  1,
  2018,
  2022,
  array[2018, 2022]::integer[],
  array['Bono'],
  array['Two shootout saves against Spain as Morocco rewrote World Cup history.', 'A Moroccan goalkeeper, Canadian born, cooler than the moment every time.', 'Sevilla''s Europa League hero before the Saudi move.', 'The 2022 wall behind Africa''s first ever semifinal run.', 'Bono. Initials Y.B.']
),
(
  'ffcab26f',
  'olivier-giroud',
  true,
  'Olivier Giroud',
  'world_cup',
  null,
  array['AC Milan'],
  'France',
  'FW',
  1986,
  9,
  2014,
  2022,
  array[2014, 2018, 2022]::integer[],
  array[]::text[],
  array['He became France''s all time top scorer at the 2022 World Cup while the world argued he wasn''t good enough.', 'A French number nine of old fashioned link play and scorpion kicks.', 'Montpellier to Arsenal to Chelsea to Milan.', 'Passing Henry''s record against Poland in Qatar.', 'Initials O.G.']
),
(
  '22a28908',
  'jude-bellingham',
  true,
  'Jude Bellingham',
  'world_cup',
  null,
  array['Real Madrid'],
  'England',
  'MF',
  2003,
  10,
  2022,
  2022,
  array[2022]::integer[],
  array[]::text[],
  array['England''s teenager in Qatar looked like their oldest head.', 'An English midfielder who skipped every queue on the way up.', 'Birmingham to Dortmund to the Bernabeu.', 'Opening England''s 2022 account against Iran, arriving like a veteran.', 'Initials J.B.']
),
(
  'ba881c79',
  'lionel-messi',
  true,
  'Lionel Messi',
  'world_cup',
  null,
  array['Inter Miami'],
  'Argentina',
  'FW',
  1987,
  10,
  2006,
  2026,
  array[2006, 2010, 2014, 2018, 2022, 2026]::integer[],
  array['Leo', 'La Pulga', 'The GOAT'],
  array['Five World Cups chasing one trophy, and the last one finally said yes.', 'An Argentine number ten who spent two decades as the answer to every question.', 'La Masia forever, Paris briefly, Miami now.', 'Lusail, December 2022. Two in the final, the shootout, the black bisht over the trophy.', 'Leo. La Pulga. The GOAT.']
),
(
  '80c61839',
  'cristiano-ronaldo',
  true,
  'Cristiano Ronaldo',
  'world_cup',
  null,
  array['Al-Nassr'],
  'Portugal',
  'FW',
  1985,
  7,
  2006,
  2026,
  array[2006, 2010, 2014, 2018, 2022, 2026]::integer[],
  array['CR7'],
  array['Five World Cups of goals in every one, still chasing the only prize that ran.', 'A Portuguese forward whose hunger outlasted three generations of rivals.', 'Sporting to United to Madrid''s 450 goals to Saudi Arabia.', 'The hat trick against Spain in 2018, capped by that free kick.', 'CR7.']
),
(
  '8a768600',
  'harry-kane',
  true,
  'Harry Kane',
  'world_cup',
  null,
  array['Bayern Munich'],
  'England',
  'FW',
  1993,
  9,
  2018,
  2026,
  array[2018, 2022, 2026]::integer[],
  array[]::text[],
  array['England''s captain and record scorer, Golden Boot in Russia, penalty pain in Qatar.', 'An English number nine who doubles as his team''s best playmaker.', 'One long Tottenham chapter, then Bavaria for the trophies.', 'Six goals at the 2018 World Cup, top of the charts.', 'Initials H.K.']
),
(
  'e0d8b072',
  'erling-haaland',
  true,
  'Erling Haaland',
  'world_cup',
  null,
  array['Manchester City'],
  'Norway',
  'FW',
  2000,
  9,
  2026,
  2026,
  array[2026]::integer[],
  array['The Terminator'],
  array['A nation of five million waited decades. In 2026 he made them a World Cup story.', 'A Norwegian number nine built in a laboratory that only produces goals.', 'Bryne to Salzburg to Dortmund to City''s record books.', 'Leading Norway''s stunning 2026 run, Brazil among the fallen.', 'The Terminator. Initials E.H.']
),
(
  '22d96210',
  'mikel-merino',
  true,
  'Mikel Merino',
  'world_cup',
  null,
  array['Arsenal'],
  'Spain',
  'MF',
  1996,
  null,
  2026,
  2026,
  array[2026]::integer[],
  array[]::text[],
  array['A midfielder by trade whose late goals keep deciding knockout nights for Spain.', 'A Spanish midfielder, tall, tidy, and lethal arriving from deep.', 'Newcastle to Sociedad to Arsenal.', 'The late winner against Belgium in the 2026 quarterfinal in the books.', 'Initials M.M.']
),
(
  '0183fa12',
  'adrien-rabiot',
  true,
  'Adrien Rabiot',
  'world_cup',
  null,
  array['AC Milan'],
  'France',
  'MF',
  1995,
  null,
  2026,
  2026,
  array[2026]::integer[],
  array[]::text[],
  array['A French midfielder whose 2026 tournament made more news than most strikers.', 'An elegant left footed midfielder with opinions and lungs to match.', 'PSG academy to Juventus to Milan.', 'A central figure of France''s 2026 semifinal run.', 'Initials A.R.']
),
(
  '8bd69ae6',
  'alan-shearer',
  true,
  'Alan Shearer',
  'premier_league',
  'premier_league',
  array['Newcastle United', 'Blackburn Rovers'],
  'England',
  'FW',
  1970,
  9,
  1992,
  2006,
  array[]::integer[],
  array[]::text[],
  array['The Premier League''s all time top scorer, and the record still hasn''t moved.', 'An English number nine, one armed celebration, zero frills.', 'A world record fee took him home to Tyneside after title glory at Blackburn.', 'The 1994-95 title with Blackburn, thirty four goals doing the lifting.', '260 goals. One raised arm. Initials A.S.']
),
(
  '4ad7a541',
  'eric-cantona',
  true,
  'Eric Cantona',
  'premier_league',
  'premier_league',
  array['Manchester United', 'Leeds United'],
  'France',
  'FW',
  1966,
  7,
  1992,
  1997,
  array[]::integer[],
  array['King Eric'],
  array['Collar up, chest out, the Frenchman who taught United how to swagger.', 'A French forward who treated the penalty box like a stage.', 'Leeds champion first, then across the Pennines for immortality.', 'The kung fu kick at Selhurst Park, and the seagulls press conference after.', 'King Eric. Initials E.C.']
),
(
  'd2340321',
  'peter-schmeichel',
  true,
  'Peter Schmeichel',
  'premier_league',
  'premier_league',
  array['Manchester United'],
  'Denmark',
  'GK',
  1963,
  1,
  1992,
  2003,
  array[]::integer[],
  array[]::text[],
  array['The great Dane whose starfish saves backboned the first United dynasty.', 'A goalkeeper who screamed at defenders and threw counterattacks like javelins.', 'United''s number one through five titles, ending on the treble.', 'Captain in the 1999 Champions League final, his last United match.', 'Father of another PL keeper. Initials P.S.']
),
(
  'd7e9228f',
  'ryan-giggs',
  true,
  'Ryan Giggs',
  'premier_league',
  'premier_league',
  array['Manchester United'],
  'Wales',
  'MF',
  1973,
  11,
  1992,
  2014,
  array[]::integer[],
  array[]::text[],
  array['He scored in every Premier League season for its first two decades.', 'A Welsh winger who aged from flyer to conductor without leaving one club.', 'United, boy to forty, thirteen league titles.', 'The 1999 FA Cup semifinal slalom, shirt off, chest bared to Highbury.', 'Initials R.G.']
),
(
  '45f97de2',
  'paul-scholes',
  true,
  'Paul Scholes',
  'premier_league',
  'premier_league',
  array['Manchester United'],
  'England',
  'MF',
  1974,
  18,
  1994,
  2013,
  array[]::integer[],
  array[]::text[],
  array['The midfielder Zidane and Xavi called the best of their era, who couldn''t tackle to save his life.', 'An English ginger number eighteen with a rocket in each boot.', 'One club, United, retirement, then a comeback five months later.', 'Volleys against Bradford and Villa that physics still disputes.', 'Initials P.S.']
),
(
  '121adbd5',
  'david-beckham',
  true,
  'David Beckham',
  'premier_league',
  'premier_league',
  array['Manchester United'],
  'England',
  'MF',
  1975,
  7,
  1995,
  2003,
  array[]::integer[],
  array['Becks'],
  array['He scored from the halfway line on opening day 1996 and never stopped being famous again.', 'An English right midfielder whose crosses were letters addressed by hand.', 'United''s class of 92 to Madrid, LA, Milan and Paris.', 'Wimbledon, day one, lob from his own half.', 'Becks. Initials D.B.']
),
(
  '25591f85',
  'roy-keane',
  true,
  'Roy Keane',
  'premier_league',
  'premier_league',
  array['Manchester United'],
  'Ireland',
  'MF',
  1971,
  16,
  1992,
  2005,
  array[]::integer[],
  array[]::text[],
  array['United''s captain of captains, feared by teammates slightly more than opponents.', 'An Irish midfielder who ran on fury and standards.', 'Forest to United, seven titles and a walkout.', 'Turin 1999, booked, out of the final, and the greatest selfless midfield performance ever.', 'Initials R.K.']
),
(
  '7256e70c',
  'dennis-bergkamp',
  false,
  'Dennis Bergkamp',
  'premier_league',
  'premier_league',
  array['Arsenal'],
  'Netherlands',
  'FW',
  1969,
  10,
  1995,
  2006,
  array[]::integer[],
  array['The Iceman'],
  array['The statue outside the Emirates is mid air, which is where he lived.', 'A Dutch forward whose first touch was a form of manners.', 'Inter misfit to Arsenal genius across eleven seasons.', 'Newcastle 2002. The spin. You know the one.', 'The Iceman. Initials D.B.']
),
(
  '7b75cd13',
  'thierry-henry',
  false,
  'Thierry Henry',
  'premier_league',
  'premier_league',
  array['Arsenal'],
  'France',
  'FW',
  1977,
  14,
  1999,
  2012,
  array[]::integer[],
  array['Titi'],
  array['The league''s greatest signing arrived a winger and left the record books rewritten.', 'A French forward who scored goals of impossible nonchalance.', 'Juventus reject to Arsenal''s all time top scorer.', 'The flick up and volley against United, then standing still to watch it.', 'Titi. Initials T.H.']
),
(
  '86f2358d',
  'patrick-vieira',
  true,
  'Patrick Vieira',
  'premier_league',
  'premier_league',
  array['Arsenal'],
  'France',
  'MF',
  1976,
  4,
  1996,
  2005,
  array[]::integer[],
  array[]::text[],
  array['Highbury''s tunnel wars had a general, and he wore four.', 'A French midfielder with telescopic legs and a captain''s snarl.', 'Milan reserve to Arsenal colossus to a City finale.', 'His last Arsenal kick won the 2005 FA Cup shootout.', 'Initials P.V.']
),
(
  'e53e2c74',
  'tony-adams',
  true,
  'Tony Adams',
  'premier_league',
  'premier_league',
  array['Arsenal'],
  'England',
  'DF',
  1966,
  6,
  1992,
  2002,
  array[]::integer[],
  array['Mr Arsenal'],
  array['Mr Arsenal captained the club in three different decades.', 'An English center back who marshalled the famous back four and raised his arm for offside like a salute.', 'One club from seventeen to retirement.', 'The title sealing goal against Everton in 1998, arms wide.', 'Initials T.A.']
),
(
  '241528b4',
  'robert-pires',
  true,
  'Robert Pires',
  'premier_league',
  'premier_league',
  array['Arsenal'],
  'France',
  'MF',
  1973,
  7,
  2000,
  2006,
  array[]::integer[],
  array[]::text[],
  array['The Invincible who glided down the left as if the grass owed him favors.', 'A French winger of silk, scorer of title winning goals.', 'Marseille to Arsenal''s double and unbeaten sides.', 'Goal of the season against Aston Villa, 2002, chip and volley.', 'Initials R.P.']
),
(
  'c3ee6c4f',
  'sol-campbell',
  true,
  'Sol Campbell',
  'premier_league',
  'premier_league',
  array['Arsenal', 'Tottenham Hotspur'],
  'England',
  'DF',
  1974,
  23,
  1992,
  2011,
  array[]::integer[],
  array[]::text[],
  array['He crossed the most dangerous divide in London football and won the double for it.', 'An English center back built like a monument, twice a title winner.', 'Tottenham captain to Arsenal Invincible.', 'Scoring in a Champions League final for Arsenal in 2006.', 'Initials S.C.']
),
(
  '1ebc9435',
  'ian-wright',
  true,
  'Ian Wright',
  'premier_league',
  'premier_league',
  array['Arsenal'],
  'England',
  'FW',
  1963,
  8,
  1992,
  2000,
  array[]::integer[],
  array['Wrighty'],
  array['Late to professional football, early to every finish, Arsenal''s record breaker of the nineties.', 'An English striker who celebrated like every goal was his first.', 'Crystal Palace to Highbury, 185 Arsenal goals.', 'The shirt under the shirt: 179, just done it, against Bolton.', 'Wrighty. Initials I.W.']
),
(
  '4b2f8772',
  'gianfranco-zola',
  true,
  'Gianfranco Zola',
  'premier_league',
  'premier_league',
  array['Chelsea'],
  'Italy',
  'FW',
  1966,
  25,
  1996,
  2003,
  array[]::integer[],
  array[]::text[],
  array['Chelsea''s little magician, voted their greatest player before the money era began.', 'An Italian forward of flicks, free kicks and permanent smiles.', 'Napoli''s apprentice to Maradona, then west London''s favorite.', 'The backheel volley against Norwich, invented mid air.', 'Magic Box. Initials G.Z.']
),
(
  'e242f25a',
  'frank-lampard',
  true,
  'Frank Lampard',
  'premier_league',
  'premier_league',
  array['Chelsea', 'West Ham United'],
  'England',
  'MF',
  1978,
  8,
  1995,
  2015,
  array[]::integer[],
  array['Super Frank'],
  array['The highest scoring midfielder the Premier League has ever seen.', 'An English number eight who arrived in the box like a scheduled train.', 'West Ham''s academy to Chelsea''s record scorer.', 'Two against Bolton in 2005 to seal Chelsea''s first title in fifty years.', 'Super Frank. Initials F.L.']
),
(
  'b72c12c9',
  'john-terry',
  true,
  'John Terry',
  'premier_league',
  'premier_league',
  array['Chelsea'],
  'England',
  'DF',
  1980,
  26,
  1998,
  2017,
  array[]::integer[],
  array['JT'],
  array['Captain, leader, and the last defender of the old English school.', 'An English center back who headed away everything including doubts.', 'One badge, Chelsea, five league titles.', 'Lifting the 2012 Champions League trophy in full kit, unused.', 'JT. Initials J.T.']
),
(
  '26e68c5c',
  'didier-drogba',
  true,
  'Didier Drogba',
  'premier_league',
  'premier_league',
  array['Chelsea'],
  'Ivory Coast',
  'FW',
  1978,
  11,
  2004,
  2015,
  array[]::integer[],
  array[]::text[],
  array['Big final, big man. Nine finals at Wembley and Munich, nine goals or thereabouts.', 'An Ivorian number nine who bullied title races single handedly.', 'Marseille to Chelsea, twice.', 'Munich 2012, the 88th minute header and the winning penalty.', 'Initials D.D.']
),
(
  'd64b4479',
  'petr-cech',
  true,
  'Petr Cech',
  'premier_league',
  'premier_league',
  array['Chelsea', 'Arsenal'],
  'Czech Republic',
  'GK',
  1982,
  1,
  2004,
  2019,
  array[]::integer[],
  array[]::text[],
  array['The helmet became a trademark, the clean sheets became a record.', 'A Czech goalkeeper of geometry and calm, 202 shutouts.', 'Chelsea''s wall for a decade, then a late Arsenal chapter.', 'The 2012 Champions League run, saving from Robben in the final.', 'Initials P.C.']
),
(
  '23c3eb2c',
  'steven-gerrard',
  true,
  'Steven Gerrard',
  'premier_league',
  'premier_league',
  array['Liverpool'],
  'England',
  'MF',
  1980,
  8,
  1998,
  2015,
  array[]::integer[],
  array['Stevie G'],
  array['Istanbul''s captain, and the league''s great almost.', 'An English midfielder who could do every job on the pitch, often in one half.', 'Liverpool from boy to legend, then LA.', 'The 2006 FA Cup final thirty five yarder in minute 91.', 'Stevie G. Initials S.G.']
),
(
  'f43c8086',
  'jamie-carragher',
  true,
  'Jamie Carragher',
  'premier_league',
  'premier_league',
  array['Liverpool'],
  'England',
  'DF',
  1978,
  23,
  1996,
  2013,
  array[]::integer[],
  array[]::text[],
  array['Liverpool''s cramping warrior of Istanbul, now arguing on your television.', 'An English defender who read danger like a local paper.', 'One club, 737 appearances.', 'Extra time 2005, cramp in both legs, still blocking everything.', 'Carra. Initials J.C.']
),
(
  '5c8788fc',
  'robbie-fowler',
  true,
  'Robbie Fowler',
  'premier_league',
  'premier_league',
  array['Liverpool'],
  'England',
  'FW',
  1975,
  9,
  1993,
  2007,
  array[]::integer[],
  array['God'],
  array['The Kop called him God, which tells you about his finishing.', 'An English striker, the most natural of his generation.', 'Liverpool''s nineties idol with a Leeds and City tour after.', 'A four minute hat trick against Arsenal in 1994.', 'God. Initials R.F.']
),
(
  'c02ad2dd',
  'michael-owen',
  false,
  'Michael Owen',
  'premier_league',
  'premier_league',
  array['Liverpool', 'Newcastle United'],
  'England',
  'FW',
  1979,
  10,
  1996,
  2013,
  array[]::integer[],
  array[]::text[],
  array['A teenage Ballon d''Or winner from the Premier League, which still sounds made up.', 'An English striker of pure speed, old before thirty, deadly before twenty.', 'Liverpool to Madrid to Newcastle to, controversially, United.', 'The 2001 FA Cup final, two late goals to rob Arsenal.', 'Initials M.O.']
),
(
  'f3449a2d',
  'fernando-torres',
  true,
  'Fernando Torres',
  'premier_league',
  'premier_league',
  array['Liverpool', 'Chelsea'],
  'Spain',
  'FW',
  1984,
  9,
  2007,
  2015,
  array[]::integer[],
  array['El Nino'],
  array['El Nino''s Anfield peak was two seasons of terror before the fifty million move.', 'A Spanish number nine whose 2007 to 2009 was untouchable.', 'Atletico''s boy captain to Liverpool to Chelsea.', 'THAT miss against United for Chelsea, and the Camp Nou goal that answered everything.', 'El Nino. Initials F.T.']
),
(
  'c52e910e',
  'luis-suarez',
  false,
  'Luis Suarez',
  'premier_league',
  'premier_league',
  array['Liverpool'],
  'Uruguay',
  'FW',
  1987,
  7,
  2011,
  2014,
  array[]::integer[],
  array[]::text[],
  array['The league''s most brilliant player of 2013-14 and its most banned.', 'A Uruguayan striker who scored, bit and cried his way through Anfield.', 'Ajax to Liverpool to the Barcelona front three.', '31 goals in the 13-14 title chase that fell one slip short.', 'Initials L.S.']
),
(
  'eb5735d5',
  'mohamed-salah',
  true,
  'Mohamed Salah',
  'premier_league',
  'premier_league',
  array['Liverpool'],
  'Egypt',
  'FW',
  1992,
  11,
  2014,
  2026,
  array[]::integer[],
  array['The Egyptian King', 'Mo Salah'],
  array['The Egyptian King rewrote the scoring records for right wingers forever.', 'An Egyptian forward whose left foot is a public monument on Merseyside.', 'A Chelsea false start, Roma repair, Liverpool coronation.', '32 goals in his debut Liverpool season, a 38 game record.', 'Mo. Initials M.S.']
),
(
  'f1d32585',
  'sadio-mane',
  true,
  'Sadio Mane',
  'premier_league',
  'premier_league',
  array['Liverpool', 'Southampton'],
  'Senegal',
  'FW',
  1992,
  10,
  2014,
  2022,
  array[]::integer[],
  array[]::text[],
  array['The other half of the fastest hat trick in Premier League history and Liverpool''s relentless left side.', 'A Senegalese forward of first touches and last laughs.', 'Southampton''s flyer to Liverpool''s champion.', '176 seconds, three goals, Villa Park, 2015.', 'Initials S.M.']
),
(
  'c1bf70e4',
  'virgil-van-dijk',
  true,
  'Virgil van Dijk',
  'premier_league',
  'premier_league',
  array['Liverpool', 'Southampton'],
  'Netherlands',
  'DF',
  1991,
  4,
  2015,
  2026,
  array[]::integer[],
  array[]::text[],
  array['The most expensive defender ever, and briefly the best footballer alive.', 'A Dutch center back who made defending look like chairing a meeting.', 'Celtic to Southampton to Anfield.', 'An entire year, 2019, without being dribbled past.', 'Initials V.V.D.']
),
(
  '813e72af',
  'ruud-van-nistelrooy',
  true,
  'Ruud van Nistelrooy',
  'premier_league',
  'premier_league',
  array['Manchester United'],
  'Netherlands',
  'FW',
  1976,
  10,
  2001,
  2006,
  array[]::integer[],
  array[]::text[],
  array['150 goals in five seasons, roughly all from eight yards.', 'A Dutch number nine allergic to scoring from outside the box.', 'PSV to United, goals to goals.', 'Ending Arsenal''s 49 game unbeaten run from the spot, eventually.', 'Van the Man. Initials R.V.N.']
),
(
  'ffa0a823',
  'wayne-rooney',
  true,
  'Wayne Rooney',
  'premier_league',
  'premier_league',
  array['Manchester United', 'Everton'],
  'England',
  'FW',
  1985,
  10,
  2002,
  2018,
  array[]::integer[],
  array['Wazza'],
  array['Sixteen years old, Goodison Park, and Arsenal''s unbeaten run ended with a thunderbolt.', 'An English forward who did everything, everywhere, for two decades.', 'Everton to United to Everton, record scorer of both club and country for a while.', 'The overhead kick in the Manchester derby, 2011.', 'Wazza. Initials W.R.']
),
(
  'a0e41c61',
  'cristiano-ronaldo',
  false,
  'Cristiano Ronaldo',
  'premier_league',
  'premier_league',
  array['Manchester United'],
  'Portugal',
  'FW',
  1985,
  7,
  2003,
  2022,
  array[]::integer[],
  array['CR7'],
  array['He arrived a show pony and left the world''s best, then came back a legend anyway.', 'A Portuguese winger turned goal machine, made in Manchester.', 'Sporting to United to Madrid, then one last Old Trafford encore.', 'The 2008 season, 42 goals, Ballon d''Or, Champions League.', 'CR7.']
),
(
  'de4f5073',
  'rio-ferdinand',
  true,
  'Rio Ferdinand',
  'premier_league',
  'premier_league',
  array['Manchester United', 'Leeds United'],
  'England',
  'DF',
  1978,
  5,
  1996,
  2015,
  array[]::integer[],
  array[]::text[],
  array['The world''s most expensive defender, twice, and the Rolls Royce of the title years.', 'An English center back who defended in cruise control.', 'West Ham to Leeds to United''s six titles.', 'The 2008 double winning partnership with Vidic, barely a goal conceded.', 'Initials R.F.']
),
(
  'a15d6c9b',
  'nemanja-vidic',
  true,
  'Nemanja Vidic',
  'premier_league',
  'premier_league',
  array['Manchester United'],
  'Serbia',
  'DF',
  1981,
  15,
  2006,
  2014,
  array[]::integer[],
  array[]::text[],
  array['The captain who ate strikers and occasionally Fernando Torres ate back.', 'A Serbian center back of scars, stitches and five titles.', 'Spartak Moscow to Old Trafford''s iron age.', 'Blood soaked headers, any given Saturday, 2006 to 2014.', 'Initials N.V.']
),
(
  '8346f6b8',
  'david-de-gea',
  true,
  'David de Gea',
  'premier_league',
  'premier_league',
  array['Manchester United'],
  'Spain',
  'GK',
  1990,
  1,
  2011,
  2023,
  array[]::integer[],
  array[]::text[],
  array['A decade of saves that repeatedly won United''s player of the year by default.', 'A Spanish goalkeeper with reflexes filed under unfair.', 'Atletico teenager to Old Trafford''s long serving number one.', 'The Arsenal afternoon of 2017, fourteen saves.', 'Initials D.D.G.']
),
(
  '9594b2b4',
  'bruno-fernandes',
  true,
  'Bruno Fernandes',
  'premier_league',
  'premier_league',
  array['Manchester United'],
  'Portugal',
  'MF',
  1994,
  8,
  2020,
  2026,
  array[]::integer[],
  array[]::text[],
  array['Signed in January 2020 and immediately became United''s entire attack.', 'A Portuguese playmaker of penalties, risks and visible frustration.', 'Sporting''s captain to United''s.', '18 goal involvements in his first half season.', 'Initials B.F.']
),
(
  'f232006a',
  'marcus-rashford',
  true,
  'Marcus Rashford',
  'premier_league',
  'premier_league',
  array['Manchester United'],
  'England',
  'FW',
  1997,
  10,
  2016,
  2025,
  array[]::integer[],
  array[]::text[],
  array['A teenage debut double, then bigger fights than football off the pitch.', 'An English forward from Wythenshawe, fast, streaky, beloved.', 'United academy through 2025.', 'Forcing a government U turn on child food poverty.', 'Initials M.R.']
),
(
  '3755f2d5',
  'sergio-aguero',
  true,
  'Sergio Aguero',
  'premier_league',
  'premier_league',
  array['Manchester City'],
  'Argentina',
  'FW',
  1988,
  10,
  2011,
  2021,
  array[]::integer[],
  array['Kun'],
  array['93:20. If you know, you know. If you don''t, ask any City fan.', 'An Argentine striker, low slung, lethal, the club''s record scorer.', 'Atletico to a decade of City goals.', 'QPR, added time, title won with the last kick of 2011-12.', 'Kun. Initials S.A.']
),
(
  'd865a8d2',
  'david-silva',
  true,
  'David Silva',
  'premier_league',
  'premier_league',
  array['Manchester City'],
  'Spain',
  'MF',
  1986,
  21,
  2010,
  2020,
  array[]::integer[],
  array['El Mago'],
  array['El Mago conducted City''s rise for ten years without raising his voice.', 'A Spanish playmaker who played in whispers and half spaces.', 'Valencia to City''s four titles.', 'The 2017-18 centurions, his midfield masterpiece.', 'El Mago. Initials D.S.']
),
(
  '0b443ef5',
  'vincent-kompany',
  true,
  'Vincent Kompany',
  'premier_league',
  'premier_league',
  array['Manchester City'],
  'Belgium',
  'DF',
  1986,
  4,
  2008,
  2019,
  array[]::integer[],
  array[]::text[],
  array['Captain of City''s first title in 44 years, scorer of the header that swung it.', 'A Belgian center back who led like a statesman.', 'Hamburg to a City statue.', 'The 2019 thirty yarder against Leicester, don''t shoot they screamed.', 'Vince the Prince. Initials V.K.']
),
(
  'c9d76c5b',
  'yaya-toure',
  true,
  'Yaya Toure',
  'premier_league',
  'premier_league',
  array['Manchester City'],
  'Ivory Coast',
  'MF',
  1983,
  42,
  2010,
  2018,
  array[]::integer[],
  array[]::text[],
  array['He ran from box to box like traffic didn''t apply to him.', 'An Ivorian midfielder who won FA Cup semifinal, final and titles almost alone.', 'Barcelona''s utility man to City''s engine.', 'The 2014 season, twenty league goals from midfield.', 'Initials Y.T.']
),
(
  'd01ada93',
  'kevin-de-bruyne',
  true,
  'Kevin De Bruyne',
  'premier_league',
  'premier_league',
  array['Manchester City'],
  'Belgium',
  'MF',
  1991,
  17,
  2015,
  2025,
  array[]::integer[],
  array['KDB'],
  array['The league''s best passer for a decade, sold by Chelsea after nine appearances.', 'A Belgian playmaker whose crosses arrive pre addressed.', 'Genk to Chelsea to Wolfsburg to City greatness.', 'Twenty assists in 2019-20, equalling the record.', 'KDB. Initials K.D.B.']
),
(
  '027a00c3',
  'erling-haaland',
  false,
  'Erling Haaland',
  'premier_league',
  'premier_league',
  array['Manchester City'],
  'Norway',
  'FW',
  2000,
  9,
  2022,
  2026,
  array[]::integer[],
  array[]::text[],
  array['36 goals in his first Premier League season. The record book needed reprinting.', 'A Norwegian number nine who scores at a rate the league had never priced in.', 'Dortmund to City, treble on arrival.', 'The 2022-23 debut season, 52 goals in all competitions.', 'Initials E.H.']
),
(
  '96c06c3a',
  'phil-foden',
  true,
  'Phil Foden',
  'premier_league',
  'premier_league',
  array['Manchester City'],
  'England',
  'MF',
  2000,
  47,
  2017,
  2026,
  array[]::integer[],
  array[]::text[],
  array['The Stockport boy Guardiola refused to sell at any price.', 'An English playmaker, low socks, quick feet, City through and through.', 'Academy to Player of the Season 2023-24.', 'The 2023-24 campaign, 19 league goals running the show.', 'Initials P.F.']
),
(
  '5b0b0fa7',
  'rodri',
  true,
  'Rodri',
  'premier_league',
  'premier_league',
  array['Manchester City'],
  'Spain',
  'MF',
  1996,
  16,
  2019,
  2026,
  array[]::integer[],
  array[]::text[],
  array['He won a Ballon d''Or as a holding midfielder, which should be impossible.', 'A Spanish number sixteen who never seems hurried and never loses.', 'Villarreal to Atletico to City''s spine.', 'The 2023 Champions League final winner, and the 2024 golden ball.', 'Initials R.']
),
(
  '101b40bb',
  'harry-kane',
  false,
  'Harry Kane',
  'premier_league',
  'premier_league',
  array['Tottenham Hotspur'],
  'England',
  'FW',
  1993,
  10,
  2011,
  2023,
  array[]::integer[],
  array[]::text[],
  array['Once caged on loan at Leyton Orient, later the club''s record scorer chasing Shearer.', 'An English number nine who drops deep to assist himself.', 'One long Tottenham story before Bavaria.', 'The 2020-21 season, top scorer and top assister at once.', 'Initials H.K.']
),
(
  'e6b444df',
  'son-heung-min',
  true,
  'Son Heung-min',
  'premier_league',
  'premier_league',
  array['Tottenham Hotspur'],
  'South Korea',
  'FW',
  1992,
  7,
  2015,
  2025,
  array[]::integer[],
  array['Sonny'],
  array['The Puskas winner who ran from his own box against Burnley.', 'A South Korean forward with two identical perfect feet.', 'Hamburg to Leverkusen to Tottenham''s captaincy.', 'Golden Boot 2021-22 without a single penalty.', 'Sonny. Initials S.H.M.']
),
(
  '9c597a5c',
  'gareth-bale',
  true,
  'Gareth Bale',
  'premier_league',
  'premier_league',
  array['Tottenham Hotspur'],
  'Wales',
  'FW',
  1989,
  11,
  2007,
  2013,
  array[]::integer[],
  array[]::text[],
  array['Taxi for Maicon. The night a full back became the world''s next superstar.', 'A Welsh winger whose 2013 season forced a world record fee.', 'Southampton boy to Spurs, then the white of Madrid.', 'The 2013 Player of the Year season and that goal at West Ham.', 'Initials G.B.']
),
(
  '405e7771',
  'jamie-vardy',
  true,
  'Jamie Vardy',
  'premier_league',
  'premier_league',
  array['Leicester City'],
  'England',
  'FW',
  1987,
  9,
  2014,
  2025,
  array[]::integer[],
  array[]::text[],
  array['From non league to title winner, chat about it all you want.', 'An English striker fuelled by pace, spite and energy drinks.', 'Fleetwood Town to Leicester immortality.', 'Eleven consecutive scoring games in the 2015-16 miracle.', 'Initials J.V.']
),
(
  '7b3a556b',
  'riyad-mahrez',
  true,
  'Riyad Mahrez',
  'premier_league',
  'premier_league',
  array['Leicester City', 'Manchester City'],
  'Algeria',
  'FW',
  1991,
  26,
  2014,
  2023,
  array[]::integer[],
  array[]::text[],
  array['Player of the Year in the 5000 to 1 season.', 'An Algerian winger with a left foot like a paintbrush.', 'Le Havre to Leicester''s fairy tale to City''s trophies.', 'The 2015-16 title, dancing past full backs weekly.', 'Initials R.M.']
),
(
  '335110ec',
  'ngolo-kante',
  false,
  'NGolo Kante',
  'premier_league',
  'premier_league',
  array['Leicester City', 'Chelsea'],
  'France',
  'MF',
  1991,
  7,
  2015,
  2023,
  array[]::integer[],
  array[]::text[],
  array['He won back to back titles with two different clubs, covering every blade both times.', 'A French midfielder, tiny, smiling, everywhere.', 'Caen to Leicester to Chelsea.', 'The 2016 and 2017 champion seasons, the league''s rarest double.', 'Initials N.K.']
),
(
  'b20eed1f',
  'eden-hazard',
  false,
  'Eden Hazard',
  'premier_league',
  'premier_league',
  array['Chelsea'],
  'Belgium',
  'FW',
  1991,
  10,
  2012,
  2019,
  array[]::integer[],
  array[]::text[],
  array['Chelsea''s tormentor in chief, kicked constantly, dispossessed rarely.', 'A Belgian winger who dribbled with the ball glued and the hips lying.', 'Lille to Stamford Bridge''s two titles.', 'The solo goal against Arsenal in 2017, half the pitch, no touch wasted.', 'Initials E.H.']
),
(
  '8b52f6a2',
  'cesc-fabregas',
  true,
  'Cesc Fabregas',
  'premier_league',
  'premier_league',
  array['Arsenal', 'Chelsea'],
  'Spain',
  'MF',
  1987,
  4,
  2003,
  2019,
  array[]::integer[],
  array[]::text[],
  array['An Arsenal captain at 21, a Chelsea title winner twice over.', 'A Spanish midfielder who saw passes a broadcast camera couldn''t.', 'La Masia to Highbury to Barcelona and back to London.', '111 Premier League assists, third all time.', 'Initials C.F.']
),
(
  '5c1ea168',
  'bukayo-saka',
  true,
  'Bukayo Saka',
  'premier_league',
  'premier_league',
  array['Arsenal'],
  'England',
  'FW',
  2001,
  7,
  2018,
  2026,
  array[]::integer[],
  array['Starboy'],
  array['Starboy carried Arsenal''s rebirth on his 21 year old shoulders.', 'An English winger from Ealing, smiling, fouled, unbothered.', 'Hale End academy to talisman.', 'The 2023-24 title push, 20 goal involvements from the right.', 'Starboy. Initials B.S.']
),
(
  'dc7eb5b0',
  'martin-odegaard',
  true,
  'Martin Odegaard',
  'premier_league',
  'premier_league',
  array['Arsenal'],
  'Norway',
  'MF',
  1998,
  8,
  2021,
  2026,
  array[]::integer[],
  array[]::text[],
  array['A wonderkid at fifteen who grew into Arsenal''s captain by 23.', 'A Norwegian playmaker of half turns and final passes.', 'Madrid''s youngest debutant, loans, then North London.', 'Captaining the young Arsenal title challenges of the mid 2020s.', 'Initials M.O.']
),
(
  'd0f955ad',
  'declan-rice',
  true,
  'Declan Rice',
  'premier_league',
  'premier_league',
  array['Arsenal', 'West Ham United'],
  'England',
  'MF',
  1999,
  41,
  2017,
  2026,
  array[]::integer[],
  array[]::text[],
  array['A hundred million pounds and instantly worth it.', 'An English midfielder who breaks up play and breaks forward late.', 'West Ham''s captain and Europa Conference winner to Arsenal.', 'Lifting West Ham''s first trophy in 43 years, Prague 2023.', 'Initials D.R.']
),
(
  '65f2bc27',
  'cole-palmer',
  true,
  'Cole Palmer',
  'premier_league',
  'premier_league',
  array['Chelsea', 'Manchester City'],
  'England',
  'MF',
  2002,
  10,
  2021,
  2026,
  array[]::integer[],
  array['Cold Palmer'],
  array['Cold. He left the champions to become the main character elsewhere.', 'An English playmaker with ice in his celebration and his penalties.', 'City academy to Chelsea''s everything.', '22 goals in his first Chelsea season, 2023-24.', 'Cold Palmer. Initials C.P.']
),
(
  '0b2b68e9',
  'alisson-becker',
  true,
  'Alisson Becker',
  'premier_league',
  'premier_league',
  array['Liverpool'],
  'Brazil',
  'GK',
  1992,
  1,
  2018,
  2026,
  array[]::integer[],
  array[]::text[],
  array['The most expensive keeper ever, repaid within a season of titles.', 'A Brazilian goalkeeper of one on one mastery and one famous header.', 'Internacional to Roma to Anfield.', 'The 95th minute headed goal at West Brom, 2021.', 'Initials A.B.']
),
(
  'fc23a7f6',
  'trent-alexander-arnold',
  true,
  'Trent Alexander-Arnold',
  'premier_league',
  'premier_league',
  array['Liverpool'],
  'England',
  'DF',
  1998,
  66,
  2016,
  2025,
  array[]::integer[],
  array[]::text[],
  array['A right back with a playmaker''s brain and one famous quick corner.', 'An English defender from West Derby who redefined the position''s job description.', 'Liverpool academy to champion of everything, then Madrid.', 'Corner taken quickly, Origi. Barcelona buried, 2019.', 'TAA. Initials T.A.A.']
),
(
  'eb2ea1b1',
  'raheem-sterling',
  true,
  'Raheem Sterling',
  'premier_league',
  'premier_league',
  array['Manchester City', 'Liverpool'],
  'England',
  'FW',
  1994,
  7,
  2012,
  2025,
  array[]::integer[],
  array[]::text[],
  array['The kid from QPR''s shadow who became the league''s most decorated winger of his era.', 'An English forward of darting runs and four titles.', 'Liverpool prodigy to City''s machine.', 'The 2018-19 title run in, goals in bunches.', 'Initials R.S.']
),
(
  '5db511a6',
  'jack-grealish',
  true,
  'Jack Grealish',
  'premier_league',
  'premier_league',
  array['Aston Villa', 'Manchester City'],
  'England',
  'MF',
  1995,
  10,
  2014,
  2026,
  array[]::integer[],
  array[]::text[],
  array['A hundred million pounds of rolled down socks and drawn fouls.', 'An English winger who carries the ball like it''s on a leash.', 'Villa''s captain and boyhood fan to City''s treble.', 'Dragging Villa to safety in 2020, then the record move.', 'Initials J.G.']
),
(
  'aeb926d2',
  'raul',
  true,
  'Raul',
  'la_liga',
  'la_liga',
  array['Real Madrid'],
  'Spain',
  'FW',
  1977,
  7,
  1994,
  2010,
  array[]::integer[],
  array['Raul Gonzalez'],
  array['Seven hundred games in white, and the badge kiss belonged to him first.', 'A Spanish forward, captain and conscience of the Galactico years.', 'Debuted at seventeen, left as record scorer of club and Champions League alike.', 'Silencing the Camp Nou with a finger to his lips, 1999.', 'Number seven of Madrid. Initials R.']
),
(
  'ed639373',
  'zinedine-zidane',
  false,
  'Zinedine Zidane',
  'la_liga',
  'la_liga',
  array['Real Madrid'],
  'France',
  'MF',
  1972,
  5,
  2001,
  2006,
  array[]::integer[],
  array['Zizou'],
  array['The most expensive player in history arrived in 2001 and repaid it with one volley.', 'A French number ten drifting through La Liga on slow motion elegance.', 'Turin to the Bernabeu for a world record.', 'Glasgow 2002, the left footed volley from the edge of the area.', 'Zizou. Initials Z.Z.']
),
(
  '9a7e76c3',
  'luis-figo',
  true,
  'Luis Figo',
  'la_liga',
  'la_liga',
  array['Real Madrid', 'Barcelona'],
  'Portugal',
  'MF',
  1972,
  10,
  1995,
  2005,
  array[]::integer[],
  array[]::text[],
  array['The most hated transfer in Clasico history, complete with a flying pig''s head.', 'A Portuguese winger of feints, whipped crosses and stolen loyalty.', 'Barcelona''s idol crossing to Madrid for a world record.', 'Returning to the Camp Nou in white, corner flags under siege, 2002.', 'Initials L.F.']
),
(
  '70127168',
  'ronaldo',
  false,
  'Ronaldo',
  'la_liga',
  'la_liga',
  array['Real Madrid', 'Barcelona'],
  'Brazil',
  'FW',
  1976,
  9,
  1996,
  2007,
  array[]::integer[],
  array['R9'],
  array['Twenty six years old at Madrid and still the scariest sight in Spain despite two rebuilt knees.', 'A Brazilian striker whose Barcelona season remains the league''s most violent single year.', 'One impossible season at Barcelona, later the Galactico years in white.', '47 goals in 96-97, including the run through half of Compostela.', 'R9. O Fenomeno.']
),
(
  '899a4959',
  'ronaldinho',
  false,
  'Ronaldinho',
  'la_liga',
  'la_liga',
  array['Barcelona'],
  'Brazil',
  'MF',
  1980,
  10,
  2003,
  2008,
  array[]::integer[],
  array['Dinho'],
  array['A standing ovation at the Bernabeu, from the enemy''s own fans.', 'A Brazilian magician whose two Barcelona peak years reset the sport''s joy levels.', 'Paris to the Camp Nou, Ballon d''Or in blue and red.', 'November 2005, two solo goals, Madrid applauding him off.', 'Dinho. Initials R.']
),
(
  '11a893ea',
  'lionel-messi',
  false,
  'Lionel Messi',
  'la_liga',
  'la_liga',
  array['Barcelona'],
  'Argentina',
  'FW',
  1987,
  10,
  2004,
  2021,
  array[]::integer[],
  array['Leo', 'La Pulga'],
  array['474 league goals for one club. The number reads like a typo.', 'An Argentine forward who spent seventeen seasons as La Liga''s answer to every question.', 'La Masia to eight league titles, all in the same shirt.', 'The 2017 Clasico winner in minute 92, shirt held to the Bernabeu.', 'Leo. La Pulga.']
),
(
  'a4d9dc53',
  'xavi',
  false,
  'Xavi',
  'la_liga',
  'la_liga',
  array['Barcelona'],
  'Spain',
  'MF',
  1980,
  6,
  1998,
  2015,
  array[]::integer[],
  array[]::text[],
  array['The pause. Nobody in La Liga history bought more time on the ball.', 'A Spanish midfielder of five hundred touches and zero panic.', 'La Masia to eight titles as the metronome.', 'The 2010-11 season, the machine at maximum purr.', 'Initials X.H.']
),
(
  '1a714aae',
  'andres-iniesta',
  false,
  'Andres Iniesta',
  'la_liga',
  'la_liga',
  array['Barcelona'],
  'Spain',
  'MF',
  1984,
  8,
  2002,
  2018,
  array[]::integer[],
  array['El Ilusionista'],
  array['Pale, silent, and the man defenders feared most in tight spaces for fifteen years.', 'A Spanish midfielder whose croquetas belong in art galleries.', 'One club career, 32 trophies in Barcelona colors.', 'The 2015 Clasico masterclass at the Bernabeu, olés included.', 'Don Andres. Initials A.I.']
),
(
  'c96af197',
  'carles-puyol',
  false,
  'Carles Puyol',
  'la_liga',
  'la_liga',
  array['Barcelona'],
  'Spain',
  'DF',
  1978,
  5,
  1999,
  2014,
  array[]::integer[],
  array[]::text[],
  array['A captain who once apologized for celebrating too loudly against a relegation side.', 'A Spanish center back of hair, heart and headers.', 'One club, fifteen years of throwing his face at danger.', 'Dragging Barcelona through the 2010 title run, bandaged as usual.', 'Tarzan. Initials C.P.']
),
(
  '2002a8bc',
  'gerard-pique',
  true,
  'Gerard Pique',
  'la_liga',
  'la_liga',
  array['Barcelona'],
  'Spain',
  'DF',
  1987,
  3,
  2008,
  2022,
  array[]::integer[],
  array[]::text[],
  array['He left United''s bench to become the league''s most decorated ball playing defender.', 'A Spanish center back with a businessman''s brain and a troll''s grin.', 'Zaragoza and Manchester detours, then home to eight titles.', 'The 2009 sextuple as the defense''s cornerstone.', 'Geri. Initials G.P.']
)
on conflict (id) do update set
  person_id = excluded.person_id,
  canonical = excluded.canonical,
  name = excluded.name,
  category = excluded.category,
  league = excluded.league,
  clubs = excluded.clubs,
  nationality = excluded.nationality,
  position = excluded.position,
  birth_year = excluded.birth_year,
  shirt_number = excluded.shirt_number,
  era_start = excluded.era_start,
  era_end = excluded.era_end,
  world_cup_editions = excluded.world_cup_editions,
  aliases = excluded.aliases,
  clues = excluded.clues;

-- Verify this batch: select count(*) from public.players; -- expect 160 cumulative after all batches through 02
