-- Batch 4/6: rows 241-320 of 407
-- Paste into Supabase SQL Editor and Run (in order 01 → 06)
insert into public.players (
  id, person_id, canonical, name, category, league, clubs,
  nationality, position, birth_year, shirt_number, era_start, era_end,
  world_cup_editions, aliases, clues
) values
(
  '78165e8d',
  'victor-osimhen',
  true,
  'Victor Osimhen',
  'serie_a',
  'serie_a',
  array['Napoli'],
  'Nigeria',
  'FW',
  1998,
  9,
  2020,
  2025,
  array[]::integer[],
  array[]::text[],
  array['The masked striker fired Napoli to their first title in 33 years.', 'A Nigerian nine of leaps, sprints and a protective mask.', 'Lille to Naples'' record signing and record joy.', 'The 2023 Scudetto, Capocannoniere in blue.', 'Initials V.O.']
),
(
  '20835fe5',
  'khvicha-kvaratskhelia',
  true,
  'Khvicha Kvaratskhelia',
  'serie_a',
  'serie_a',
  array['Napoli'],
  'Georgia',
  'FW',
  2001,
  77,
  2022,
  2025,
  array[]::integer[],
  array['Kvaradona'],
  array['Kvaradona, they called him, and Naples doesn''t hand that name out lightly.', 'A Georgian winger who arrived unknown and left title winning highlights.', 'Rubin Kazan to Napoli''s title, then Paris.', 'The 2022-23 debut season of feints and delirium.', 'Kvaradona. Initials K.K.']
),
(
  '4c25ad4f',
  'lautaro-martinez',
  true,
  'Lautaro Martinez',
  'serie_a',
  'serie_a',
  array['Inter Milan'],
  'Argentina',
  'FW',
  1997,
  10,
  2018,
  2026,
  array[]::integer[],
  array['El Toro'],
  array['Inter''s captain and the bull who fired the second star Scudetto.', 'An Argentine striker of pressing fury and clean finishing.', 'Racing to Inter''s armband.', 'The 2024 title, Capocannoniere as captain.', 'El Toro. Initials L.M.']
),
(
  '3cbd2b15',
  'nicolo-barella',
  true,
  'Nicolo Barella',
  'serie_a',
  'serie_a',
  array['Inter Milan', 'Cagliari'],
  'Italy',
  'MF',
  1997,
  23,
  2015,
  2026,
  array[]::integer[],
  array[]::text[],
  array['Cagliari''s boy became the box to box heartbeat of Inter''s new era.', 'An Italian midfielder who plays angry and passes calm.', 'Sardinia to Inter''s engine.', 'The 2021 title run as Serie A''s best midfielder.', 'Initials N.B.']
),
(
  'e9f6b0ce',
  'romelu-lukaku',
  false,
  'Romelu Lukaku',
  'serie_a',
  'serie_a',
  array['Inter Milan', 'Napoli', 'Roma'],
  'Belgium',
  'FW',
  1993,
  90,
  2019,
  2026,
  array[]::integer[],
  array[]::text[],
  array['Conte rebuilt him at Inter into the most unplayable striker in Italy.', 'A Belgian nine of back to goal power and title goals.', 'United''s misfit to Inter''s 2021 crown.', 'The 2021 Scudetto, 24 goals ending the Juve decade.', 'Big Rom. Initials R.L.']
),
(
  '4597356b',
  'dusan-vlahovic',
  true,
  'Dusan Vlahovic',
  'serie_a',
  'serie_a',
  array['Juventus', 'Fiorentina'],
  'Serbia',
  'FW',
  2000,
  9,
  2018,
  2026,
  array[]::integer[],
  array[]::text[],
  array['A January world of money took him from Florence to Turin, fury included.', 'A Serbian striker of left foot venom and penalty box hunger.', 'Fiorentina''s jewel to Juve''s nine.', 'The 2022 mid season move that enraged a city.', 'Initials D.V.']
),
(
  '8b3aca0d',
  'giuseppe-signori',
  true,
  'Giuseppe Signori',
  'serie_a',
  'serie_a',
  array['Lazio', 'Bologna'],
  'Italy',
  'FW',
  1968,
  11,
  1992,
  2004,
  array[]::integer[],
  array['Beppe'],
  array['Three scoring titles in the nineties, penalties taken without a run up.', 'An Italian forward, Lazio''s darling of the pre Cragnotti gold rush.', 'Foggia''s miracle to Lazio''s talisman.', 'The no run up penalties, casually rolled home.', 'Beppe. Initials G.S.']
),
(
  '9e40999a',
  'gianfranco-zola',
  false,
  'Gianfranco Zola',
  'serie_a',
  'serie_a',
  array['Parma', 'Napoli', 'Cagliari'],
  'Italy',
  'FW',
  1966,
  10,
  1992,
  2005,
  array[]::integer[],
  array['Magic Box'],
  array['Maradona''s apprentice at Napoli before conquering another country.', 'An Italian ten of free kicks learned from the master himself.', 'Napoli''s understudy to Parma''s star.', 'Learning dead balls next to Diego, 1989 to 1993.', 'Magic Box. Initials G.Z.']
),
(
  '68b7bcba',
  'roberto-mancini',
  true,
  'Roberto Mancini',
  'serie_a',
  'serie_a',
  array['Sampdoria', 'Lazio'],
  'Italy',
  'FW',
  1964,
  10,
  1992,
  2000,
  array[]::integer[],
  array[]::text[],
  array['Sampdoria''s prince, a one club romantic until the Lazio silver years.', 'An Italian forward of flicks, vision and a famous partnership.', 'Fifteen Samp years and the 1991 miracle title.', 'The 1991 Scudetto with Vialli, football''s great romance.', 'Mancio. Initials R.M.']
),
(
  '23193c2a',
  'giuseppe-bergomi',
  true,
  'Giuseppe Bergomi',
  'serie_a',
  'serie_a',
  array['Inter Milan'],
  'Italy',
  'DF',
  1963,
  2,
  1992,
  1999,
  array[]::integer[],
  array['Lo Zio'],
  array['Lo Zio wore Inter''s shirt for twenty years and a World Cup at eighteen.', 'An Italian defender, eyebrows of legend, loyalty of granite.', 'One club, 750 games.', 'Captaining the 1989 record Scudetto.', 'Lo Zio. Initials G.B.']
),
(
  'e639e9a9',
  'fabrizio-ravanelli',
  true,
  'Fabrizio Ravanelli',
  'serie_a',
  'serie_a',
  array['Juventus', 'Lazio'],
  'Italy',
  'FW',
  1968,
  11,
  1992,
  2004,
  array[]::integer[],
  array['Penna Bianca'],
  array['The silver fox pulled his shirt over his head after every goal, including a Champions League final.', 'An Italian striker, white haired at 26, prolific everywhere.', 'Perugia to Juve''s 1996 European crown.', 'Scoring in the 1996 Champions League final win.', 'Penna Bianca. Initials F.R.']
),
(
  '56b8b17c',
  'antonio-di-natale',
  true,
  'Antonio Di Natale',
  'serie_a',
  'serie_a',
  array['Udinese', 'Empoli'],
  'Italy',
  'FW',
  1977,
  10,
  2002,
  2016,
  array[]::integer[],
  array['Toto'],
  array['He refused every big club and out scored them all from Udine.', 'An Italian forward, two straight Capocannonieri in his thirties.', 'Empoli to Udinese forever.', 'Back to back scoring titles, 2010 and 2011.', 'Toto. Initials A.D.N.']
),
(
  'ef3dadf3',
  'francesco-toldo',
  true,
  'Francesco Toldo',
  'serie_a',
  'serie_a',
  array['Fiorentina', 'Inter Milan'],
  'Italy',
  'GK',
  1971,
  1,
  1993,
  2010,
  array[]::integer[],
  array[]::text[],
  array['A Euro 2000 hero who became the wall of Inter''s trophy era.', 'An Italian goalkeeper, enormous and understated.', 'Fiorentina''s decade to Inter''s cabinet.', 'The 2010 treble squad''s veteran guardian.', 'Initials F.T.']
),
(
  'bde2b495',
  'marek-hamsik',
  true,
  'Marek Hamsik',
  'serie_a',
  'serie_a',
  array['Napoli', 'Brescia'],
  'Slovakia',
  'MF',
  1987,
  17,
  2004,
  2019,
  array[]::integer[],
  array['Marekiaro'],
  array['Mohawked captain who broke Maradona''s Napoli appearance and goal records.', 'A Slovak midfielder of late runs and lifelong loyalty.', 'Brescia teen to twelve Napoli years.', 'Passing Maradona''s goal record in 2017.', 'Marekiaro. Initials M.H.']
),
(
  '932a590e',
  'edinson-cavani',
  false,
  'Edinson Cavani',
  'serie_a',
  'serie_a',
  array['Napoli', 'Palermo'],
  'Uruguay',
  'FW',
  1987,
  7,
  2007,
  2013,
  array[]::integer[],
  array['El Matador'],
  array['A hat trick on his Napoli home debut and 104 goals in three years.', 'A Uruguayan striker whose Napoli spell was pure fire.', 'Palermo to the San Paolo''s adoration.', 'The 2013 Capocannoniere, 29 goals of frenzy.', 'El Matador. Initials E.C.']
),
(
  '0106efc4',
  'mohamed-salah',
  false,
  'Mohamed Salah',
  'serie_a',
  'serie_a',
  array['Roma', 'Fiorentina'],
  'Egypt',
  'FW',
  1992,
  74,
  2015,
  2017,
  array[]::integer[],
  array[]::text[],
  array['Serie A rebuilt the Chelsea reject into the machine Liverpool bought.', 'An Egyptian winger learning final product in Rome and Florence.', 'Chelsea loanee to Roma''s 19 goal star.', 'The 2016-17 Roma season that changed his price tag forever.', 'Initials M.S.']
),
(
  '5074c622',
  'miralem-pjanic',
  true,
  'Miralem Pjanic',
  'serie_a',
  'serie_a',
  array['Juventus', 'Roma'],
  'Bosnia and Herzegovina',
  'MF',
  1990,
  5,
  2011,
  2020,
  array[]::integer[],
  array[]::text[],
  array['Free kicks like postage stamps, from Rome to Turin''s title machine.', 'A Bosnian midfielder of dead ball perfection.', 'Lyon to Roma to four Juve titles.', 'The 2016 move up the table that Roma never forgave.', 'Initials M.P.']
),
(
  'd87a57c4',
  'kalidou-koulibaly',
  true,
  'Kalidou Koulibaly',
  'serie_a',
  'serie_a',
  array['Napoli'],
  'Senegal',
  'DF',
  1991,
  26,
  2014,
  2022,
  array[]::integer[],
  array[]::text[],
  array['The best defender in Italy for half a decade, and Napoli''s rock of dignity.', 'A Senegalese center back of recovery pace and leadership.', 'Metz to Napoli''s colossus years.', 'The 2018 header at Juventus, title dream alive in minute 90.', 'Initials K.K.']
),
(
  '52531e2e',
  'federico-chiesa',
  true,
  'Federico Chiesa',
  'serie_a',
  'serie_a',
  array['Juventus', 'Fiorentina'],
  'Italy',
  'FW',
  1997,
  7,
  2016,
  2024,
  array[]::integer[],
  array[]::text[],
  array['A Euro winning winger whose knee robbed Serie A of its most direct threat.', 'An Italian winger, son of a Sampdoria great, all acceleration.', 'Florence to Juve like his father''s rival path.', 'The Euro 2020 summer as Italy''s spark.', 'Initials F.C.']
),
(
  '61b6ff34',
  'rafael-leao',
  true,
  'Rafael Leao',
  'serie_a',
  'serie_a',
  array['AC Milan'],
  'Portugal',
  'FW',
  1999,
  10,
  2019,
  2026,
  array[]::integer[],
  array[]::text[],
  array['Milan''s title winning wildcard, dancing past defenders and expectations.', 'A Portuguese winger of long strides and longer patience demands.', 'Lille to Milan''s number ten shirt.', 'The 2022 Scudetto, MVP of the season.', 'Initials R.L.']
),
(
  'd15e7e16',
  'lothar-matthaus',
  false,
  'Lothar Matthaus',
  'bundesliga',
  'bundesliga',
  array['Bayern Munich'],
  'Germany',
  'MF',
  1961,
  10,
  1992,
  2000,
  array[]::integer[],
  array[]::text[],
  array['Germany''s record cap holder finished his league career as a sweeper who still ran box to box.', 'A German leader of two Bayern eras, either side of Italian glory.', 'Gladbach to Bayern, twice, seven titles between.', 'The 1999-2000 farewell season, still bossing at 39.', 'Initials L.M.']
),
(
  '4af0233d',
  'jurgen-klinsmann',
  false,
  'Jurgen Klinsmann',
  'bundesliga',
  'bundesliga',
  array['Bayern Munich', 'Stuttgart'],
  'Germany',
  'FW',
  1964,
  18,
  1995,
  1997,
  array[]::integer[],
  array[]::text[],
  array['He arrived at Bayern with a diving celebration ready for his critics.', 'A German striker, Bundesliga bred, world famous abroad, home for the title.', 'Stuttgart''s breakout to a Bayern championship.', 'The 1997 title and the famous kicked advertising bin.', 'Klinsi. Initials J.K.']
),
(
  '4c255a67',
  'oliver-kahn',
  false,
  'Oliver Kahn',
  'bundesliga',
  'bundesliga',
  array['Bayern Munich', 'Karlsruher SC'],
  'Germany',
  'GK',
  1969,
  1,
  1992,
  2008,
  array[]::integer[],
  array['Der Titan'],
  array['Eight titles, three World Keeper awards, and one bitten opponent''s neck, allegedly affectionately.', 'A German goalkeeper who treated dropped points as personal insults.', 'Karlsruher to Bayern''s eternal number one.', 'The 2001 title, won in stoppage time of the final day at Hamburg.', 'Der Titan. Initials O.K.']
),
(
  '5cff8c87',
  'stefan-effenberg',
  true,
  'Stefan Effenberg',
  'bundesliga',
  'bundesliga',
  array['Bayern Munich', 'Borussia Monchengladbach'],
  'Germany',
  'MF',
  1968,
  11,
  1992,
  2003,
  array[]::integer[],
  array['Der Tiger'],
  array['The Tiger captained the treble era Bayern with maximum arrogance and maximum delivery.', 'A German midfielder of long passes and longer feuds.', 'Gladbach to Bayern''s 2001 crown.', 'Captaining the 2001 Champions League and title double.', 'Der Tiger. Initials S.E.']
),
(
  '6c9ecd06',
  'mehmet-scholl',
  true,
  'Mehmet Scholl',
  'bundesliga',
  'bundesliga',
  array['Bayern Munich'],
  'Germany',
  'MF',
  1970,
  7,
  1992,
  2007,
  array[]::integer[],
  array[]::text[],
  array['Munich''s darling of the nineties, all left foot and mischief.', 'A German playmaker of chips, free kicks and eight titles.', 'One club career of trophies and wit.', 'The 2001 double as the creative heart.', 'Initials M.S.']
),
(
  'fe22147f',
  'michael-ballack',
  false,
  'Michael Ballack',
  'bundesliga',
  'bundesliga',
  array['Bayern Munich', 'Bayer Leverkusen', 'Kaiserslautern'],
  'Germany',
  'MF',
  1976,
  13,
  1997,
  2012,
  array[]::integer[],
  array[]::text[],
  array['Four second place heartbreaks in one year, then three straight titles anyway.', 'A German number 13 arriving late into every box in the league.', 'Kaiserslautern to Leverkusen''s almosts to Bayern''s certainty.', 'The 2002 Vizekusen year, then the redemption treble of titles.', 'Initials M.B.']
),
(
  'b9b6fe76',
  'miroslav-klose',
  false,
  'Miroslav Klose',
  'bundesliga',
  'bundesliga',
  array['Bayern Munich', 'Werder Bremen', 'Kaiserslautern'],
  'Germany',
  'FW',
  1978,
  18,
  1999,
  2011,
  array[]::integer[],
  array[]::text[],
  array['The league knew him as a Kaiserslautern flip celebration before the world records came.', 'A German striker of headers, honesty and a famous front flip.', 'Kaiserslautern to Werder to Bayern''s titles.', 'The 2006 golden season at Werder, 25 goals.', 'Initials M.K.']
),
(
  '79600922',
  'lukas-podolski',
  true,
  'Lukas Podolski',
  'bundesliga',
  'bundesliga',
  array['Cologne', 'Bayern Munich'],
  'Germany',
  'FW',
  1985,
  10,
  2003,
  2012,
  array[]::integer[],
  array['Poldi'],
  array['Prinz Poldi''s left foot was licensed as a weapon in Cologne twice.', 'A German forward, Cologne''s beloved son, thunder on demand.', 'Cologne to Bayern and home again.', 'The teenage breakout keeping Cologne''s hopes alive.', 'Poldi. Initials L.P.']
),
(
  '1e5e1f90',
  'bastian-schweinsteiger',
  true,
  'Bastian Schweinsteiger',
  'bundesliga',
  'bundesliga',
  array['Bayern Munich'],
  'Germany',
  'MF',
  1984,
  31,
  2002,
  2015,
  array[]::integer[],
  array['Schweini'],
  array['From winger with highlights in his hair to the league''s midfield emperor.', 'A German midfielder who grew up with the league watching.', 'Bayern academy to eight titles.', 'The 2013 treble as the team''s heartbeat.', 'Schweini. Initials B.S.']
),
(
  '6a6c0b10',
  'philipp-lahm',
  true,
  'Philipp Lahm',
  'bundesliga',
  'bundesliga',
  array['Bayern Munich', 'Stuttgart'],
  'Germany',
  'DF',
  1983,
  21,
  2002,
  2017,
  array[]::integer[],
  array[]::text[],
  array['The best full back of his generation, described by Pep as the most intelligent player he coached.', 'A German captain, five foot seven, mistake proof.', 'Stuttgart loan to Bayern''s armband.', 'Captaining the 2013 treble, then reinventing as a six.', 'Initials P.L.']
),
(
  '3cd0a7f6',
  'thomas-muller',
  false,
  'Thomas Muller',
  'bundesliga',
  'bundesliga',
  array['Bayern Munich'],
  'Germany',
  'FW',
  1989,
  25,
  2008,
  2025,
  array[]::integer[],
  array['Raumdeuter'],
  array['Twelve league titles. Nobody in Bundesliga history has more.', 'A German space investigator with a trophy warehouse.', 'One club, 25 seasons of Bayern from academy to farewell.', 'The record twelfth title, 2023, still grinning.', 'Raumdeuter. Initials T.M.']
),
(
  '3be4f9e3',
  'manuel-neuer',
  false,
  'Manuel Neuer',
  'bundesliga',
  'bundesliga',
  array['Bayern Munich', 'Schalke 04'],
  'Germany',
  'GK',
  1986,
  1,
  2006,
  2026,
  array[]::integer[],
  array[]::text[],
  array['Schalke''s academy built the keeper who redefined the position at their rival.', 'A German goalkeeper playing eleven against ten by himself.', 'Gelsenkirchen to Munich''s sweeper keeper era.', 'The 2013 treble, redefining where keepers live.', 'Initials M.N.']
),
(
  '00573d6d',
  'arjen-robben',
  false,
  'Arjen Robben',
  'bundesliga',
  'bundesliga',
  array['Bayern Munich'],
  'Netherlands',
  'FW',
  1984,
  10,
  2009,
  2019,
  array[]::integer[],
  array[]::text[],
  array['Cut inside, far corner, eight German titles. The league knew and couldn''t stop it.', 'A Dutch winger whose left foot ended a decade of Bayern European pain.', 'Madrid to a decade in Munich.', 'Wembley 2013, minute 89, the treble winner.', 'Initials A.R.']
),
(
  'dff5564b',
  'franck-ribery',
  true,
  'Franck Ribery',
  'bundesliga',
  'bundesliga',
  array['Bayern Munich'],
  'France',
  'FW',
  1983,
  7,
  2007,
  2019,
  array[]::integer[],
  array[]::text[],
  array['Scarface ran the left wing for nine titles and one glorious 2013.', 'A French winger of chaos, cuts and telepathy with his Dutch twin.', 'Marseille to Bayern''s greatest wing pair.', 'The Robbery years, peaking in the 2013 treble.', 'Initials F.R.']
),
(
  '6eda2422',
  'robert-lewandowski',
  false,
  'Robert Lewandowski',
  'bundesliga',
  'bundesliga',
  array['Bayern Munich', 'Borussia Dortmund'],
  'Poland',
  'FW',
  1988,
  9,
  2010,
  2022,
  array[]::integer[],
  array['Lewy'],
  array['41 goals in a Bundesliga season, and Gerd Muller''s record finally moved.', 'A Polish machine who scored five in nine minutes as a substitute.', 'Dortmund''s double to Bayern''s records.', 'The five goals in nine minutes against Wolfsburg, 2015.', 'Lewy. Initials R.L.']
),
(
  'e5ecc184',
  'marco-reus',
  true,
  'Marco Reus',
  'bundesliga',
  'bundesliga',
  array['Borussia Dortmund', 'Borussia Monchengladbach'],
  'Germany',
  'MF',
  1989,
  11,
  2009,
  2024,
  array[]::integer[],
  array[]::text[],
  array['Dortmund''s boy captain stayed through every heartbreak and finally lifted a trophy in the rain.', 'A German attacker of glass ankles and gold moments.', 'Gladbach detour, then home to Dortmund''s armband.', 'The 2021 cup, captain at last with silverware.', 'Initials M.R.']
),
(
  '29299e31',
  'mats-hummels',
  true,
  'Mats Hummels',
  'bundesliga',
  'bundesliga',
  array['Borussia Dortmund', 'Bayern Munich'],
  'Germany',
  'DF',
  1988,
  15,
  2007,
  2024,
  array[]::integer[],
  array[]::text[],
  array['Bayern let him go as a kid, he beat them as Dortmund''s champion, twice, then went back.', 'A German center back of long diagonals and longer reads.', 'Munich academy to Dortmund''s double and back again.', 'The 2011 and 2012 title machine''s defensive brain.', 'Initials M.H.']
),
(
  '868c907a',
  'jerome-boateng',
  true,
  'Jerome Boateng',
  'bundesliga',
  'bundesliga',
  array['Bayern Munich', 'Hamburger SV'],
  'Germany',
  'DF',
  1988,
  17,
  2007,
  2021,
  array[]::integer[],
  array[]::text[],
  array['City discarded him, Pep rebuilt him into the league''s best defender.', 'A German center back famous for one Messi moment and a decade of dominance.', 'Hamburg to Bayern''s nine titles.', 'The 2013 treble''s defensive cornerstone.', 'Initials J.B.']
),
(
  '06700132',
  'joshua-kimmich',
  true,
  'Joshua Kimmich',
  'bundesliga',
  'bundesliga',
  array['Bayern Munich', 'RB Leipzig'],
  'Germany',
  'MF',
  1995,
  6,
  2015,
  2026,
  array[]::integer[],
  array[]::text[],
  array['Signed as a nobody from Leipzig''s reserves, became the league''s most complete player.', 'A German six or right back or captain, depending on the week''s need.', 'Stuttgart academy to Bayern''s brain.', 'The 2020 chipped winner in the empty Klassiker.', 'Initials J.K.']
),
(
  '89b35e1f',
  'leon-goretzka',
  true,
  'Leon Goretzka',
  'bundesliga',
  'bundesliga',
  array['Bayern Munich', 'Schalke 04'],
  'Germany',
  'MF',
  1995,
  8,
  2013,
  2026,
  array[]::integer[],
  array[]::text[],
  array['He arrived on a free from Schalke and turned into a box crashing tank.', 'A German midfielder of late runs and heavy metal shoulders.', 'Bochum to Schalke to Bayern for nothing.', 'The lockdown physique glow up that became a meme and a weapon.', 'Initials L.G.']
),
(
  '466d9515',
  'leroy-sane',
  true,
  'Leroy Sane',
  'bundesliga',
  'bundesliga',
  array['Bayern Munich', 'Schalke 04'],
  'Germany',
  'FW',
  1996,
  10,
  2014,
  2025,
  array[]::integer[],
  array[]::text[],
  array['Schalke''s teenage flyer came home from England with silverware appetite.', 'A German winger of top speed few in league history matched.', 'Gelsenkirchen to City and back to Bayern.', 'The 2020 return, wing partner to the treble chase.', 'Initials L.S.']
),
(
  'fff3083d',
  'serge-gnabry',
  true,
  'Serge Gnabry',
  'bundesliga',
  'bundesliga',
  array['Bayern Munich', 'Werder Bremen'],
  'Germany',
  'FW',
  1995,
  7,
  2016,
  2026,
  array[]::integer[],
  array[]::text[],
  array['West Brom said not good enough. He scored four in London to answer.', 'A German winger, Arsenal reject, Bayern champion.', 'Werder rebirth to Bayern''s treble wing.', 'Four against Spurs in Tottenham''s own stadium, 2019.', 'Initials S.G.']
),
(
  '0b6ffbec',
  'jamal-musiala',
  true,
  'Jamal Musiala',
  'bundesliga',
  'bundesliga',
  array['Bayern Munich'],
  'Germany',
  'MF',
  2003,
  42,
  2020,
  2026,
  array[]::integer[],
  array['Bambi'],
  array['Bambi glides between defenders like they''re training cones.', 'A German playmaker, England raised, Munich crowned.', 'Chelsea academy escapee to Bayern''s jewel.', 'The 2023 final day title winner at Cologne, minute 89.', 'Bambi. Initials J.M.']
),
(
  'e0f654b7',
  'florian-wirtz',
  true,
  'Florian Wirtz',
  'bundesliga',
  'bundesliga',
  array['Bayer Leverkusen'],
  'Germany',
  'MF',
  2003,
  10,
  2020,
  2025,
  array[]::integer[],
  array[]::text[],
  array['Leverkusen''s teenage conductor of the unbeaten miracle season.', 'A German playmaker of impossible vision between the lines.', 'Cologne academy defection to Leverkusen history.', 'The 2023-24 invincible title, the league''s first ever.', 'Initials F.W.']
),
(
  'bff4c118',
  'erling-haaland',
  false,
  'Erling Haaland',
  'bundesliga',
  'bundesliga',
  array['Borussia Dortmund'],
  'Norway',
  'FW',
  2000,
  9,
  2020,
  2022,
  array[]::integer[],
  array[]::text[],
  array['He scored a hat trick in 23 minutes of his Bundesliga debut, off the bench.', 'A Norwegian striker whose German chapter was two seasons of highlight film.', 'Salzburg to Dortmund''s yellow wall worship.', 'The debut hat trick against Augsburg, January 2020.', 'Initials E.H.']
),
(
  '523a9c74',
  'jude-bellingham',
  false,
  'Jude Bellingham',
  'bundesliga',
  'bundesliga',
  array['Borussia Dortmund'],
  'England',
  'MF',
  2003,
  22,
  2020,
  2023,
  array[]::integer[],
  array[]::text[],
  array['Number 22 at Dortmund because every academy number he wanted was taken, and he made it iconic.', 'An English teenager captaining Bundesliga midfields at 19.', 'Birmingham to Dortmund''s heartbeat.', 'The 2022-23 near title, carrying the yellow charge.', 'Initials J.B.']
),
(
  '8bdf2bc3',
  'jadon-sancho',
  true,
  'Jadon Sancho',
  'bundesliga',
  'bundesliga',
  array['Borussia Dortmund'],
  'England',
  'FW',
  2000,
  7,
  2017,
  2021,
  array[]::integer[],
  array[]::text[],
  array['He left City''s academy to prove England''s kids could rule Germany.', 'An English winger of one v one cruelty and assist charts.', 'Manchester exodus to Dortmund stardom.', 'The 2020-21 cup winning season, 16 goals from the wing.', 'Initials J.S.']
),
(
  'ceed2d87',
  'pierre-emerick-aubameyang',
  true,
  'Pierre-Emerick Aubameyang',
  'bundesliga',
  'bundesliga',
  array['Borussia Dortmund'],
  'Gabon',
  'FW',
  1989,
  17,
  2013,
  2018,
  array[]::integer[],
  array['Auba'],
  array['Batman masks, backflips and a scoring title in black and yellow.', 'A Gabonese striker of sprinter speed, literally trained on a track.', 'Saint Etienne to Dortmund''s number 17.', 'The 2017 Torjagerkanone, 31 goals.', 'Auba. Initials P.E.A.']
),
(
  'b8c418ea',
  'ousmane-dembele',
  true,
  'Ousmane Dembele',
  'bundesliga',
  'bundesliga',
  array['Borussia Dortmund'],
  'France',
  'FW',
  1997,
  7,
  2016,
  2017,
  array[]::integer[],
  array[]::text[],
  array['One Dortmund season so absurd Barcelona paid nine figures on the spot.', 'A French winger with two identical feet and zero predictability.', 'Rennes to a single yellow lightning year.', 'The 2016-17 breakout, 21 assists across competitions.', 'Initials O.D.']
),
(
  '0630cdbb',
  'mario-gotze',
  false,
  'Mario Gotze',
  'bundesliga',
  'bundesliga',
  array['Borussia Dortmund', 'Bayern Munich', 'Eintracht Frankfurt'],
  'Germany',
  'MF',
  1992,
  10,
  2009,
  2026,
  array[]::integer[],
  array[]::text[],
  array['The hometown boy whose Bayern announcement broke Dortmund hearts mid season.', 'A German playmaker, wonderkid of the Klopp uprising.', 'Dortmund''s academy jewel, the defection, the returns.', 'The 2012 double as the league''s golden child.', 'Initials M.G.']
),
(
  '387c01da',
  'toni-kroos',
  false,
  'Toni Kroos',
  'bundesliga',
  'bundesliga',
  array['Bayern Munich', 'Bayer Leverkusen'],
  'Germany',
  'MF',
  1990,
  39,
  2007,
  2014,
  array[]::integer[],
  array[]::text[],
  array['Leverkusen borrowed him and the league discovered a metronome; Bayern took him back for a treble.', 'A German midfielder whose passing was finished software at 20.', 'Bayern academy, Leverkusen polish, treble return.', 'The 2013 treble before the world took him.', 'Initials T.K.']
),
(
  '9e60ff64',
  'xabi-alonso',
  false,
  'Xabi Alonso',
  'bundesliga',
  'bundesliga',
  array['Bayern Munich'],
  'Spain',
  'MF',
  1981,
  3,
  2014,
  2017,
  array[]::integer[],
  array[]::text[],
  array['Three Bayern titles as a player, then the manager who ended their reign unbeaten.', 'A Spanish midfielder who conducted Munich then out coached it.', 'Madrid to Bayern''s midfield professor years.', 'Returning as Leverkusen''s invincible title coach, 2024.', 'Initials X.A.']
),
(
  '6852ede8',
  'arturo-vidal',
  true,
  'Arturo Vidal',
  'bundesliga',
  'bundesliga',
  array['Bayern Munich', 'Bayer Leverkusen'],
  'Chile',
  'MF',
  1987,
  23,
  2007,
  2018,
  array[]::integer[],
  array['King Arturo'],
  array['The warrior arrived with a mohawk and left with three straight titles.', 'A Chilean midfielder of tackles, headers and casino stories.', 'Leverkusen''s discovery to Bayern''s engine.', 'The Leverkusen years that made Juventus pounce, then the Bayern return.', 'King Arturo. Initials A.V.']
),
(
  '278ce37e',
  'thiago-alcantara',
  true,
  'Thiago Alcantara',
  'bundesliga',
  'bundesliga',
  array['Bayern Munich'],
  'Spain',
  'MF',
  1991,
  6,
  2013,
  2020,
  array[]::integer[],
  array[]::text[],
  array['Thiago or nothing, said Pep, and Bayern listened.', 'A Spanish midfielder of 360 degree escapes.', 'Barcelona''s cage to seven Munich titles.', 'The 2020 treble masterclass before the Liverpool goodbye.', 'Initials T.A.']
),
(
  'ff45cbe8',
  'kingsley-coman',
  true,
  'Kingsley Coman',
  'bundesliga',
  'bundesliga',
  array['Bayern Munich'],
  'France',
  'FW',
  1996,
  11,
  2015,
  2026,
  array[]::integer[],
  array[]::text[],
  array['A Champions League final winner against the club that raised his transfer.', 'A French winger of touchline chalk and big final nerve.', 'PSG teen to a decade of Bayern wings.', 'The 2020 final header against Paris, of all clubs.', 'Initials K.C.']
),
(
  '614f3a12',
  'alphonso-davies',
  true,
  'Alphonso Davies',
  'bundesliga',
  'bundesliga',
  array['Bayern Munich'],
  'Canada',
  'DF',
  2000,
  19,
  2019,
  2026,
  array[]::integer[],
  array['Road Runner'],
  array['A refugee camp to the fastest recorded sprint the league had seen.', 'A Canadian left back converted from winger mid season.', 'Vancouver to Bayern''s Roadrunner.', 'The 2020 treble breakout, cooking Europe''s wingers.', 'Road Runner. Initials A.D.']
),
(
  '2316b133',
  'harry-kane',
  false,
  'Harry Kane',
  'bundesliga',
  'bundesliga',
  array['Bayern Munich'],
  'England',
  'FW',
  1993,
  9,
  2023,
  2026,
  array[]::integer[],
  array[]::text[],
  array['He arrived chasing his first ever trophy and broke the debut season scoring record instead.', 'An English striker finally cashing his career in Bavaria.', 'North London to Munich''s number nine.', '36 goals in his first Bundesliga season.', 'Initials H.K.']
),
(
  '09a41114',
  'giovane-elber',
  true,
  'Giovane Elber',
  'bundesliga',
  'bundesliga',
  array['Bayern Munich', 'Stuttgart'],
  'Brazil',
  'FW',
  1972,
  9,
  1994,
  2003,
  array[]::integer[],
  array[]::text[],
  array['Bayern''s smiling Brazilian led the line for four titles around the millennium.', 'A Brazilian striker of samba feet and cold finishing.', 'Stuttgart to Munich''s spearhead.', 'The 2001 title and Champions League year up front.', 'Initials G.E.']
),
(
  '243ff3e7',
  'roy-makaay',
  true,
  'Roy Makaay',
  'bundesliga',
  'bundesliga',
  array['Bayern Munich'],
  'Netherlands',
  'FW',
  1975,
  10,
  2003,
  2007,
  array[]::integer[],
  array['Das Phantom'],
  array['The Phantom scored the fastest Champions League goal ever, ten seconds, for Bayern.', 'A Dutch striker who appeared from nothing and finished everything.', 'Deportivo''s golden boot to Munich.', 'Ten point twelve seconds against Madrid, 2007.', 'Das Phantom. Initials R.M.']
),
(
  '862666d5',
  'claudio-pizarro',
  true,
  'Claudio Pizarro',
  'bundesliga',
  'bundesliga',
  array['Werder Bremen', 'Bayern Munich'],
  'Peru',
  'FW',
  1978,
  14,
  1999,
  2020,
  array[]::integer[],
  array[]::text[],
  array['The league''s record foreign scorer kept returning to Bremen like a homing pigeon.', 'A Peruvian striker who played Bundesliga football until 40.', 'Werder and Bayern, alternating for two decades.', 'Scoring for Werder at 40 years old.', 'Initials C.P.']
),
(
  '6e61fb41',
  'ze-roberto',
  true,
  'Ze Roberto',
  'bundesliga',
  'bundesliga',
  array['Bayern Munich', 'Bayer Leverkusen', 'Hamburger SV'],
  'Brazil',
  'MF',
  1974,
  15,
  1998,
  2011,
  array[]::integer[],
  array[]::text[],
  array['He played top flight football until 43, and the league''s left flank belonged to him for a decade.', 'A Brazilian winger turned six of eternal fitness.', 'Leverkusen to Bayern to Hamburg''s evergreen.', 'The 2002 Leverkusen treble of second places, brilliance in defeat.', 'Initials Z.R.']
),
(
  '41804426',
  'jay-jay-okocha',
  true,
  'Jay-Jay Okocha',
  'bundesliga',
  'bundesliga',
  array['Eintracht Frankfurt'],
  'Nigeria',
  'MF',
  1973,
  10,
  1992,
  1996,
  array[]::integer[],
  array[]::text[],
  array['So good they named him twice, and his Frankfurt solo goal proved it.', 'A Nigerian magician of stepovers before stepovers were legal.', 'Frankfurt''s early nineties street theater.', 'The 1993 slalom against Kahn''s Karlsruhe, spinning the keeper twice.', 'Jay-Jay. Initials J.J.O.']
),
(
  '7a120298',
  'ailton',
  true,
  'Ailton',
  'bundesliga',
  'bundesliga',
  array['Werder Bremen', 'Schalke 04'],
  'Brazil',
  'FW',
  1973,
  18,
  1998,
  2006,
  array[]::integer[],
  array['Kugelblitz'],
  array['The Kugelblitz won Werder the double and a scoring title, all belly and bursts.', 'A Brazilian striker built round and fast, beloved in Bremen.', 'Werder''s cult hero of the 2004 miracle.', 'The 2004 double, 28 goals of chaos.', 'Kugelblitz. Initials A.']
),
(
  '50ba08d8',
  'raul',
  false,
  'Raul',
  'bundesliga',
  'bundesliga',
  array['Schalke 04'],
  'Spain',
  'FW',
  1977,
  7,
  2010,
  2012,
  array[]::integer[],
  array[]::text[],
  array['Madrid''s eternal captain chose Gelsenkirchen for his final European act, and Schalke fell in love.', 'A Spanish forward, elegant to the last, in royal blue.', 'The Bernabeu to two beloved Schalke years.', 'The 2011 cup run and semifinal charge in blue.', 'Initials R.']
),
(
  '2853b9f2',
  'kevin-de-bruyne',
  false,
  'Kevin De Bruyne',
  'bundesliga',
  'bundesliga',
  array['Wolfsburg', 'Werder Bremen'],
  'Belgium',
  'MF',
  1991,
  14,
  2012,
  2015,
  array[]::integer[],
  array[]::text[],
  array['Chelsea''s loan clause funded Wolfsburg''s assist record before City called.', 'A Belgian playmaker breaking the league assist record at 23.', 'Bremen loan to Wolfsburg''s 2015 masterpiece.', 'The 2015 season, 21 assists, Player of the Year.', 'KDB. Initials K.D.B.']
),
(
  'ea5b95b7',
  'naby-keita',
  true,
  'Naby Keita',
  'bundesliga',
  'bundesliga',
  array['RB Leipzig', 'Werder Bremen'],
  'Guinea',
  'MF',
  1995,
  8,
  2016,
  2024,
  array[]::integer[],
  array[]::text[],
  array['Leipzig''s box to box comet, the league''s best midfielder for two loud seasons.', 'A Guinean midfielder of press resistance and burst.', 'Salzburg to Leipzig''s rise.', 'The 2016-17 promotion season stunner, second place as newcomers.', 'Initials N.K.']
),
(
  'f2643478',
  'timo-werner',
  true,
  'Timo Werner',
  'bundesliga',
  'bundesliga',
  array['RB Leipzig', 'Stuttgart'],
  'Germany',
  'FW',
  1996,
  11,
  2013,
  2020,
  array[]::integer[],
  array[]::text[],
  array['Leipzig''s sprinter finished the counters that announced a new league power.', 'A German striker of straight lines and left foot finishes.', 'Stuttgart teen to Leipzig''s record scorer.', 'The 2019-20 season, 28 goals before the Chelsea move.', 'Initials T.W.']
),
(
  'f01ff4e2',
  'christopher-nkunku',
  true,
  'Christopher Nkunku',
  'bundesliga',
  'bundesliga',
  array['RB Leipzig'],
  'France',
  'FW',
  1997,
  18,
  2019,
  2023,
  array[]::integer[],
  array[]::text[],
  array['PSG let him leave quietly; he became the league''s Player of the Season loudly.', 'A French attacker of drifting positions and clean strikes.', 'Paris to Leipzig''s talisman.', 'The 2021-22 season, 35 goal involvements.', 'Initials C.N.']
),
(
  '59306ad5',
  'andre-schurrle',
  true,
  'Andre Schurrle',
  'bundesliga',
  'bundesliga',
  array['Borussia Dortmund', 'Wolfsburg', 'Bayer Leverkusen'],
  'Germany',
  'FW',
  1990,
  9,
  2009,
  2019,
  array[]::integer[],
  array[]::text[],
  array['A World Cup final assist, and the Dortmund wonder goal in the 4 4 against Schalke.', 'A German forward of streaks and huge single moments.', 'Mainz to Leverkusen to Dortmund.', 'The last minute leveler in the 4 4 Revierderby, 2017.', 'Initials A.S.']
),
(
  'def5944b',
  'rudi-voller',
  true,
  'Rudi Voller',
  'bundesliga',
  'bundesliga',
  array['Bayer Leverkusen', 'Werder Bremen'],
  'Germany',
  'FW',
  1960,
  9,
  1994,
  1996,
  array[]::integer[],
  array[]::text[],
  array['Aunt Kathe returned from Rome to lead Leverkusen, mustache intact.', 'A German striker of the old school, later the touchline''s most famous rant.', 'Bremen''s eighties star, Leverkusen''s nineties finale.', 'The 1996 farewell seasons in Leverkusen red.', 'Tante Kathe. Initials R.V.']
),
(
  '198e62f3',
  'granit-xhaka',
  true,
  'Granit Xhaka',
  'bundesliga',
  'bundesliga',
  array['Bayer Leverkusen', 'Borussia Monchengladbach'],
  'Switzerland',
  'MF',
  1992,
  34,
  2012,
  2026,
  array[]::integer[],
  array[]::text[],
  array['Arsenal''s most argued player became Leverkusen''s unbeaten general overnight.', 'A Swiss midfielder reborn as a title winning leader.', 'Gladbach''s captain, the Premier League decade, the redemption return.', 'The 2023-24 invincible season, barely losing a duel.', 'Initials G.X.']
),
(
  'cb0ad5f7',
  'victor-boniface',
  true,
  'Victor Boniface',
  'bundesliga',
  'bundesliga',
  array['Bayer Leverkusen'],
  'Nigeria',
  'FW',
  2000,
  22,
  2023,
  2026,
  array[]::integer[],
  array[]::text[],
  array['Nigerian striker whose debut season powered the league''s first unbeaten champions.', 'A forward of bulldozer runs and deadpan interviews.', 'Union SG to Leverkusen''s history makers.', 'The 2023-24 invincible title, main striker.', 'Initials V.B.']
),
(
  '364d674b',
  'zlatan-ibrahimovic',
  false,
  'Zlatan Ibrahimovic',
  'ligue_1',
  'ligue_1',
  array['Paris Saint-Germain'],
  'Sweden',
  'FW',
  1981,
  10,
  2012,
  2016,
  array[]::integer[],
  array['Ibra'],
  array['Four French titles in four seasons, and a country informed it was welcome.', 'A Swedish striker who treated Ligue 1 as his personal exhibition.', 'Milan to Paris'' new project''s first superstar.', '113 goals in four seasons, records annually.', 'Ibra. Initials Z.I.']
),
(
  '2f0dafcd',
  'edinson-cavani',
  false,
  'Edinson Cavani',
  'ligue_1',
  'ligue_1',
  array['Paris Saint-Germain'],
  'Uruguay',
  'FW',
  1987,
  9,
  2013,
  2020,
  array[]::integer[],
  array['El Matador'],
  array['PSG''s all time record scorer, bought for a French record and worth it weekly.', 'A Uruguayan striker of pressing shifts and net bursting.', 'Naples to 200 Paris goals.', 'Breaking the club scoring record, 2018.', 'El Matador. Initials E.C.']
),
(
  '42e691ec',
  'kylian-mbappe',
  false,
  'Kylian Mbappe',
  'ligue_1',
  'ligue_1',
  array['Paris Saint-Germain', 'Monaco'],
  'France',
  'FW',
  1998,
  7,
  2015,
  2024,
  array[]::integer[],
  array[]::text[],
  array['A title with Monaco as a teenager, then six more with the club that bought him for 180.', 'A French forward who won everything domestic before the world stage called.', 'Monaco''s title kid to Paris'' record scorer.', 'The 2017 Monaco title, terrorizing Europe at 18.', 'Initials K.M.']
),
(
  '756602b9',
  'neymar',
  false,
  'Neymar',
  'ligue_1',
  'ligue_1',
  array['Paris Saint-Germain'],
  'Brazil',
  'FW',
  1992,
  10,
  2017,
  2023,
  array[]::integer[],
  array['Ney'],
  array['222 million euros broke football''s market and bought Ligue 1 its biggest star.', 'A Brazilian winger of rainbows, rondos and rehab rooms.', 'Barcelona to the world record Paris move.', 'The 2018 debut season, 28 goals in 30 games.', 'Ney. Initials N.']
),
(
  '7f127186',
  'lionel-messi',
  false,
  'Lionel Messi',
  'ligue_1',
  'ligue_1',
  array['Paris Saint-Germain'],
  'Argentina',
  'FW',
  1987,
  30,
  2021,
  2023,
  array[]::integer[],
  array['Leo'],
  array['The strangest sight in league history: him, in Paris, winning titles quietly.', 'An Argentine legend on a two year French residency.', 'Barcelona''s forced goodbye to two Ligue 1 crowns.', 'The 2021 arrival that broke the internet and shirt printers.', 'Leo.']
),
(
  '0bd10477',
  'thiago-silva',
  true,
  'Thiago Silva',
  'ligue_1',
  'ligue_1',
  array['Paris Saint-Germain'],
  'Brazil',
  'DF',
  1984,
  2,
  2012,
  2020,
  array[]::integer[],
  array['O Monstro'],
  array['O Monstro captained Paris'' project through eight seasons of dominance.', 'A Brazilian center back of impeccable reading and quiet command.', 'Milan to PSG''s defensive throne.', 'Seven titles as the back line''s brain.', 'O Monstro. Initials T.S.']
),
(
  '274baf73',
  'marquinhos',
  true,
  'Marquinhos',
  'ligue_1',
  'ligue_1',
  array['Paris Saint-Germain'],
  'Brazil',
  'DF',
  1994,
  5,
  2013,
  2026,
  array[]::integer[],
  array[]::text[],
  array['Signed as a teenager, captain for a decade, PSG''s record appearance holder.', 'A Brazilian defender who grew up inside the project.', 'Roma to Paris at 19, never left.', 'The 2020 Champions League run as captain and midfield fix.', 'Initials M.']
),
(
  'e35c1267',
  'marco-verratti',
  true,
  'Marco Verratti',
  'ligue_1',
  'ligue_1',
  array['Paris Saint-Germain'],
  'Italy',
  'MF',
  1992,
  6,
  2012,
  2023,
  array[]::integer[],
  array['Il Gufetto'],
  array['Never played a Serie A minute; owned French midfields for eleven years.', 'An Italian midfielder, tiny, press proof, permanently booked.', 'Pescara''s Serie B jewel straight to Paris.', 'Eleven seasons of escaping presses that should have worked.', 'Il Gufetto. Initials M.V.']
)
on conflict (id) do update set
  person_id = excluded.person_id,
  canonical = excluded.canonical,
  name = excluded.name,
  category = excluded.category,
  league = excluded.league,
  clubs = excluded.clubs,
  nationality = excluded.nationality,
  position = excluded.position,
  birth_year = excluded.birth_year,
  shirt_number = excluded.shirt_number,
  era_start = excluded.era_start,
  era_end = excluded.era_end,
  world_cup_editions = excluded.world_cup_editions,
  aliases = excluded.aliases,
  clues = excluded.clues;

-- Verify this batch: select count(*) from public.players; -- expect 320 cumulative after all batches through 04
