-- Batch 1/6: rows 1-80 of 407
-- Paste into Supabase SQL Editor and Run (in order 01 → 06)
insert into public.players (
  id, person_id, canonical, name, category, league, clubs,
  nationality, position, birth_year, shirt_number, era_start, era_end,
  world_cup_editions, aliases, clues
) values
(
  'd6d88a2d',
  'diego-maradona',
  true,
  'Diego Maradona',
  'world_cup',
  null,
  array['Napoli'],
  'Argentina',
  'FW',
  1960,
  10,
  1982,
  1994,
  array[1982, 1986, 1990, 1994]::integer[],
  array['El Diego', 'D10S'],
  array['A number ten from Buenos Aires who made a whole World Cup his personal property in 1986.', 'An Argentine playmaker, small, left footed, and worshipped like something more than a footballer.', 'Boca to Barcelona to Naples, where a city still paints his face on its walls.', 'One tournament, two goals against England. One with his hand, one with his soul.', 'D10S. El Diego. Argentina''s number ten of number tens.']
),
(
  'e9f08944',
  'paolo-rossi',
  true,
  'Paolo Rossi',
  'world_cup',
  null,
  array['Juventus'],
  'Italy',
  'FW',
  1956,
  20,
  1982,
  1982,
  array[1982]::integer[],
  array[]::text[],
  array['Banned for two years, then top scorer and champion of the 1982 World Cup within weeks of returning.', 'An Italian poacher whose entire legend fits inside one summer in Spain.', 'Juventus was home, but 1982 made him Italy''s property forever.', 'A hat trick against the great Brazil side of 1982. The day tiki taka''s grandfather died.', 'Golden Boot, Golden Ball, world champion. Paolo. Initials P.R.']
),
(
  'ccd9c693',
  'dino-zoff',
  true,
  'Dino Zoff',
  'world_cup',
  null,
  array['Juventus'],
  'Italy',
  'GK',
  1942,
  1,
  1982,
  1982,
  array[1982]::integer[],
  array[]::text[],
  array['He lifted the 1982 World Cup at forty, the oldest champion the tournament has ever crowned.', 'An Italian goalkeeper who treated goalkeeping as a quiet public service for two decades.', 'Udinese to Napoli to Juventus, where the trophies stacked up.', 'Captain in Spain 1982, arms aloft, grey haired and unbeatable.', 'Italy''s eternal number one. Initials D.Z.']
),
(
  'd6c36545',
  'michel-platini',
  true,
  'Michel Platini',
  'world_cup',
  null,
  array['Juventus'],
  'France',
  'MF',
  1955,
  10,
  1982,
  1986,
  array[1982, 1986]::integer[],
  array[]::text[],
  array['Three consecutive Ballons d''Or in the mid eighties, and France''s artist in chief at two World Cups.', 'A French number ten who scored like a striker while playing like a poet.', 'Nancy to Saint Etienne to Juventus, where he became Le Roi.', 'The 1982 semifinal against West Germany, the greatest match he never won.', 'Le Roi Michel. Later ran UEFA. Initials M.P.']
),
(
  'd5b2b843',
  'zico',
  true,
  'Zico',
  'world_cup',
  null,
  array['Flamengo'],
  'Brazil',
  'MF',
  1953,
  10,
  1982,
  1986,
  array[1982, 1986]::integer[],
  array[]::text[],
  array['The white Pele wore ten for the most loved Brazil side never to win a World Cup.', 'A Brazilian attacking midfielder of the early eighties, free kicks like calligraphy.', 'Flamengo''s greatest son, with a late chapter in Udine and Japan.', 'The 1982 side of him, Socrates and Falcao. Beautiful, doomed, immortal.', 'Arthur Antunes Coimbra. Everyone just says his nickname.']
),
(
  '30c37fe8',
  'socrates',
  true,
  'Socrates',
  'world_cup',
  null,
  array['Corinthians'],
  'Brazil',
  'MF',
  1954,
  8,
  1982,
  1986,
  array[1982, 1986]::integer[],
  array[]::text[],
  array['A chain smoking doctor of medicine who captained Brazil''s most romantic team.', 'A tall, bearded Brazilian midfielder who passed backwards through his own heels and forwards through history.', 'Corinthians, where he turned a dressing room into a democracy movement.', 'Captain of the 1982 side that lost to Italy and won everything else.', 'Named after a philosopher. Played like one too.']
),
(
  '919071ca',
  'falcao',
  true,
  'Falcao',
  'world_cup',
  null,
  array['Roma'],
  'Brazil',
  'MF',
  1953,
  15,
  1982,
  1986,
  array[1982, 1986]::integer[],
  array[]::text[],
  array['Rome crowned him king of a midfield that already had Zico and Socrates behind him for Brazil.', 'A Brazilian midfielder of the early eighties, elegant enough to run Serie A.', 'Internacional to Roma, where they still sing about the 1983 Scudetto.', 'His goal in the 1982 epic against Italy, celebrated with veins bulging and eyes lost.', 'O Rei de Roma. Initials P.R.F.']
),
(
  '7807cc81',
  'karl-heinz-rummenigge',
  true,
  'Karl-Heinz Rummenigge',
  'world_cup',
  null,
  array['Bayern Munich'],
  'West Germany',
  'FW',
  1955,
  11,
  1982,
  1986,
  array[1982, 1986]::integer[],
  array[]::text[],
  array['Twice a Ballon d''Or winner and twice a beaten World Cup finalist in the eighties.', 'A German forward who mixed sprinter''s pace with a director''s brain.', 'Bayern Munich''s main man, then Inter, then decades running Bayern in a suit.', 'Half fit in the 1982 final, still the man Italy feared most.', 'Kalle. Initials K.H.R.']
),
(
  'd7b487fc',
  'zbigniew-boniek',
  true,
  'Zbigniew Boniek',
  'world_cup',
  null,
  array['Juventus'],
  'Poland',
  'FW',
  1956,
  20,
  1982,
  1986,
  array[1982, 1986]::integer[],
  array[]::text[],
  array['The star of Poland''s third place side in 1982, bought by Juventus that same summer.', 'A Polish forward with red hair and cold finishing, made for big European nights.', 'Widzew Lodz to Juventus to Roma.', 'A perfect hat trick against Belgium in 1982, header, left foot, right foot.', 'Zibi. Later president of Polish football. Initials Z.B.']
),
(
  'cca67b20',
  'gary-lineker',
  true,
  'Gary Lineker',
  'world_cup',
  null,
  array['Barcelona'],
  'England',
  'FW',
  1960,
  10,
  1986,
  1990,
  array[1986, 1990]::integer[],
  array[]::text[],
  array['Golden Boot at the 1986 World Cup and never once booked in his entire career.', 'An English striker who lived exclusively inside the six yard box.', 'Leicester to Everton to Barcelona to Tottenham.', 'Six goals in Mexico 86, then the tears of Italia 90 alongside Gazza.', 'Now he hosts the highlights. Initials G.L.']
),
(
  'b377ca33',
  'emilio-butragueno',
  true,
  'Emilio Butragueno',
  'world_cup',
  null,
  array['Real Madrid'],
  'Spain',
  'FW',
  1963,
  null,
  1986,
  1990,
  array[1986, 1990]::integer[],
  array[]::text[],
  array['The Vulture led Spain''s line through two World Cups in the late eighties.', 'A Spanish forward, slight and silent, deadly around loose balls.', 'One club man of the Quinta del Buitre at Real Madrid.', 'Four goals in one game against Denmark at Mexico 86.', 'El Buitre. Initials E.B.']
),
(
  '60758f61',
  'jorge-valdano',
  true,
  'Jorge Valdano',
  'world_cup',
  null,
  array['Real Madrid'],
  'Argentina',
  'FW',
  1955,
  null,
  1986,
  1986,
  array[1986]::integer[],
  array[]::text[],
  array['World champion in 1986 and later the man who called football''s beauty into microphones.', 'An Argentine forward, tall and cerebral, Maradona''s favorite target that summer.', 'Real Madrid, as player, coach and executive.', 'Scored in the 1986 final against West Germany.', 'Football''s philosopher in residence. Initials J.V.']
),
(
  'e63ff057',
  'jorge-burruchaga',
  true,
  'Jorge Burruchaga',
  'world_cup',
  null,
  array['Nantes'],
  'Argentina',
  'MF',
  1962,
  7,
  1986,
  1990,
  array[1986, 1990]::integer[],
  array[]::text[],
  array['He scored the winner in a World Cup final and somehow it is only the third most famous goal of that tournament.', 'An Argentine midfielder who did Maradona''s running in 1986.', 'Independiente to Nantes, a quiet French career after a loud Mexican summer.', 'Minute 84 of the 1986 final. Through ball from Diego, finish from him.', 'Burru. Initials J.B.']
),
(
  '037d0b51',
  'careca',
  true,
  'Careca',
  'world_cup',
  null,
  array['Napoli'],
  'Brazil',
  'FW',
  1960,
  9,
  1986,
  1990,
  array[1986, 1990]::integer[],
  array[]::text[],
  array['Brazil''s number nine either side of 1990, feeding off Maradona''s passes at club level.', 'A Brazilian striker, explosive and smiling, born for the penalty box.', 'Sao Paulo to Napoli, where he formed the Ma Gi Ca attack with Diego.', 'His 1986 tournament, four goals and the sense of a machine at full speed.', 'The bald one, by name at least. Careca.']
),
(
  '39382774',
  'enzo-francescoli',
  true,
  'Enzo Francescoli',
  'world_cup',
  null,
  array['River Plate'],
  'Uruguay',
  'MF',
  1961,
  null,
  1986,
  1990,
  array[1986, 1990]::integer[],
  array[]::text[],
  array['Uruguay''s prince, elegant enough that a young Zidane named his son after him.', 'A Uruguayan number ten of the late eighties, all glide and no noise.', 'River Plate''s idol, with French years at Marseille in between.', 'Carried Uruguay through the 1986 and 1990 World Cups almost alone.', 'El Principe. Initials E.F.']
),
(
  'c9cb4068',
  'lothar-matthaus',
  true,
  'Lothar Matthaus',
  'world_cup',
  null,
  array['Bayern Munich'],
  'Germany',
  'MF',
  1961,
  10,
  1982,
  1998,
  array[1982, 1986, 1990, 1994, 1998]::integer[],
  array[]::text[],
  array['He played in five World Cups, more matches in the tournament than any outfield player in history.', 'A German midfielder who aged backwards into a sweeper across two decades.', 'Borussia Monchengladbach to Bayern to Inter and back.', 'Captain and Ballon d''Or winner lifting the trophy in Rome, 1990.', 'Record caps for Germany. Initials L.M.']
),
(
  '49c9504b',
  'jurgen-klinsmann',
  true,
  'Jurgen Klinsmann',
  'world_cup',
  null,
  array['Inter Milan'],
  'Germany',
  'FW',
  1964,
  18,
  1990,
  1998,
  array[1990, 1994, 1998]::integer[],
  array[]::text[],
  array['World champion in 1990 and the striker England could never quite forgive or stop.', 'A German forward famous for movement, finishing, and one ironic dive celebration.', 'Stuttgart to Inter to Monaco to Tottenham, twice.', 'The 1990 final in Rome, gold confetti in blond hair.', 'Klinsi. Later coached Germany and the USA. Initials J.K.']
),
(
  'd6913c63',
  'salvatore-schillaci',
  true,
  'Salvatore Schillaci',
  'world_cup',
  null,
  array['Juventus'],
  'Italy',
  'FW',
  1964,
  19,
  1990,
  1990,
  array[1990]::integer[],
  array['Toto'],
  array['A near unknown who woke up one Italian summer and scored six goals with eyes like saucers.', 'A Sicilian striker whose entire international legend lasted one home World Cup.', 'Messina to Juventus to Inter, then Japan.', 'Golden Boot of Italia 90, wide eyed after every goal.', 'Toto. Initials S.S.']
),
(
  '9a425d8b',
  'roberto-baggio',
  true,
  'Roberto Baggio',
  'world_cup',
  null,
  array['Juventus'],
  'Italy',
  'FW',
  1967,
  10,
  1990,
  1998,
  array[1990, 1994, 1998]::integer[],
  array['Il Divin Codino'],
  array['The Divine Ponytail dragged Italy to a final on one working knee.', 'An Italian number ten, Buddhist, fragile, and touched by something the rest never had.', 'Fiorentina to Juventus to both Milans to Brescia.', 'Pasadena, 1994. The penalty over the bar and the loneliest stance in football.', 'Il Divin Codino. Initials R.B.']
),
(
  '7ecff21c',
  'roger-milla',
  true,
  'Roger Milla',
  'world_cup',
  null,
  array['Tonnerre Yaounde'],
  'Cameroon',
  'FW',
  1952,
  9,
  1982,
  1994,
  array[1982, 1990, 1994]::integer[],
  array[]::text[],
  array['He danced at corner flags in 1990 aged thirty eight, then came back four years later even older.', 'A Cameroonian striker who made the world fall for African football.', 'Tonnerre Yaounde and a long tour of France.', 'Four goals at Italia 90, hips swaying by the flag after each one.', 'The oldest scorer in World Cup history. Initials R.M.']
),
(
  '347a521a',
  'sergio-goycochea',
  true,
  'Sergio Goycochea',
  'world_cup',
  null,
  array['Racing Club'],
  'Argentina',
  'GK',
  1963,
  null,
  1990,
  1994,
  array[1990, 1994]::integer[],
  array[]::text[],
  array['A backup goalkeeper who became a penalty shootout executioner all the way to the 1990 final.', 'An Argentine keeper with a gift for guessing right when it mattered most.', 'River Plate, Racing, and a tour of the Americas.', 'Two shootout wins at Italia 90, Yugoslavia and Italy both slain.', 'Goyco. Initials S.G.']
),
(
  'da110bf4',
  'andreas-brehme',
  true,
  'Andreas Brehme',
  'world_cup',
  null,
  array['Inter Milan'],
  'Germany',
  'DF',
  1960,
  3,
  1986,
  1994,
  array[1986, 1990, 1994]::integer[],
  array[]::text[],
  array['He settled a World Cup final from the penalty spot with his supposedly weaker foot.', 'A German full back, genuinely two footed, deadly from dead balls.', 'Kaiserslautern to Bayern to Inter.', 'Minute 85, Rome, 1990. Low to Goycochea''s left.', 'Initials A.B.']
),
(
  '16cefe7f',
  'paul-gascoigne',
  true,
  'Paul Gascoigne',
  'world_cup',
  null,
  array['Tottenham Hotspur'],
  'England',
  'MF',
  1967,
  19,
  1990,
  1990,
  array[1990]::integer[],
  array['Gazza'],
  array['The tears of Turin turned an entire country''s heart in 1990.', 'An English midfielder, part genius, part chaos, entirely loved.', 'Newcastle to Tottenham to Lazio to Rangers.', 'The booking against Germany, the trembling lip, the semifinal that changed English football.', 'Gazza. Initials P.G.']
),
(
  'ca73ae76',
  'dragan-stojkovic',
  true,
  'Dragan Stojkovic',
  'world_cup',
  null,
  array['Red Star Belgrade'],
  'Yugoslavia',
  'MF',
  1965,
  10,
  1990,
  1998,
  array[1990, 1998]::integer[],
  array[]::text[],
  array['Yugoslavia''s last great number ten before the country itself disappeared.', 'A Balkan playmaker with a touch soft enough to quiet stadiums.', 'Red Star Belgrade to Marseille to Nagoya, where he became a legend twice.', 'Two goals against Spain at Italia 90, the second a work of stillness.', 'Piksi. Initials D.S.']
),
(
  'cc0aefb3',
  'romario',
  true,
  'Romario',
  'world_cup',
  null,
  array['Barcelona'],
  'Brazil',
  'FW',
  1966,
  11,
  1990,
  1994,
  array[1990, 1994]::integer[],
  array[]::text[],
  array['He promised Brazil the 1994 World Cup, then delivered it almost personally.', 'A Brazilian striker built low to the ground, allergic to training, addicted to goals.', 'Vasco to PSV to Barcelona, where he terrorized defenders for fun.', 'Five goals in 1994 and the Golden Ball that came with them.', 'O Baixinho, the little one. Initials R.']
),
(
  'fcb8a991',
  'bebeto',
  true,
  'Bebeto',
  'world_cup',
  null,
  array['Deportivo La Coruna'],
  'Brazil',
  'FW',
  1964,
  7,
  1990,
  1998,
  array[1990, 1994, 1998]::integer[],
  array[]::text[],
  array['His rocking baby celebration in 1994 is copied by every new father in football since.', 'A Brazilian forward, slight and precise, Romario''s quieter partner.', 'Flamengo to Deportivo, where he became Spain''s top scorer.', 'The cradle celebration against Holland, arms swaying with two teammates.', 'Initials B.']
),
(
  'c2be1967',
  'franco-baresi',
  true,
  'Franco Baresi',
  'world_cup',
  null,
  array['AC Milan'],
  'Italy',
  'DF',
  1960,
  6,
  1990,
  1994,
  array[1990, 1994]::integer[],
  array[]::text[],
  array['He played a World Cup final on a knee operated on twenty five days earlier, and saved his worst luck for the shootout.', 'An Italian sweeper who defended with geometry instead of tackles.', 'One club, Milan, and the number six retired behind him.', 'The 1994 final, heroic for 120 minutes, heartbroken from twelve yards.', 'Il Capitano of the Milan dynasty. Initials F.B.']
),
(
  'd3eb99cf',
  'paolo-maldini',
  true,
  'Paolo Maldini',
  'world_cup',
  null,
  array['AC Milan'],
  'Italy',
  'DF',
  1968,
  3,
  1990,
  2002,
  array[1990, 1994, 1998, 2002]::integer[],
  array[]::text[],
  array['Four World Cups, twenty five years, one club, and somehow never a world title.', 'An Italian defender so elegant that tackling felt like his plan B.', 'Milan, only Milan, six hundred times and more.', 'Captain through 1994''s final heartbreak and 1998''s quarterfinal pain.', 'Il Capitano. Son of Cesare. Initials P.M.']
),
(
  '7ef4634e',
  'gheorghe-hagi',
  true,
  'Gheorghe Hagi',
  'world_cup',
  null,
  array['Galatasaray'],
  'Romania',
  'MF',
  1965,
  10,
  1990,
  1998,
  array[1990, 1994, 1998]::integer[],
  array[]::text[],
  array['The Maradona of the Carpathians lit up three World Cups for Romania.', 'A Romanian number ten with a left foot that treated forty yards like four.', 'Steaua to Real Madrid to Barcelona to Galatasaray.', 'The lob from the halfway line against Colombia, USA 94.', 'Initials G.H.']
),
(
  'd0d41ddb',
  'hristo-stoichkov',
  true,
  'Hristo Stoichkov',
  'world_cup',
  null,
  array['Barcelona'],
  'Bulgaria',
  'FW',
  1966,
  8,
  1994,
  1998,
  array[1994, 1998]::integer[],
  array[]::text[],
  array['Angry, brilliant, and joint top scorer of the 1994 World Cup as Bulgaria stunned everyone.', 'A Bulgarian forward who played every match like a personal grudge.', 'CSKA Sofia to Cruyff''s Barcelona Dream Team.', 'The 1994 quarterfinal, beating Germany, then a semifinal nobody predicted.', 'Initials H.S.']
),
(
  '8e5a57fa',
  'gabriel-batistuta',
  true,
  'Gabriel Batistuta',
  'world_cup',
  null,
  array['Fiorentina'],
  'Argentina',
  'FW',
  1969,
  9,
  1994,
  2002,
  array[1994, 1998, 2002]::integer[],
  array['Batigol'],
  array['Hat tricks at consecutive World Cups and a machine gun celebration to match the name.', 'An Argentine number nine with hair like a lion and a strike like a hammer.', 'Fiorentina''s god through relegation and back, then a Scudetto at Roma.', 'Batigol against Jamaica in 1998, three more in the books.', 'Batigol. Initials G.B.']
),
(
  'a24d8d45',
  'dunga',
  true,
  'Dunga',
  'world_cup',
  null,
  array['Stuttgart'],
  'Brazil',
  'MF',
  1963,
  8,
  1990,
  1998,
  array[1990, 1994, 1998]::integer[],
  array[]::text[],
  array['The unglamorous captain who lifted the 1994 trophy for the most pragmatic Brazil ever built.', 'A Brazilian holding midfielder whose job was saying no, beautifully.', 'Internacional to Stuttgart to Japan.', 'Raised the cup in Pasadena as critics ate their words.', 'His nickname is Dopey in Portuguese. Initials D.']
),
(
  'cf6bb0b1',
  'claudio-taffarel',
  true,
  'Claudio Taffarel',
  'world_cup',
  null,
  array['Parma'],
  'Brazil',
  'GK',
  1966,
  1,
  1990,
  1998,
  array[1990, 1994, 1998]::integer[],
  array[]::text[],
  array['The safe hands behind Brazil''s 1994 title and the 1998 run to the final.', 'A Brazilian goalkeeper, calm as furniture, brilliant in shootouts.', 'Internacional to Parma to Galatasaray.', 'Two penalty saves against Holland in the 1998 semifinal shootout.', 'Initials C.T.']
),
(
  '15fb685e',
  'oleg-salenko',
  true,
  'Oleg Salenko',
  'world_cup',
  null,
  array['Valencia'],
  'Russia',
  'FW',
  1969,
  null,
  1994,
  1994,
  array[1994]::integer[],
  array[]::text[],
  array['Five goals in one World Cup match. Nobody else has ever done it.', 'A Russian striker whose entire fame is one afternoon in 1994.', 'Dynamo Kyiv to Logrones to Valencia.', 'Russia 6, Cameroon 1, and one man scored five of them.', 'Shared the 1994 Golden Boot. Initials O.S.']
),
(
  'e4b67989',
  'tomas-brolin',
  true,
  'Tomas Brolin',
  'world_cup',
  null,
  array['Parma'],
  'Sweden',
  'FW',
  1969,
  null,
  1990,
  1994,
  array[1990, 1994]::integer[],
  array[]::text[],
  array['The face of Sweden''s charge to third place at USA 94.', 'A Swedish forward, round cheeked and quick brained, at his peak in yellow.', 'Parma''s early nineties darling before English misadventure.', 'His goal against Romania in the 1994 quarterfinal, a training ground free kick made real.', 'Initials T.B.']
),
(
  '14527eb8',
  'zinedine-zidane',
  true,
  'Zinedine Zidane',
  'world_cup',
  null,
  array['Real Madrid'],
  'France',
  'MF',
  1972,
  10,
  1998,
  2006,
  array[1998, 2002, 2006]::integer[],
  array['Zizou'],
  array['Two headers in a World Cup final at home, and one headbutt in another.', 'A French number ten of Algerian roots who made control look like slow motion.', 'Cannes to Bordeaux to Juventus to Madrid.', 'Paris 1998, twice rising at corners, a nation redefined.', 'Zizou. Initials Z.Z.']
),
(
  'e8a183a5',
  'ronaldo',
  true,
  'Ronaldo',
  'world_cup',
  null,
  array['Real Madrid'],
  'Brazil',
  'FW',
  1976,
  9,
  1994,
  2006,
  array[1994, 1998, 2002, 2006]::integer[],
  array['R9', 'O Fenomeno'],
  array['He left Brazil as a teenager in 1994 with the world already calling him the next great number nine.', 'A Brazilian striker whose peak years redefined what forwards could be.', 'Cruzeiro to PSV to Barcelona to Inter, then the white of Madrid.', 'Wept before the 1998 final. Answered with both goals in the 2002 final.', 'O Fenomeno. R9.']
),
(
  '3b953d53',
  'davor-suker',
  true,
  'Davor Suker',
  'world_cup',
  null,
  array['Real Madrid'],
  'Croatia',
  'FW',
  1968,
  9,
  1998,
  2002,
  array[1998, 2002]::integer[],
  array[]::text[],
  array['Golden Boot of France 98 as a brand new country finished third.', 'A Croatian striker with a left foot he claimed he would insure over his life.', 'Sevilla to Real Madrid to Arsenal.', 'Six goals in 1998, including one in the semifinal against France.', 'Now runs Croatian football. Initials D.S.']
),
(
  'c6f80b00',
  'lilian-thuram',
  true,
  'Lilian Thuram',
  'world_cup',
  null,
  array['Juventus'],
  'France',
  'DF',
  1972,
  15,
  1998,
  2006,
  array[1998, 2002, 2006]::integer[],
  array[]::text[],
  array['Two goals in his entire international career, both in one World Cup semifinal.', 'A French defender, intellectual and immovable, part of the 98 back line of legend.', 'Monaco to Parma to Juventus to Barcelona.', 'The 1998 semifinal against Croatia, both goals his, forever out of character.', 'France''s most capped man for years. Initials L.T.']
),
(
  '05413f09',
  'michael-owen',
  true,
  'Michael Owen',
  'world_cup',
  null,
  array['Liverpool'],
  'England',
  'FW',
  1979,
  10,
  1998,
  2006,
  array[1998, 2002, 2006]::integer[],
  array[]::text[],
  array['Eighteen years old, England shirt, and one slalom through Argentina that announced him to the planet.', 'An English striker built entirely of acceleration and certainty.', 'Liverpool''s boy wonder, later Madrid and Newcastle.', 'Saint Etienne, 1998. Pick up, run, finish, legend.', 'Ballon d''Or 2001. Initials M.O.']
),
(
  '48592228',
  'dennis-bergkamp',
  true,
  'Dennis Bergkamp',
  'world_cup',
  null,
  array['Arsenal'],
  'Netherlands',
  'FW',
  1969,
  8,
  1994,
  1998,
  array[1994, 1998]::integer[],
  array[]::text[],
  array['A flick, a spin, and a finish against Argentina in 1998 that people replay like music.', 'A Dutch forward who refused to fly and never needed to.', 'Ajax to Inter to Arsenal, where statues followed.', 'Minute 89, quarterfinal 1998. Frank de Boer''s pass, three touches, art.', 'The Non Flying Dutchman. Initials D.B.']
),
(
  '7ac9e000',
  'rivaldo',
  true,
  'Rivaldo',
  'world_cup',
  null,
  array['Barcelona'],
  'Brazil',
  'MF',
  1972,
  10,
  1998,
  2002,
  array[1998, 2002]::integer[],
  array[]::text[],
  array['The bow legged Brazilian who carried the 2002 front three alongside two other Rs.', 'A left footed number ten from poverty in Recife to the top of the world.', 'Palmeiras to Deportivo to Barcelona.', 'Five goals in 2002, and one theatrical fall he never lived down.', 'Ballon d''Or 1999. Initials R.']
),
(
  'b0b859f7',
  'alessandro-del-piero',
  true,
  'Alessandro Del Piero',
  'world_cup',
  null,
  array['Juventus'],
  'Italy',
  'FW',
  1974,
  7,
  1998,
  2006,
  array[1998, 2002, 2006]::integer[],
  array[]::text[],
  array['Italy''s darling scored the semifinal killer in Dortmund on their way to the 2006 title.', 'An Italian number ten who curled shots into the same top corner so often they named the zone after him.', 'One badge on his heart, Juventus, through glory and Serie B.', 'Berlin bound after his goal in the 2006 semi against Germany.', 'Alex. Pinturicchio. Initials A.D.P.']
),
(
  '07a42f40',
  'fabien-barthez',
  true,
  'Fabien Barthez',
  'world_cup',
  null,
  array['Manchester United'],
  'France',
  'GK',
  1971,
  16,
  1998,
  2006,
  array[1998, 2002, 2006]::integer[],
  array[]::text[],
  array['A bald head kissed by his defender before every match of France 98.', 'A French goalkeeper, eccentric and brave, champion of world and continent.', 'Monaco to Manchester United and back to Marseille.', 'Laurent Blanc''s kiss on his head, repeated all the way to the trophy.', 'Initials F.B.']
),
(
  '17841be4',
  'oliver-kahn',
  true,
  'Oliver Kahn',
  'world_cup',
  null,
  array['Bayern Munich'],
  'Germany',
  'GK',
  1969,
  1,
  2002,
  2006,
  array[2002, 2006]::integer[],
  array['Der Titan'],
  array['The only goalkeeper ever to win the World Cup Golden Ball, in the tournament that broke his heart.', 'A German keeper who played every match like a bar fight he intended to win.', 'Karlsruher to Bayern, where he became a monument.', 'Yokohama 2002, one spilled ball, Ronaldo pouncing, the image of the final.', 'Der Titan. Initials O.K.']
),
(
  'ec8e2531',
  'michael-ballack',
  true,
  'Michael Ballack',
  'world_cup',
  null,
  array['Bayern Munich'],
  'Germany',
  'MF',
  1976,
  13,
  2002,
  2006,
  array[2002, 2006]::integer[],
  array[]::text[],
  array['Germany''s captain of the 2002 run, suspended for the final he dragged them to.', 'A German midfielder who arrived late in boxes and early in importance.', 'Kaiserslautern to Leverkusen to Bayern to Chelsea.', 'The yellow card against South Korea, taking one for the team he then couldn''t join.', 'Initials M.B.']
),
(
  '2c510943',
  'ronaldinho',
  true,
  'Ronaldinho',
  'world_cup',
  null,
  array['Barcelona'],
  'Brazil',
  'MF',
  1980,
  10,
  2002,
  2006,
  array[2002, 2006]::integer[],
  array['Dinho'],
  array['The chip over Seaman in 2002 that he swears was intentional.', 'A Brazilian magician who grinned his way through the game''s hardest tricks.', 'Gremio to PSG to Barcelona, where football fell in love again.', 'That free kick from forty yards in the 2002 quarterfinal against England.', 'Dinho. Initials R.']
),
(
  'b246bdec',
  'cafu',
  true,
  'Cafu',
  'world_cup',
  null,
  array['AC Milan'],
  'Brazil',
  'DF',
  1970,
  2,
  1994,
  2006,
  array[1994, 1998, 2002, 2006]::integer[],
  array[]::text[],
  array['The only man to play in three consecutive World Cup finals, winning two.', 'A Brazilian right back who ran the touchline like it owed him money.', 'Sao Paulo to Roma to Milan.', 'Captain in 2002, lifting the trophy on the podium, standing on the plinth.', 'Il Pendolino. Initials C.']
),
(
  '668740c6',
  'roberto-carlos',
  true,
  'Roberto Carlos',
  'world_cup',
  null,
  array['Real Madrid'],
  'Brazil',
  'DF',
  1973,
  3,
  1998,
  2006,
  array[1998, 2002, 2006]::integer[],
  array[]::text[],
  array['The banana free kick against France in 1997 promised what his World Cups delivered.', 'A Brazilian left back with thighs like oak and a run up from another postcode.', 'Palmeiras to Inter to a decade at Real Madrid.', 'Part of the 2002 champion side, bombing forward as ever.', 'Initials R.C.']
),
(
  'c106e3d2',
  'miroslav-klose',
  true,
  'Miroslav Klose',
  'world_cup',
  null,
  array['Lazio'],
  'Germany',
  'FW',
  1978,
  11,
  2002,
  2014,
  array[2002, 2006, 2010, 2014]::integer[],
  array[]::text[],
  array['The record. Sixteen World Cup goals, more than anyone who ever played.', 'A German striker who celebrated with a front flip and finished with plain honesty.', 'Kaiserslautern to Werder to Bayern to Lazio.', 'Passing the great Ronaldo''s record in Brazil, 2014, in a 7 1 that shook the world.', 'Initials M.K.']
),
(
  'b3ddc0be',
  'gianluigi-buffon',
  true,
  'Gianluigi Buffon',
  'world_cup',
  null,
  array['Juventus'],
  'Italy',
  'GK',
  1978,
  1,
  1998,
  2014,
  array[1998, 2002, 2006, 2010, 2014]::integer[],
  array[]::text[],
  array['Five World Cups on the squad list, one golden clean sheet run in 2006.', 'An Italian goalkeeper who guarded a net for nearly three decades.', 'Parma to Juventus, loyalty measured in decades.', 'Berlin 2006, two goals conceded all tournament, neither from open play.', 'Gigi. Initials G.B.']
),
(
  '4f7093cd',
  'ahn-jung-hwan',
  true,
  'Ahn Jung-hwan',
  'world_cup',
  null,
  array['Perugia'],
  'South Korea',
  'FW',
  1976,
  null,
  2002,
  2010,
  array[2002, 2006, 2010]::integer[],
  array[]::text[],
  array['He scored the golden goal that knocked out Italy in 2002, and his Italian club fired him for it.', 'A South Korean forward at the heart of the great home run to the semifinals.', 'Perugia, until that header. Then Japan and beyond.', 'Minute 117 against Italy, glancing header, national holiday.', 'Initials A.J.H.']
),
(
  '8e3e6200',
  'fabio-cannavaro',
  true,
  'Fabio Cannavaro',
  'world_cup',
  null,
  array['Real Madrid'],
  'Italy',
  'DF',
  1973,
  5,
  1998,
  2010,
  array[1998, 2002, 2006, 2010]::integer[],
  array[]::text[],
  array['A five foot nine center back who won the Ballon d''Or by defending.', 'An Italian captain whose 2006 was the greatest defensive tournament ever played.', 'Napoli to Parma to Juventus to Madrid.', 'Lifting the cup in Berlin as captain, confetti gold on blue.', 'Il Muro di Berlino. Initials F.C.']
),
(
  '51639836',
  'andrea-pirlo',
  true,
  'Andrea Pirlo',
  'world_cup',
  null,
  array['Juventus'],
  'Italy',
  'MF',
  1979,
  21,
  2006,
  2014,
  array[2006, 2010, 2014]::integer[],
  array['The Architect'],
  array['He invented time and space in midfield and won a World Cup while barely breaking a sweat.', 'An Italian deep playmaker with a beard, a vineyard, and a wand of a right foot.', 'Brescia to Inter to Milan to Juventus.', 'Man of the match in the 2006 final, then that no look assist for Grosso in the semi.', 'The Architect. Initials A.P.']
),
(
  '34b935e6',
  'francesco-totti',
  true,
  'Francesco Totti',
  'world_cup',
  null,
  array['Roma'],
  'Italy',
  'FW',
  1976,
  10,
  2002,
  2006,
  array[2002, 2006]::integer[],
  array['Il Capitano'],
  array['The king of Rome came back from a broken ankle to win the 2006 World Cup.', 'An Italian number ten who could have gone anywhere and stayed home instead.', 'One club, Roma, for a quarter of a century.', 'The last minute penalty against Australia in 2006, ice in Kaiserslautern.', 'Er Pupone. Initials F.T.']
),
(
  'b67c4d86',
  'marco-materazzi',
  true,
  'Marco Materazzi',
  'world_cup',
  null,
  array['Inter Milan'],
  'Italy',
  'DF',
  1973,
  23,
  2006,
  2006,
  array[2006]::integer[],
  array[]::text[],
  array['He scored in a World Cup final, equalized it, converted in the shootout, and is remembered for a headbutt he received.', 'An Italian center back who lived to provoke and defended like a wall.', 'Inter, mostly, with an Everton detour.', 'Berlin 2006. The words, the headbutt, the red card that changed a final.', 'Matrix. Initials M.M.']
),
(
  '70ed3e20',
  'thierry-henry',
  true,
  'Thierry Henry',
  'world_cup',
  null,
  array['Arsenal'],
  'France',
  'FW',
  1977,
  12,
  1998,
  2010,
  array[1998, 2002, 2006, 2010]::integer[],
  array['Titi'],
  array['World champion at twenty, a handball in Paris eleven years later.', 'A French forward who turned the inside left channel into private property.', 'Monaco to Juventus to Arsenal, where he became the league''s greatest import.', 'The 1998 title as a kid, the 2006 final as the main man.', 'Titi. Initials T.H.']
),
(
  '929f2b19',
  'andres-iniesta',
  true,
  'Andres Iniesta',
  'world_cup',
  null,
  array['Barcelona'],
  'Spain',
  'MF',
  1984,
  6,
  2006,
  2018,
  array[2006, 2010, 2014, 2018]::integer[],
  array[]::text[],
  array['Minute 116 in Johannesburg. One touch, one volley, one country''s first star.', 'A Spanish midfielder, pale and silent, who decided the biggest games ever played.', 'La Masia to a lifetime at Barcelona.', 'The 2010 final winner against Holland, shirt off, tribute to Jarque underneath.', 'El Ilusionista. Initials A.I.']
),
(
  '209ca47f',
  'xavi',
  true,
  'Xavi',
  'world_cup',
  null,
  array['Barcelona'],
  'Spain',
  'MF',
  1980,
  8,
  2002,
  2014,
  array[2002, 2006, 2010, 2014]::integer[],
  array['Xavi Hernandez'],
  array['The metronome of the Spain side that passed the world into submission.', 'A Spanish midfielder who received, turned and gave, five hundred times a match.', 'Barcelona, boy to legend, then Qatar and back as coach.', 'The 2010 title as the heartbeat, 2008 and 2012 as bookends.', 'Initials X.H.']
),
(
  '9d81ef87',
  'david-villa',
  true,
  'David Villa',
  'world_cup',
  null,
  array['Barcelona'],
  'Spain',
  'FW',
  1981,
  7,
  2006,
  2014,
  array[2006, 2010, 2014]::integer[],
  array['El Guaje'],
  array['Spain''s all time top scorer and the sharp edge of their 2010 triumph.', 'A Spanish striker from a mining family, lethal from the left channel.', 'Sporting Gijon to Valencia to Barcelona.', 'Five goals in South Africa 2010, dragging the champions through.', 'El Guaje. Initials D.V.']
),
(
  '083e7afe',
  'iker-casillas',
  true,
  'Iker Casillas',
  'world_cup',
  null,
  array['Real Madrid'],
  'Spain',
  'GK',
  1981,
  1,
  2002,
  2014,
  array[2002, 2006, 2010, 2014]::integer[],
  array['San Iker'],
  array['The captain saint whose one on one save against Robben preserved a nation''s destiny.', 'A Spanish goalkeeper who debuted as a teenager and left as a monument.', 'Real Madrid for sixteen trophies, then Porto.', 'The outstretched boot against Robben, minute 62, final 2010.', 'San Iker. Initials I.C.']
),
(
  '0d2aa440',
  'diego-forlan',
  true,
  'Diego Forlan',
  'world_cup',
  null,
  array['Atletico Madrid'],
  'Uruguay',
  'FW',
  1979,
  10,
  2002,
  2014,
  array[2002, 2010, 2014]::integer[],
  array[]::text[],
  array['Golden Ball winner of the 2010 World Cup as Uruguay charmed a continent.', 'A Uruguayan striker who hit the cleanest long range ball of his generation.', 'Manchester United misfire, Villarreal and Atletico redemption.', 'Four goals in South Africa and the last kick of the semifinal off the bar.', 'Cachavacha. Initials D.F.']
),
(
  '67eddfdf',
  'wesley-sneijder',
  true,
  'Wesley Sneijder',
  'world_cup',
  null,
  array['Inter Milan'],
  'Netherlands',
  'MF',
  1984,
  10,
  2006,
  2014,
  array[2006, 2010, 2014]::integer[],
  array[]::text[],
  array['Five goals in 2010 and ninety minutes from the treble plus a World Cup.', 'A Dutch number ten, small, furious, and unerring from range.', 'Ajax to Madrid to Inter''s treble.', 'The 2010 run, dragging Holland to Soccer City.', 'Initials W.S.']
),
(
  '674213e0',
  'arjen-robben',
  true,
  'Arjen Robben',
  'world_cup',
  null,
  array['Bayern Munich'],
  'Netherlands',
  'FW',
  1984,
  11,
  2006,
  2014,
  array[2006, 2010, 2014]::integer[],
  array[]::text[],
  array['Cut inside on the left, shoot far corner. Everyone knew, nobody stopped it, especially in 2014.', 'A Dutch winger bald by twenty five and unstoppable to thirty five.', 'Groningen to PSV to Chelsea to Madrid to Bayern.', 'The sprint from his own half past Ramos, Brazil 2014.', 'Initials A.R.']
),
(
  '97f3982d',
  'carles-puyol',
  true,
  'Carles Puyol',
  'world_cup',
  null,
  array['Barcelona'],
  'Spain',
  'DF',
  1978,
  5,
  2002,
  2010,
  array[2002, 2006, 2010]::integer[],
  array[]::text[],
  array['A caveman''s hair, a captain''s heart, and the header that sent Spain to their first final.', 'A Spanish center back who defended like the ball had insulted his family.', 'One club, Barcelona.', 'The thumping header against Germany, semifinal 2010.', 'Tarzan. Initials C.P.']
),
(
  '79e05a5e',
  'mario-gotze',
  true,
  'Mario Gotze',
  'world_cup',
  null,
  array['Borussia Dortmund'],
  'Germany',
  'MF',
  1992,
  19,
  2014,
  2014,
  array[2014]::integer[],
  array[]::text[],
  array['Super Mario came off the bench in the Maracana and finished a World Cup with his chest and left foot.', 'A German attacking midfielder whose whole career distilled into one extra time volley.', 'Dortmund to Bayern and back.', 'Minute 113, final 2014. Schurrle''s cross, the touch, the goal.', 'Initials M.G.']
),
(
  'fc10e0a8',
  'manuel-neuer',
  true,
  'Manuel Neuer',
  'world_cup',
  null,
  array['Bayern Munich'],
  'Germany',
  'GK',
  1986,
  1,
  2010,
  2022,
  array[2010, 2014, 2018, 2022]::integer[],
  array[]::text[],
  array['He redefined goalkeeping as an outfield position and won the 2014 title doing it.', 'A German keeper who spent half of Brazil 2014 outside his own box.', 'Schalke to Bayern.', 'Sweeper keeper masterclass against Algeria, last sixteen, 2014.', 'Initials M.N.']
),
(
  'b430f126',
  'thomas-muller',
  true,
  'Thomas Muller',
  'world_cup',
  null,
  array['Bayern Munich'],
  'Germany',
  'FW',
  1989,
  13,
  2010,
  2022,
  array[2010, 2014, 2018, 2022]::integer[],
  array['Raumdeuter'],
  array['Ten World Cup goals before turning twenty five, and a job title he invented himself.', 'A German forward who found space that tactics boards say does not exist.', 'Bayern, only ever Bayern.', 'Golden Boot 2010 as a nobody, champion 2014 as a somebody.', 'The Raumdeuter. Initials T.M.']
),
(
  'bb070c43',
  'james-rodriguez',
  true,
  'James Rodriguez',
  'world_cup',
  null,
  array['Real Madrid'],
  'Colombia',
  'MF',
  1991,
  10,
  2014,
  2018,
  array[2014, 2018]::integer[],
  array[]::text[],
  array['The volley of Brazil 2014 and the Golden Boot nobody saw coming.', 'A Colombian number ten with a left foot dipped in honey.', 'Monaco to Madrid on the back of one tournament.', 'Chest, swivel, volley off the bar and in, against Uruguay.', 'Initials J.R.']
),
(
  '0d8161f4',
  'toni-kroos',
  true,
  'Toni Kroos',
  'world_cup',
  null,
  array['Real Madrid'],
  'Germany',
  'MF',
  1990,
  8,
  2010,
  2022,
  array[2010, 2014, 2018, 2022]::integer[],
  array[]::text[],
  array['The last passer of the great German school, world champion at twenty four.', 'A German midfielder who misplaced roughly one pass per calendar year.', 'Bayern to a decade of Champions League silver at Madrid.', 'Two goals in 179 seconds during the 7 1 in Belo Horizonte.', 'Initials T.K.']
),
(
  '6fb4ba42',
  'luka-modric',
  true,
  'Luka Modric',
  'world_cup',
  null,
  array['Real Madrid'],
  'Croatia',
  'MF',
  1985,
  10,
  2006,
  2022,
  array[2006, 2014, 2018, 2022]::integer[],
  array[]::text[],
  array['Golden Ball winner of 2018 as a nation of four million reached the final.', 'A Croatian midfielder who runs box to box on the energy of grievance and grace.', 'Dinamo to Tottenham to endless trophies in Madrid.', 'Russia 2018, carrying Croatia through three straight extra times.', 'Initials L.M.']
),
(
  '4c8c9420',
  'antoine-griezmann',
  true,
  'Antoine Griezmann',
  'world_cup',
  null,
  array['Atletico Madrid'],
  'France',
  'FW',
  1991,
  7,
  2014,
  2022,
  array[2014, 2018, 2022]::integer[],
  array['Grizi'],
  array['World champion in 2018, doing three players'' jobs and celebrating in Fortnite dances.', 'A French forward raised in Spain, equal parts creator and finisher.', 'Real Sociedad to Atletico to Barcelona and back.', 'Four goals in Russia including the final, plus the tournament''s dirty work.', 'Grizi. Initials A.G.']
),
(
  'f476dc18',
  'ngolo-kante',
  true,
  'NGolo Kante',
  'world_cup',
  null,
  array['Chelsea'],
  'France',
  'MF',
  1991,
  13,
  2018,
  2022,
  array[2018, 2022]::integer[],
  array[]::text[],
  array['He covered so much ground in 2018 that France effectively fielded twelve.', 'A French midfielder, tiny, smiling, and everywhere at once.', 'Leicester''s miracle engine, then Chelsea''s.', 'The 2018 title, quietly the champion''s most important part.', 'Initials N.K.']
),
(
  'fadf345a',
  'eden-hazard',
  true,
  'Eden Hazard',
  'world_cup',
  null,
  array['Chelsea'],
  'Belgium',
  'FW',
  1991,
  10,
  2014,
  2022,
  array[2014, 2018, 2022]::integer[],
  array[]::text[],
  array['Captain of Belgium''s golden generation and the best player England couldn''t touch in 2018.', 'A Belgian winger with a low center of gravity and a high sense of mischief.', 'Lille to Chelsea to an unhappy Madrid ending.', 'Russia 2018, third place, and a semifinal where he was the best player on a losing side.', 'Initials E.H.']
),
(
  '38fa1c95',
  'romelu-lukaku',
  true,
  'Romelu Lukaku',
  'world_cup',
  null,
  array['Inter Milan'],
  'Belgium',
  'FW',
  1993,
  9,
  2014,
  2022,
  array[2014, 2018, 2022]::integer[],
  array[]::text[],
  array['Belgium''s all time top scorer across three World Cups of feast and famine.', 'A Belgian number nine built like a heavyweight with a sprinter''s start.', 'Anderlecht to Everton to United to Inter.', 'Four goals in the 2018 groups powering the golden generation.', 'Big Rom. Initials R.L.']
),
(
  '8605cdbf',
  'edinson-cavani',
  true,
  'Edinson Cavani',
  'world_cup',
  null,
  array['Paris Saint-Germain'],
  'Uruguay',
  'FW',
  1987,
  21,
  2010,
  2022,
  array[2010, 2014, 2018, 2022]::integer[],
  array['El Matador'],
  array['Both goals against Portugal in 2018, then injured before the quarterfinal Uruguay needed him for.', 'A Uruguayan striker who pressed defenders like it was a moral duty.', 'Napoli to PSG, where he became record scorer.', 'The chest and finish one two with Suarez, Sochi 2018.', 'El Matador. Initials E.C.']
),
(
  '4f294bd5',
  'luis-suarez',
  true,
  'Luis Suarez',
  'world_cup',
  null,
  array['Barcelona'],
  'Uruguay',
  'FW',
  1987,
  9,
  2010,
  2022,
  array[2010, 2014, 2018, 2022]::integer[],
  array['El Pistolero'],
  array['Two World Cup handball scandals, one bite, and a lot of goals in between.', 'A Uruguayan striker, brilliant and feral in equal measure.', 'Ajax to Liverpool to Barcelona.', 'The goal line handball against Ghana in 2010, celebrated from the tunnel.', 'El Pistolero. Initials L.S.']
),
(
  '7de1c69c',
  'kylian-mbappe',
  true,
  'Kylian Mbappe',
  'world_cup',
  null,
  array['Real Madrid'],
  'France',
  'FW',
  1998,
  10,
  2018,
  2022,
  array[2018, 2022]::integer[],
  array['Donatello'],
  array['A World Cup final hat trick, and it still wasn''t enough.', 'A French forward who plays the game at a speed the rest rent by the hour.', 'Monaco to PSG to the white shirt he chased for years.', 'Three goals in the 2022 final against Argentina, the greatest losing performance ever.', 'Initials K.M.']
),
(
  '61d8e518',
  'julian-alvarez',
  true,
  'Julian Alvarez',
  'world_cup',
  null,
  array['Atletico Madrid'],
  'Argentina',
  'FW',
  2000,
  9,
  2022,
  2022,
  array[2022]::integer[],
  array['La Arana'],
  array['The spider ran, pressed and scored his way through Argentina''s 2022 title as a twenty two year old.', 'An Argentine forward who does every job on the pitch, including Messi''s errands.', 'River Plate to City to Atletico.', 'Two in the semifinal against Croatia, including a sixty yard charge.', 'La Arana. Initials J.A.']
),
(
  '3603e2cf',
  'emiliano-martinez',
  true,
  'Emiliano Martinez',
  'world_cup',
  null,
  array['Aston Villa'],
  'Argentina',
  'GK',
  1992,
  23,
  2022,
  2022,
  array[2022]::integer[],
  array['Dibu'],
  array['The save from Kolo Muani in the final minute of extra time, then the shootout he owned.', 'An Argentine goalkeeper who weaponized villainy in Qatar.', 'A decade of Arsenal patience, then Aston Villa stardom.', 'The outstretched leg in minute 123 of the 2022 final.', 'Dibu. Initials E.M.']
)
on conflict (id) do update set
  person_id = excluded.person_id,
  canonical = excluded.canonical,
  name = excluded.name,
  category = excluded.category,
  league = excluded.league,
  clubs = excluded.clubs,
  nationality = excluded.nationality,
  position = excluded.position,
  birth_year = excluded.birth_year,
  shirt_number = excluded.shirt_number,
  era_start = excluded.era_start,
  era_end = excluded.era_end,
  world_cup_editions = excluded.world_cup_editions,
  aliases = excluded.aliases,
  clues = excluded.clues;

-- Verify this batch: select count(*) from public.players; -- expect 80 cumulative after all batches through 01
