-- TM SAMPLE merge batch 1/4: 80 new rows (of 292 new)
-- Paste into Supabase SQL Editor AFTER players_batch_01–06.
-- Run in order tm_01 → tm_04.
insert into public.players (
  id, person_id, canonical, name, category, league, clubs,
  nationality, position, birth_year, shirt_number, era_start, era_end,
  world_cup_editions, aliases, clues
) values
(
  'c8b9ec17',
  'james-ward-prowse',
  true,
  'James Ward-Prowse',
  'premier_league',
  'premier_league',
  array['Burnley', 'Nottingham Forest', 'Southampton', 'West Ham United'],
  'England',
  'MF',
  1994,
  null,
  2012,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A England midfielder in the 2012-2025 window.', 'SAMPLE: Club path in this league window: Burnley, Nottingham Forest, Southampton, West Ham United.', 'SAMPLE: 422 appearances, 57 goals, 50 assists (107 combined) in the logged window.', 'SAMPLE: Initials J.W.P. Surname shape length 6.']
),
(
  'b1af864f',
  'jordan-pickford',
  true,
  'Jordan Pickford',
  'premier_league',
  'premier_league',
  array['Everton', 'Sunderland AFC'],
  'England',
  'GK',
  1994,
  null,
  2015,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2015-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A England goalkeeper in the 2015-2025 window.', 'SAMPLE: Club path in this league window: Everton, Sunderland AFC.', 'SAMPLE: 362 appearances, 0 goals, 2 assists (2 combined) in the logged window.', 'SAMPLE: Initials J.P. Surname shape length 8.']
),
(
  'dfde5821',
  'hugo-lloris',
  true,
  'Hugo Lloris',
  'premier_league',
  'premier_league',
  array['Tottenham Hotspur'],
  'France',
  'GK',
  1986,
  null,
  2012,
  2022,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2022 league regular logged near the top of the appearances table.', 'SAMPLE: A France goalkeeper in the 2012-2022 window.', 'SAMPLE: Club path in this league window: Tottenham Hotspur.', 'SAMPLE: 361 appearances, 0 goals, 0 assists (0 combined) in the logged window.', 'SAMPLE: Initials H.L. Surname shape length 6.']
),
(
  '81ab05b0',
  'james-milner',
  true,
  'James Milner',
  'premier_league',
  'premier_league',
  array['Brighton & Hove Albion', 'Liverpool', 'Manchester City'],
  'England',
  'MF',
  1986,
  null,
  2012,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A England midfielder in the 2012-2025 window.', 'SAMPLE: Club path in this league window: Brighton & Hove Albion, Liverpool, Manchester City.', 'SAMPLE: 358 appearances, 30 goals, 49 assists (79 combined) in the logged window.', 'SAMPLE: Initials J.M. Surname shape length 6.']
),
(
  '849ed137',
  'jordan-henderson',
  true,
  'Jordan Henderson',
  'premier_league',
  'premier_league',
  array['Brentford', 'Liverpool'],
  'England',
  'MF',
  1990,
  null,
  2012,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A England midfielder in the 2012-2025 window.', 'SAMPLE: Club path in this league window: Brentford, Liverpool.', 'SAMPLE: 355 appearances, 28 goals, 48 assists (76 combined) in the logged window.', 'SAMPLE: Initials J.H. Surname shape length 9.']
),
(
  '3fcb1687',
  'cesar-azpilicueta',
  true,
  'César Azpilicueta',
  'premier_league',
  'premier_league',
  array['Chelsea'],
  'Spain',
  'DF',
  1989,
  null,
  2012,
  2022,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2022 league regular logged near the top of the appearances table.', 'SAMPLE: A Spain defender in the 2012-2022 window.', 'SAMPLE: Club path in this league window: Chelsea.', 'SAMPLE: 349 appearances, 10 goals, 41 assists (51 combined) in the logged window.', 'SAMPLE: Initials C.A. Surname shape length 11.']
),
(
  '1d2789cd',
  'lukasz-fabianski',
  true,
  'Lukasz Fabianski',
  'premier_league',
  'premier_league',
  array['Arsenal', 'Swansea City', 'West Ham United'],
  'Poland',
  'GK',
  1985,
  null,
  2012,
  2024,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2024 league regular logged near the top of the appearances table.', 'SAMPLE: A Poland goalkeeper in the 2012-2024 window.', 'SAMPLE: Club path in this league window: Arsenal, Swansea City, West Ham United.', 'SAMPLE: 349 appearances, 0 goals, 1 assists (1 combined) in the logged window.', 'SAMPLE: Initials L.F. Surname shape length 9.']
),
(
  'f161f0a5',
  'james-tarkowski',
  true,
  'James Tarkowski',
  'premier_league',
  'premier_league',
  array['Burnley', 'Everton'],
  'England',
  'DF',
  1992,
  null,
  2016,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2016-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A England defender in the 2016-2025 window.', 'SAMPLE: Club path in this league window: Burnley, Everton.', 'SAMPLE: 340 appearances, 12 goals, 11 assists (23 combined) in the logged window.', 'SAMPLE: Initials J.T. Surname shape length 9.']
),
(
  '311d63d3',
  'danny-welbeck',
  true,
  'Danny Welbeck',
  'premier_league',
  'premier_league',
  array['Arsenal', 'Brighton & Hove Albion', 'Manchester United', 'Watford'],
  'England',
  'FW',
  1990,
  null,
  2012,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A England forward in the 2012-2025 window.', 'SAMPLE: Club path in this league window: Arsenal, Brighton & Hove Albion, Manchester United, Watford.', 'SAMPLE: 336 appearances, 74 goals, 37 assists (111 combined) in the logged window.', 'SAMPLE: Initials D.W. Surname shape length 7.']
),
(
  'f577332a',
  'andrew-robertson',
  true,
  'Andrew Robertson',
  'premier_league',
  'premier_league',
  array['Hull City', 'Liverpool'],
  'Scotland',
  'DF',
  1994,
  null,
  2014,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2014-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Scotland defender in the 2014-2025 window.', 'SAMPLE: Club path in this league window: Hull City, Liverpool.', 'SAMPLE: 332 appearances, 12 goals, 60 assists (72 combined) in the logged window.', 'SAMPLE: Initials A.R. Surname shape length 9.']
),
(
  '33db44a6',
  'willian',
  true,
  'Willian',
  'premier_league',
  'premier_league',
  array['Arsenal', 'Chelsea', 'Fulham'],
  'Brazil',
  'FW',
  1988,
  null,
  2013,
  2024,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2013-2024 league regular logged near the top of the appearances table.', 'SAMPLE: A Brazil forward in the 2013-2024 window.', 'SAMPLE: Club path in this league window: Arsenal, Chelsea, Fulham.', 'SAMPLE: 327 appearances, 47 goals, 52 assists (99 combined) in the logged window.', 'SAMPLE: Initials W. Surname shape length 7.']
),
(
  '6cf1b796',
  'alex-iwobi',
  true,
  'Alex Iwobi',
  'premier_league',
  'premier_league',
  array['Arsenal', 'Everton', 'Fulham'],
  'Nigeria',
  'FW',
  1996,
  null,
  2015,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2015-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Nigeria forward in the 2015-2025 window.', 'SAMPLE: Club path in this league window: Arsenal, Everton, Fulham.', 'SAMPLE: 320 appearances, 35 goals, 39 assists (74 combined) in the logged window.', 'SAMPLE: Initials A.I. Surname shape length 5.']
),
(
  'a31bc6fe',
  'seamus-coleman',
  true,
  'Séamus Coleman',
  'premier_league',
  'premier_league',
  array['Everton'],
  'Ireland',
  'DF',
  1988,
  null,
  2012,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Ireland defender in the 2012-2025 window.', 'SAMPLE: Club path in this league window: Everton.', 'SAMPLE: 319 appearances, 18 goals, 25 assists (43 combined) in the logged window.', 'SAMPLE: Initials S.C. Surname shape length 7.']
),
(
  '3faca398',
  'ben-davies',
  true,
  'Ben Davies',
  'premier_league',
  'premier_league',
  array['Swansea City', 'Tottenham Hotspur'],
  'Wales',
  'DF',
  1993,
  null,
  2012,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Wales defender in the 2012-2025 window.', 'SAMPLE: Club path in this league window: Swansea City, Tottenham Hotspur.', 'SAMPLE: 316 appearances, 11 goals, 20 assists (31 combined) in the logged window.', 'SAMPLE: Initials B.D. Surname shape length 6.']
),
(
  '1e9aeca7',
  'aaron-cresswell',
  true,
  'Aaron Cresswell',
  'premier_league',
  'premier_league',
  array['West Ham United'],
  'England',
  'DF',
  1989,
  null,
  2014,
  2024,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2014-2024 league regular logged near the top of the appearances table.', 'SAMPLE: A England defender in the 2014-2024 window.', 'SAMPLE: Club path in this league window: West Ham United.', 'SAMPLE: 312 appearances, 10 goals, 30 assists (40 combined) in the logged window.', 'SAMPLE: Initials A.C. Surname shape length 9.']
),
(
  'ca1f23b8',
  'christian-eriksen',
  true,
  'Christian Eriksen',
  'premier_league',
  'premier_league',
  array['Brentford', 'Manchester United', 'Tottenham Hotspur'],
  'Denmark',
  'MF',
  1992,
  null,
  2013,
  2024,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2013-2024 league regular logged near the top of the appearances table.', 'SAMPLE: A Denmark midfielder in the 2013-2024 window.', 'SAMPLE: Club path in this league window: Brentford, Manchester United, Tottenham Hotspur.', 'SAMPLE: 310 appearances, 55 goals, 83 assists (138 combined) in the logged window.', 'SAMPLE: Initials C.E. Surname shape length 7.']
),
(
  '61b63617',
  'adam-lallana',
  true,
  'Adam Lallana',
  'premier_league',
  'premier_league',
  array['Brighton & Hove Albion', 'Liverpool', 'Southampton'],
  'England',
  'MF',
  1988,
  null,
  2012,
  2024,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2024 league regular logged near the top of the appearances table.', 'SAMPLE: A England midfielder in the 2012-2024 window.', 'SAMPLE: Club path in this league window: Brighton & Hove Albion, Liverpool, Southampton.', 'SAMPLE: 305 appearances, 33 goals, 37 assists (70 combined) in the logged window.', 'SAMPLE: Initials A.L. Surname shape length 7.']
),
(
  '5d80f26a',
  'jordan-ayew',
  true,
  'Jordan Ayew',
  'premier_league',
  'premier_league',
  array['Aston Villa', 'Crystal Palace', 'Leicester City', 'Swansea City'],
  'Ghana',
  'FW',
  1991,
  null,
  2015,
  2024,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2015-2024 league regular logged near the top of the appearances table.', 'SAMPLE: A Ghana forward in the 2015-2024 window.', 'SAMPLE: Club path in this league window: Aston Villa, Crystal Palace, Leicester City, Swansea City.', 'SAMPLE: 305 appearances, 42 goals, 25 assists (67 combined) in the logged window.', 'SAMPLE: Initials J.A. Surname shape length 4.']
),
(
  'f95a18c3',
  'wilfried-zaha',
  true,
  'Wilfried Zaha',
  'premier_league',
  'premier_league',
  array['Cardiff City', 'Crystal Palace', 'Manchester United'],
  'Ivory Coast',
  'FW',
  1992,
  null,
  2013,
  2022,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2013-2022 league regular logged near the top of the appearances table.', 'SAMPLE: A Ivory Coast forward in the 2013-2022 window.', 'SAMPLE: Club path in this league window: Cardiff City, Crystal Palace, Manchester United.', 'SAMPLE: 305 appearances, 68 goals, 43 assists (111 combined) in the logged window.', 'SAMPLE: Initials W.Z. Surname shape length 4.']
),
(
  '5e7e26f4',
  'gylfi-sigurdsson',
  true,
  'Gylfi Sigurdsson',
  'premier_league',
  'premier_league',
  array['Everton', 'Swansea City', 'Tottenham Hotspur'],
  'Iceland',
  'MF',
  1989,
  null,
  2012,
  2020,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2020 league regular logged near the top of the appearances table.', 'SAMPLE: A Iceland midfielder in the 2012-2020 window.', 'SAMPLE: Club path in this league window: Everton, Swansea City, Tottenham Hotspur.', 'SAMPLE: 300 appearances, 60 goals, 47 assists (107 combined) in the logged window.', 'SAMPLE: Initials G.S. Surname shape length 10.']
),
(
  'f2280b76',
  'lewis-dunk',
  true,
  'Lewis Dunk',
  'premier_league',
  'premier_league',
  array['Brighton & Hove Albion'],
  'England',
  'DF',
  1991,
  null,
  2017,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2017-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A England defender in the 2017-2025 window.', 'SAMPLE: Club path in this league window: Brighton & Hove Albion.', 'SAMPLE: 299 appearances, 17 goals, 6 assists (23 combined) in the logged window.', 'SAMPLE: Initials L.D. Surname shape length 4.']
),
(
  'b4efe031',
  'ross-barkley',
  true,
  'Ross Barkley',
  'premier_league',
  'premier_league',
  array['Aston Villa', 'Chelsea', 'Everton', 'Luton Town'],
  'England',
  'MF',
  1993,
  null,
  2012,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A England midfielder in the 2012-2025 window.', 'SAMPLE: Club path in this league window: Aston Villa, Chelsea, Everton, Luton Town.', 'SAMPLE: 299 appearances, 40 goals, 37 assists (77 combined) in the logged window.', 'SAMPLE: Initials R.B. Surname shape length 7.']
),
(
  '3bf4363f',
  'luke-shaw',
  true,
  'Luke Shaw',
  'premier_league',
  'premier_league',
  array['Manchester United', 'Southampton'],
  'England',
  'DF',
  1995,
  null,
  2012,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A England defender in the 2012-2025 window.', 'SAMPLE: Club path in this league window: Manchester United, Southampton.', 'SAMPLE: 296 appearances, 4 goals, 20 assists (24 combined) in the logged window.', 'SAMPLE: Initials L.S. Surname shape length 4.']
),
(
  'a2003a9c',
  'craig-dawson',
  true,
  'Craig Dawson',
  'premier_league',
  'premier_league',
  array['Watford', 'West Bromwich Albion', 'West Ham United', 'Wolverhampton Wanderers'],
  'England',
  'DF',
  1990,
  null,
  2012,
  2024,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2024 league regular logged near the top of the appearances table.', 'SAMPLE: A England defender in the 2012-2024 window.', 'SAMPLE: Club path in this league window: Watford, West Bromwich Albion, West Ham United, Wolverhampton Wanderers.', 'SAMPLE: 295 appearances, 21 goals, 6 assists (27 combined) in the logged window.', 'SAMPLE: Initials C.D. Surname shape length 6.']
),
(
  '7210f713',
  'moussa-sissoko',
  true,
  'Moussa Sissoko',
  'premier_league',
  'premier_league',
  array['Newcastle United', 'Tottenham Hotspur', 'Watford'],
  'France',
  'MF',
  1989,
  null,
  2012,
  2021,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2021 league regular logged near the top of the appearances table.', 'SAMPLE: A France midfielder in the 2012-2021 window.', 'SAMPLE: Club path in this league window: Newcastle United, Tottenham Hotspur, Watford.', 'SAMPLE: 295 appearances, 16 goals, 26 assists (42 combined) in the logged window.', 'SAMPLE: Initials M.S. Surname shape length 7.']
),
(
  'e4435f16',
  'jonny-evans',
  true,
  'Jonny Evans',
  'premier_league',
  'premier_league',
  array['Leicester City', 'Manchester United', 'West Bromwich Albion'],
  'Northern Ireland',
  'DF',
  1988,
  null,
  2012,
  2024,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2024 league regular logged near the top of the appearances table.', 'SAMPLE: A Northern Ireland defender in the 2012-2024 window.', 'SAMPLE: Club path in this league window: Leicester City, Manchester United, West Bromwich Albion.', 'SAMPLE: 294 appearances, 13 goals, 11 assists (24 combined) in the logged window.', 'SAMPLE: Initials J.E. Surname shape length 5.']
),
(
  '422096dd',
  'andros-townsend',
  true,
  'Andros Townsend',
  'premier_league',
  'premier_league',
  array['Crystal Palace', 'Everton', 'Luton Town', 'Newcastle United', 'Queens Park Rangers', 'Tottenham Hotspur'],
  'England',
  'FW',
  1991,
  null,
  2012,
  2023,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2023 league regular logged near the top of the appearances table.', 'SAMPLE: A England forward in the 2012-2023 window.', 'SAMPLE: Club path in this league window: Crystal Palace, Everton, Luton Town, Newcastle United.', 'SAMPLE: 291 appearances, 26 goals, 38 assists (64 combined) in the logged window.', 'SAMPLE: Initials A.T. Surname shape length 8.']
),
(
  '53ea1b9d',
  'cheikhou-kouyate',
  true,
  'Cheikhou Kouyaté',
  'premier_league',
  'premier_league',
  array['Crystal Palace', 'Nottingham Forest', 'West Ham United'],
  'Senegal',
  'MF',
  1989,
  null,
  2014,
  2023,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2014-2023 league regular logged near the top of the appearances table.', 'SAMPLE: A Senegal midfielder in the 2014-2023 window.', 'SAMPLE: Club path in this league window: Crystal Palace, Nottingham Forest, West Ham United.', 'SAMPLE: 291 appearances, 15 goals, 14 assists (29 combined) in the logged window.', 'SAMPLE: Initials C.K. Surname shape length 7.']
),
(
  'c8d3270d',
  'harry-maguire',
  true,
  'Harry Maguire',
  'premier_league',
  'premier_league',
  array['Hull City', 'Leicester City', 'Manchester United'],
  'England',
  'DF',
  1993,
  null,
  2014,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2014-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A England defender in the 2014-2025 window.', 'SAMPLE: Club path in this league window: Hull City, Leicester City, Manchester United.', 'SAMPLE: 291 appearances, 15 goals, 12 assists (27 combined) in the logged window.', 'SAMPLE: Initials H.M. Surname shape length 7.']
),
(
  '1d83922e',
  'mark-noble',
  true,
  'Mark Noble',
  'premier_league',
  'premier_league',
  array['West Ham United'],
  'England',
  'MF',
  1987,
  null,
  2012,
  2021,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2021 league regular logged near the top of the appearances table.', 'SAMPLE: A England midfielder in the 2012-2021 window.', 'SAMPLE: Club path in this league window: West Ham United.', 'SAMPLE: 286 appearances, 33 goals, 25 assists (58 combined) in the logged window.', 'SAMPLE: Initials M.N. Surname shape length 5.']
),
(
  'd30af1c0',
  'michael-keane',
  true,
  'Michael Keane',
  'premier_league',
  'premier_league',
  array['Burnley', 'Everton', 'Manchester United'],
  'England',
  'DF',
  1993,
  null,
  2014,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2014-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A England defender in the 2014-2025 window.', 'SAMPLE: Club path in this league window: Burnley, Everton, Manchester United.', 'SAMPLE: 286 appearances, 19 goals, 11 assists (30 combined) in the logged window.', 'SAMPLE: Initials M.K. Surname shape length 5.']
),
(
  'c8c6fbed',
  'ashley-young',
  true,
  'Ashley Young',
  'premier_league',
  'premier_league',
  array['Aston Villa', 'Everton', 'Manchester United'],
  'England',
  'DF',
  1985,
  null,
  2012,
  2024,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2024 league regular logged near the top of the appearances table.', 'SAMPLE: A England defender in the 2012-2024 window.', 'SAMPLE: Club path in this league window: Aston Villa, Everton, Manchester United.', 'SAMPLE: 283 appearances, 11 goals, 30 assists (41 combined) in the logged window.', 'SAMPLE: Initials A.Y. Surname shape length 5.']
),
(
  'dac8aec2',
  'christian-benteke',
  true,
  'Christian Benteke',
  'premier_league',
  'premier_league',
  array['Aston Villa', 'Crystal Palace', 'Liverpool'],
  'Belgium',
  'FW',
  1990,
  null,
  2012,
  2021,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2021 league regular logged near the top of the appearances table.', 'SAMPLE: A Belgium forward in the 2012-2021 window.', 'SAMPLE: Club path in this league window: Aston Villa, Crystal Palace, Liverpool.', 'SAMPLE: 280 appearances, 86 goals, 23 assists (109 combined) in the logged window.', 'SAMPLE: Initials C.B. Surname shape length 7.']
),
(
  '157b0a4b',
  'jeffrey-schlupp',
  true,
  'Jeffrey Schlupp',
  'premier_league',
  'premier_league',
  array['Crystal Palace', 'Leicester City'],
  'Ghana',
  'MF',
  1992,
  null,
  2014,
  2024,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2014-2024 league regular logged near the top of the appearances table.', 'SAMPLE: A Ghana midfielder in the 2014-2024 window.', 'SAMPLE: Club path in this league window: Crystal Palace, Leicester City.', 'SAMPLE: 280 appearances, 22 goals, 19 assists (41 combined) in the logged window.', 'SAMPLE: Initials J.S. Surname shape length 7.']
),
(
  'a10a37c3',
  'abdoulaye-doucoure',
  true,
  'Abdoulaye Doucouré',
  'premier_league',
  'premier_league',
  array['Everton', 'Watford'],
  'Mali',
  'MF',
  1993,
  null,
  2016,
  2024,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2016-2024 league regular logged near the top of the appearances table.', 'SAMPLE: A Mali midfielder in the 2016-2024 window.', 'SAMPLE: Club path in this league window: Everton, Watford.', 'SAMPLE: 278 appearances, 36 goals, 25 assists (61 combined) in the logged window.', 'SAMPLE: Initials A.D. Surname shape length 8.']
),
(
  '20eef45e',
  'nathaniel-clyne',
  true,
  'Nathaniel Clyne',
  'premier_league',
  'premier_league',
  array['AFC Bournemouth', 'Crystal Palace', 'Liverpool', 'Southampton'],
  'England',
  'DF',
  1991,
  null,
  2012,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A England defender in the 2012-2025 window.', 'SAMPLE: Club path in this league window: AFC Bournemouth, Crystal Palace, Liverpool, Southampton.', 'SAMPLE: 278 appearances, 4 goals, 14 assists (18 combined) in the logged window.', 'SAMPLE: Initials N.C. Surname shape length 5.']
),
(
  '096c43f2',
  'kasper-schmeichel',
  true,
  'Kasper Schmeichel',
  'premier_league',
  'premier_league',
  array['Leicester City'],
  'Denmark',
  'GK',
  1986,
  null,
  2014,
  2021,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2014-2021 league regular logged near the top of the appearances table.', 'SAMPLE: A Denmark goalkeeper in the 2014-2021 window.', 'SAMPLE: Club path in this league window: Leicester City.', 'SAMPLE: 276 appearances, 0 goals, 0 assists (0 combined) in the logged window.', 'SAMPLE: Initials K.S. Surname shape length 10.']
),
(
  '50ed5719',
  'nathan-redmond',
  true,
  'Nathan Redmond',
  'premier_league',
  'premier_league',
  array['Burnley', 'Norwich City', 'Southampton'],
  'England',
  'FW',
  1994,
  null,
  2013,
  2023,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2013-2023 league regular logged near the top of the appearances table.', 'SAMPLE: A England forward in the 2013-2023 window.', 'SAMPLE: Club path in this league window: Burnley, Norwich City, Southampton.', 'SAMPLE: 276 appearances, 28 goals, 26 assists (54 combined) in the logged window.', 'SAMPLE: Initials N.R. Surname shape length 7.']
),
(
  '758d7cdd',
  'chris-wood',
  true,
  'Chris Wood',
  'premier_league',
  'premier_league',
  array['Burnley', 'Leicester City', 'Newcastle United', 'Nottingham Forest'],
  'New Zealand',
  'FW',
  1991,
  null,
  2014,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2014-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A New Zealand forward in the 2014-2025 window.', 'SAMPLE: Club path in this league window: Burnley, Leicester City, Newcastle United, Nottingham Forest.', 'SAMPLE: 275 appearances, 92 goals, 11 assists (103 combined) in the logged window.', 'SAMPLE: Initials C.W. Surname shape length 4.']
),
(
  '706e2b4b',
  'richarlison',
  true,
  'Richarlison',
  'premier_league',
  'premier_league',
  array['Everton', 'Tottenham Hotspur', 'Watford'],
  'Brazil',
  'FW',
  1997,
  null,
  2017,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2017-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Brazil forward in the 2017-2025 window.', 'SAMPLE: Club path in this league window: Everton, Tottenham Hotspur, Watford.', 'SAMPLE: 275 appearances, 75 goals, 31 assists (106 combined) in the logged window.', 'SAMPLE: Initials R. Surname shape length 11.']
),
(
  'd15637a1',
  'ben-foster',
  true,
  'Ben Foster',
  'premier_league',
  'premier_league',
  array['Watford', 'West Bromwich Albion'],
  'England',
  'GK',
  1983,
  null,
  2012,
  2021,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2021 league regular logged near the top of the appearances table.', 'SAMPLE: A England goalkeeper in the 2012-2021 window.', 'SAMPLE: Club path in this league window: Watford, West Bromwich Albion.', 'SAMPLE: 274 appearances, 0 goals, 1 assists (1 combined) in the logged window.', 'SAMPLE: Initials B.F. Surname shape length 6.']
),
(
  '14fc12ef',
  'dominic-calvert-lewin',
  true,
  'Dominic Calvert-Lewin',
  'premier_league',
  'premier_league',
  array['Everton', 'Leeds United'],
  'England',
  'FW',
  1997,
  null,
  2016,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2016-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A England forward in the 2016-2025 window.', 'SAMPLE: Club path in this league window: Everton, Leeds United.', 'SAMPLE: 274 appearances, 71 goals, 21 assists (92 combined) in the logged window.', 'SAMPLE: Initials D.C.L. Surname shape length 5.']
),
(
  'c59d830c',
  'eric-dier',
  true,
  'Eric Dier',
  'premier_league',
  'premier_league',
  array['Tottenham Hotspur'],
  'England',
  'DF',
  1994,
  null,
  2014,
  2023,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2014-2023 league regular logged near the top of the appearances table.', 'SAMPLE: A England defender in the 2014-2023 window.', 'SAMPLE: Club path in this league window: Tottenham Hotspur.', 'SAMPLE: 274 appearances, 12 goals, 9 assists (21 combined) in the logged window.', 'SAMPLE: Initials E.D. Surname shape length 4.']
),
(
  'bf6d16eb',
  'james-mcarthur',
  true,
  'James McArthur',
  'premier_league',
  'premier_league',
  array['Crystal Palace', 'Wigan Athletic'],
  'Scotland',
  'MF',
  1987,
  null,
  2012,
  2022,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2022 league regular logged near the top of the appearances table.', 'SAMPLE: A Scotland midfielder in the 2012-2022 window.', 'SAMPLE: Club path in this league window: Crystal Palace, Wigan Athletic.', 'SAMPLE: 274 appearances, 20 goals, 25 assists (45 combined) in the logged window.', 'SAMPLE: Initials J.M. Surname shape length 8.']
),
(
  '64e012bb',
  'adama-traore',
  true,
  'Adama Traoré',
  'premier_league',
  'premier_league',
  array['Aston Villa', 'Fulham', 'Middlesbrough', 'West Ham United', 'Wolverhampton Wanderers'],
  'Spain',
  'FW',
  1996,
  null,
  2015,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2015-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Spain forward in the 2015-2025 window.', 'SAMPLE: Club path in this league window: Aston Villa, Fulham, Middlesbrough, West Ham United.', 'SAMPLE: 271 appearances, 14 goals, 28 assists (42 combined) in the logged window.', 'SAMPLE: Initials A.T. Surname shape length 6.']
),
(
  'a035ba82',
  'callum-wilson',
  true,
  'Callum Wilson',
  'premier_league',
  'premier_league',
  array['AFC Bournemouth', 'Newcastle United', 'West Ham United'],
  'England',
  'FW',
  1992,
  null,
  2015,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2015-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A England forward in the 2015-2025 window.', 'SAMPLE: Club path in this league window: AFC Bournemouth, Newcastle United, West Ham United.', 'SAMPLE: 271 appearances, 95 goals, 28 assists (123 combined) in the logged window.', 'SAMPLE: Initials C.W. Surname shape length 6.']
),
(
  '4bbe6018',
  'michail-antonio',
  true,
  'Michail Antonio',
  'premier_league',
  'premier_league',
  array['West Ham United'],
  'Jamaica',
  'FW',
  1990,
  null,
  2015,
  2024,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2015-2024 league regular logged near the top of the appearances table.', 'SAMPLE: A Jamaica forward in the 2015-2024 window.', 'SAMPLE: Club path in this league window: West Ham United.', 'SAMPLE: 268 appearances, 68 goals, 39 assists (107 combined) in the logged window.', 'SAMPLE: Initials M.A. Surname shape length 7.']
),
(
  '48a301c8',
  'shane-long',
  true,
  'Shane Long',
  'premier_league',
  'premier_league',
  array['Hull City', 'Southampton', 'West Bromwich Albion'],
  'Ireland',
  'FW',
  1987,
  null,
  2012,
  2021,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2021 league regular logged near the top of the appearances table.', 'SAMPLE: A Ireland forward in the 2012-2021 window.', 'SAMPLE: Club path in this league window: Hull City, Southampton, West Bromwich Albion.', 'SAMPLE: 262 appearances, 43 goals, 27 assists (70 combined) in the logged window.', 'SAMPLE: Initials S.L. Surname shape length 4.']
),
(
  'adf0e0b0',
  'jay-rodriguez',
  true,
  'Jay Rodríguez',
  'premier_league',
  'premier_league',
  array['Burnley', 'Southampton', 'West Bromwich Albion'],
  'England',
  'FW',
  1989,
  null,
  2012,
  2023,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2023 league regular logged near the top of the appearances table.', 'SAMPLE: A England forward in the 2012-2023 window.', 'SAMPLE: Club path in this league window: Burnley, Southampton, West Bromwich Albion.', 'SAMPLE: 258 appearances, 46 goals, 21 assists (67 combined) in the logged window.', 'SAMPLE: Initials J.R. Surname shape length 9.']
),
(
  '3a68cdbb',
  'roberto-firmino',
  true,
  'Roberto Firmino',
  'premier_league',
  'premier_league',
  array['Liverpool'],
  'Brazil',
  'FW',
  1991,
  null,
  2015,
  2022,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2015-2022 league regular logged near the top of the appearances table.', 'SAMPLE: A Brazil forward in the 2015-2022 window.', 'SAMPLE: Club path in this league window: Liverpool.', 'SAMPLE: 256 appearances, 82 goals, 55 assists (137 combined) in the logged window.', 'SAMPLE: Initials R.F. Surname shape length 7.']
),
(
  '5be39868',
  'adam-smith',
  true,
  'Adam Smith',
  'premier_league',
  'premier_league',
  array['AFC Bournemouth'],
  'England',
  'DF',
  1991,
  null,
  2015,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2015-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A England defender in the 2015-2025 window.', 'SAMPLE: Club path in this league window: AFC Bournemouth.', 'SAMPLE: 255 appearances, 5 goals, 15 assists (20 combined) in the logged window.', 'SAMPLE: Initials A.S. Surname shape length 5.']
),
(
  'cbdec818',
  'idrissa-gueye',
  true,
  'Idrissa Gueye',
  'premier_league',
  'premier_league',
  array['Aston Villa', 'Everton'],
  'Senegal',
  'MF',
  1989,
  null,
  2015,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2015-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Senegal midfielder in the 2015-2025 window.', 'SAMPLE: Club path in this league window: Aston Villa, Everton.', 'SAMPLE: 254 appearances, 9 goals, 13 assists (22 combined) in the logged window.', 'SAMPLE: Initials I.G. Surname shape length 5.']
),
(
  'd30b9359',
  'pierre-emile-hjbjerg',
  true,
  'Pierre-Emile Højbjerg',
  'premier_league',
  'premier_league',
  array['Southampton', 'Tottenham Hotspur'],
  'Denmark',
  'MF',
  1995,
  null,
  2016,
  2023,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2016-2023 league regular logged near the top of the appearances table.', 'SAMPLE: A Denmark midfielder in the 2016-2023 window.', 'SAMPLE: Club path in this league window: Southampton, Tottenham Hotspur.', 'SAMPLE: 254 appearances, 12 goals, 16 assists (28 combined) in the logged window.', 'SAMPLE: Initials P.E.H. Surname shape length 8.']
),
(
  '522f07be',
  'ryan-bertrand',
  true,
  'Ryan Bertrand',
  'premier_league',
  'premier_league',
  array['Aston Villa', 'Chelsea', 'Leicester City', 'Southampton'],
  'England',
  'DF',
  1989,
  null,
  2012,
  2021,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2021 league regular logged near the top of the appearances table.', 'SAMPLE: A England defender in the 2012-2021 window.', 'SAMPLE: Club path in this league window: Aston Villa, Chelsea, Leicester City, Southampton.', 'SAMPLE: 254 appearances, 7 goals, 18 assists (25 combined) in the logged window.', 'SAMPLE: Initials R.B. Surname shape length 8.']
),
(
  '8abc8f20',
  'lucas-digne',
  true,
  'Lucas Digne',
  'premier_league',
  'premier_league',
  array['Aston Villa', 'Everton'],
  'France',
  'DF',
  1993,
  null,
  2018,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2018-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A France defender in the 2018-2025 window.', 'SAMPLE: Club path in this league window: Aston Villa, Everton.', 'SAMPLE: 253 appearances, 6 goals, 36 assists (42 combined) in the logged window.', 'SAMPLE: Initials L.D. Surname shape length 5.']
),
(
  '47b07978',
  'nathan-ake',
  true,
  'Nathan Aké',
  'premier_league',
  'premier_league',
  array['AFC Bournemouth', 'Chelsea', 'Manchester City', 'Watford'],
  'Netherlands',
  'DF',
  1995,
  null,
  2012,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Netherlands defender in the 2012-2025 window.', 'SAMPLE: Club path in this league window: AFC Bournemouth, Chelsea, Manchester City, Watford.', 'SAMPLE: 253 appearances, 18 goals, 9 assists (27 combined) in the logged window.', 'SAMPLE: Initials N.A. Surname shape length 3.']
),
(
  '905d79ef',
  'samir-nasri',
  true,
  'Samir Nasri',
  'premier_league',
  'premier_league',
  array['Manchester City', 'West Ham United'],
  'France',
  'MF',
  1987,
  null,
  2012,
  2018,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2018 league regular logged near the top of the appearances table.', 'SAMPLE: A France midfielder in the 2012-2018 window.', 'SAMPLE: Club path in this league window: Manchester City, West Ham United.', 'SAMPLE: 104 appearances, 13 goals, 27 assists (40 combined) in the logged window.', 'SAMPLE: Initials S.N. Surname shape length 5.']
),
(
  '20d53cd8',
  'dani-parejo',
  true,
  'Dani Parejo',
  'la_liga',
  'la_liga',
  array['Valencia', 'Villarreal'],
  'Spain',
  'MF',
  1989,
  null,
  2012,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Spain midfielder in the 2012-2025 window.', 'SAMPLE: Club path in this league window: Valencia, Villarreal.', 'SAMPLE: 473 appearances, 68 goals, 77 assists (145 combined) in the logged window.', 'SAMPLE: Initials D.P. Surname shape length 6.']
),
(
  'b8461ad2',
  'inaki-williams',
  true,
  'Iñaki Williams',
  'la_liga',
  'la_liga',
  array['Athletic Bilbao'],
  'Ghana',
  'FW',
  1994,
  null,
  2014,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2014-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Ghana forward in the 2014-2025 window.', 'SAMPLE: Club path in this league window: Athletic Bilbao.', 'SAMPLE: 407 appearances, 85 goals, 59 assists (144 combined) in the logged window.', 'SAMPLE: Initials I.W. Surname shape length 8.']
),
(
  '84b9c35c',
  'inigo-martinez',
  true,
  'Iñigo Martínez',
  'la_liga',
  'la_liga',
  array['Athletic Bilbao', 'Barcelona', 'Real Sociedad'],
  'Spain',
  'DF',
  1991,
  null,
  2012,
  2024,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2024 league regular logged near the top of the appearances table.', 'SAMPLE: A Spain defender in the 2012-2024 window.', 'SAMPLE: Club path in this league window: Athletic Bilbao, Barcelona, Real Sociedad.', 'SAMPLE: 379 appearances, 19 goals, 12 assists (31 combined) in the logged window.', 'SAMPLE: Initials I.M. Surname shape length 8.']
),
(
  '7750f016',
  'raul-garcia',
  true,
  'Raúl García',
  'la_liga',
  'la_liga',
  array['Athletic Bilbao', 'Atletico Madrid'],
  'Spain',
  'FW',
  1986,
  null,
  2012,
  2023,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2023 league regular logged near the top of the appearances table.', 'SAMPLE: A Spain forward in the 2012-2023 window.', 'SAMPLE: Club path in this league window: Athletic Bilbao, Atletico Madrid.', 'SAMPLE: 357 appearances, 79 goals, 33 assists (112 combined) in the logged window.', 'SAMPLE: Initials R.G. Surname shape length 6.']
),
(
  'd17eb0f9',
  'mikel-oyarzabal',
  true,
  'Mikel Oyarzabal',
  'la_liga',
  'la_liga',
  array['Real Sociedad'],
  'Spain',
  'FW',
  1997,
  null,
  2015,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2015-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Spain forward in the 2015-2025 window.', 'SAMPLE: Club path in this league window: Real Sociedad.', 'SAMPLE: 349 appearances, 100 goals, 54 assists (154 combined) in the logged window.', 'SAMPLE: Initials M.O. Surname shape length 9.']
),
(
  '2b140120',
  'ruben-garcia',
  true,
  'Rubén García',
  'la_liga',
  'la_liga',
  array['CA Osasuna', 'Levante UD'],
  'Spain',
  'FW',
  1993,
  null,
  2012,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Spain forward in the 2012-2025 window.', 'SAMPLE: Club path in this league window: CA Osasuna, Levante UD.', 'SAMPLE: 346 appearances, 32 goals, 33 assists (65 combined) in the logged window.', 'SAMPLE: Initials R.G. Surname shape length 6.']
),
(
  'de3e1d81',
  'iker-muniain',
  true,
  'Iker Muniain',
  'la_liga',
  'la_liga',
  array['Athletic Bilbao'],
  'Spain',
  'FW',
  1992,
  null,
  2012,
  2023,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2023 league regular logged near the top of the appearances table.', 'SAMPLE: A Spain forward in the 2012-2023 window.', 'SAMPLE: Club path in this league window: Athletic Bilbao.', 'SAMPLE: 340 appearances, 45 goals, 40 assists (85 combined) in the logged window.', 'SAMPLE: Initials I.M. Surname shape length 7.']
),
(
  '4a1b04ce',
  'angel-correa',
  true,
  'Ángel Correa',
  'la_liga',
  'la_liga',
  array['Atletico Madrid'],
  'Argentina',
  'FW',
  1995,
  null,
  2015,
  2024,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2015-2024 league regular logged near the top of the appearances table.', 'SAMPLE: A Argentina forward in the 2015-2024 window.', 'SAMPLE: Club path in this league window: Atletico Madrid.', 'SAMPLE: 335 appearances, 68 goals, 43 assists (111 combined) in the logged window.', 'SAMPLE: Initials Á.C. Surname shape length 6.']
),
(
  'cf737a1b',
  'jose-luis-morales',
  true,
  'José Luis Morales',
  'la_liga',
  'la_liga',
  array['Levante UD', 'Villarreal'],
  'Spain',
  'FW',
  1987,
  null,
  2014,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2014-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Spain forward in the 2014-2025 window.', 'SAMPLE: Club path in this league window: Levante UD, Villarreal.', 'SAMPLE: 332 appearances, 77 goals, 34 assists (111 combined) in the logged window.', 'SAMPLE: Initials J.L.M. Surname shape length 7.']
),
(
  '3fc2c7a1',
  'sergio-canales',
  true,
  'Sergio Canales',
  'la_liga',
  'la_liga',
  array['Real Betis Balompié', 'Real Sociedad', 'Valencia'],
  'Spain',
  'MF',
  1991,
  null,
  2012,
  2022,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2022 league regular logged near the top of the appearances table.', 'SAMPLE: A Spain midfielder in the 2012-2022 window.', 'SAMPLE: Club path in this league window: Real Betis Balompié, Real Sociedad, Valencia.', 'SAMPLE: 331 appearances, 42 goals, 44 assists (86 combined) in the logged window.', 'SAMPLE: Initials S.C. Surname shape length 7.']
),
(
  '5be82746',
  'saul-niguez',
  true,
  'Saúl Ñíguez',
  'la_liga',
  'la_liga',
  array['Atletico Madrid', 'Rayo Vallecano', 'Sevilla'],
  'Spain',
  'MF',
  1994,
  null,
  2012,
  2024,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2024 league regular logged near the top of the appearances table.', 'SAMPLE: A Spain midfielder in the 2012-2024 window.', 'SAMPLE: Club path in this league window: Atletico Madrid, Rayo Vallecano, Sevilla.', 'SAMPLE: 329 appearances, 29 goals, 26 assists (55 combined) in the logged window.', 'SAMPLE: Initials S.Ñ. Surname shape length 6.']
),
(
  '68ebfdba',
  'kike-garcia',
  true,
  'Kike García',
  'la_liga',
  'la_liga',
  array['CA Osasuna', 'Deportivo Alavés', 'RCD Espanyol Barcelona', 'SD Eibar'],
  'Spain',
  'FW',
  1989,
  null,
  2016,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2016-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Spain forward in the 2016-2025 window.', 'SAMPLE: Club path in this league window: CA Osasuna, Deportivo Alavés, RCD Espanyol Barcelona, SD Eibar.', 'SAMPLE: 326 appearances, 66 goals, 12 assists (78 combined) in the logged window.', 'SAMPLE: Initials K.G. Surname shape length 6.']
),
(
  '334e9439',
  'gerard-moreno',
  true,
  'Gerard Moreno',
  'la_liga',
  'la_liga',
  array['RCD Espanyol Barcelona', 'Villarreal'],
  'Spain',
  'FW',
  1992,
  null,
  2015,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2015-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Spain forward in the 2015-2025 window.', 'SAMPLE: Club path in this league window: RCD Espanyol Barcelona, Villarreal.', 'SAMPLE: 317 appearances, 124 goals, 36 assists (160 combined) in the logged window.', 'SAMPLE: Initials G.M. Surname shape length 6.']
),
(
  '6c9ba48d',
  'moi-gomez',
  true,
  'Moi Gómez',
  'la_liga',
  'la_liga',
  array['CA Osasuna', 'Getafe', 'SD Huesca', 'Sporting Gijón', 'Villarreal'],
  'Spain',
  'MF',
  1994,
  null,
  2013,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2013-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Spain midfielder in the 2013-2025 window.', 'SAMPLE: Club path in this league window: CA Osasuna, Getafe, SD Huesca, Sporting Gijón.', 'SAMPLE: 317 appearances, 25 goals, 34 assists (59 combined) in the logged window.', 'SAMPLE: Initials M.G. Surname shape length 5.']
),
(
  '968dd42f',
  'jose-gaya',
  true,
  'José Gayà',
  'la_liga',
  'la_liga',
  array['Valencia'],
  'Spain',
  'DF',
  1995,
  null,
  2013,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2013-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Spain defender in the 2013-2025 window.', 'SAMPLE: Club path in this league window: Valencia.', 'SAMPLE: 310 appearances, 8 goals, 32 assists (40 combined) in the logged window.', 'SAMPLE: Initials J.G. Surname shape length 4.']
),
(
  '869c708a',
  'lucas-vazquez',
  true,
  'Lucas Vázquez',
  'la_liga',
  'la_liga',
  array['RCD Espanyol Barcelona', 'Real Madrid'],
  'Spain',
  'DF',
  1991,
  null,
  2014,
  2024,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2014-2024 league regular logged near the top of the appearances table.', 'SAMPLE: A Spain defender in the 2014-2024 window.', 'SAMPLE: Club path in this league window: RCD Espanyol Barcelona, Real Madrid.', 'SAMPLE: 310 appearances, 29 goals, 56 assists (85 combined) in the logged window.', 'SAMPLE: Initials L.V. Surname shape length 7.']
),
(
  '5154b7fd',
  'david-soria',
  true,
  'David Soria',
  'la_liga',
  'la_liga',
  array['Getafe', 'Sevilla'],
  'Spain',
  'GK',
  1993,
  null,
  2016,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2016-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Spain goalkeeper in the 2016-2025 window.', 'SAMPLE: Club path in this league window: Getafe, Sevilla.', 'SAMPLE: 309 appearances, 0 goals, 0 assists (0 combined) in the logged window.', 'SAMPLE: Initials D.S. Surname shape length 5.']
),
(
  'a281ac71',
  'hugo-mallo',
  true,
  'Hugo Mallo',
  'la_liga',
  'la_liga',
  array['Celta de Vigo'],
  'Spain',
  'DF',
  1991,
  null,
  2012,
  2022,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2012-2022 league regular logged near the top of the appearances table.', 'SAMPLE: A Spain defender in the 2012-2022 window.', 'SAMPLE: Club path in this league window: Celta de Vigo.', 'SAMPLE: 309 appearances, 9 goals, 22 assists (31 combined) in the logged window.', 'SAMPLE: Initials H.M. Surname shape length 5.']
),
(
  '17138ca1',
  'dimitri-foulquier',
  true,
  'Dimitri Foulquier',
  'la_liga',
  'la_liga',
  array['Getafe', 'Granada', 'Valencia'],
  'Guadeloupe',
  'DF',
  1993,
  null,
  2013,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2013-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Guadeloupe defender in the 2013-2025 window.', 'SAMPLE: Club path in this league window: Getafe, Granada, Valencia.', 'SAMPLE: 306 appearances, 5 goals, 16 assists (21 combined) in the logged window.', 'SAMPLE: Initials D.F. Surname shape length 9.']
),
(
  '3eba3146',
  'damian-suarez',
  true,
  'Damián Suárez',
  'la_liga',
  'la_liga',
  array['Elche', 'Getafe'],
  'Uruguay',
  'DF',
  1988,
  null,
  2013,
  2023,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2013-2023 league regular logged near the top of the appearances table.', 'SAMPLE: A Uruguay defender in the 2013-2023 window.', 'SAMPLE: Club path in this league window: Elche, Getafe.', 'SAMPLE: 305 appearances, 6 goals, 22 assists (28 combined) in the logged window.', 'SAMPLE: Initials D.S. Surname shape length 6.']
),
(
  'bff5d315',
  'dani-garcia',
  true,
  'Dani García',
  'la_liga',
  'la_liga',
  array['Athletic Bilbao', 'SD Eibar'],
  'Spain',
  'MF',
  1990,
  null,
  2014,
  2023,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2014-2023 league regular logged near the top of the appearances table.', 'SAMPLE: A Spain midfielder in the 2014-2023 window.', 'SAMPLE: Club path in this league window: Athletic Bilbao, SD Eibar.', 'SAMPLE: 303 appearances, 3 goals, 9 assists (12 combined) in the logged window.', 'SAMPLE: Initials D.G. Surname shape length 6.']
),
(
  'becb7b71',
  'daniel-carvajal',
  true,
  'Daniel Carvajal',
  'la_liga',
  'la_liga',
  array['Real Madrid'],
  'Spain',
  'DF',
  1992,
  null,
  2013,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2013-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Spain defender in the 2013-2025 window.', 'SAMPLE: Club path in this league window: Real Madrid.', 'SAMPLE: 303 appearances, 10 goals, 37 assists (47 combined) in the logged window.', 'SAMPLE: Initials D.C. Surname shape length 8.']
),
(
  '52ea255c',
  'portu',
  true,
  'Portu',
  'la_liga',
  'la_liga',
  array['Getafe', 'Girona', 'Real Sociedad', 'Valencia'],
  'Spain',
  'FW',
  1992,
  null,
  2013,
  2025,
  array[]::integer[],
  array[]::text[],
  array['SAMPLE: A 2013-2025 league regular logged near the top of the appearances table.', 'SAMPLE: A Spain forward in the 2013-2025 window.', 'SAMPLE: Club path in this league window: Getafe, Girona, Real Sociedad, Valencia.', 'SAMPLE: 288 appearances, 44 goals, 31 assists (75 combined) in the logged window.', 'SAMPLE: Initials P. Surname shape length 5.']
)
on conflict (id) do update set
  person_id = excluded.person_id,
  canonical = excluded.canonical,
  name = excluded.name,
  category = excluded.category,
  league = excluded.league,
  clubs = excluded.clubs,
  nationality = excluded.nationality,
  position = excluded.position,
  birth_year = excluded.birth_year,
  shirt_number = excluded.shirt_number,
  era_start = excluded.era_start,
  era_end = excluded.era_end,
  world_cup_editions = excluded.world_cup_editions,
  aliases = excluded.aliases,
  clues = excluded.clues;

