-- Batch 5/6: rows 321-400 of 407
-- Paste into Supabase SQL Editor and Run (in order 01 → 06)
insert into public.players (
  id, person_id, canonical, name, category, league, clubs,
  nationality, position, birth_year, shirt_number, era_start, era_end,
  world_cup_editions, aliases, clues
) values
(
  '59bec0e1',
  'angel-di-maria',
  false,
  'Angel Di Maria',
  'ligue_1',
  'ligue_1',
  array['Paris Saint-Germain'],
  'Argentina',
  'MF',
  1988,
  11,
  2015,
  2022,
  array[]::integer[],
  array['Fideo'],
  array['The record assist import who saved his best for Le Classique.', 'An Argentine winger of curled crosses and cup final goals.', 'United rescue to Paris'' creative decade.', 'Repeated finals decided by his left foot.', 'Fideo. Initials A.D.M.']
),
(
  '090d5bf9',
  'gianluigi-donnarumma',
  false,
  'Gianluigi Donnarumma',
  'ligue_1',
  'ligue_1',
  array['Paris Saint-Germain'],
  'Italy',
  'GK',
  1999,
  99,
  2021,
  2026,
  array[]::integer[],
  array['Gigio'],
  array['He arrived on a free after a Euro final shootout and kept Paris'' goal through a Champions League triumph.', 'An Italian goalkeeper of enormous frame and bigger nights.', 'Milan''s storm exit to Paris'' wall.', 'The 2025 Champions League title run''s penalty heroics.', 'Gigio. Initials G.D.']
),
(
  '3cb52e22',
  'achraf-hakimi',
  false,
  'Achraf Hakimi',
  'ligue_1',
  'ligue_1',
  array['Paris Saint-Germain'],
  'Morocco',
  'DF',
  1998,
  2,
  2021,
  2026,
  array[]::integer[],
  array[]::text[],
  array['The league''s best right back plays like its best right winger.', 'A Moroccan defender of relentless overlaps.', 'Inter''s title to Paris'' flank.', 'The 2025 treble season, attacking from full back.', 'Initials A.H.']
),
(
  '5940843f',
  'ousmane-dembele',
  false,
  'Ousmane Dembele',
  'ligue_1',
  'ligue_1',
  array['Paris Saint-Germain', 'Rennes'],
  'France',
  'FW',
  1997,
  10,
  2015,
  2026,
  array[]::integer[],
  array[]::text[],
  array['Written off for years, then a Ballon d''Or campaign as a Paris striker.', 'A French forward reborn through the middle.', 'Rennes teen, the Barcelona saga, the Paris peak.', 'The 2024-25 season, 30 plus goals and the golden ball.', 'Initials O.D.']
),
(
  '408e13e7',
  'vitinha',
  true,
  'Vitinha',
  'ligue_1',
  'ligue_1',
  array['Paris Saint-Germain'],
  'Portugal',
  'MF',
  2000,
  17,
  2022,
  2026,
  array[]::integer[],
  array[]::text[],
  array['Small, press proof, and suddenly the best midfielder in Europe''s conversations.', 'A Portuguese midfielder running Paris'' new machine.', 'Porto to the post Messi rebuild''s brain.', 'The 2025 Champions League triumph''s midfield masterclass.', 'Initials V.']
),
(
  '40e80456',
  'warren-zaire-emery',
  true,
  'Warren Zaire-Emery',
  'ligue_1',
  'ligue_1',
  array['Paris Saint-Germain'],
  'France',
  'MF',
  2006,
  33,
  2022,
  2026,
  array[]::integer[],
  array[]::text[],
  array['A PSG debutant at sixteen, France international at seventeen.', 'A French midfielder who skipped adolescence professionally.', 'Academy to youngest everything records.', 'Debuting at 16 years 151 days, club record.', 'Initials W.Z.E.']
),
(
  'dee70b3c',
  'bradley-barcola',
  true,
  'Bradley Barcola',
  'ligue_1',
  'ligue_1',
  array['Paris Saint-Germain', 'Lyon'],
  'France',
  'FW',
  2002,
  29,
  2021,
  2026,
  array[]::integer[],
  array[]::text[],
  array['Lyon''s kid crossed the rivalry line and became a champion''s winger.', 'A French forward of straight line menace.', 'Lyon academy to Paris'' front line.', 'The 2024-25 title season breakout.', 'Initials B.B.']
),
(
  '3eb8e9bf',
  'khvicha-kvaratskhelia',
  false,
  'Khvicha Kvaratskhelia',
  'ligue_1',
  'ligue_1',
  array['Paris Saint-Germain'],
  'Georgia',
  'FW',
  2001,
  7,
  2025,
  2026,
  array[]::integer[],
  array['Kvara'],
  array['Naples'' beloved Georgian chose Paris mid season and won the biggest prize months later.', 'A Georgian winger of feints imported at a premium.', 'Napoli''s title hero to PSG''s January statement.', 'Arriving January 2025, Champions League by May.', 'Kvara. Initials K.K.']
),
(
  'b4e26066',
  'pauleta',
  true,
  'Pauleta',
  'ligue_1',
  'ligue_1',
  array['Paris Saint-Germain', 'Bordeaux'],
  'Portugal',
  'FW',
  1973,
  9,
  2000,
  2008,
  array[]::integer[],
  array['The Eagle of the Azores'],
  array['The Eagle of the Azores was PSG''s record scorer before the money arrived.', 'A Portuguese striker who carried pre Qatar Paris.', 'Bordeaux''s golden boot to Paris'' old king.', 'Club record scorer until a Uruguayan passed him.', 'Initials P.']
),
(
  'c14b066a',
  'ronaldinho',
  false,
  'Ronaldinho',
  'ligue_1',
  'ligue_1',
  array['Paris Saint-Germain'],
  'Brazil',
  'MF',
  1980,
  21,
  2001,
  2003,
  array[]::integer[],
  array['Dinho'],
  array['Two Paris years of nutmegs and nightlife before Barcelona made him god.', 'A Brazilian magician in his mischievous apprenticeship.', 'Gremio to the Parc''s first glimpse of genius.', 'The 2002-03 season Le Classique solo masterpieces.', 'Dinho. Initials R.']
),
(
  '2066d51e',
  'youri-djorkaeff',
  true,
  'Youri Djorkaeff',
  'ligue_1',
  'ligue_1',
  array['Paris Saint-Germain', 'Monaco'],
  'France',
  'MF',
  1968,
  null,
  1992,
  1996,
  array[]::integer[],
  array['The Snake'],
  array['The Snake struck for PSG''s mid nineties European adventures.', 'A French forward of angles nobody else saw.', 'Monaco to PSG before Italian glory.', 'The 1996 Cup Winners Cup run.', 'The Snake. Initials Y.D.']
),
(
  '48adedfc',
  'nicolas-anelka',
  true,
  'Nicolas Anelka',
  'ligue_1',
  'ligue_1',
  array['Paris Saint-Germain'],
  'France',
  'FW',
  1979,
  9,
  1996,
  2005,
  array[]::integer[],
  array[]::text[],
  array['Sold by PSG as a teen, bought back for a fortune, the original transfer saga.', 'A French striker whose career was a world tour with a Paris hub.', 'Academy exit, Madrid detour, record return.', 'The 2000 return for 220 million francs.', 'Le Sulk. Initials N.A.']
),
(
  'd42caef0',
  'juninho-pernambucano',
  true,
  'Juninho Pernambucano',
  'ligue_1',
  'ligue_1',
  array['Lyon'],
  'Brazil',
  'MF',
  1975,
  8,
  2001,
  2009,
  array[]::integer[],
  array['The Free-Kick King'],
  array['The greatest free kick taker who ever lived, and seven straight titles to frame it.', 'A Brazilian midfielder whose knuckleballs invented a technique.', 'Vasco to Lyon''s dynasty conductor.', '44 direct free kicks, each one a physics paper.', 'Initials J.P.']
),
(
  '0c978a00',
  'karim-benzema',
  false,
  'Karim Benzema',
  'ligue_1',
  'ligue_1',
  array['Lyon'],
  'France',
  'FW',
  1987,
  10,
  2004,
  2009,
  array[]::integer[],
  array[]::text[],
  array['Lyon''s academy jewel fired the last title of the dynasty at 20.', 'A French striker announcing himself before the white shirt called.', 'Bron boy to Lyon''s number ten.', 'The 2008 title, 20 goals as a kid.', 'Initials K.B.']
),
(
  'db74a3da',
  'alexandre-lacazette',
  true,
  'Alexandre Lacazette',
  'ligue_1',
  'ligue_1',
  array['Lyon'],
  'France',
  'FW',
  1991,
  10,
  2009,
  2026,
  array[]::integer[],
  array[]::text[],
  array['Lyon''s boy came home from London to wear the armband again.', 'A French striker, academy made, twice the club''s talisman.', 'OL academy, Arsenal years, the return.', 'The 2014-15 season, 27 goals and top scorer.', 'Initials A.L.']
),
(
  'c22a9a3b',
  'sonny-anderson',
  true,
  'Sonny Anderson',
  'ligue_1',
  'ligue_1',
  array['Lyon', 'Monaco', 'Marseille'],
  'Brazil',
  'FW',
  1970,
  9,
  1993,
  2003,
  array[]::integer[],
  array[]::text[],
  array['Lyon paid a club record for the striker who taught them to win it all.', 'A Brazilian forward bridging Monaco flair and Lyon''s first titles.', 'Monaco to Barcelona to Lyon''s first crowns.', 'The 2002 first ever title, his goals founding a dynasty.', 'Initials S.A.']
),
(
  '548bb996',
  'sidney-govou',
  true,
  'Sidney Govou',
  'ligue_1',
  'ligue_1',
  array['Lyon'],
  'France',
  'FW',
  1979,
  14,
  1999,
  2010,
  array[]::integer[],
  array[]::text[],
  array['A one club flyer through all seven of Lyon''s consecutive titles.', 'A French winger of pace and derby goals.', 'Lyon academy through the entire dynasty.', 'All seven titles, 2002 to 2008.', 'Initials S.G.']
),
(
  'd9c04429',
  'gregory-coupet',
  true,
  'Gregory Coupet',
  'ligue_1',
  'ligue_1',
  array['Lyon', 'Saint-Etienne'],
  'France',
  'GK',
  1972,
  1,
  1993,
  2011,
  array[]::integer[],
  array[]::text[],
  array['The safest hands of the dynasty years, robbed of World Cups by one man.', 'A French goalkeeper of spectacular reflex saves.', 'Saint Etienne to Lyon''s seven straight.', 'The impossible triple save against Sochaux.', 'Initials G.C.']
),
(
  '6cb546c3',
  'memphis-depay',
  true,
  'Memphis Depay',
  'ligue_1',
  'ligue_1',
  array['Lyon'],
  'Netherlands',
  'FW',
  1994,
  10,
  2017,
  2021,
  array[]::integer[],
  array[]::text[],
  array['United''s misfit became Lyon''s captain, poet and penalty king.', 'A Dutch forward who rebuilt his career in French freedom.', 'Manchester exit to Lyon''s main character.', 'The 2020 Champions League semifinal run as leader.', 'Initials M.D.']
),
(
  '81ca8183',
  'nabil-fekir',
  true,
  'Nabil Fekir',
  'ligue_1',
  'ligue_1',
  array['Lyon'],
  'France',
  'MF',
  1993,
  18,
  2013,
  2019,
  array[]::integer[],
  array[]::text[],
  array['A World Cup winner whose Lyon derby celebrations needed police escorts.', 'A French playmaker of low center and high nerve.', 'Lyon academy to captain.', 'The 2017 derby shirt celebration in front of the Saint Etienne kop.', 'Initials N.F.']
),
(
  'd92a1653',
  'rayan-cherki',
  true,
  'Rayan Cherki',
  'ligue_1',
  'ligue_1',
  array['Lyon'],
  'France',
  'MF',
  2003,
  18,
  2019,
  2025,
  array[]::integer[],
  array[]::text[],
  array['Lyon''s academy conjurer, two footed to the point of ambidexterity debates.', 'A French playmaker of no look everything.', 'OL''s youngest ever debutant lineage.', 'The 2024-25 breakout of assists and audacity.', 'Initials R.C.']
),
(
  '6d3bc58e',
  'didier-drogba',
  false,
  'Didier Drogba',
  'ligue_1',
  'ligue_1',
  array['Marseille', 'Guingamp', 'Le Mans'],
  'Ivory Coast',
  'FW',
  1978,
  11,
  1998,
  2004,
  array[]::integer[],
  array[]::text[],
  array['Le Classique of 2003-04 belonged to Marseille''s one season wonder before England called.', 'An Ivorian striker whose single Marseille year became legend.', 'Guingamp''s late bloomer to the Velodrome''s fire.', 'The 2004 UEFA Cup final run, 32 goals that season.', 'Initials D.D.']
),
(
  '6cf10c15',
  'dimitri-payet',
  true,
  'Dimitri Payet',
  'ligue_1',
  'ligue_1',
  array['Marseille', 'Saint-Etienne', 'Lille', 'Nantes'],
  'France',
  'MF',
  1987,
  10,
  2005,
  2022,
  array[]::integer[],
  array[]::text[],
  array['The Velodrome''s free kick artist chose Marseille over everything, twice.', 'A French playmaker of whipped dead balls and second acts.', 'Nantes to West Ham to Marseille''s heart.', 'The 2018 Europa League final run as captain.', 'Initials D.P.']
),
(
  'f9d08c4a',
  'andre-pierre-gignac',
  true,
  'Andre-Pierre Gignac',
  'ligue_1',
  'ligue_1',
  array['Marseille', 'Toulouse', 'Lorient'],
  'France',
  'FW',
  1985,
  10,
  2004,
  2015,
  array[]::integer[],
  array['Dede'],
  array['The Velodrome sang his name to the tune everyone knows, before Mexico deified him.', 'A French striker of touch surprising for the frame.', 'Toulouse to Marseille''s spearhead.', 'The 2010s Marseille years before the Tigres legend.', 'Dede. Initials A.P.G.']
),
(
  'd04d0455',
  'mamadou-niang',
  true,
  'Mamadou Niang',
  'ligue_1',
  'ligue_1',
  array['Marseille', 'Strasbourg'],
  'Senegal',
  'FW',
  1979,
  11,
  2002,
  2011,
  array[]::integer[],
  array[]::text[],
  array['Marseille''s captain and top scorer of the 2010 title, their first in 18 years.', 'A Senegalese striker of penalty box certainty.', 'Strasbourg to the Velodrome armband.', 'The 2010 title, captain and leading scorer.', 'Initials M.N.']
),
(
  'dd1054a3',
  'steve-mandanda',
  true,
  'Steve Mandanda',
  'ligue_1',
  'ligue_1',
  array['Marseille', 'Rennes'],
  'France',
  'GK',
  1985,
  30,
  2007,
  2024,
  array[]::integer[],
  array['Il Fenomeno'],
  array['Il Fenomeno of Marseille, record appearance holder across two spells.', 'A French goalkeeper of quiet excellence for 15 years.', 'Le Havre to 600 plus Marseille games.', 'The 2010 title behind Deschamps'' champions.', 'Il Fenomeno. Initials S.M.']
),
(
  'aa9ad0f7',
  'florian-thauvin',
  true,
  'Florian Thauvin',
  'ligue_1',
  'ligue_1',
  array['Marseille', 'Bastia'],
  'France',
  'FW',
  1993,
  26,
  2013,
  2021,
  array[]::integer[],
  array[]::text[],
  array['A World Cup winner''s medal and a 26 goal season at the Velodrome.', 'A French winger, left foot loaded, redemption arc complete.', 'Bastia to Marseille via a Newcastle nightmare.', 'The 2017-18 season, 26 goals from the right.', 'Initials F.T.']
),
(
  '2d9085d1',
  'pierre-emerick-aubameyang',
  false,
  'Pierre-Emerick Aubameyang',
  'ligue_1',
  'ligue_1',
  array['Marseille', 'Saint-Etienne', 'Lille', 'Monaco'],
  'Gabon',
  'FW',
  1989,
  10,
  2008,
  2025,
  array[]::integer[],
  array['Auba'],
  array['He returned to France at 34 and out scored the kids for Marseille.', 'A Gabonese striker whose French chapters bookend his story.', 'Saint Etienne''s flyer, the world tour, the Marseille encore.', 'The 2023-24 Europa League campaign, 30 goals at 34.', 'Auba. Initials P.E.A.']
),
(
  'e4d7c2de',
  'thierry-henry',
  false,
  'Thierry Henry',
  'ligue_1',
  'ligue_1',
  array['Monaco'],
  'France',
  'FW',
  1977,
  12,
  1994,
  1999,
  array[]::integer[],
  array['Titi'],
  array['The league watched a teenage winger win the title before the world renamed him a striker.', 'A French kid of pace and promise in red and white diagonal.', 'Monaco''s academy to the 1997 crown.', 'The 1996-97 title as the league''s best young player.', 'Titi. Initials T.H.']
),
(
  'be5c47a0',
  'david-trezeguet',
  true,
  'David Trezeguet',
  'ligue_1',
  'ligue_1',
  array['Monaco'],
  'France',
  'FW',
  1977,
  17,
  1995,
  2000,
  array[]::integer[],
  array['Trezegol'],
  array['Monaco''s other teenage striker hit the hardest shot the league had measured.', 'A French forward of penalty box economy.', 'Argentina raised, Monaco made.', 'The 1998 golden goal generation''s Monaco years.', 'Trezegol. Initials D.T.']
),
(
  '5958129c',
  'fabien-barthez',
  false,
  'Fabien Barthez',
  'ligue_1',
  'ligue_1',
  array['Monaco', 'Marseille', 'Toulouse'],
  'France',
  'GK',
  1971,
  16,
  1992,
  2007,
  array[]::integer[],
  array[]::text[],
  array['A Champions League with Marseille at 21, and titles either side of the bald head kisses.', 'A French goalkeeper of chaos and charisma.', 'Marseille''s 93 miracle to Monaco''s titles.', 'The 1993 Champions League, France''s only ever.', 'Initials F.B.']
),
(
  'cbdf60a7',
  'emmanuel-petit',
  true,
  'Emmanuel Petit',
  'ligue_1',
  'ligue_1',
  array['Monaco'],
  'France',
  'MF',
  1970,
  17,
  1992,
  1997,
  array[]::integer[],
  array[]::text[],
  array['Monaco''s ponytailed defender turned midfielder before Wenger called him to London.', 'A French midfielder of long strides and longer passes.', 'Monaco''s academy through the 1997 title.', 'The Monaco years that built the 98 world champion.', 'Initials E.P.']
),
(
  '65847cf1',
  'radamel-falcao',
  false,
  'Radamel Falcao',
  'ligue_1',
  'ligue_1',
  array['Monaco'],
  'Colombia',
  'FW',
  1986,
  9,
  2013,
  2019,
  array[]::integer[],
  array['El Tigre'],
  array['Monaco bought the world''s deadliest striker, and for one autumn he was exactly that.', 'A Colombian nine of movement and menace before the knee.', 'Atletico to the principality''s statement signing.', 'The 2013-14 autumn, a goal a game until January.', 'El Tigre. Initials R.F.']
),
(
  '0876de58',
  'james-rodriguez',
  false,
  'James Rodriguez',
  'ligue_1',
  'ligue_1',
  array['Monaco'],
  'Colombia',
  'MF',
  1991,
  10,
  2013,
  2014,
  array[]::integer[],
  array[]::text[],
  array['One Monaco season of outside foot passes bought him a World Cup stage.', 'A Colombian playmaker of velvet delivery.', 'Porto to Monaco''s project''s jewel.', 'The 2013-14 season that priced him for Madrid.', 'Initials J.R.']
),
(
  'bb22340f',
  'bernardo-silva',
  true,
  'Bernardo Silva',
  'ligue_1',
  'ligue_1',
  array['Monaco'],
  'Portugal',
  'MF',
  1994,
  10,
  2014,
  2017,
  array[]::integer[],
  array[]::text[],
  array['Monaco''s tiny winger ran the title miracle that toppled Paris.', 'A Portuguese midfielder of infinite touches.', 'Benfica reserve to Monaco''s 2017 crown.', 'The 2016-17 title, dancing through the money.', 'Initials B.S.']
),
(
  '1ac753d0',
  'fabinho',
  true,
  'Fabinho',
  'ligue_1',
  'ligue_1',
  array['Monaco'],
  'Brazil',
  'MF',
  1993,
  2,
  2013,
  2018,
  array[]::integer[],
  array[]::text[],
  array['A right back converted to the league''s best six during Monaco''s miracle.', 'A Brazilian midfielder of interceptions and calm.', 'Rio reserve teams to Monaco''s spine.', 'The 2017 title season as the destroyer.', 'Initials F.']
),
(
  '61e20734',
  'aurelien-tchouameni',
  true,
  'Aurelien Tchouameni',
  'ligue_1',
  'ligue_1',
  array['Monaco', 'Bordeaux'],
  'France',
  'MF',
  2000,
  8,
  2019,
  2022,
  array[]::integer[],
  array[]::text[],
  array['Bordeaux''s teen became Monaco''s midfield colossus before the record Madrid bid.', 'A French midfielder of recovery range and press resistance.', 'Bordeaux to Monaco''s engine room.', 'The 2021-22 season, France''s future confirmed.', 'Initials A.T.']
),
(
  '15738461',
  'wissam-ben-yedder',
  true,
  'Wissam Ben Yedder',
  'ligue_1',
  'ligue_1',
  array['Monaco', 'Toulouse'],
  'France',
  'FW',
  1990,
  10,
  2010,
  2024,
  array[]::integer[],
  array[]::text[],
  array['Futsal feet, penalty ice, and scoring titles in the principality.', 'A French striker of tiny backlift and huge numbers.', 'Toulouse to Sevilla to Monaco''s captaincy.', 'The 2019-20 shared Golden Boot with a Paris kid.', 'Initials W.B.Y.']
),
(
  '93bbfab4',
  'eden-hazard',
  false,
  'Eden Hazard',
  'ligue_1',
  'ligue_1',
  array['Lille'],
  'Belgium',
  'FW',
  1991,
  26,
  2007,
  2012,
  array[]::integer[],
  array[]::text[],
  array['Player of the Year at 20, and Lille''s last title bearer.', 'A Belgian winger announcing genius in northern France.', 'Lille academy to the 2011 double.', 'The 2011 title and cup, teenaged and untouchable.', 'Initials E.H.']
),
(
  'e28bae7d',
  'victor-osimhen',
  false,
  'Victor Osimhen',
  'ligue_1',
  'ligue_1',
  array['Lille'],
  'Nigeria',
  'FW',
  1998,
  7,
  2019,
  2020,
  array[]::integer[],
  array[]::text[],
  array['One Lille season of leaps and goals bought Naples'' record fee.', 'A Nigerian striker announcing himself at 21.', 'Charleroi to Lille''s springboard.', 'The 2019-20 season, 18 goals and gone.', 'Initials V.O.']
),
(
  '579c054a',
  'jonathan-david',
  true,
  'Jonathan David',
  'ligue_1',
  'ligue_1',
  array['Lille'],
  'Canada',
  'FW',
  2000,
  9,
  2020,
  2025,
  array[]::integer[],
  array[]::text[],
  array['Lille''s ice cold Canadian out scored the oil money year after year.', 'A Canadian striker of first time finishes.', 'Gent to Lille''s 2021 champions.', 'The 2021 title, decisive goals down the stretch.', 'Initials J.D.']
),
(
  '4d85738b',
  'nicolas-pepe',
  true,
  'Nicolas Pepe',
  'ligue_1',
  'ligue_1',
  array['Lille', 'Angers'],
  'Ivory Coast',
  'FW',
  1995,
  19,
  2016,
  2019,
  array[]::integer[],
  array[]::text[],
  array['Lille sold one season of stepovers for 80 million euros.', 'An Ivorian winger, left footed, right sided, unstoppable briefly.', 'Angers to Lille''s 22 goal explosion.', 'The 2018-19 season that fooled, sorry, convinced Arsenal.', 'Initials N.P.']
),
(
  '5aa1c08b',
  'eduardo-camavinga',
  true,
  'Eduardo Camavinga',
  'ligue_1',
  'ligue_1',
  array['Rennes'],
  'France',
  'MF',
  2002,
  10,
  2019,
  2021,
  array[]::integer[],
  array[]::text[],
  array['A Rennes debutant at sixteen who bossed PSG''s midfield within months.', 'A French midfielder of limbs everywhere, teenaged everything.', 'Rennes academy to record breaking youth.', 'Dominating Paris at 16 in 2019, announced to the world.', 'Initials E.C.']
),
(
  '5dbb5092',
  'mario-balotelli',
  true,
  'Mario Balotelli',
  'ligue_1',
  'ligue_1',
  array['Nice', 'Marseille'],
  'Italy',
  'FW',
  1990,
  9,
  2016,
  2019,
  array[]::integer[],
  array['Super Mario'],
  array['Why always him? Nice found out: 33 goals in two happy seasons.', 'An Italian striker''s French redemption chapter.', 'The world tour''s Riviera stop.', 'The 2016-18 Nice revival, trouble free and prolific.', 'Super Mario. Initials M.B.']
),
(
  '5a2dcb1f',
  'claude-makelele',
  true,
  'Claude Makelele',
  'ligue_1',
  'ligue_1',
  array['Paris Saint-Germain', 'Nantes', 'Marseille'],
  'France',
  'MF',
  1973,
  4,
  1992,
  2011,
  array[]::integer[],
  array[]::text[],
  array['They named the position after him, and Nantes built the title where he learned it.', 'A French midfielder of interceptions and invisibility.', 'Nantes'' 1995 champions to the world.', 'The 1995 title as the young shield.', 'Initials C.M.']
),
(
  '546ffe69',
  'jean-pierre-papin',
  true,
  'Jean-Pierre Papin',
  'ligue_1',
  'ligue_1',
  array['Marseille'],
  'France',
  'FW',
  1963,
  9,
  1992,
  1992,
  array[]::integer[],
  array['JPP'],
  array['A Ballon d''Or from the Velodrome, volleys so good they got their own name.', 'A French striker of first time hits from any height.', 'Marseille''s late eighties god.', 'The Papinades, volleys catalogued like art.', 'JPP. Initials J.P.P.']
),
(
  'a708f33e',
  'sofiane-boufal',
  true,
  'Sofiane Boufal',
  'ligue_1',
  'ligue_1',
  array['Lille', 'Angers'],
  'Morocco',
  'MF',
  1993,
  19,
  2014,
  2023,
  array[]::integer[],
  array[]::text[],
  array['The dribble king of Ligue 1 before the Premier League goal of the season.', 'A Moroccan playmaker of low gravity slaloms.', 'Angers to Lille''s number ten.', 'The 2015-16 season leading Europe''s dribble charts.', 'Initials S.B.']
),
(
  '8e9e7b41',
  'robin-van-persie',
  true,
  'Robin van Persie',
  'premier_league',
  'premier_league',
  array['Arsenal', 'Manchester United'],
  'Netherlands',
  'FW',
  1983,
  20,
  2004,
  2015,
  array[]::integer[],
  array['RvP'],
  array['The flying header in a title decider that came after the fat Dutchman chant died.', 'A Dutch striker whose left foot was, in his words, a technique of its own.', 'Arsenal''s captain to United''s final title push.', 'The 2013 title clinching volley against Villa, off a fifty yard pass.', 'RvP. Initials R.V.P.']
),
(
  '948b2db6',
  'carlos-tevez',
  true,
  'Carlos Tevez',
  'premier_league',
  'premier_league',
  array['West Ham United', 'Manchester United', 'Manchester City'],
  'Argentina',
  'FW',
  1984,
  32,
  2006,
  2013,
  array[]::integer[],
  array[]::text[],
  array['Welcome to Manchester, said the poster. Both Manchesters, as it turned out.', 'An Argentine forward who ran like the ball owed his family money.', 'Upton Park''s savior to United to City.', 'The West Ham survival goal at Old Trafford, 2007.', 'Carlitos. Initials C.T.']
),
(
  '177992ce',
  'dimitar-berbatov',
  true,
  'Dimitar Berbatov',
  'premier_league',
  'premier_league',
  array['Tottenham Hotspur', 'Manchester United', 'Fulham'],
  'Bulgaria',
  'FW',
  1981,
  9,
  2006,
  2014,
  array[]::integer[],
  array['Berba'],
  array['He controlled footballs the way other people close doors, silently.', 'A Bulgarian striker of unbearable elegance and zero visible effort.', 'Spurs to United''s twenty goal season.', 'The overhead kick against Liverpool in 2010.', 'Berba. Initials D.B.']
),
(
  '8c161584',
  'teddy-sheringham',
  true,
  'Teddy Sheringham',
  'premier_league',
  'premier_league',
  array['Tottenham Hotspur', 'Manchester United'],
  'England',
  'FW',
  1966,
  10,
  1992,
  2007,
  array[]::integer[],
  array[]::text[],
  array['He came off the bench in the 1999 final and changed everything in stoppage time.', 'An English forward whose brain outran everyone''s legs.', 'Spurs to United to Spurs, playing past forty.', 'Equalizer in Barcelona, minute 91, treble alive.', 'Initials T.S.']
),
(
  '5bffbe51',
  'andy-cole',
  true,
  'Andy Cole',
  'premier_league',
  'premier_league',
  array['Newcastle United', 'Manchester United'],
  'England',
  'FW',
  1971,
  9,
  1993,
  2008,
  array[]::integer[],
  array[]::text[],
  array['34 goals in a season for Newcastle, then the record transfer south.', 'An English striker who only needed one chance, statistically.', 'Newcastle''s darling to United''s treble.', 'The five goal haul against Ipswich, 1995.', 'Initials A.C.']
),
(
  '93e2892e',
  'dwight-yorke',
  true,
  'Dwight Yorke',
  'premier_league',
  'premier_league',
  array['Aston Villa', 'Manchester United'],
  'Trinidad and Tobago',
  'FW',
  1971,
  19,
  1992,
  2009,
  array[]::integer[],
  array[]::text[],
  array['The smiling half of the treble season''s deadliest duo.', 'A Trinidadian forward who played like the game was a beach.', 'Villa''s gem to United''s treble.', 'The 1999 partnership with Cole, telepathy in shirts.', 'Initials D.Y.']
),
(
  'b1f3bfaa',
  'ole-gunnar-solskjaer',
  true,
  'Ole Gunnar Solskjaer',
  'premier_league',
  'premier_league',
  array['Manchester United'],
  'Norway',
  'FW',
  1973,
  20,
  1996,
  2007,
  array[]::integer[],
  array[]::text[],
  array['The baby faced assassin''s toe ended the greatest season ever in minute 93.', 'A Norwegian super sub who studied games from the bench like homework.', 'Molde to a lifetime at United.', 'Barcelona 1999, the toe poke, the slide on knees.', 'Initials O.G.S.']
),
(
  'c113d8de',
  'nicolas-anelka',
  false,
  'Nicolas Anelka',
  'premier_league',
  'premier_league',
  array['Arsenal', 'Chelsea', 'Manchester City', 'Bolton Wanderers'],
  'France',
  'FW',
  1979,
  39,
  1997,
  2012,
  array[]::integer[],
  array[]::text[],
  array['Le Sulk won the title as a teenager and toured half the league after.', 'A French striker of speed, silence and endless transfers.', 'Arsenal''s double winning kid, later Chelsea''s golden boot.', 'The 1998 double at nineteen years old.', 'Le Sulk. Initials N.A.']
),
(
  'eefd0664',
  'peter-crouch',
  true,
  'Peter Crouch',
  'premier_league',
  'premier_league',
  array['Liverpool', 'Tottenham Hotspur', 'Portsmouth', 'Stoke City'],
  'England',
  'FW',
  1981,
  null,
  2000,
  2019,
  array[]::integer[],
  array[]::text[],
  array['Six foot seven with better feet than yours, and one robot.', 'An English target man who scored overheads he had no business attempting.', 'Liverpool, Spurs, Stoke, and a podcast empire.', 'The robot celebration, England, 2006, still requested at weddings.', 'Crouchy. Initials P.C.']
),
(
  '6ec30f32',
  'jermain-defoe',
  true,
  'Jermain Defoe',
  'premier_league',
  'premier_league',
  array['West Ham United', 'Tottenham Hotspur', 'Sunderland'],
  'England',
  'FW',
  1982,
  18,
  2001,
  2019,
  array[]::integer[],
  array[]::text[],
  array['A five goal half against Wigan and two decades of pure finishing.', 'An English striker who lived on the last shoulder.', 'West Ham to Spurs to a friendship that moved a nation.', 'Five against Wigan in one half, 2009.', 'Initials J.D.']
),
(
  'c76a9b25',
  'robbie-keane',
  true,
  'Robbie Keane',
  'premier_league',
  'premier_league',
  array['Coventry City', 'Leeds United', 'Tottenham Hotspur', 'Liverpool'],
  'Ireland',
  'FW',
  1980,
  null,
  1999,
  2011,
  array[]::integer[],
  array[]::text[],
  array['Cartwheel, roll, finger guns. Ireland''s record scorer toured the league doing it.', 'An Irish forward of improvisation and permanent confidence.', 'Coventry teen to Leeds to Spurs'' captaincy.', 'The 2008 season partnership with Berbatov at Spurs.', 'Initials R.K.']
),
(
  'd9fcd7d1',
  'matt-le-tissier',
  true,
  'Matt Le Tissier',
  'premier_league',
  'premier_league',
  array['Southampton'],
  'England',
  'MF',
  1968,
  7,
  1992,
  2002,
  array[]::integer[],
  array['Le God'],
  array['He turned down every big club to score worldies for one unfashionable one.', 'An English playmaker of volleys, chips and one missed penalty in fifty.', 'Southampton, only ever Southampton.', 'The flick up and volley against Newcastle, 1993.', 'Le God. Initials M.L.T.']
),
(
  'd0d08f1d',
  'david-ginola',
  true,
  'David Ginola',
  'premier_league',
  'premier_league',
  array['Newcastle United', 'Tottenham Hotspur', 'Aston Villa'],
  'France',
  'MF',
  1967,
  14,
  1995,
  2002,
  array[]::integer[],
  array[]::text[],
  array['Shampoo adverts, dropped shoulders, and Player of the Year at a mid table club.', 'A French winger who played football like a catwalk.', 'Newcastle''s entertainer to Spurs'' award winner.', 'The 1999 FA Cup slalom against Barnsley.', 'Initials D.G.']
),
(
  'e8055585',
  'marc-overmars',
  true,
  'Marc Overmars',
  'premier_league',
  'premier_league',
  array['Arsenal'],
  'Netherlands',
  'FW',
  1973,
  11,
  1997,
  2000,
  array[]::integer[],
  array[]::text[],
  array['The flying Dutchman of the 1998 double, terrorizing right backs for three seasons.', 'A Dutch winger of pure straight line menace.', 'Ajax to Arsenal to a Barcelona record fee.', 'The title clinching goal at Old Trafford, 1998.', 'Initials M.O.']
),
(
  'fb721088',
  'freddie-ljungberg',
  true,
  'Freddie Ljungberg',
  'premier_league',
  'premier_league',
  array['Arsenal'],
  'Sweden',
  'MF',
  1977,
  8,
  1998,
  2007,
  array[]::integer[],
  array[]::text[],
  array['Red streaked hair, underwear billboards, and goals in consecutive FA Cup finals.', 'A Swedish midfielder who arrived in boxes unannounced.', 'Halmstad to the Invincibles.', 'Cup final goals in 2001 and 2002, back to back.', 'Freddie. Initials F.L.']
),
(
  'b9a57c57',
  'ashley-cole',
  true,
  'Ashley Cole',
  'premier_league',
  'premier_league',
  array['Arsenal', 'Chelsea'],
  'England',
  'DF',
  1980,
  3,
  1999,
  2014,
  array[]::integer[],
  array[]::text[],
  array['The best left back of his generation, booed everywhere and bothered nowhere.', 'An English defender who kept Ronaldo quiet more than anyone alive.', 'Arsenal Invincible to Chelsea''s serial winner.', 'The 2006 crossing of London that named him Cashley forever.', 'Initials A.C.']
),
(
  '496e0f0f',
  'gary-neville',
  true,
  'Gary Neville',
  'premier_league',
  'premier_league',
  array['Manchester United'],
  'England',
  'DF',
  1975,
  2,
  1992,
  2011,
  array[]::integer[],
  array[]::text[],
  array['Red Nev hated scousers professionally for two decades, then joined one on TV.', 'An English right back of maximum effort and maximum badge kissing.', 'One club, United, 602 games.', 'The badge kiss in front of the Liverpool end, 2006.', 'Red Nev. Initials G.N.']
),
(
  'f8140cf8',
  'jaap-stam',
  true,
  'Jaap Stam',
  'premier_league',
  'premier_league',
  array['Manchester United'],
  'Netherlands',
  'DF',
  1972,
  6,
  1998,
  2001,
  array[]::integer[],
  array[]::text[],
  array['Sold by Ferguson over a book, a decision the manager called his worst.', 'A Dutch center back who defended like the door of a nightclub.', 'PSV to United''s treble to Italian redemption.', 'The 1999 treble, conceding almost nothing behind it.', 'Initials J.S.']
),
(
  '983bb7d8',
  'edwin-van-der-sar',
  true,
  'Edwin van der Sar',
  'premier_league',
  'premier_league',
  array['Fulham', 'Manchester United'],
  'Netherlands',
  'GK',
  1970,
  1,
  2001,
  2011,
  array[]::integer[],
  array[]::text[],
  array['The penalty save from Anelka that finished the 2008 Champions League.', 'A Dutch goalkeeper who aged like advice, better with time.', 'Ajax legend, Fulham detour, United''s answer at last.', 'Moscow 2008, the wagging finger, the save, the cup.', 'Initials E.V.D.S.']
),
(
  'b12ab522',
  'david-seaman',
  true,
  'David Seaman',
  'premier_league',
  'premier_league',
  array['Arsenal', 'Manchester City'],
  'England',
  'GK',
  1963,
  1,
  1992,
  2004,
  array[]::integer[],
  array['Safe Hands'],
  array['Ponytail, mustache, and the save against Sheffield United that defied dimensions.', 'An English goalkeeper, Arsenal''s calm for over a decade.', 'Rotherham roots to Highbury''s number one.', 'The 2003 semifinal save from Peschisolido, scooped off the line backwards.', 'Safe Hands. Initials D.S.']
),
(
  'c60ea42d',
  'michael-carrick',
  true,
  'Michael Carrick',
  'premier_league',
  'premier_league',
  array['West Ham United', 'Tottenham Hotspur', 'Manchester United'],
  'England',
  'MF',
  1981,
  16,
  1999,
  2018,
  array[]::integer[],
  array[]::text[],
  array['The quiet fulcrum of five United titles that pundits took a decade to notice.', 'An English deep midfielder who passed like a metronome set to calm.', 'West Ham academy to Spurs to Old Trafford.', 'The 2013 title season, finally in the team of the year.', 'Initials M.C.']
),
(
  '05f61dc4',
  'xabi-alonso',
  false,
  'Xabi Alonso',
  'premier_league',
  'premier_league',
  array['Liverpool'],
  'Spain',
  'MF',
  1981,
  14,
  2004,
  2009,
  array[]::integer[],
  array[]::text[],
  array['He scored from his own half twice and rebounded home the most famous miss in Istanbul.', 'A Spanish midfielder whose passing range needed air traffic control.', 'Sociedad to Anfield to Madrid and Munich.', 'Istanbul 2005, the saved penalty, the follow up, 3 3.', 'Initials X.A.']
),
(
  '992e1257',
  'javier-mascherano',
  true,
  'Javier Mascherano',
  'premier_league',
  'premier_league',
  array['West Ham United', 'Liverpool'],
  'Argentina',
  'MF',
  1984,
  null,
  2006,
  2010,
  array[]::integer[],
  array[]::text[],
  array['He arrived at West Ham in the strangest transfer saga the league has seen.', 'An Argentine destroyer who later became a Barcelona center back.', 'Corinthians to Upton Park mystery to Anfield.', 'The 2007 Champions League final run as Liverpool''s shield.', 'El Jefecito. Initials J.M.']
),
(
  '6175f76a',
  'fernandinho',
  true,
  'Fernandinho',
  'premier_league',
  'premier_league',
  array['Manchester City'],
  'Brazil',
  'MF',
  1985,
  25,
  2013,
  2022,
  array[]::integer[],
  array[]::text[],
  array['City''s quiet Brazilian screen for five titles, captain for the last.', 'A Brazilian holding midfielder who committed the smartest fouls in the league.', 'Shakhtar''s champion to City''s spine.', 'The centurions season, 2018, holding it all together.', 'Initials F.']
),
(
  '847c86f5',
  'ederson',
  true,
  'Ederson',
  'premier_league',
  'premier_league',
  array['Manchester City'],
  'Brazil',
  'GK',
  1993,
  31,
  2017,
  2025,
  array[]::integer[],
  array[]::text[],
  array['A goalkeeper whose passing map looks like a playmaker''s.', 'A Brazilian keeper with a tattooed neck and a sixty yard wedge.', 'Benfica to City''s revolution in goal.', 'The assist for Aguero against Huddersfield, one kick.', 'Initials E.']
),
(
  '274fa91f',
  'bernardo-silva',
  false,
  'Bernardo Silva',
  'premier_league',
  'premier_league',
  array['Manchester City'],
  'Portugal',
  'MF',
  1994,
  20,
  2017,
  2026,
  array[]::integer[],
  array[]::text[],
  array['Pep called him the player he''d buy with his own money.', 'A Portuguese midfielder who dribbles in cursive.', 'Monaco''s title kid to City''s everywhere man.', 'The 2019 title run in, best player in the league for two months.', 'Initials B.S.']
),
(
  '342ff9fd',
  'ilkay-gundogan',
  true,
  'Ilkay Gundogan',
  'premier_league',
  'premier_league',
  array['Manchester City'],
  'Germany',
  'MF',
  1990,
  8,
  2016,
  2025,
  array[]::integer[],
  array[]::text[],
  array['Captain of the treble, scorer of the FA Cup final''s fastest ever goal.', 'A German midfielder of late runs and calm nerves.', 'Dortmund to City''s silverware machine.', 'Twelve seconds into the 2023 FA Cup final, volleyed in.', 'Gundo. Initials I.G.']
),
(
  '286761d9',
  'kyle-walker',
  true,
  'Kyle Walker',
  'premier_league',
  'premier_league',
  array['Tottenham Hotspur', 'Manchester City'],
  'England',
  'DF',
  1990,
  2,
  2009,
  2025,
  array[]::integer[],
  array[]::text[],
  array['The fastest full back of his era, still recovering situations at 34.', 'An English right back from Sheffield with jet engines for calves.', 'Spurs to City''s six titles.', 'The 2019 recovery tackle culture, a highlight genre of his own.', 'Initials K.W.']
),
(
  '92cf151a',
  'john-stones',
  true,
  'John Stones',
  'premier_league',
  'premier_league',
  array['Everton', 'Manchester City'],
  'England',
  'DF',
  1994,
  5,
  2013,
  2026,
  array[]::integer[],
  array[]::text[],
  array['The Barnsley Beckenbauer stepped into midfield and won a treble doing it.', 'An English defender who passes his way out of rooms most would burn down.', 'Everton to City''s evolution.', 'The 2023 treble as a hybrid center back midfielder.', 'Initials J.S.']
),
(
  'ad017cf3',
  'mesut-ozil',
  true,
  'Mesut Ozil',
  'premier_league',
  'premier_league',
  array['Arsenal'],
  'Germany',
  'MF',
  1988,
  10,
  2013,
  2021,
  array[]::integer[],
  array[]::text[],
  array['Assist king of the league in 2015-16, nineteen of them like gift wrap.', 'A German playmaker of no look passes and eternal debate.', 'Madrid to Arsenal''s record signing.', 'The 2015-16 season, an assist chart lapping the field.', 'Initials M.O.']
),
(
  'e094ae3c',
  'alexis-sanchez',
  true,
  'Alexis Sanchez',
  'premier_league',
  'premier_league',
  array['Arsenal', 'Manchester United'],
  'Chile',
  'FW',
  1988,
  7,
  2014,
  2020,
  array[]::integer[],
  array[]::text[],
  array['Arsenal''s all action Chilean, later the league''s most infamous free transfer.', 'A Chilean forward with a dog named Atom and a bite in his game.', 'Barcelona to Arsenal''s talisman to Old Trafford regret.', 'The 2017 FA Cup final, running Chelsea ragged.', 'Initials A.S.']
),
(
  '106ef152',
  'philippe-coutinho',
  true,
  'Philippe Coutinho',
  'premier_league',
  'premier_league',
  array['Liverpool', 'Aston Villa'],
  'Brazil',
  'MF',
  1992,
  10,
  2013,
  2023,
  array[]::integer[],
  array[]::text[],
  array['The little magician whose curlers from the right half space paid for a stadium stand.', 'A Brazilian playmaker sold for 142 million.', 'Inter misfit to Anfield''s magician.', 'The 2017-18 half season so good Barcelona emptied the vault.', 'Initials P.C.']
),
(
  '5cf45000',
  'luka-modric',
  false,
  'Luka Modric',
  'premier_league',
  'premier_league',
  array['Tottenham Hotspur'],
  'Croatia',
  'MF',
  1985,
  14,
  2008,
  2012,
  array[]::integer[],
  array[]::text[],
  array['Spurs fans watched him leave and then watched him win everything, still applauding.', 'A Croatian midfielder who ran London''s midfields before Europe''s.', 'Dinamo to White Hart Lane to the Bernabeu.', 'The 2011 season that made Madrid inevitable.', 'Initials L.M.']
)
on conflict (id) do update set
  person_id = excluded.person_id,
  canonical = excluded.canonical,
  name = excluded.name,
  category = excluded.category,
  league = excluded.league,
  clubs = excluded.clubs,
  nationality = excluded.nationality,
  position = excluded.position,
  birth_year = excluded.birth_year,
  shirt_number = excluded.shirt_number,
  era_start = excluded.era_start,
  era_end = excluded.era_end,
  world_cup_editions = excluded.world_cup_editions,
  aliases = excluded.aliases,
  clues = excluded.clues;

-- Verify this batch: select count(*) from public.players; -- expect 400 cumulative after all batches through 05
